#!/usr/bin/env python3
"""Generate ~558 new Hindi cards to fill nodes to 112 each."""
import json, random

random.seed(42)

NODES = {
    "node-06": {"need": 16, "topic": "Food, drink & ordering"},
    "node-07": {"need": 17, "topic": "Family & relationships"},
    "node-11": {"need": 28, "topic": "Modal verbs"},
    "node-15": {"need": 46, "topic": "Adjective agreement & comparison"},
    "node-16": {"need": 38, "topic": "Past habitual tense"},
    "node-17": {"need": 47, "topic": "Directions & transport"},
    "node-21": {"need": 19, "topic": "Relative clauses"},
    "node-22": {"need": 69, "topic": "Passive voice"},
    "node-24": {"need": 37, "topic": "Future tense"},
    "node-30": {"need": 58, "topic": "Sanskritized vs Persianized Hindi"},
    "node-32": {"need": 59, "topic": "Literary & written Hindi"},
    "node-33": {"need": 73, "topic": "Academic discourse"},
    "node-34": {"need": 49, "topic": "Cultural fluency"},
    "node-35": {"need": 2, "topic": "Advanced mixed mastery"},
}

# ~30% get grammar tips
TIPS = {
    "node-06": [
        "दीजिए is the polite imperative of देना (to give). Use it when ordering.",
        "Use कम/ज़्यादा for less/more: चीनी कम डालिए (put less sugar).",
        "पानी is always masculine. चाय is always feminine: गर्म चाय.",
        "लीजिए (please take) vs दीजिए (please give). Both polite imperatives.",
        "मसालेदार = spicy, मीठा = sweet, खट्टा = sour, नमकीन = salty.",
        "बिल लाइए = bring the bill. Polite request form with -इए.",
        "पकवान (dishes) is formal; खाना (food) is everyday.",
        "थाली = a platter with multiple dishes. Common restaurant order.",
    ],
    "node-07": [
        "ससुराल = in-laws' home. मायका = maternal home (woman's parents).",
        "बड़े/छोटे before relations shows elder/younger: बड़े भाई (elder brother).",
        "जी suffix shows respect: पापा जी, मम्मी जी, दादा जी.",
        "रिश्तेदार = relative. Hindi has specific terms for every relation.",
        "फूफा = father's sister's husband. मौसा = mother's sister's husband.",
        "नानी = maternal grandmother. दादी = paternal grandmother.",
        "भाभी = elder brother's wife. जीजा = elder sister's husband.",
    ],
    "node-11": [
        "सकना = ability: बोल सकता हूँ (I can speak).",
        "चाहिए = should/need: आपको जाना चाहिए (you should go).",
        "पाना = manage to: वह समझ नहीं पाया (he couldn't understand).",
        "होना = have to: मुझे काम करना होगा (I will have to work).",
        "सकना conjugates; चाहिए stays fixed regardless of subject.",
        "पड़ना = compulsion: मुझे जाना पड़ा (I had to go, no choice).",
        "चुकना = already done: खा चुका हूँ (I have already eaten).",
        "लगना = start to: बारिश होने लगी (it started to rain).",
        "देना = do for someone: बता दो (tell, do the favor).",
        "लेना = do for self: सीख लिया (learned for oneself).",
    ],
    "node-15": [
        "Adjectives ending in -ा change: अच्छा लड़का, अच्छी लड़की, अच्छे लड़के.",
        "से + adjective = comparative: राम श्याम से लंबा है.",
        "सबसे + adjective = superlative: सबसे अच्छा (the best).",
        "कम = less, ज़्यादा = more, बराबर = equal for comparisons.",
        "Invariable adjectives (सुंदर, लाल) don't change with gender/number.",
        "इतना...जितना = as much as: इतना बड़ा जितना हाथी.",
        "और भी = even more: और भी सुंदर (even more beautiful).",
        "कितना = how much/many: कितना महँगा है? (how expensive?).",
        "बहुत = very, काफ़ी = quite, थोड़ा = a little (degree words).",
        "ज़रा = slightly/a bit: ज़रा धीरे बोलिए (speak a bit slowly).",
        "उतना...जितना = as much as (correlative): उतना ही अच्छा.",
        "पूरा = complete/whole: पूरा दिन (the whole day).",
        "कुछ = some/a few: कुछ लोग (some people). Invariable.",
        "हर/प्रत्येक = every/each: हर बच्चा (every child).",
        "ऐसा/वैसा = such/like that: ऐसा आदमी (such a man). Changes with gender.",
    ],
    "node-16": [
        "Past habitual: stem + ता/ती/ते + था/थी/थे: वह जाता था.",
        "Negation: नहीं before verb: वह नहीं जाता था (he didn't used to go).",
        "Gender agreement: वह खाती थी (she used to eat, feminine).",
        "करता था (habitual) vs किया (one-time past). Different aspects.",
        "Plural: हम जाते थे (we used to go). लड़कियाँ खेलती थीं.",
        "अक्सर (often), हमेशा (always) pair naturally with habitual.",
        "रोज़ (daily), कभी-कभी (sometimes) are common habitual markers.",
        "पहले = before/earlier: पहले हम यहाँ रहते थे (we used to live here).",
        "बचपन में = in childhood: बचपन में हम खेलते थे.",
        "उन दिनों = in those days: उन दिनों बिजली नहीं होती थी.",
        "Contrast habitual with progressive: करता था vs कर रहा था.",
        "होती थी = used to be (f.): दुकान यहाँ होती थी.",
    ],
    "node-17": [
        "सीधा/सीधे = straight: सीधे जाइए (go straight).",
        "दाएँ/बाएँ मुड़िए = turn right/left. Polite imperative.",
        "से = by (transport): बस से, ट्रेन से, ऑटो से.",
        "कितनी दूर = how far: स्टेशन कितनी दूर है?",
        "चौराहा = crossroads, गली = lane, सड़क = road.",
        "रुकिए = stop (polite): यहाँ रुकिए (stop here).",
        "पहुँचना = to reach: हम समय पर पहुँच गए.",
        "किराया = fare: ऑटो का किराया कितना है?",
        "Use के पास for near: स्टेशन के पास (near the station).",
        "तक = up to/until: दिल्ली तक (up to Delhi).",
        "की ओर/तरफ़ = towards: बाज़ार की तरफ़ जाइए.",
        "पार करना = to cross: सड़क पार कीजिए.",
        "मोड़ = turn/bend: अगले मोड़ पर बाएँ जाइए.",
        "ठहरना = to stay/halt: यहाँ ठहरिए (halt here).",
        "यातायात = traffic: आज यातायात बहुत है.",
    ],
    "node-21": [
        "जो...वह pattern: जो आदमी आया, वह मेरा दोस्त है.",
        "जो agrees with antecedent: जो लड़की (f.), जो लड़के (pl.).",
        "जहाँ...वहाँ = where...there: जहाँ तुम हो, वहाँ मैं आऊँगा.",
        "जब...तब = when...then: जब बारिश होती है, तब ठंड लगती है.",
        "जैसा...वैसा = as...so: जैसा बोओगे, वैसा काटोगे.",
        "जितना...उतना = as much...that much.",
        "जिसका = whose: जिसका घर यह है, वह बाहर गया.",
    ],
    "node-22": [
        "Passive: stem + आ/ई/ए + जाना: लिखा जाता है (is written).",
        "Agent with से/द्वारा: राम द्वारा लिखा गया (written by Ram).",
        "Passive habitual: बनाया जाता है (is made regularly).",
        "Negative passive: नहीं किया जाता (is not done).",
        "Passive for inability: मुझसे चला नहीं जाता (I can't walk).",
        "Impersonal passive: यहाँ बैठा नहीं जाता (one can't sit here).",
        "Past passive: भेजा गया (was sent), खोला गया (was opened).",
        "Future passive: किया जाएगा (will be done).",
        "Passive progressive: पढ़ाया जा रहा है (is being taught).",
        "Modal passive: किया जा सकता है (can be done).",
        "Compound passive: तोड़ दिया गया (was broken, completive).",
        "Obligation passive: यह काम करना होगा vs किया जाना चाहिए.",
        "गया/गई/गए agrees with object gender: किताब पढ़ी गई.",
        "Experiential passive: मुझसे गलती हो गई (a mistake happened by me).",
        "Honorific passive: आपसे अनुरोध किया जाता है (you are requested).",
        "Permission passive: जाने दिया गया (was allowed to go).",
        "Causative passive: करवाया गया (was made to be done).",
        "News register passive: गिरफ़्तार किया गया (was arrested).",
        "Habitual passive neg: खाया नहीं जाता (cannot be eaten/tolerated).",
        "Double passive: बनवाया गया (was got made by someone).",
        "Passive with को: उसको बुलाया गया (he was called).",
    ],
    "node-24": [
        "Future: stem + ऊँगा/एगा/एगी/एँगे: मैं जाऊँगा.",
        "Presumptive: होगा = must be/probably: वह घर पर होगा.",
        "Negative future: नहीं करेगा (will not do).",
        "Question future: क्या तुम आओगे? (will you come?).",
        "Formal future: -एँगे for हम/आप/वे: हम करेंगे.",
        "Immediate future with वाला: जाने वाला हूँ (about to go).",
        "Conditional future: अगर बारिश होगी तो हम नहीं जाएँगे.",
        "शायद + future = maybe: शायद वह आएगा.",
        "ज़रूर + future = definitely: मैं ज़रूर आऊँगा.",
        "Female future: -ऊँगी/एगी: मैं जाऊँगी, वह आएगी.",
        "Plural future: लोग समझेंगे (people will understand).",
        "Future with चाहना: मैं जाना चाहूँगा (I would like to go).",
    ],
    "node-30": [
        "Sanskritized: विद्यालय (school). Persianized: मदरसा. Loan: स्कूल.",
        "Formal register prefers Sanskrit: कार्यालय over दफ़्तर (office).",
        "Persianized: दिल (heart), ख़ून (blood), ज़िंदगी (life).",
        "Sanskrit: हृदय (heart), रक्त (blood), जीवन (life).",
        "Daily Hindi mixes freely: ज़रूरत (Pers.) + आवश्यकता (Skt.).",
        "News Hindi uses more Sanskrit: प्रधानमंत्री, सरकार, विकास.",
        "Urdu-origin: इंतज़ार (wait), मोहब्बत (love), ख़्वाब (dream).",
        "Sanskrit-origin: प्रतीक्षा (wait), प्रेम (love), स्वप्न (dream).",
        "Persian suffix -दार: ज़िम्मेदार, दुकानदार, हिस्सेदार.",
        "Sanskrit suffix -कर्ता: कार्यकर्ता, सूत्रधार.",
        "Casual: ठीक है, formal Skt: उचित है, formal Pers: मुनासिब है.",
        "Persian compound verbs: इस्तेमाल करना, इंतज़ार करना.",
        "Sanskrit compound verbs: उपयोग करना, प्रतीक्षा करना.",
        "Food terms are mixed: रोटी (Hindi), नान (Persian), पराँठा.",
        "ख़/ग़/ज़/फ़ with nuqta are Perso-Arabic. Without nuqta = Hindi.",
        "Legal Hindi is highly Sanskritized: अधिनियम, प्रावधान, न्यायालय.",
        "Film/music Hindi is heavily Persianized: इश्क़, जुनून, अदा.",
        "Polite Persianized: मेहरबानी, formal Skt: कृपा (kindness).",
    ],
    "node-32": [
        "Literary Hindi uses longer Sanskrit compounds: महाविद्यालय, राजधानी.",
        "साहित्यिक (literary) vs बोलचाल (colloquial): different registers.",
        "Written Hindi avoids English loanwords: दूरभाष for telephone.",
        "Formal connectors: तथापि (nevertheless), अतः (therefore).",
        "Passive voice is preferred in formal writing.",
        "यद्यपि...तथापि = although...nevertheless (literary pair).",
        "Written: किंतु/परंतु (but). Spoken: लेकिन/मगर/पर.",
        "Honorific plural in writing: गांधी जी ने कहा था.",
        "Abstract nouns with -ता/-त्व: मानवता (humanity), नेतृत्व (leadership).",
        "Formal address: महोदय (sir), महोदया (madam).",
        "Compound words: जनसंख्या (population), पर्यावरण (environment).",
        "अर्थात् = that is to say. Used in formal explanation.",
        "Nominalisation: -ना converts verbs to nouns: पढ़ना अच्छा है.",
        "Written Hindi punctuation: पूर्णविराम (।) not period (.).",
        "Echo words in literary prose: खाना-वाना, चाय-शाय.",
        "Relative-correlative in formal: जो...वह, जहाँ...वहाँ pattern.",
        "उक्त = aforementioned, निम्नलिखित = following (written register).",
        "Sanskrit verb prefixes: प्र-, अनु-, सम-, वि- (प्रगति, अनुमान).",
    ],
    "node-33": [
        "Academic: अध्ययन (study), अनुसंधान (research), विश्लेषण (analysis).",
        "Thesis language: प्रस्तुत शोध (the present research), निष्कर्ष (conclusion).",
        "Impersonal: देखा जा सकता है (it can be seen).",
        "Citation: के अनुसार (according to), के मतानुसार (in the opinion of).",
        "Hedging: संभवतः (possibly), प्रतीत होता है (it appears).",
        "Academic passive: प्रमाणित किया गया (it was proven).",
        "परिकल्पना = hypothesis. सिद्धांत = theory. प्रमाण = evidence.",
        "तालिका = table, आरेख = diagram, चित्र = figure (academic).",
        "संदर्भ = reference/context. उद्धरण = citation/quote.",
        "Conjunctions: इसके अतिरिक्त (in addition), फलस्वरूप (consequently).",
        "अध्याय = chapter. खंड = section. परिशिष्ट = appendix.",
        "तुलनात्मक = comparative. व्याख्यात्मक = explanatory.",
        "प्रश्नावली = questionnaire. साक्षात्कार = interview (research).",
        "यथा = as/for example (literary). जैसे कि = such as (spoken).",
        "उपरोक्त = abovementioned. पूर्वोक्त = previously stated.",
        "निष्कर्षतः = in conclusion. सारांशतः = in summary.",
        "मूल्यांकन = evaluation. समीक्षा = review/critique.",
        "शोध-प्रविधि = research methodology. प्रतिदर्श = sample.",
        "पारिभाषिक = technical/terminological: पारिभाषिक शब्दावली.",
        "सह-संबंध = correlation. कारण-परिणाम = cause-effect.",
        "साहित्य-समीक्षा = literature review (academic section).",
        "अनुभवजन्य = empirical: अनुभवजन्य अध्ययन (empirical study).",
    ],
    "node-34": [
        "अतिथि देवो भव = The guest is God. Core hospitality value.",
        "जुगाड़ = creative problem-solving with limited resources.",
        "नमस्ते vs आदाब: Hindu vs Muslim greeting, both widely used.",
        "दहेज = dowry. A social issue often discussed.",
        "बड़ों के पैर छूना = touching elders' feet as respect gesture.",
        "जी हाँ/जी नहीं: polite yes/no. जी alone = polite acknowledgment.",
        "प्रणाम = formal greeting to elders. More respectful than नमस्ते.",
        "तीज-त्योहार = festivals collectively. Cultural calendar concept.",
        "संयुक्त परिवार = joint family. बड़ा परिवार = big family.",
        "बरकत = abundance/blessing (Pers.). Common in household context.",
        "मेहमान-नवाज़ी = hospitality (Persianized). आतिथ्य (Sanskritized).",
        "रीति-रिवाज = customs and traditions.",
        "शुभ-अशुभ = auspicious-inauspicious. Key cultural concept.",
        "कर्म = action/deed. Philosophical and everyday usage.",
        "धर्म = duty/religion/righteousness. Context-dependent meaning.",
        "सेवा = service/selfless work. Cultural and spiritual concept.",
    ],
    "node-35": [
        "Politeness scale: stem < -ओ < -इए < -इएगा.",
    ],
}

# Sentence templates per node
SENTENCES = {
    "node-06": [
        ("क्या आपके यहाँ शुद्ध शाकाहारी खाना मिलता है?", "Do you serve pure vegetarian food here?"),
        ("मुझे बिना मसाले वाला सूप चाहिए।", "I want soup without spices."),
        ("यह सब्ज़ी बहुत स्वादिष्ट बनी है।", "This vegetable dish has turned out very tasty."),
        ("क्या आप हमें एक और रोटी ला सकते हैं?", "Can you bring us one more roti?"),
        ("मुझे बिल में कोई गलती दिख रही है।", "I see an error in the bill."),
        ("इस रेस्तराँ का पनीर टिक्का बहुत मशहूर है।", "This restaurant's paneer tikka is very famous."),
        ("कृपया हमारे लिए दो गिलास पानी लाइए।", "Please bring two glasses of water for us."),
        ("खाने में नमक थोड़ा कम है, और डालिए।", "The food has less salt, please add more."),
        ("मैं मिठाई के बदले फल खाना पसंद करूँगा।", "I would prefer to eat fruit instead of sweets."),
        ("क्या यह व्यंजन बहुत तीखा है?", "Is this dish very spicy?"),
        ("हमने चार लोगों के लिए टेबल बुक किया है।", "We have booked a table for four people."),
        ("मेन्यू में आज का विशेष व्यंजन कौन सा है?", "What is today's special dish on the menu?"),
        ("माँ ने आज बहुत मेहनत से खाना बनाया है।", "Mother has cooked food with great effort today."),
        ("चाय में अदरक और इलायची डालने से स्वाद बढ़ जाता है।", "Adding ginger and cardamom to tea enhances the flavor."),
        ("दादी की बनाई खीर सबसे लाजवाब होती है।", "Grandmother's kheer is the most delicious."),
        ("आज हम बाहर खाना खाने चलते हैं।", "Let's go out to eat today."),
    ],
    "node-07": [
        ("मेरे चाचा और चाची दोनों डॉक्टर हैं।", "My uncle and aunt are both doctors."),
        ("बड़ी बहन की शादी अगले महीने है।", "Elder sister's wedding is next month."),
        ("नानी हर रविवार को हमारे घर आती हैं।", "Grandmother comes to our house every Sunday."),
        ("मेरे ससुर बहुत सम्मानित व्यक्ति हैं।", "My father-in-law is a very respected person."),
        ("भाभी ने सबके लिए नाश्ता तैयार किया।", "Sister-in-law prepared breakfast for everyone."),
        ("दादा जी ने हमें बचपन की कहानियाँ सुनाईं।", "Grandfather told us stories from his childhood."),
        ("मौसी के बच्चे गर्मियों की छुट्टियों में आए हैं।", "Aunt's children have come for summer holidays."),
        ("परिवार में सबसे छोटा भाई सबका लाड़ला है।", "The youngest brother in the family is everyone's darling."),
        ("हमारे संयुक्त परिवार में बीस लोग रहते हैं।", "Twenty people live in our joint family."),
        ("फूफी ने मुझे जन्मदिन पर सुंदर उपहार दिया।", "Paternal aunt gave me a beautiful gift on my birthday."),
        ("माँ-बाप के बिना जीवन की कल्पना कठिन है।", "It is hard to imagine life without parents."),
        ("जीजा जी हमें हर त्योहार पर मिठाई भेजते हैं।", "Brother-in-law sends us sweets on every festival."),
        ("बहन और भाई का रिश्ता बहुत ख़ास होता है।", "The relationship between sister and brother is very special."),
        ("मेरी भतीजी इस साल पहली कक्षा में जाएगी।", "My niece will go to first grade this year."),
        ("ताऊ जी गाँव में खेती-बाड़ी करते हैं।", "Uncle does farming in the village."),
        ("पूरा परिवार दिवाली पर एक साथ इकट्ठा होता है।", "The whole family gathers together on Diwali."),
        ("देवर ने भाभी को राखी पर साड़ी दी।", "Younger brother-in-law gave sister-in-law a saree on Rakhi."),
    ],
    "node-11": [
        ("क्या तुम यह भारी बक्सा उठा सकते हो?", "Can you lift this heavy box?"),
        ("मुझे अभी दवाई लेनी चाहिए।", "I should take medicine right now."),
        ("वह इतनी तेज़ दौड़ नहीं पाती।", "She cannot manage to run that fast."),
        ("हमें सुबह जल्दी उठना पड़ता है।", "We have to wake up early in the morning."),
        ("तुम्हें अपने स्वास्थ्य का ध्यान रखना चाहिए।", "You should take care of your health."),
        ("बच्चे अब अकेले स्कूल जा सकते हैं।", "The children can now go to school alone."),
        ("मुझे यह काम आज ही करना होगा।", "I will have to do this work today itself."),
        ("क्या आप थोड़ा धीरे बोल सकते हैं?", "Can you speak a little slowly?"),
        ("उसे रोज़ अभ्यास करना चाहिए।", "He/she should practice every day."),
        ("वह हिंदी में गाना गा सकती है।", "She can sing a song in Hindi."),
        ("हमें समय पर पहुँचना पड़ेगा।", "We will have to reach on time."),
        ("तुम्हें डॉक्टर से मिलना चाहिए।", "You should see a doctor."),
        ("मैं यह पहाड़ चढ़ नहीं पाऊँगा।", "I won't be able to climb this mountain."),
        ("उन्हें हर महीने किराया देना पड़ता है।", "They have to pay rent every month."),
        ("क्या तुम मेरी बात समझ सकते हो?", "Can you understand what I am saying?"),
        ("बच्चों को जल्दी सोना चाहिए।", "Children should sleep early."),
        ("मुझसे इतना भारी सामान उठाया नहीं जाता।", "I am unable to lift such heavy luggage."),
        ("आपको ज़रूर कोशिश करनी चाहिए।", "You should definitely try."),
        ("वह अब ठीक से चल नहीं पाता।", "He is not able to walk properly now."),
        ("मुझे कल सुबह जल्दी निकलना होगा।", "I will have to leave early tomorrow morning."),
        ("तुम यह सवाल हल कर सकती हो।", "You can solve this question."),
        ("हमें बुज़ुर्गों की सेवा करनी चाहिए।", "We should serve the elderly."),
        ("वह तैरना सीख नहीं पाया।", "He could not manage to learn swimming."),
        ("मुझे हर रोज़ व्यायाम करना पड़ता है।", "I have to exercise every day."),
        ("आप यहाँ से सीधे जा सकते हैं।", "You can go straight from here."),
        ("उसे अपनी ग़लती मानकर माफ़ी माँगनी चाहिए।", "He should accept his mistake and apologize."),
        ("मैं इतनी दूर पैदल चल नहीं पाती।", "I cannot manage to walk that far on foot."),
        ("हमें पानी बचाना होगा।", "We will have to save water."),
    ],
    "node-15": [
        ("यह लाल साड़ी नीली साड़ी से ज़्यादा सुंदर है।", "This red saree is more beautiful than the blue saree."),
        ("ताज महल दुनिया की सबसे ख़ूबसूरत इमारतों में से एक है।", "The Taj Mahal is one of the most beautiful buildings in the world."),
        ("छोटा भाई बड़े भाई से ज़्यादा लंबा है।", "The younger brother is taller than the elder brother."),
        ("गर्मियों में दिन सर्दियों से ज़्यादा बड़े होते हैं।", "In summer, days are longer than in winter."),
        ("यह सबसे पुरानी किताब हमारे पुस्तकालय में है।", "This is the oldest book in our library."),
        ("आज का मौसम कल से बेहतर है।", "Today's weather is better than yesterday's."),
        ("मोहन उतना ही होशियार है जितना सोहन।", "Mohan is as clever as Sohan."),
        ("नई सड़क पुरानी सड़क से चौड़ी है।", "The new road is wider than the old road."),
        ("यह फ़िल्म पिछली फ़िल्म से ज़्यादा रोचक थी।", "This film was more interesting than the last film."),
        ("सबसे ऊँचा पहाड़ एवरेस्ट है।", "The tallest mountain is Everest."),
        ("इतना मीठा आम मैंने पहले कभी नहीं खाया।", "I have never eaten such a sweet mango before."),
        ("मेरे कुत्ते का रंग तुम्हारे कुत्ते से गहरा है।", "My dog's color is darker than your dog's."),
        ("यह कमरा उस कमरे से छोटा लेकिन साफ़ है।", "This room is smaller than that room but clean."),
        ("दोनों भाइयों में बड़ा भाई ज़्यादा मेहनती है।", "Among both brothers, the elder brother is more hardworking."),
        ("हिमालय की चोटियाँ बहुत ऊँची और बर्फ़ीली हैं।", "The peaks of the Himalayas are very high and snowy."),
        ("यह रास्ता उस रास्ते से कम ख़तरनाक है।", "This path is less dangerous than that path."),
        ("आज का खाना कल के खाने जैसा स्वादिष्ट नहीं था।", "Today's food was not as tasty as yesterday's food."),
        ("सबसे सस्ती चीज़ यह पेन है।", "The cheapest thing is this pen."),
        ("गाँव शहर से ज़्यादा शांत होता है।", "The village is more peaceful than the city."),
        ("तुम्हारा बगीचा हमारे बगीचे से बड़ा है।", "Your garden is bigger than our garden."),
        ("यह कपड़ा उस कपड़े से ज़्यादा मुलायम है।", "This cloth is softer than that cloth."),
        ("पुरानी दिल्ली नई दिल्ली से ज़्यादा भीड़-भाड़ वाली है।", "Old Delhi is more crowded than New Delhi."),
        ("इस बार की फ़सल पिछले साल से अच्छी रही।", "This time the harvest was better than last year."),
        ("कॉफ़ी चाय से ज़्यादा कड़वी होती है।", "Coffee is more bitter than tea."),
        ("सबसे नज़दीकी अस्पताल दो किलोमीटर दूर है।", "The nearest hospital is two kilometers away."),
        ("बच्चा बहुत ही प्यारा और समझदार है।", "The child is very cute and sensible."),
        ("दक्षिण भारत का खाना उत्तर भारत से अलग होता है।", "South Indian food is different from North Indian food."),
        ("इतनी ठंडी रात पहले कभी नहीं हुई।", "Such a cold night has never happened before."),
        ("उसका मकान सबसे ऊँची पहाड़ी पर बना है।", "His house is built on the highest hill."),
        ("यह परीक्षा पिछली परीक्षा से आसान थी।", "This exam was easier than the last exam."),
        ("मेरी दादी सबसे बुज़ुर्ग सदस्य हैं।", "My grandmother is the oldest member."),
        ("इतना शोर मैंने कभी नहीं सुना।", "I have never heard such noise."),
        ("काली मिर्च लाल मिर्च से कम तीखी होती है।", "Black pepper is less spicy than red chili."),
        ("यह कहानी उस कहानी से ज़्यादा दिलचस्प है।", "This story is more interesting than that story."),
        ("हमारे गाँव का तालाब सबसे गहरा है।", "Our village's pond is the deepest."),
        ("अमरूद सेब से ज़्यादा सस्ता मिलता है।", "Guava is available cheaper than apple."),
        ("यह साल पिछले साल से और भी गर्म रहा।", "This year was even hotter than last year."),
        ("उसकी आवाज़ सबमें सबसे मीठी है।", "Her voice is the sweetest among all."),
        ("पुराना बाज़ार नए बाज़ार से ज़्यादा रंगीन है।", "The old market is more colorful than the new market."),
        ("यह फूल उस फूल जितना सुगंधित नहीं है।", "This flower is not as fragrant as that flower."),
        ("सबसे तेज़ धावक ने सोने का तमग़ा जीता।", "The fastest runner won the gold medal."),
        ("गंगा भारत की सबसे पवित्र नदी मानी जाती है।", "The Ganges is considered the most sacred river of India."),
        ("मसालेदार खाना सादे खाने से ज़्यादा लोकप्रिय है।", "Spicy food is more popular than plain food."),
        ("उतना कठिन काम मैंने पहले कभी नहीं किया।", "I have never done such difficult work before."),
        ("छोटी बच्ची बड़ी बच्ची से ज़्यादा चंचल है।", "The younger girl is more playful than the older girl."),
        ("यह पुल शहर का सबसे लंबा पुल है।", "This bridge is the longest bridge in the city."),
    ],
    "node-16": [
        ("बचपन में हम रोज़ नदी में नहाते थे।", "In childhood, we used to bathe in the river every day."),
        ("दादी हर शाम कहानियाँ सुनाती थीं।", "Grandmother used to tell stories every evening."),
        ("पहले यहाँ खेत हुआ करते थे।", "There used to be fields here before."),
        ("वह हर रोज़ सुबह पाँच बजे उठता था।", "He used to wake up at five o'clock every morning."),
        ("हम गर्मियों की छुट्टियों में नानी के घर जाते थे।", "We used to go to grandmother's house during summer holidays."),
        ("पुराने ज़माने में लोग कुएँ से पानी भरते थे।", "In the old days, people used to draw water from wells."),
        ("माँ हर त्योहार पर मिठाइयाँ बनाती थीं।", "Mother used to make sweets on every festival."),
        ("बच्चे शाम को पार्क में खेला करते थे।", "Children used to play in the park in the evening."),
        ("दादा जी रोज़ सवेरे मंदिर जाते थे।", "Grandfather used to go to the temple every morning."),
        ("पहले यहाँ बिजली नहीं होती थी।", "Earlier there used to be no electricity here."),
        ("हम स्कूल पैदल जाया करते थे।", "We used to go to school on foot."),
        ("वह अक्सर हमारे घर आया करती थी।", "She used to visit our house often."),
        ("छोटे शहरों में लोग एक-दूसरे को जानते थे।", "In small towns, people used to know each other."),
        ("पहले दूध का दाम बहुत कम होता था।", "Earlier, the price of milk used to be very low."),
        ("उन दिनों हम साइकिल से स्कूल जाते थे।", "In those days, we used to go to school by bicycle."),
        ("मेरी माँ हर रात हमें लोरी सुनाती थी।", "My mother used to sing a lullaby to us every night."),
        ("त्योहारों पर पूरा मोहल्ला जगमगाता था।", "On festivals, the whole neighborhood used to light up."),
        ("पुराने समय में लोग पत्र लिखा करते थे।", "In old times, people used to write letters."),
        ("नदी का पानी पहले बहुत साफ़ होता था।", "The river water used to be very clean before."),
        ("चाचा जी हर गर्मी में हमें आइसक्रीम खिलाते थे।", "Uncle used to treat us to ice cream every summer."),
        ("उस गाँव में बहुत सारे पेड़ हुआ करते थे।", "There used to be many trees in that village."),
        ("बच्चे कंचों से खेला करते थे।", "Children used to play with marbles."),
        ("पापा हर शनिवार को हमें बाज़ार ले जाते थे।", "Papa used to take us to the market every Saturday."),
        ("पहले ट्रेन में इतनी भीड़ नहीं होती थी।", "Earlier, the train used not to be this crowded."),
        ("सर्दियों में हम आग के पास बैठते थे।", "In winter, we used to sit near the fire."),
        ("वह हमेशा सबकी मदद किया करता था।", "He always used to help everyone."),
        ("बाज़ार में खिलौनों की दुकान हुआ करती थी।", "There used to be a toy shop in the market."),
        ("मौसी हर महीने हमें चिट्ठी भेजती थीं।", "Aunt used to send us a letter every month."),
        ("गाँव के लोग मिलकर फ़सल काटते थे।", "Village people used to harvest crops together."),
        ("पहले के लोग ज़्यादा मेहनती हुआ करते थे।", "People in the past used to be more hardworking."),
        ("हम हर होली पर रंगों से खेलते थे।", "We used to play with colors on every Holi."),
        ("नानी हमेशा हमें प्यार से खाना खिलाती थीं।", "Grandmother always used to feed us with love."),
        ("पहले गाँवों में डॉक्टर नहीं मिलता था।", "Earlier, doctors were not available in villages."),
        ("उस ज़माने में लोग बैलगाड़ी से सफ़र करते थे।", "In that era, people used to travel by bullock cart."),
        ("हम बारिश में काग़ज़ की नावें बनाते थे।", "We used to make paper boats in the rain."),
        ("दादी हमें हर सुबह दूध पिलाती थीं।", "Grandmother used to give us milk every morning."),
        ("गर्मियों में आम के पेड़ फलों से लदे होते थे।", "In summer, mango trees used to be loaded with fruits."),
        ("शाम को मोहल्ले के बच्चे मिलकर क्रिकेट खेलते थे।", "In the evening, neighborhood children used to play cricket together."),
    ],
    "node-17": [
        ("स्टेशन जाने के लिए कौन सी बस लेनी होगी?", "Which bus will I need to take to go to the station?"),
        ("यहाँ से हवाई अड्डा कितनी दूर है?", "How far is the airport from here?"),
        ("कृपया मुझे निकटतम मेट्रो स्टेशन बताइए।", "Please tell me the nearest metro station."),
        ("इस सड़क पर सीधे जाकर दाएँ मुड़ जाइए।", "Go straight on this road and turn right."),
        ("ऑटो वाले ने हमसे ज़्यादा किराया माँगा।", "The auto driver asked us for more fare."),
        ("ट्रेन का समय बदल गया है, कृपया जाँच लीजिए।", "The train timing has changed, please check."),
        ("बस स्टॉप यहाँ से पाँच मिनट की दूरी पर है।", "The bus stop is five minutes' distance from here."),
        ("हमें अगले चौराहे पर बाएँ मुड़ना होगा।", "We will have to turn left at the next crossroads."),
        ("ट्रैफ़िक की वजह से हमें देर हो गई।", "We got late because of the traffic."),
        ("क्या यह रास्ता बाज़ार की तरफ़ जाता है?", "Does this road go towards the market?"),
        ("कृपया गाड़ी धीरे चलाइए, स्कूल का इलाक़ा है।", "Please drive slowly, this is a school area."),
        ("रेलवे स्टेशन पर बहुत भीड़ थी।", "There was a big crowd at the railway station."),
        ("आप पहले पुल पार कीजिए, फिर बाएँ मुड़िए।", "First cross the bridge, then turn left."),
        ("मेट्रो में सफ़र करना बस से ज़्यादा आरामदायक है।", "Traveling by metro is more comfortable than by bus."),
        ("टैक्सी बुक करने के लिए ऐप का इस्तेमाल कीजिए।", "Use the app to book a taxi."),
        ("मुझे हवाई अड्डे पर सुबह छह बजे पहुँचना है।", "I have to reach the airport at six in the morning."),
        ("यह गली बहुत तंग है, गाड़ी नहीं जा सकती।", "This lane is very narrow, a car cannot go through."),
        ("पैदल चलने से सेहत अच्छी रहती है।", "Walking keeps you healthy."),
        ("अगला मोड़ लेकर सीधे चले जाइए।", "Take the next turn and go straight."),
        ("इस रास्ते पर बहुत गड्ढे हैं, सँभलकर चलिए।", "There are many potholes on this road, walk carefully."),
        ("हमने नाव से नदी पार की।", "We crossed the river by boat."),
        ("साइकिल चलाकर ऑफ़िस जाना मेरी आदत है।", "It is my habit to go to the office by bicycle."),
        ("बस हर दस मिनट में आती है।", "The bus comes every ten minutes."),
        ("क्या यहाँ से रिक्शा मिल सकता है?", "Can I get a rickshaw from here?"),
        ("उस गली के अंत में एक बड़ा चौराहा है।", "At the end of that lane, there is a big crossroads."),
        ("सड़क के किनारे चलिए, बीच में ख़तरा है।", "Walk on the side of the road, it is dangerous in the middle."),
        ("फ़्लाइट दो घंटे देरी से आ रही है।", "The flight is arriving two hours late."),
        ("हम पहाड़ों पर बस से गए और वापस ट्रेन से आए।", "We went to the mountains by bus and returned by train."),
        ("यात्रा के दौरान खिड़की वाली सीट मुझे पसंद है।", "I prefer a window seat during the journey."),
        ("भीड़ में अपना सामान सँभालकर रखिए।", "Keep your belongings safe in the crowd."),
        ("पार्किंग की जगह खोजने में बहुत समय लगा।", "It took a lot of time to find a parking spot."),
        ("अगली गली में मुड़ने के बाद अस्पताल दिखेगा।", "After turning into the next lane, you will see the hospital."),
        ("वह रोज़ पैदल दो किलोमीटर चलकर दफ़्तर जाता है।", "He walks two kilometers to the office every day."),
        ("यह पुल बहुत पुराना है, सावधानी से पार कीजिए।", "This bridge is very old, cross it carefully."),
        ("ट्रेन में ऊपर वाली बर्थ ख़ाली है।", "The upper berth in the train is empty."),
        ("लाल बत्ती पर गाड़ी रोकना ज़रूरी है।", "It is necessary to stop the car at the red light."),
        ("मैंने ऑनलाइन टिकट पहले से बुक कर लिया है।", "I have already booked the ticket online."),
        ("कृपया सीट बेल्ट बाँध लीजिए।", "Please fasten your seat belt."),
        ("शहर में एक नई मेट्रो लाइन शुरू हो रही है।", "A new metro line is starting in the city."),
        ("बाएँ तरफ़ पेट्रोल पंप है, वहीं रुक जाइए।", "There is a petrol pump on the left, stop right there."),
        ("रात को सड़कें काफ़ी सुनसान हो जाती हैं।", "At night, the roads become quite deserted."),
        ("बच्चों को सड़क पार करते समय हाथ पकड़िए।", "Hold children's hands while crossing the road."),
        ("यह शॉर्टकट रास्ता है, जल्दी पहुँच जाएँगे।", "This is a shortcut route, we will reach quickly."),
        ("हमने टोल नाके पर शुल्क चुकाया।", "We paid the toll at the toll booth."),
        ("गाँव जाने के लिए कच्ची सड़क पर चलना पड़ता है।", "One has to walk on an unpaved road to go to the village."),
        ("ड्राइवर ने बहुत कुशलता से गाड़ी चलाई।", "The driver drove the car very skillfully."),
        ("शहर के बाहर एक नया बाइपास बन रहा है।", "A new bypass is being built outside the city."),
    ],
    "node-21": [
        ("जो लोग मेहनत करते हैं, वे सफल होते हैं।", "Those who work hard are successful."),
        ("जहाँ फूल खिलते हैं, वहाँ तितलियाँ आती हैं।", "Where flowers bloom, butterflies come there."),
        ("जब तक बारिश नहीं रुकती, तब तक रुकिए।", "Until the rain stops, please wait."),
        ("जो किताब तुमने दी थी, वह बहुत अच्छी थी।", "The book that you gave me was very good."),
        ("जैसा काम करोगे, वैसा फल मिलेगा।", "As you work, so shall you reap."),
        ("जिसने यह चित्र बनाया, वह बहुत प्रतिभाशाली है।", "Whoever made this painting is very talented."),
        ("जो बच्चे रोज़ पढ़ते हैं, वे परीक्षा में अच्छा करते हैं।", "Children who study daily do well in exams."),
        ("जहाँ शांति होती है, वहाँ सुख मिलता है।", "Where there is peace, there is happiness."),
        ("जब मैं छोटा था, तब दादा जी कहानियाँ सुनाते थे।", "When I was young, grandfather used to tell stories."),
        ("जो अपनी ग़लती मानता है, वह समझदार है।", "He who accepts his mistake is wise."),
        ("जिस गाँव में मैं पैदा हुआ, वह बहुत छोटा है।", "The village in which I was born is very small."),
        ("जितना पढ़ोगे, उतना सीखोगे।", "The more you read, the more you will learn."),
        ("जिनसे मैंने बात की, वे बहुत विनम्र थे।", "Those with whom I spoke were very polite."),
        ("जब चाहो तब आ सकते हो।", "You can come whenever you want."),
        ("जो दवाई डॉक्टर ने दी है, वह समय पर लीजिए।", "Take the medicine that the doctor has given on time."),
        ("जहाँ हम पहले रहते थे, वहाँ अब पार्क बन गया है।", "Where we used to live, a park has now been built."),
        ("जिसे तुम ढूँढ रहे हो, वह बाहर गया है।", "The one you are looking for has gone out."),
        ("जब तक धूप है, तब तक कपड़े सूख जाएँगे।", "The clothes will dry as long as there is sunshine."),
        ("जो मेहमान आए हैं, उनका स्वागत कीजिए।", "Please welcome the guests who have come."),
    ],
    "node-22": [
        ("इस पुस्तक को बहुत लोगों द्वारा पढ़ा गया है।", "This book has been read by many people."),
        ("नई सड़क सरकार द्वारा बनाई जा रही है।", "A new road is being built by the government."),
        ("मीटिंग कल के लिए स्थगित कर दी गई।", "The meeting was postponed until tomorrow."),
        ("गाँव में एक नया स्कूल खोला गया है।", "A new school has been opened in the village."),
        ("चोर को पुलिस द्वारा पकड़ लिया गया।", "The thief was caught by the police."),
        ("इस मंदिर का निर्माण सौ साल पहले किया गया था।", "This temple was constructed a hundred years ago."),
        ("पत्र कल भेजा जाएगा।", "The letter will be sent tomorrow."),
        ("परीक्षा के नतीजे अगले सप्ताह घोषित किए जाएँगे।", "The exam results will be announced next week."),
        ("यह फ़ैसला सबकी सहमति से लिया गया।", "This decision was taken with everyone's consent."),
        ("अस्पताल में मरीज़ों का इलाज किया जा रहा है।", "Patients are being treated in the hospital."),
        ("खाना पहले ही तैयार कर दिया गया था।", "The food had already been prepared."),
        ("बच्चों को स्कूल से जल्दी छोड़ दिया गया।", "The children were released from school early."),
        ("यह क़ानून संसद द्वारा पारित किया गया।", "This law was passed by the Parliament."),
        ("मेहमानों के लिए कमरे तैयार किए जा रहे हैं।", "Rooms are being prepared for the guests."),
        ("उसे कंपनी से निकाल दिया गया।", "He was fired from the company."),
        ("पुराने मकान को तोड़ दिया गया है।", "The old building has been demolished."),
        ("सड़क पर नए पेड़ लगाए गए हैं।", "New trees have been planted on the road."),
        ("इस विषय पर बहुत शोध किया जा चुका है।", "A lot of research has already been done on this topic."),
        ("रोगियों को समय पर दवाई दी जानी चाहिए।", "Patients should be given medicine on time."),
        ("शिकायत दर्ज कर ली गई है।", "The complaint has been registered."),
        ("यह गीत पूरे देश में गाया जाता है।", "This song is sung across the entire country."),
        ("बाढ़ से प्रभावित लोगों को बचाया गया।", "People affected by the flood were rescued."),
        ("प्रदूषण कम करने के लिए कई उपाय किए जा रहे हैं।", "Many measures are being taken to reduce pollution."),
        ("उम्मीदवारों को साक्षात्कार के लिए बुलाया गया है।", "The candidates have been called for an interview."),
        ("मंच पर कार्यक्रम की तैयारी की जा रही है।", "Preparations for the program are being made on stage."),
        ("पार्क में बच्चों के लिए झूले लगाए गए हैं।", "Swings have been installed for children in the park."),
        ("इस क्षेत्र में पहले कभी खेती नहीं की गई थी।", "Farming had never been done in this area before."),
        ("उनकी नई किताब पिछले महीने प्रकाशित की गई।", "Their new book was published last month."),
        ("यह पुरस्कार हर साल दिया जाता है।", "This award is given every year."),
        ("सभी टिकटें पहले ही बेच दी गई हैं।", "All the tickets have already been sold."),
        ("मुख्य सड़क की मरम्मत की जा रही है।", "The main road is being repaired."),
        ("सम्मेलन में कई महत्वपूर्ण विषयों पर चर्चा की गई।", "Many important topics were discussed at the conference."),
        ("नदी में मछली पकड़ने पर प्रतिबंध लगाया गया है।", "A ban has been imposed on fishing in the river."),
        ("भोजन मेज़ पर परोसा जा चुका है।", "The food has been served on the table."),
        ("छात्रों को प्रतियोगिता में भाग लेने के लिए चुना गया।", "Students were selected to participate in the competition."),
        ("मरम्मत का काम पूरा कर लिया गया है।", "The repair work has been completed."),
        ("यहाँ नई इमारत बनाई जाएगी।", "A new building will be constructed here."),
        ("पूरे शहर में सफ़ाई अभियान चलाया गया।", "A cleanliness campaign was run across the city."),
        ("ग़रीबों को राशन बाँटा गया है।", "Rations have been distributed to the poor."),
        ("खिलाड़ियों को पदक से सम्मानित किया गया।", "The players were honored with medals."),
        ("इस फ़िल्म को कई पुरस्कारों से नवाज़ा गया।", "This film was bestowed with several awards."),
        ("उसे अस्पताल में भर्ती कर लिया गया है।", "He/she has been admitted to the hospital."),
        ("सार्वजनिक छुट्टी की घोषणा की गई है।", "A public holiday has been announced."),
        ("सभी दरवाज़े शाम को बंद कर दिए जाते हैं।", "All doors are closed in the evening."),
        ("खेल का आयोजन अगले रविवार को किया जाएगा।", "The sports event will be organized next Sunday."),
        ("ज़रूरतमंदों को कंबल और कपड़े बाँटे गए।", "Blankets and clothes were distributed to the needy."),
        ("सड़क दुर्घटना में तीन लोग घायल हुए और उन्हें अस्पताल ले जाया गया।", "Three people were injured in a road accident and taken to the hospital."),
        ("इस जगह को ऐतिहासिक धरोहर घोषित किया गया है।", "This place has been declared a historical heritage site."),
        ("आवेदन पत्र जमा कर दिए गए हैं।", "The application forms have been submitted."),
        ("त्योहार की तैयारी ज़ोर-शोर से की जा रही है।", "Festival preparations are being done enthusiastically."),
        ("बस सेवा अस्थायी रूप से बंद कर दी गई है।", "The bus service has been temporarily suspended."),
        ("आरोपी को ज़मानत दे दी गई।", "The accused was granted bail."),
        ("पेड़ों को कटने से बचाने के लिए याचिका दायर की गई।", "A petition was filed to save the trees from being cut."),
        ("विद्यालय को सर्वश्रेष्ठ विद्यालय का पुरस्कार दिया गया।", "The school was given the award of the best school."),
        ("चुनाव की तारीख़ की घोषणा कर दी गई है।", "The election date has been announced."),
        ("सड़क पर नई लाइटें लगाई गई हैं।", "New lights have been installed on the road."),
        ("उसकी ज़मीन पर अवैध निर्माण किया गया था।", "Illegal construction was done on his land."),
        ("पुलिस द्वारा इलाक़े की जाँच की जा रही है।", "The area is being investigated by the police."),
        ("सभी यात्रियों को सुरक्षित निकाल लिया गया।", "All passengers were safely evacuated."),
        ("इस मामले की जाँच उच्च अधिकारियों द्वारा की जा रही है।", "This case is being investigated by senior officers."),
        ("पुराने नियम बदलकर नए नियम लागू किए गए हैं।", "Old rules have been changed and new rules have been implemented."),
        ("पत्रिका में उनका लेख प्रकाशित किया गया।", "Their article was published in the magazine."),
        ("गाँव में सड़क, बिजली और पानी की व्यवस्था की गई।", "Arrangements for road, electricity, and water were made in the village."),
        ("राहत सामग्री हेलीकॉप्टर से भेजी गई।", "Relief material was sent by helicopter."),
        ("यह आयोजन हर साल बड़े उत्साह से मनाया जाता है।", "This event is celebrated with great enthusiasm every year."),
        ("कार्यालय में नए कंप्यूटर लगाए गए हैं।", "New computers have been installed in the office."),
        ("बच्चों के लिए विशेष कार्यक्रम आयोजित किया गया।", "A special program was organized for children."),
        ("बारिश के कारण मैच रद्द कर दिया गया।", "The match was canceled due to rain."),
        ("शहर में कई जगह सीसीटीवी कैमरे लगाए गए हैं।", "CCTV cameras have been installed at many places in the city."),
    ],
    "node-24": [
        ("कल हम सब मिलकर पिकनिक पर जाएँगे।", "Tomorrow we will all go on a picnic together."),
        ("अगले साल मैं विदेश में पढ़ाई करूँगी।", "Next year I will study abroad."),
        ("शायद वे लोग शाम तक आ जाएँगे।", "Perhaps those people will come by evening."),
        ("अगर मौसम अच्छा रहा तो हम बाहर खेलेंगे।", "If the weather is good, we will play outside."),
        ("मैं तुम्हें कल सुबह फ़ोन करूँगा।", "I will call you tomorrow morning."),
        ("बच्चे बड़े होकर क्या बनेंगे?", "What will the children become when they grow up?"),
        ("हम इस परियोजना को समय पर पूरा करेंगे।", "We will complete this project on time."),
        ("क्या तुम मेरे साथ बाज़ार चलोगे?", "Will you come to the market with me?"),
        ("वह ज़रूर अपना वादा निभाएगा।", "He will definitely keep his promise."),
        ("अगले महीने नई दुकान खुलेगी।", "A new shop will open next month."),
        ("मैं यह काम कल तक ज़रूर कर दूँगा।", "I will definitely do this work by tomorrow."),
        ("वे लोग अगले हफ़्ते दिल्ली से लौटेंगे।", "Those people will return from Delhi next week."),
        ("बारिश होगी तो फ़सल अच्छी होगी।", "If it rains, the crop will be good."),
        ("मैं शाम को तुम्हारे घर आऊँगी।", "I will come to your house in the evening."),
        ("सरकार नया पुल बनाएगी।", "The government will build a new bridge."),
        ("क्या तुम कल की पार्टी में जाओगी?", "Will you go to tomorrow's party?"),
        ("वह जल्दी ठीक हो जाएगा, चिंता मत करो।", "He will recover soon, don't worry."),
        ("अगर हम जल्दी निकलेंगे तो समय पर पहुँचेंगे।", "If we leave early, we will reach on time."),
        ("शायद कल बारिश होगी।", "Maybe it will rain tomorrow."),
        ("मैं अगले साल गाँव ज़रूर आऊँगा।", "I will definitely come to the village next year."),
        ("बच्चे इस खेल में बहुत मज़ा करेंगे।", "The children will have a lot of fun in this game."),
        ("हम मिलकर यह समस्या हल करेंगे।", "We will solve this problem together."),
        ("उसकी नई किताब जल्दी ही बाज़ार में आएगी।", "His new book will come to the market soon."),
        ("नतीजे अगले सोमवार को आएँगे।", "The results will come on next Monday."),
        ("क्या तुम इस बार दिवाली पर घर आओगे?", "Will you come home for Diwali this time?"),
        ("वह अपनी ग़लती ज़रूर सुधारेगा।", "He will definitely correct his mistake."),
        ("मैं तुम्हारी बात कभी नहीं भूलूँगा।", "I will never forget your words."),
        ("सर्दियों में दिन जल्दी छोटे हो जाएँगे।", "In winter, the days will become shorter quickly."),
        ("अगले महीने से नया नियम लागू होगा।", "The new rule will be implemented from next month."),
        ("यह पौधा बड़ा होकर सुंदर फूल देगा।", "This plant will give beautiful flowers when it grows."),
        ("हम इस बार की छुट्टियों में पहाड़ों पर जाएँगे।", "We will go to the mountains on this vacation."),
        ("वह कल सुबह तक रिपोर्ट तैयार कर देगा।", "He will prepare the report by tomorrow morning."),
        ("अगर हम साथ मिलकर काम करेंगे तो सफल होंगे।", "If we work together, we will succeed."),
        ("क्या तुम मुझे यह सिखाओगे?", "Will you teach me this?"),
        ("जल्दी ही सब ठीक हो जाएगा।", "Everything will be fine soon."),
        ("माँ शाम को हमारे लिए कुछ ख़ास बनाएँगी।", "Mother will make something special for us in the evening."),
        ("वे अगले सप्ताह तक जवाब दे देंगे।", "They will give a reply by next week."),
    ],
    "node-30": [
        ("हृदय और दिल दोनों एक ही अर्थ रखते हैं।", "Hriday and dil both carry the same meaning."),
        ("सरकारी दस्तावेज़ों में संस्कृतनिष्ठ हिंदी का प्रयोग होता है।", "Sanskritized Hindi is used in government documents."),
        ("इश्क़ और प्रेम दोनों प्यार के पर्यायवाची हैं।", "Ishq and prem are both synonyms for love."),
        ("न्यायालय में कार्यवाही हिंदी में संचालित की गई।", "The proceedings were conducted in Hindi in the court."),
        ("उसने अपनी ज़िंदगी का सबसे मुश्किल फ़ैसला लिया।", "He made the most difficult decision of his life."),
        ("विद्यालय में छात्रों को नई शिक्षा नीति के बारे में बताया गया।", "Students were informed about the new education policy in the school."),
        ("वह बाज़ार से सब्ज़ी और मसाले लेकर आई।", "She came from the market with vegetables and spices."),
        ("दफ़्तर में सब लोग बहुत व्यस्त थे।", "Everyone in the office was very busy."),
        ("किताबों की दुकानदार ने हमें अच्छी सलाह दी।", "The bookshop owner gave us good advice."),
        ("संसद में नए विधेयक पर बहस हुई।", "There was a debate on the new bill in the Parliament."),
        ("आज रात ख़्वाब में मैंने अपना गाँव देखा।", "Tonight in my dream I saw my village."),
        ("प्रतीक्षा करने से बेहतर है कि हम ख़ुद चलें।", "It is better to go ourselves than to wait."),
        ("उनकी ज़िम्मेदारी बहुत बड़ी है।", "His responsibility is very big."),
        ("कार्यकर्ताओं ने पर्यावरण के लिए अभियान चलाया।", "The workers ran a campaign for the environment."),
        ("शहर के मुनासिब इलाक़े में नई दुकान खोली गई।", "A new shop was opened in a suitable area of the city."),
        ("विकास के लिए सरकार ने नई योजना की घोषणा की।", "The government announced a new scheme for development."),
        ("उसने अपने दोस्त से इंतज़ार करने को कहा।", "He asked his friend to wait."),
        ("महोदय, कृपया अपना परिचय दीजिए।", "Sir, please introduce yourself."),
        ("आज का समाचार बहुत चिंताजनक था।", "Today's news was very worrying."),
        ("लोगों ने सरकार से न्याय की माँग की।", "People demanded justice from the government."),
        ("मदद और सहायता दोनों शब्द रोज़मर्रा में इस्तेमाल होते हैं।", "Both madad and sahayata are used in everyday language."),
        ("अदालत ने इस मामले में कड़ा फ़ैसला सुनाया।", "The court pronounced a strict decision in this case."),
        ("पर्यावरण संरक्षण सबकी ज़िम्मेदारी है।", "Environmental conservation is everyone's responsibility."),
        ("फ़िल्मों में जुनून और इश्क़ बहुत दिखाया जाता है।", "Passion and love are shown a lot in films."),
        ("शिक्षा और तालीम दोनों एक ही बात है।", "Shiksha and taleem both mean the same thing."),
        ("वह मोहब्बत और प्रेम दोनों शब्द समझता है।", "He understands both mohabbat and prem."),
        ("सरकारी भाषा में प्रधानमंत्री लिखते हैं, बोलचाल में पीएम।", "In official language they write Pradhanmantri, in speech PM."),
        ("दुकानदार ने हमें उचित दाम पर सामान दिया।", "The shopkeeper gave us goods at a fair price."),
        ("कृपा करके मेरी बात सुनिए।", "Kindly listen to what I have to say."),
        ("इस्तेमाल और उपयोग दोनों रोज़ बोले जाते हैं।", "Both istemaal and upyog are spoken daily."),
        ("वकील ने अधिनियम की धारा का हवाला दिया।", "The lawyer cited the section of the act."),
        ("गाने में अदा और जुनून जैसे शब्द आम हैं।", "Words like ada and junoon are common in songs."),
        ("मेहरबानी करके इस फ़ॉर्म को भर दीजिए।", "Please be kind enough to fill out this form."),
        ("आवश्यकता पड़ने पर मदद माँगना ग़लत नहीं है।", "It is not wrong to ask for help when needed."),
        ("जीवन और ज़िंदगी दोनों में संघर्ष है।", "Both jeevan and zindagi involve struggle."),
        ("दफ़्तर के बजाय कार्यालय लिखना ज़्यादा औपचारिक है।", "Writing karyalaya instead of daftar is more formal."),
        ("रक्त और ख़ून दोनों अलग-अलग भाषाई स्रोतों से आए हैं।", "Both rakt and khoon come from different linguistic sources."),
        ("स्वप्न साहित्य में और ख़्वाब बोलचाल में ज़्यादा आता है।", "Swapn appears more in literature and khwab more in speech."),
        ("हिस्सेदारों को बराबर अधिकार मिलने चाहिए।", "Stakeholders should get equal rights."),
        ("आज के प्रमुख समाचार इस प्रकार हैं।", "Today's main news items are as follows."),
        ("उन्होंने अपनी ग़ज़ल में मोहब्बत का बयान किया।", "He expressed love in his ghazal."),
        ("प्रतीक्षा करने में धैर्य चाहिए।", "Patience is needed in waiting."),
        ("नई परियोजना के लिए सूत्रधार की ज़रूरत है।", "A coordinator is needed for the new project."),
        ("उसने अपनी अदा से सबको मंत्रमुग्ध कर दिया।", "She mesmerized everyone with her charm."),
        ("विधेयक पर सांसदों ने गहन चर्चा की।", "Members of Parliament had an intense discussion on the bill."),
        ("बच्चों को दोनों शैलियों के शब्द सिखाने चाहिए।", "Children should be taught words from both styles."),
        ("उर्दू और हिंदी के मिश्रण को हिंदुस्तानी कहते हैं।", "The mixture of Urdu and Hindi is called Hindustani."),
        ("औपचारिक पत्र में संस्कृत शब्दावली ज़्यादा प्रयुक्त होती है।", "Sanskrit vocabulary is used more in formal letters."),
        ("ग़ज़ल और कविता दोनों में भावनाएँ व्यक्त होती हैं।", "Emotions are expressed in both ghazal and poetry."),
        ("समाज में सबको बराबर अवसर मिलने चाहिए।", "Everyone in society should get equal opportunities."),
        ("तहज़ीब और संस्कृति दोनों सभ्यता के पर्यायवाची हैं।", "Both tahzeeb and sanskriti are synonyms for civilization."),
        ("नेता ने जनता से वादा और प्रतिज्ञा दोनों की।", "The leader made both a promise and a pledge to the people."),
        ("रोज़ाना की भाषा में फ़ारसी शब्द बहुत आम हैं।", "Persian words are very common in everyday language."),
        ("क़ानून और विधि दोनों अलग भाषाई परंपराओं से हैं।", "Both qanoon and vidhi come from different linguistic traditions."),
        ("उन्होंने हिंदी साहित्य में अमूल्य योगदान दिया।", "He made invaluable contribution to Hindi literature."),
        ("ख़बर और समाचार दोनों हर दिन सुनने को मिलते हैं।", "Both khabar and samachar are heard every day."),
        ("इंतज़ाम और व्यवस्था दोनों का मतलब एक ही है।", "Both intezaam and vyavastha mean the same thing."),
        ("उसने बड़ी हिम्मत और साहस से काम किया।", "He worked with great courage and bravery."),
    ],
    "node-32": [
        ("तथापि, यह नियम सभी पर लागू होता है।", "Nevertheless, this rule applies to everyone."),
        ("अतः हमें इस विषय पर गंभीरता से विचार करना चाहिए।", "Therefore, we should think seriously about this topic."),
        ("यद्यपि वह थका हुआ था, तथापि उसने काम पूरा किया।", "Although he was tired, nevertheless he completed the work."),
        ("महोदय, आपका यह प्रस्ताव स्वीकार्य है।", "Sir, your proposal is acceptable."),
        ("मानवता की सेवा ही सबसे बड़ा धर्म है।", "Service to humanity is the greatest duty."),
        ("नेतृत्व का गुण हर किसी में नहीं होता।", "The quality of leadership is not in everyone."),
        ("पर्यावरण संरक्षण हमारा सामूहिक दायित्व है।", "Environmental conservation is our collective responsibility."),
        ("जनसंख्या वृद्धि एक गंभीर समस्या बनती जा रही है।", "Population growth is becoming a serious problem."),
        ("उक्त विषय पर विस्तृत चर्चा की गई।", "A detailed discussion was held on the aforementioned topic."),
        ("निम्नलिखित नियमों का पालन अनिवार्य है।", "Following the rules mentioned below is mandatory."),
        ("शिक्षा का उद्देश्य मानव विकास होना चाहिए।", "The purpose of education should be human development."),
        ("प्रगति के लिए सामूहिक प्रयास आवश्यक है।", "Collective effort is necessary for progress."),
        ("अनुमान के अनुसार यह योजना सफल होगी।", "According to estimates, this plan will be successful."),
        ("इस लेख में भाषा की विविधता पर प्रकाश डाला गया है।", "This article sheds light on linguistic diversity."),
        ("साहित्य में भाषा का सौंदर्य देखा जा सकता है।", "The beauty of language can be seen in literature."),
        ("किंतु इस निर्णय पर पुनर्विचार की आवश्यकता है।", "But there is a need to reconsider this decision."),
        ("गांधी जी ने कहा था कि सत्य ही ईश्वर है।", "Gandhi ji had said that truth is God."),
        ("अर्थात् इस विषय में और अधिक शोध की आवश्यकता है।", "That is to say, more research is needed on this topic."),
        ("विद्यार्थियों को स्वावलंबी बनना चाहिए।", "Students should become self-reliant."),
        ("सर्वप्रथम, हमें इस समस्या को पहचानना होगा।", "First of all, we will have to identify this problem."),
        ("भारतीय संस्कृति विविधताओं से भरी हुई है।", "Indian culture is full of diversities."),
        ("तत्पश्चात् उन्होंने अपना भाषण समाप्त किया।", "Thereafter, he concluded his speech."),
        ("राजधानी में नए विधेयक पर विमर्श हो रहा है।", "A deliberation is happening on the new bill in the capital."),
        ("इस ग्रंथ की रचना सौ वर्ष पूर्व हुई थी।", "This text was composed a hundred years ago."),
        ("परंतु इस प्रश्न का उत्तर सरल नहीं है।", "But the answer to this question is not simple."),
        ("शब्दावली को समृद्ध बनाने से लेखन में सुधार होता है।", "Enriching vocabulary improves writing."),
        ("इसके अतिरिक्त, कई अन्य कारण भी हैं।", "In addition to this, there are several other reasons."),
        ("पूर्णविराम हिंदी लेखन में विराम चिह्न का मुख्य भाग है।", "The full stop is the main punctuation mark in Hindi writing."),
        ("वि- उपसर्ग से विशेष, विज्ञान, विद्या जैसे शब्द बनते हैं।", "Words like special, science, knowledge are formed with the prefix vi-."),
        ("सामाजिक न्याय एक महत्वपूर्ण राष्ट्रीय विषय है।", "Social justice is an important national topic."),
        ("साहित्यिक भाषा बोलचाल से भिन्न होती है।", "Literary language differs from colloquial speech."),
        ("लोकतंत्र में जनता की भागीदारी अनिवार्य है।", "People's participation is essential in democracy."),
        ("प्रत्येक नागरिक को अपने अधिकारों का ज्ञान होना चाहिए।", "Every citizen should have knowledge of their rights."),
        ("वैश्विक स्तर पर पर्यावरण चिंता का विषय है।", "Environment is a matter of concern at the global level."),
        ("इस पुस्तक की भूमिका बहुत विचारपूर्ण है।", "The preface of this book is very thoughtful."),
        ("संपादक ने लेख में कई सुधार सुझाए।", "The editor suggested several improvements in the article."),
        ("तदनुसार, सभी संबंधित विभागों को सूचित किया जाए।", "Accordingly, all concerned departments should be informed."),
        ("हिंदी दिवस पर भाषा के महत्व पर चर्चा हुई।", "There was a discussion on the importance of language on Hindi Day."),
        ("आत्मनिर्भरता राष्ट्र की प्रगति का आधार है।", "Self-reliance is the foundation of national progress."),
        ("औपचारिक लेखन में दूरभाष लिखना उचित है।", "Writing doorbhash is appropriate in formal writing."),
        ("नवीनतम आँकड़े इस बात की पुष्टि करते हैं।", "The latest data confirms this fact."),
        ("एतद्द्वारा सूचित किया जाता है कि कार्यालय बंद रहेगा।", "It is hereby informed that the office will remain closed."),
        ("वाक्य-विन्यास का अध्ययन भाषाविज्ञान का अंग है।", "The study of syntax is a part of linguistics."),
        ("प्रस्तावना में लेखक ने अपने उद्देश्य स्पष्ट किए।", "In the preamble, the author clarified his objectives."),
        ("समीक्षक ने इस कृति की बहुत सराहना की।", "The critic highly appreciated this work."),
        ("उपर्युक्त तथ्यों के आधार पर निर्णय लिया गया।", "The decision was taken on the basis of the above facts."),
        ("क्रियाविशेषण वाक्य में क्रिया की विशेषता बताता है।", "An adverb describes the quality of a verb in a sentence."),
        ("मुहावरे भाषा को जीवंत और रोचक बनाते हैं।", "Idioms make language lively and interesting."),
        ("समास हिंदी व्याकरण का एक महत्वपूर्ण अंग है।", "Compound words are an important part of Hindi grammar."),
        ("अलंकार काव्य की शोभा बढ़ाते हैं।", "Figures of speech enhance the beauty of poetry."),
        ("तत्सम शब्द सीधे संस्कृत से लिए गए हैं।", "Tatsam words are taken directly from Sanskrit."),
        ("तद्भव शब्द संस्कृत से बदलकर हिंदी में आए हैं।", "Tadbhav words came into Hindi after changing from Sanskrit."),
        ("देशज शब्द स्थानीय भाषाओं से उत्पन्न हुए हैं।", "Deshaj words originated from local languages."),
        ("संज्ञा, सर्वनाम, क्रिया हिंदी व्याकरण के मूल तत्व हैं।", "Noun, pronoun, verb are fundamental elements of Hindi grammar."),
        ("पद्य और गद्य साहित्य की दो प्रमुख विधाएँ हैं।", "Verse and prose are two major forms of literature."),
        ("वचन हिंदी में एकवचन और बहुवचन दो प्रकार के होते हैं।", "Number in Hindi is of two types: singular and plural."),
        ("निबंध लेखन में विषय का विश्लेषण आवश्यक है।", "Analysis of the topic is necessary in essay writing."),
        ("रचनाकार ने समाज की विसंगतियों पर कटाक्ष किया।", "The author satirized the contradictions of society."),
        ("हिंदी साहित्य का आदिकाल बहुत समृद्ध था।", "The early period of Hindi literature was very rich."),
    ],
    "node-33": [
        ("इस शोध-पत्र में भाषा-विज्ञान के नए सिद्धांत प्रस्तुत किए गए हैं।", "New theories of linguistics have been presented in this research paper."),
        ("प्रस्तुत अध्ययन का उद्देश्य ग्रामीण शिक्षा का विश्लेषण करना है।", "The objective of the present study is to analyze rural education."),
        ("संभवतः यह परिकल्पना सही है, लेकिन और प्रमाण चाहिए।", "Possibly this hypothesis is correct, but more evidence is needed."),
        ("तालिका संख्या तीन में आँकड़े दिए गए हैं।", "The data has been given in table number three."),
        ("निष्कर्ष के रूप में यह कहा जा सकता है कि शिक्षा महत्वपूर्ण है।", "In conclusion, it can be said that education is important."),
        ("इस शोध की प्रविधि गुणात्मक विश्लेषण पर आधारित है।", "The methodology of this research is based on qualitative analysis."),
        ("पूर्व अध्ययनों ने इस विषय पर विभिन्न दृष्टिकोण प्रस्तुत किए हैं।", "Previous studies have presented various perspectives on this topic."),
        ("सह-संबंध विश्लेषण से पता चलता है कि दोनों चर जुड़े हैं।", "Correlation analysis shows that both variables are linked."),
        ("प्रश्नावली के माध्यम से दो सौ उत्तरदाताओं से डेटा एकत्र किया गया।", "Data was collected from two hundred respondents through a questionnaire."),
        ("अनुभवजन्य साक्ष्य इस सिद्धांत का समर्थन करते हैं।", "Empirical evidence supports this theory."),
        ("सारांशतः, यह अध्ययन ग्रामीण विकास पर केंद्रित है।", "In summary, this study is focused on rural development."),
        ("साहित्य-समीक्षा में पूर्ववर्ती शोधों का अवलोकन किया गया।", "Previous research was reviewed in the literature review."),
        ("इस अध्याय में शोध-प्रविधि का विस्तृत विवरण दिया गया है।", "A detailed description of the research methodology is given in this chapter."),
        ("मूल्यांकन के आधार पर यह कार्यक्रम सफल रहा।", "Based on the evaluation, this program was successful."),
        ("प्रतिदर्श का चयन यादृच्छिक विधि से किया गया।", "The sample was selected using a random method."),
        ("पारिभाषिक शब्दावली का सही उपयोग शोध में अनिवार्य है।", "Correct use of technical terminology is essential in research."),
        ("कारण-परिणाम संबंध को स्पष्ट करना इस शोध का लक्ष्य है।", "Clarifying the cause-effect relationship is the goal of this research."),
        ("यथा, भारत की जनसंख्या विश्व में दूसरे स्थान पर है।", "For example, India's population ranks second in the world."),
        ("उपरोक्त तथ्यों से यह स्पष्ट होता है कि बदलाव ज़रूरी है।", "From the above facts, it becomes clear that change is necessary."),
        ("फलस्वरूप, शिक्षा प्रणाली में सुधार देखा गया।", "Consequently, improvement was seen in the education system."),
        ("इसके अतिरिक्त, सामाजिक कारकों पर भी विचार करना आवश्यक है।", "In addition, it is necessary to consider social factors as well."),
        ("शोधार्थी ने साक्षात्कार विधि का उपयोग किया।", "The researcher used the interview method."),
        ("आरेख संख्या दो में परिणाम दर्शाए गए हैं।", "The results are shown in diagram number two."),
        ("परिशिष्ट में अतिरिक्त सामग्री दी गई है।", "Additional material is given in the appendix."),
        ("तुलनात्मक अध्ययन से दोनों विधियों की विशेषताएँ स्पष्ट हुईं।", "The comparative study clarified the features of both methods."),
        ("व्याख्यात्मक शोध में घटनाओं के कारणों की खोज की जाती है।", "Explanatory research investigates the causes of phenomena."),
        ("संदर्भ सूची में सभी स्रोतों का उल्लेख किया गया है।", "All sources have been mentioned in the reference list."),
        ("उद्धरण चिह्नों का सही प्रयोग शोध-लेखन में अनिवार्य है।", "Correct use of quotation marks is essential in research writing."),
        ("खंड दो में सैद्धांतिक पृष्ठभूमि प्रस्तुत की गई है।", "The theoretical background is presented in section two."),
        ("मात्रात्मक विश्लेषण ने स्पष्ट परिणाम दिए।", "Quantitative analysis provided clear results."),
        ("इस विषय पर पर्याप्त साहित्य उपलब्ध नहीं है।", "Sufficient literature is not available on this topic."),
        ("पूर्वोक्त सिद्धांत इस संदर्भ में लागू नहीं होता।", "The previously stated theory does not apply in this context."),
        ("शोध-निर्देशक ने शोधार्थी को उचित मार्गदर्शन दिया।", "The research supervisor gave appropriate guidance to the researcher."),
        ("समीक्षा से ज्ञात होता है कि अधिकांश अध्ययन सकारात्मक हैं।", "The review shows that most studies are positive."),
        ("निष्कर्षतः, यह कहा जा सकता है कि प्रयोग सफल रहा।", "In conclusion, it can be said that the experiment was successful."),
        ("चर्चा अध्याय में परिणामों की व्याख्या की गई है।", "The results have been interpreted in the discussion chapter."),
        ("अध्ययन की सीमाएँ भी स्वीकार की गई हैं।", "The limitations of the study have also been acknowledged."),
        ("भविष्य के शोध के लिए कई सुझाव दिए गए हैं।", "Several suggestions have been given for future research."),
        ("डेटा संग्रहण की प्रक्रिया तीन महीने तक चली।", "The data collection process lasted three months."),
        ("सांख्यिकीय विश्लेषण एसपीएसएस सॉफ़्टवेयर से किया गया।", "Statistical analysis was done using SPSS software."),
        ("शोध-प्रश्न स्पष्ट और सुपरिभाषित होने चाहिए।", "Research questions should be clear and well-defined."),
        ("चर को स्वतंत्र और आश्रित में वर्गीकृत किया गया।", "Variables were classified into independent and dependent."),
        ("वैधता और विश्वसनीयता शोध-उपकरण के दो मुख्य गुण हैं।", "Validity and reliability are two main qualities of a research tool."),
        ("अवलोकन विधि में शोधकर्ता प्रत्यक्ष रूप से डेटा एकत्र करता है।", "In the observation method, the researcher collects data directly."),
        ("केस स्टडी विधि से गहन विश्लेषण संभव होता है।", "In-depth analysis is possible through the case study method."),
        ("शोध-प्रविधि का चयन अध्ययन के उद्देश्य पर निर्भर करता है।", "The choice of research methodology depends on the study's objective."),
        ("प्राथमिक और द्वितीयक दोनों स्रोतों का उपयोग किया गया।", "Both primary and secondary sources were used."),
        ("प्रत्युत्तर दर अस्सी प्रतिशत से अधिक रही।", "The response rate was more than eighty percent."),
        ("सामग्री विश्लेषण विधि से पाठ्य-सामग्री का अध्ययन किया गया।", "Textual material was studied through the content analysis method."),
        ("अनुसंधान नैतिकता का पालन सभी चरणों में किया गया।", "Research ethics were followed at all stages."),
        ("शोध-अंतराल को भरने के लिए यह अध्ययन किया गया।", "This study was conducted to fill the research gap."),
        ("नमूना आकार सांख्यिकीय रूप से पर्याप्त था।", "The sample size was statistically adequate."),
        ("गुणात्मक डेटा को कोडिंग के माध्यम से विश्लेषित किया गया।", "Qualitative data was analyzed through coding."),
        ("बहु-चर विश्लेषण ने जटिल संबंधों को स्पष्ट किया।", "Multi-variable analysis clarified complex relationships."),
        ("मिश्रित-विधि शोध में गुणात्मक और मात्रात्मक दोनों शामिल हैं।", "Mixed-method research includes both qualitative and quantitative."),
        ("परिणामों की सामान्यीकरणीयता इस शोध की एक सीमा है।", "Generalizability of results is a limitation of this research."),
        ("प्रायोगिक समूह और नियंत्रण समूह में अंतर देखा गया।", "A difference was observed between the experimental and control groups."),
        ("अंतर-विषयक दृष्टिकोण से समस्या को समझना आसान हुआ।", "Understanding the problem became easier with an interdisciplinary approach."),
        ("शोध का सामाजिक महत्व इसकी प्रासंगिकता को बढ़ाता है।", "The social significance of the research enhances its relevance."),
        ("सैद्धांतिक ढाँचा इस अध्ययन की नींव है।", "The theoretical framework is the foundation of this study."),
        ("विश्लेषण के परिणाम परिकल्पना की पुष्टि करते हैं।", "The results of the analysis confirm the hypothesis."),
        ("शोध-पत्रिका में प्रकाशन के लिए सहकर्मी समीक्षा आवश्यक है।", "Peer review is necessary for publication in a research journal."),
        ("लेखक ने अपने शोध में नवीन दृष्टिकोण अपनाया।", "The author adopted a novel approach in his research."),
        ("आँकड़ों का त्रिभुजीकरण शोध की विश्वसनीयता बढ़ाता है।", "Triangulation of data enhances the reliability of research."),
        ("चयनित प्रतिदर्श शहरी और ग्रामीण दोनों क्षेत्रों से था।", "The selected sample was from both urban and rural areas."),
        ("शोध-प्रस्ताव को विश्वविद्यालय की नैतिकता समिति ने अनुमोदित किया।", "The research proposal was approved by the university's ethics committee."),
        ("अध्ययन की पुनरावृत्ति से परिणामों की पुष्टि हो सकती है।", "Replication of the study can confirm the results."),
        ("क्षेत्रीय सर्वेक्षण में कई चुनौतियाँ सामने आईं।", "Several challenges were encountered in the field survey."),
        ("शोध-पत्र की संरचना में सार, भूमिका और निष्कर्ष शामिल हैं।", "The structure of a research paper includes abstract, introduction, and conclusion."),
        ("सैद्धांतिक और व्यावहारिक दोनों पहलुओं पर ध्यान दिया गया।", "Attention was paid to both theoretical and practical aspects."),
        ("शोध-कार्य में समय-प्रबंधन अत्यंत महत्वपूर्ण है।", "Time management is extremely important in research work."),
        ("डेटा प्रस्तुतीकरण में ग्राफ़ और चार्ट का उपयोग किया गया।", "Graphs and charts were used in data presentation."),
        ("सांस्कृतिक संदर्भ में इस सिद्धांत की प्रासंगिकता जाँची गई।", "The relevance of this theory was examined in a cultural context."),
        ("अध्ययन के निहितार्थ शैक्षिक नीति के लिए महत्वपूर्ण हैं।", "The implications of the study are significant for educational policy."),
    ],
    "node-34": [
        ("भारत में अतिथि का सम्मान करना सबसे बड़ा धर्म माना जाता है।", "In India, respecting the guest is considered the greatest duty."),
        ("रक्षाबंधन पर बहन भाई की कलाई पर राखी बाँधती है।", "On Rakshabandhan, the sister ties a rakhi on the brother's wrist."),
        ("दिवाली पर पूरा घर दीयों और रंगोलियों से सजाया जाता है।", "On Diwali, the whole house is decorated with lamps and rangolis."),
        ("बड़ों के पैर छूना भारतीय संस्कृति में सम्मान का प्रतीक है।", "Touching elders' feet is a symbol of respect in Indian culture."),
        ("होली पर लोग रंगों से खेलते और मिठाइयाँ बाँटते हैं।", "On Holi, people play with colors and distribute sweets."),
        ("संयुक्त परिवार में रहने से बच्चों को संस्कार मिलते हैं।", "Living in a joint family gives children good values."),
        ("जुगाड़ से उसने टूटी साइकिल को फिर से चालू कर दिया।", "With jugaad, he got the broken bicycle running again."),
        ("भारतीय विवाह में कई दिनों तक रस्में चलती हैं।", "In Indian weddings, rituals continue for several days."),
        ("छठ पूजा में सूर्य देव की उपासना की जाती है।", "In Chhath Puja, the Sun God is worshipped."),
        ("भारत में चाय पीना सामाजिक जुड़ाव का हिस्सा है।", "In India, drinking tea is a part of social connection."),
        ("गाँवों में अभी भी चौपाल की परंपरा जीवित है।", "The tradition of chaupal is still alive in villages."),
        ("नमस्ते कहते समय दोनों हाथ जोड़कर सिर झुकाया जाता है।", "When saying namaste, both hands are joined and the head is bowed."),
        ("बसंत पंचमी पर सरस्वती पूजा का विशेष महत्व है।", "Saraswati Puja holds special significance on Basant Panchami."),
        ("करवा चौथ पर पत्नी पति की लंबी उम्र के लिए व्रत रखती है।", "On Karwa Chauth, the wife fasts for the long life of the husband."),
        ("भारतीय घरों में तुलसी का पौधा पवित्र माना जाता है।", "The tulsi plant is considered sacred in Indian homes."),
        ("ईद पर सेवइयाँ बनाकर पड़ोसियों में बाँटी जाती हैं।", "On Eid, vermicelli is made and distributed among neighbors."),
        ("गुरु पूर्णिमा पर गुरु के प्रति कृतज्ञता व्यक्त की जाती है।", "On Guru Purnima, gratitude is expressed towards the teacher."),
        ("भारतीय संगीत में राग और ताल का बहुत महत्व है।", "Raag and taal hold great importance in Indian music."),
        ("लोहड़ी पर आग जलाकर तिल और गुड़ डाले जाते हैं।", "On Lohri, a fire is lit and sesame and jaggery are offered."),
        ("भारत में जूते उतारकर घर में प्रवेश करने की परंपरा है।", "In India, there is a tradition of removing shoes before entering the house."),
        ("ओणम केरल का सबसे बड़ा फ़सल उत्सव है।", "Onam is Kerala's biggest harvest festival."),
        ("भारतीय शास्त्रीय नृत्य में भावों की अभिव्यक्ति होती है।", "Indian classical dance involves the expression of emotions."),
        ("गणेश चतुर्थी पर विशाल गणेश प्रतिमाएँ स्थापित की जाती हैं।", "On Ganesh Chaturthi, large Ganesh idols are installed."),
        ("भारतीय समाज में विवाह को पवित्र बंधन माना जाता है।", "In Indian society, marriage is considered a sacred bond."),
        ("मकर संक्रांति पर पतंग उड़ाने की परंपरा बहुत पुरानी है।", "The tradition of flying kites on Makar Sankranti is very old."),
        ("भारतीय खान-पान में मसालों का विशेष स्थान है।", "Spices hold a special place in Indian cuisine."),
        ("जन्माष्टमी पर भगवान कृष्ण की झाँकियाँ सजाई जाती हैं।", "On Janmashtami, tableaux of Lord Krishna are decorated."),
        ("नवरात्रि में नौ दिन माँ दुर्गा की पूजा होती है।", "During Navratri, Goddess Durga is worshipped for nine days."),
        ("भारत में अनेकता में एकता की भावना विशेष है।", "The spirit of unity in diversity is special in India."),
        ("बिहू असम का प्रमुख लोक उत्सव है।", "Bihu is Assam's major folk festival."),
        ("भारतीय परंपरा में अन्न को देवता माना जाता है।", "In Indian tradition, food grains are considered divine."),
        ("पोंगल तमिलनाडु में धान की फ़सल का त्योहार है।", "Pongal is the rice harvest festival in Tamil Nadu."),
        ("भारतीय समाज में गुरु का स्थान माता-पिता के बराबर है।", "In Indian society, the teacher's place is equal to parents."),
        ("दुर्गा पूजा बंगाल का सबसे बड़ा उत्सव है।", "Durga Puja is Bengal's biggest festival."),
        ("भारत में हर क्षेत्र की अपनी अलग वेशभूषा है।", "Every region in India has its own distinct attire."),
        ("योग और ध्यान भारतीय संस्कृति की प्राचीन विरासत हैं।", "Yoga and meditation are ancient heritage of Indian culture."),
        ("भारतीय बाज़ारों में मोल-भाव करना आम बात है।", "Bargaining is common in Indian markets."),
        ("आयुर्वेद भारत की प्राचीन चिकित्सा पद्धति है।", "Ayurveda is India's ancient medical system."),
        ("भारत में गाय को माता का दर्जा दिया जाता है।", "In India, the cow is given the status of a mother."),
        ("भारतीय संस्कृति में वसुधैव कुटुंबकम् का आदर्श है।", "Indian culture upholds the ideal of Vasudhaiva Kutumbakam (the world is one family)."),
        ("हिंदी सिनेमा ने भारतीय संस्कृति को विश्व में पहुँचाया।", "Hindi cinema has taken Indian culture to the world."),
        ("भारतीय विवाह में मेहंदी की रस्म बहुत रंगीन होती है।", "The mehndi ceremony in Indian weddings is very colorful."),
        ("महाभारत और रामायण भारतीय संस्कृति के आधार-स्तंभ हैं।", "Mahabharata and Ramayana are the pillars of Indian culture."),
        ("सत्संग में भजन और कीर्तन करना आम परंपरा है।", "Singing bhajans and kirtans in satsang is a common tradition."),
        ("प्रसाद बाँटना मंदिर की पूजा का अभिन्न अंग है।", "Distributing prasad is an integral part of temple worship."),
        ("भारत में बुज़ुर्गों को हमेशा आदर से संबोधित किया जाता है।", "In India, elders are always addressed with respect."),
        ("कथक और भरतनाट्यम भारत की प्रसिद्ध नृत्य शैलियाँ हैं।", "Kathak and Bharatanatyam are famous dance styles of India."),
        ("वट सावित्री व्रत पति की दीर्घायु के लिए रखा जाता है।", "Vat Savitri fast is observed for the long life of the husband."),
        ("भारतीय दर्शन में कर्म और धर्म का गहरा संबंध है।", "In Indian philosophy, karma and dharma have a deep connection."),
    ],
    "node-35": [
        ("उसने बड़ी चालाकी से बात को टाल दिया, जो सबको समझ आ गया।", "He cleverly deflected the topic, which everyone understood."),
        ("अगर बारिश हो जाती तो हमारा कार्यक्रम रद्द हो जाता, लेकिन मौसम साथ दे गया।", "If it had rained, our program would have been canceled, but the weather cooperated."),
    ],
}

def pick_tags():
    tags = ["general"]
    if random.random() < 0.50:
        tags.append("travel")
    if random.random() < 0.50:
        tags.append("work")
    if random.random() < 0.50:
        tags.append("family")
    return tags

def main():
    with open("src/data/hindi/deck.json", "r", encoding="utf-8") as f:
        deck = json.load(f)

    next_id = 3326
    new_cards = []

    for node, info in NODES.items():
        need = info["need"]
        sentences = SENTENCES[node]
        tips = TIPS.get(node, [])

        if len(sentences) < need:
            print(f"WARNING: {node} has {len(sentences)} sentences but needs {need}")

        for i in range(need):
            sent = sentences[i % len(sentences)]
            # ~30% get a grammar tip
            if tips and (i % 3 == 0):
                tip = tips[i % len(tips)]
            else:
                tip = ""

            card_id = f"hi-{next_id:04d}"
            card = {
                "id": card_id,
                "target": sent[0],
                "english": sent[1],
                "audio": f"hi/{card_id}.mp3",
                "grammar": tip,
                "tags": pick_tags(),
                "grammarNode": node,
            }
            new_cards.append(card)
            next_id += 1

    print(f"Generated {len(new_cards)} new cards")
    deck.extend(new_cards)
    print(f"Total deck size: {len(deck)}")

    with open("src/data/hindi/deck.json", "w", encoding="utf-8") as f:
        json.dump(deck, f, ensure_ascii=False, indent=2)
        f.write("\n")

    # Verify counts
    from collections import Counter
    counts = Counter(c["grammarNode"] for c in deck)
    for node in sorted(NODES.keys(), key=lambda x: int(x.split("-")[1])):
        print(f"  {node}: {counts[node]} cards")

if __name__ == "__main__":
    main()
