#!/usr/bin/env python3
"""Generate Swedish deck.json with ~3930 cards across 35 grammar nodes."""
import json
import random

random.seed(42)

# Node definitions: (node_id, name, target_count)
NODES = [
    ("node-01", "Greetings & introductions", 115),
    ("node-02", "Present tense regular verbs", 115),
    ("node-03", "Vara vs ha", 115),
    ("node-04", "Articles & gender (en/ett)", 115),
    ("node-05", "Word order (V2 rule)", 115),
    ("node-06", "Numbers & time", 110),
    ("node-07", "Food, drink & ordering", 110),
    ("node-08", "Common expressions", 110),
    ("node-09", "Preteritum (simple past)", 115),
    ("node-10", "Object pronouns", 110),
    ("node-11", "Modal verbs", 110),
    ("node-12", "Daily routine & reflexives", 110),
    ("node-13", "Negation & word order", 110),
    ("node-14", "Prepositions", 115),
    ("node-15", "Adjective agreement & comparison", 110),
    ("node-16", "Perfekt (har + supinum)", 115),
    ("node-17", "Directions & transport", 110),
    ("node-18", "Subordinate clauses", 110),
    ("node-19", "Imperative", 110),
    ("node-20", "Definite forms & double definite", 115),
    ("node-21", "Relative clauses (som)", 110),
    ("node-22", "Passive voice", 115),
    ("node-23", "S-verbs (deponent verbs)", 110),
    ("node-24", "Future & conditional", 110),
    ("node-25", "Advanced connectors", 110),
    ("node-26", "Participle constructions", 115),
    ("node-27", "Reported speech", 110),
    ("node-28", "Idiomatic expressions", 115),
    ("node-29", "Formal vs informal register", 112),
    ("node-30", "Particle verbs", 113),
    ("node-31", "Advanced word order", 110),
    ("node-32", "Literary & written Swedish", 112),
    ("node-33", "Academic discourse", 113),
    ("node-34", "Cultural fluency", 112),
    ("node-35", "Advanced mixed mastery", 113),
]

###############################################################################
# CARD DATA PER NODE
# Each node has a list of (target, english, grammar_or_None) tuples.
# We define enough unique cards per node.
###############################################################################

node_01_cards = [
    ("Hej, hur mår du?", "Hi, how are you?", "\"Hur mår du?\" is the everyday informal greeting. Use \"Hur står det till?\" for more formal situations."),
    ("God morgon!", "Good morning!", "\"God morgon\" is used until about noon. After that, switch to \"God dag\" or just \"Hej\"."),
    ("God kväll!", "Good evening!", "\"God kväll\" is typically used from around 6 PM onwards."),
    ("Hej då!", "Goodbye!", "\"Hej då\" is the standard goodbye. \"Vi ses\" (see you) is more casual among friends."),
    ("Jag heter Erik.", "My name is Erik.", "\"Jag heter\" literally means \"I am called.\" Swedes rarely use \"Mitt namn är\" in everyday speech."),
    ("Vad heter du?", "What is your name?", "In Swedish you ask \"What are you called?\" rather than \"What is your name?\""),
    ("Trevligt att träffas!", "Nice to meet you!", "This is the standard phrase when meeting someone for the first time. Very commonly used."),
    ("Hur är det?", "How's it going?", "\"Hur är det?\" is slightly more casual than \"Hur mår du?\" and often used between acquaintances."),
    ("Jag mår bra, tack.", "I'm fine, thanks.", None),
    ("Varifrån kommer du?", "Where do you come from?", "\"Varifrån\" combines \"var\" (where) and \"ifrån\" (from). The V2 rule keeps the verb second."),
    ("Jag kommer från Sverige.", "I come from Sweden.", None),
    ("Jag bor i Stockholm.", "I live in Stockholm.", "Use \"i\" (in) for cities and countries: \"Jag bor i Göteborg,\" \"Jag bor i Sverige.\""),
    ("Var bor du?", "Where do you live?", None),
    ("Jag är svensk.", "I am Swedish.", "Nationality adjectives are not capitalized in Swedish: \"svensk,\" \"finsk,\" \"norsk.\""),
    ("Pratar du svenska?", "Do you speak Swedish?", "\"Prata\" and \"tala\" both mean \"to speak.\" \"Prata\" is more colloquial; \"tala\" is more formal."),
    ("Jag pratar lite svenska.", "I speak a little Swedish.", None),
    ("Tack så mycket!", "Thank you very much!", "\"Tack\" alone is sufficient for thanks. \"Tack så mycket\" adds emphasis and warmth."),
    ("Varsågod.", "You're welcome.", "\"Varsågod\" also means \"here you go\" when handing something to someone."),
    ("Ursäkta mig.", "Excuse me.", "Use \"Ursäkta\" to get someone's attention or apologize for a minor inconvenience. \"Förlåt\" is for a deeper apology."),
    ("Förlåt!", "I'm sorry!", "\"Förlåt\" carries more emotional weight than \"ursäkta.\" Use it when you genuinely want to apologize."),
    ("Ja, absolut!", "Yes, absolutely!", None),
    ("Nej, tyvärr.", "No, unfortunately.", "\"Tyvärr\" softens a refusal. Swedes often avoid blunt \"nej\" and add softeners."),
    ("Hur gammal är du?", "How old are you?", "Literally \"How old are you?\" — same structure as English. Age uses \"vara\" (to be)."),
    ("Jag är trettio år gammal.", "I am thirty years old.", None),
    ("Vad jobbar du med?", "What do you work with?", "Swedes say \"work with\" rather than \"work as.\" It's the standard way to ask about someone's occupation."),
    ("Jag är lärare.", "I am a teacher.", "Swedish drops the article before professions: \"Jag är lärare\" not \"Jag är en lärare.\""),
    ("Kan du hjälpa mig?", "Can you help me?", None),
    ("Det var trevligt att prata med dig.", "It was nice talking to you.", None),
    ("Vi ses!", "See you!", "\"Vi ses\" literally means \"we see each other.\" It's a casual, friendly goodbye."),
    ("Ha en bra dag!", "Have a nice day!", None),
    ("God natt!", "Good night!", "\"God natt\" is only used when someone is going to sleep, unlike \"good night\" in English which can be a general evening farewell."),
    ("Välkommen!", "Welcome!", "\"Välkommen\" for one person, \"välkomna\" for addressing a group."),
    ("Hej allihopa!", "Hi everyone!", "\"Allihopa\" is informal for \"everyone.\" In formal settings, use \"alla\" instead."),
    ("Jag förstår inte.", "I don't understand.", None),
    ("Kan du säga det igen?", "Can you say that again?", None),
    ("Vad betyder det?", "What does that mean?", None),
    ("Hur säger man det på svenska?", "How do you say that in Swedish?", "\"Man\" is the impersonal pronoun, like English \"one\" or \"you\" in general statements."),
    ("Jag lär mig svenska.", "I am learning Swedish.", "\"Lära sig\" is reflexive — you literally \"teach yourself.\" Don't forget \"mig\" (myself)."),
    ("Jag är ny här.", "I am new here.", None),
    ("Var kommer du ifrån?", "Where are you from?", "\"Ifrån\" can be placed at the end or merged into \"varifrån\" at the start — both are correct."),
    ("Jag kommer från England.", "I come from England.", None),
    ("Det är mitt första besök i Sverige.", "It is my first visit to Sweden.", None),
    ("Jag är här på semester.", "I am here on vacation.", "\"Semester\" means vacation in Swedish — a false friend with the English word \"semester.\""),
    ("Jag är här för jobbet.", "I am here for work.", None),
    ("Jag har bott här i tre år.", "I have lived here for three years.", None),
    ("Vad sysslar du med?", "What do you do?", "\"Syssla med\" is a slightly more informal way to ask about someone's occupation or hobbies."),
    ("Jag studerar medicin.", "I study medicine.", None),
    ("Vad kul!", "How fun!", "\"Vad\" + adjective is an exclamation pattern: \"Vad fint!\" (How nice!), \"Vad roligt!\" (How fun!)."),
    ("Ska vi ta en fika?", "Shall we have a fika?", "Fika is a cornerstone of Swedish culture — a coffee break often with pastry. It's both a noun and a verb."),
    ("Det låter bra.", "That sounds good.", None),
    ("Jag håller med.", "I agree.", "\"Hålla med\" is the standard way to express agreement. Literally \"hold with.\""),
    ("Vad heter du i efternamn?", "What is your last name?", None),
    ("Mitt efternamn är Lindgren.", "My last name is Lindgren.", None),
    ("Jag har två barn.", "I have two children.", None),
    ("Är du gift?", "Are you married?", "\"Gift\" means both \"married\" and \"poison\" in Swedish — context makes the difference clear."),
    ("Jag är singel.", "I am single.", None),
    ("Jag har en sambo.", "I have a partner I live with.", "\"Sambo\" (live-in partner) is a legally recognized status in Sweden, distinct from \"gift\" (married)."),
    ("Ska vi gå ut och äta?", "Shall we go out to eat?", None),
    ("Jag bjuder.", "My treat.", "\"Bjuda\" means to treat/invite. \"Jag bjuder\" is a common way to say you're paying."),
    ("Skål!", "Cheers!", "When toasting in Sweden, make eye contact with each person. It's an important social custom."),
    ("Vad gör du på fritiden?", "What do you do in your free time?", None),
    ("Jag gillar att läsa.", "I like to read.", "\"Gilla\" is the casual way to say \"like.\" \"Tycka om\" is slightly more formal but also common."),
    ("Jag tycker om musik.", "I like music.", None),
    ("Trivs du här?", "Do you enjoy it here?", "\"Trivas\" is a uniquely Swedish concept — to feel at home, content, and comfortable in a place."),
    ("Det är mysigt här.", "It's cozy here.", "\"Mysig\" captures the Swedish love of coziness — warm lighting, candles, good company."),
    ("Talar du engelska?", "Do you speak English?", None),
    ("Jag talar lite svenska.", "I speak a little Swedish.", None),
    ("Kan du prata långsammare?", "Can you speak more slowly?", None),
    ("Jag heter Anna och jag kommer från Malmö.", "My name is Anna and I come from Malmö.", None),
    ("Vad trevligt!", "How nice!", None),
    ("Vi bor i en lägenhet i centrala Göteborg.", "We live in an apartment in central Gothenburg.", None),
    ("Min familj är stor.", "My family is big.", None),
    ("Jag har en bror och en syster.", "I have a brother and a sister.", None),
    ("Mina föräldrar bor i Uppsala.", "My parents live in Uppsala.", None),
    ("Jag jobbar som ingenjör.", "I work as an engineer.", None),
    ("Jag pluggar på universitetet.", "I study at the university.", "\"Plugga\" is the everyday word for studying. \"Studera\" is slightly more formal."),
    ("Hur länge har du bott här?", "How long have you lived here?", None),
    ("Jag flyttade hit förra året.", "I moved here last year.", None),
    ("Vad har du för hobbyer?", "What hobbies do you have?", "\"Vad har du för...\" is a common pattern meaning \"What kind of... do you have?\""),
    ("Jag springer varje morgon.", "I run every morning.", None),
    ("Jag älskar att resa.", "I love to travel.", None),
    ("Har du varit i Sverige förut?", "Have you been to Sweden before?", None),
    ("Det här är första gången.", "This is the first time.", None),
    ("Jag trivs jättebra här.", "I really enjoy it here.", "\"Jätte-\" is a prefix meaning \"very/really\" — \"jättebra\" (really good), \"jättefin\" (really nice)."),
    ("Vad gör du ikväll?", "What are you doing tonight?", None),
    ("Vill du hänga med?", "Do you want to come along?", "\"Hänga med\" is casual slang for joining someone. More formal: \"Vill du följa med?\""),
    ("Absolut, gärna!", "Absolutely, gladly!", "\"Gärna\" means \"gladly/with pleasure\" — a very Swedish way to accept an invitation."),
    ("Vi kan ses imorgon.", "We can meet tomorrow.", None),
    ("Hur tar man sig dit?", "How do you get there?", None),
    ("Det ligger nära centralstationen.", "It's near the central station.", None),
    ("Jag ser fram emot det.", "I look forward to it.", "\"Se fram emot\" is a separable particle verb meaning \"to look forward to.\""),
    ("Hej, jag heter Sven och det här är min fru.", "Hi, my name is Sven and this is my wife.", None),
    ("Trevligt att lära känna dig.", "Nice to get to know you.", None),
    ("Vi är här över helgen.", "We are here over the weekend.", "\"Helgen\" means \"the weekend\" in its definite form. \"En helg\" = a weekend."),
    ("Vad fint väder det är idag!", "What nice weather it is today!", None),
    ("Ja, det är underbart.", "Yes, it is wonderful.", None),
    ("Jag saknar mitt hemland ibland.", "I miss my home country sometimes.", None),
    ("Sverige är ett vackert land.", "Sweden is a beautiful country.", None),
    ("Jag vill lära mig mer svenska.", "I want to learn more Swedish.", None),
    ("Det är svårt men roligt.", "It's hard but fun.", None),
    ("Vi hörs!", "We'll be in touch!", "\"Vi hörs\" literally means \"we hear each other\" — used like \"talk to you later.\""),
    ("Hälsa alla därhemma!", "Say hi to everyone at home!", "\"Hälsa\" means \"to greet\" — a common way to send regards through someone."),
    ("Ha det bra!", "Take care!", "\"Ha det bra\" is one of the most common Swedish farewells, meaning \"have it good.\""),
    ("Sköt om dig!", "Take care of yourself!", None),
    ("Vi ses snart igen.", "We'll see each other again soon.", None),
    ("Tack för idag!", "Thanks for today!", None),
    ("Det var kul att ses.", "It was fun to meet.", None),
    ("Jag hoppas vi ses igen.", "I hope we meet again.", None),
    ("Lycka till!", "Good luck!", None),
    ("Grattis!", "Congratulations!", "\"Grattis\" is the informal form. \"Gratulerar\" is the full formal version."),
    ("Grattis på födelsedagen!", "Happy birthday!", None),
    ("God jul och gott nytt år!", "Merry Christmas and happy new year!", None),
    ("Glad midsommar!", "Happy midsummer!", "Midsommar is one of Sweden's most important holidays, celebrated around the summer solstice with dancing, flowers, and herring."),
    ("Trevlig helg!", "Have a nice weekend!", None),
    ("Jag presenterar mig: jag heter Karin.", "Let me introduce myself: my name is Karin.", None),
    ("Får jag presentera min kollega?", "May I introduce my colleague?", None),
    ("Det här är min vän Lisa.", "This is my friend Lisa.", None),
    ("Vi känner varandra sedan universitetet.", "We have known each other since university.", None),
]

node_02_cards = [
    ("Jag pratar svenska varje dag.", "I speak Swedish every day.", "Regular Group 1 verbs (like \"prata\") add -r in present tense: prata → pratar."),
    ("Hon läser en bok.", "She reads a book.", "\"Läsa\" is a Group 2 verb. Present tense: läser. The -er ending is typical for Group 2."),
    ("Vi äter lunch klockan tolv.", "We eat lunch at twelve o'clock.", None),
    ("De bor i ett stort hus.", "They live in a big house.", None),
    ("Han jobbar på ett sjukhus.", "He works at a hospital.", "\"Jobba\" is more casual than \"arbeta.\" Both are correct; \"jobba\" dominates in everyday speech."),
    ("Jag skriver ett mejl.", "I am writing an email.", "Swedish uses \"mejl\" (from English \"mail\") or \"e-post\" for email. \"Mejl\" is more casual."),
    ("Du lagar mat varje kväll.", "You cook dinner every evening.", None),
    ("Barnen leker i parken.", "The children play in the park.", None),
    ("Hon sjunger vackert.", "She sings beautifully.", None),
    ("Vi dricker kaffe på morgonen.", "We drink coffee in the morning.", "Swedish present tense covers both \"I drink\" and \"I am drinking\" — no continuous form exists."),
    ("Jag cyklar till jobbet.", "I cycle to work.", "Cycling is the primary mode of transport for many Swedes, especially in cities like Malmö and Uppsala."),
    ("Han springer i skogen.", "He runs in the forest.", None),
    ("De studerar på biblioteket.", "They study at the library.", None),
    ("Vi handlar i mataffären.", "We shop at the grocery store.", "\"Handla\" specifically means to shop for groceries or goods. \"Shoppa\" is used for clothes/leisure shopping."),
    ("Jag tittar på TV.", "I watch TV.", None),
    ("Hon lyssnar på musik.", "She listens to music.", "\"Lyssna på\" always requires \"på\" — you listen \"on\" something in Swedish."),
    ("Du spelar gitarr.", "You play guitar.", None),
    ("Vi bakar bröd varje söndag.", "We bake bread every Sunday.", None),
    ("Jag simmar i sjön.", "I swim in the lake.", "Sweden has nearly 100,000 lakes. Swimming in lakes is a beloved summer activity."),
    ("De dansar hela kvällen.", "They dance all evening.", None),
    ("Han målar tavlor.", "He paints pictures.", None),
    ("Jag öppnar fönstret.", "I open the window.", None),
    ("Hon stänger dörren.", "She closes the door.", None),
    ("Vi börjar klockan nio.", "We start at nine o'clock.", None),
    ("De slutar klockan fem.", "They finish at five o'clock.", None),
    ("Jag ringer min mamma.", "I call my mom.", None),
    ("Du svarar på telefonen.", "You answer the phone.", None),
    ("Han köper en tidning.", "He buys a newspaper.", None),
    ("Vi säljer vår bil.", "We are selling our car.", None),
    ("Jag betalar med kort.", "I pay by card.", "Sweden is one of the world's most cashless societies. Most transactions use card or Swish (mobile payment)."),
    ("Hon tvättar kläderna.", "She washes the clothes.", None),
    ("De städar huset varje vecka.", "They clean the house every week.", None),
    ("Jag lagar cykeln.", "I fix the bicycle.", "\"Laga\" means both \"to cook\" and \"to fix/repair\" — context makes it clear."),
    ("Vi reser till Norrland.", "We travel to Norrland.", None),
    ("Han flyger till London.", "He flies to London.", None),
    ("Jag packar min väska.", "I pack my bag.", None),
    ("Du visar mig vägen.", "You show me the way.", None),
    ("Hon berättar en historia.", "She tells a story.", None),
    ("Vi planerar en fest.", "We are planning a party.", None),
    ("De bjuder in alla grannar.", "They invite all the neighbors.", None),
    ("Jag tränar på gymmet.", "I work out at the gym.", None),
    ("Han klättrar i bergen.", "He climbs in the mountains.", None),
    ("Vi fiskar i sjön.", "We fish in the lake.", None),
    ("Jag fotograferar fåglar.", "I photograph birds.", None),
    ("Hon pluggar till provet.", "She studies for the test.", None),
    ("De diskuterar politik.", "They discuss politics.", None),
    ("Jag hämtar barnen från skolan.", "I pick up the children from school.", "\"Hämta\" means to fetch/pick up. Very common in daily life with kids."),
    ("Vi promenerar längs stranden.", "We walk along the beach.", None),
    ("Han kör bil till jobbet.", "He drives a car to work.", None),
    ("Jag parkerar utanför affären.", "I park outside the store.", None),
    ("Du drömmer om sommaren.", "You dream about summer.", None),
    ("Hon undervisar i matematik.", "She teaches mathematics.", None),
    ("Vi delar på notan.", "We split the bill.", "\"Dela på notan\" is standard practice in Sweden — splitting bills is the norm, not the exception."),
    ("Jag vaknar tidigt varje morgon.", "I wake up early every morning.", None),
    ("De sover till lunch.", "They sleep until lunch.", None),
    ("Han duschar varje morgon.", "He showers every morning.", None),
    ("Jag borstar tänderna.", "I brush my teeth.", None),
    ("Vi äter frukost tillsammans.", "We eat breakfast together.", None),
    ("Hon dricker te istället för kaffe.", "She drinks tea instead of coffee.", None),
    ("De spelar fotboll efter skolan.", "They play football after school.", None),
    ("Jag läser tidningen på morgonen.", "I read the newspaper in the morning.", None),
    ("Han räknar pengarna.", "He counts the money.", None),
    ("Vi väntar på bussen.", "We wait for the bus.", None),
    ("Jag letar efter mina nycklar.", "I look for my keys.", None),
    ("Du frågar om vägen.", "You ask about the way.", None),
    ("Hon byter jobb nästa månad.", "She is changing jobs next month.", "Swedish present tense can express near-future events, just like English \"She is changing...\""),
    ("Vi flyttar till en ny stad.", "We are moving to a new city.", None),
    ("De firar midsommar varje år.", "They celebrate midsummer every year.", None),
    ("Jag fyller år i juni.", "My birthday is in June.", "\"Fylla år\" literally means \"to fill years\" — the Swedish idiom for having a birthday."),
    ("Han skickar ett paket.", "He sends a package.", None),
    ("Jag tar bussen till jobbet.", "I take the bus to work.", None),
    ("Vi möter våra vänner på lördag.", "We meet our friends on Saturday.", None),
    ("Du arbetar hemifrån idag.", "You work from home today.", "\"Hemifrån\" means \"from home.\" Remote work is very common and accepted in Swedish work culture."),
    ("Hon sköter trädgården.", "She tends the garden.", None),
    ("De odlar grönsaker.", "They grow vegetables.", None),
    ("Jag sorterar soporna.", "I sort the garbage.", "Recycling (\"källsortering\") is deeply embedded in Swedish culture. Most homes sort waste into many categories."),
    ("Vi hjälper varandra.", "We help each other.", None),
    ("Jag behöver mer tid.", "I need more time.", None),
    ("Han förstår problemet.", "He understands the problem.", None),
    ("De gillar svensk mat.", "They like Swedish food.", None),
    ("Jag älskar den svenska naturen.", "I love Swedish nature.", "\"Naturen\" (nature) is central to Swedish identity. Allemansrätten gives everyone the right to roam freely."),
    ("Vi njuter av solen.", "We enjoy the sun.", None),
    ("Jag hoppas på bra väder.", "I hope for good weather.", None),
    ("Hon tror att det blir regn.", "She thinks it will rain.", None),
    ("De vet svaret.", "They know the answer.", "\"Veta\" means to know a fact. \"Känna\" means to know a person or to feel."),
    ("Jag känner honom väl.", "I know him well.", None),
    ("Vi tycker att filmen var bra.", "We think the movie was good.", "\"Tycka\" expresses an opinion. \"Tänka\" means to think/ponder. \"Tro\" means to believe/assume."),
    ("Du behöver vila.", "You need to rest.", None),
    ("Jag saknar mina vänner.", "I miss my friends.", None),
    ("Han lovar att komma.", "He promises to come.", None),
    ("Vi önskar dig lycka.", "We wish you luck.", None),
    ("Jag bestämmer mig imorgon.", "I'll decide tomorrow.", None),
    ("De glömmer alltid sina nycklar.", "They always forget their keys.", None),
    ("Jag minns den dagen.", "I remember that day.", None),
    ("Hon söker ett nytt jobb.", "She is looking for a new job.", None),
    ("Vi använder datorn varje dag.", "We use the computer every day.", None),
    ("Jag laddar min telefon.", "I charge my phone.", None),
    ("Han bygger en hylla.", "He builds a shelf.", None),
    ("De renoverar sitt hus.", "They are renovating their house.", None),
    ("Jag planterar blommor.", "I plant flowers.", None),
    ("Vi plockar svamp i skogen.", "We pick mushrooms in the forest.", "Mushroom picking is a popular autumn activity in Sweden, tied to allemansrätten (freedom to roam)."),
    ("Hon samlar på frimärken.", "She collects stamps.", None),
    ("Jag följer nyheterna.", "I follow the news.", None),
    ("De protesterar mot beslutet.", "They protest against the decision.", None),
    ("Jag anmäler mig till kursen.", "I sign up for the course.", None),
    ("Vi förbereder oss för vintern.", "We prepare ourselves for winter.", None),
    ("Hon klär sig varmt.", "She dresses warmly.", None),
    ("De åker skidor varje vinter.", "They ski every winter.", None),
    ("Jag vandrar i fjällen.", "I hike in the mountains.", "\"Fjällen\" refers to the Scandinavian mountain range — a popular destination for hiking and skiing."),
    ("Vi paddlar kajak i skärgården.", "We kayak in the archipelago.", None),
    ("Han seglar på sommaren.", "He sails in the summer.", None),
    ("Jag plockar bär i skogen.", "I pick berries in the forest.", "Berry picking (especially blueberries and lingonberries) is a cherished Swedish tradition protected by allemansrätten."),
    ("De campar vid sjön.", "They camp by the lake.", None),
    ("Vi grillar i trädgården.", "We barbecue in the garden.", None),
    ("Jag byter till vinterdäck.", "I switch to winter tires.", "Switching to winter tires is legally required in Sweden from December 1 to March 31."),
]

node_03_cards = [
    ("Jag är trött.", "I am tired.", "\"Vara\" (to be) is used for states and qualities: \"Jag är glad\" (I am happy), \"Jag är trött\" (I am tired)."),
    ("Hon är läkare.", "She is a doctor.", "No article before professions in Swedish: \"Hon är läkare,\" not \"Hon är en läkare.\""),
    ("Vi är hemma.", "We are at home.", "\"Hemma\" means \"at home\" (location). \"Hem\" means \"home\" (direction): \"Vi går hem.\""),
    ("De är glada.", "They are happy.", "\"Glad\" becomes \"glada\" in plural. Adjectives agree with the noun's number and definiteness."),
    ("Jag har en hund.", "I have a dog.", "\"Ha\" (to have) is irregular: har (present), hade (past), haft (supine)."),
    ("Han har ont i huvudet.", "He has a headache.", "Swedish expresses pain as \"ha ont i\" + body part. \"Ont\" means pain/ache."),
    ("Vi har det bra.", "We are doing well.", "\"Ha det bra\" is an idiomatic phrase meaning \"to be doing well/fine.\" Also used as a goodbye."),
    ("Det är kallt ute.", "It is cold outside.", "\"Det\" is used as an impersonal subject for weather and general conditions."),
    ("Jag har tid imorgon.", "I have time tomorrow.", None),
    ("Hon är min bästa vän.", "She is my best friend.", None),
    ("Vi har tre katter.", "We have three cats.", None),
    ("De har semester i juli.", "They have vacation in July.", "July is the main vacation month in Sweden. Many businesses slow down or close."),
    ("Jag är hungrig.", "I am hungry.", None),
    ("Det är långt härifrån.", "It is far from here.", None),
    ("Han är från Göteborg.", "He is from Gothenburg.", None),
    ("Jag har inte bil.", "I don't have a car.", "\"Inte\" is placed after the verb in main clauses: \"Jag har inte...\""),
    ("Vi är på väg.", "We are on our way.", None),
    ("Hon har rätt.", "She is right.", "\"Ha rätt\" means \"to be right.\" \"Ha fel\" means \"to be wrong.\" Swedish uses \"have\" where English uses \"be.\""),
    ("De är ute och går.", "They are out walking.", None),
    ("Jag har en fråga.", "I have a question.", None),
    ("Det är en vacker dag.", "It is a beautiful day.", None),
    ("Vi har fullt upp.", "We are very busy.", "\"Ha fullt upp\" is an idiom meaning \"to be very busy/have a lot on one's plate.\""),
    ("Han är nyfiken.", "He is curious.", None),
    ("Jag har ont i ryggen.", "I have a backache.", None),
    ("Hon är snäll.", "She is kind.", None),
    ("De har bråttom.", "They are in a hurry.", "\"Ha bråttom\" means \"to be in a hurry.\" An untranslatable Swedish idiom."),
    ("Vi är redo.", "We are ready.", None),
    ("Jag har pengar med mig.", "I have money with me.", None),
    ("Det är möjligt.", "It is possible.", None),
    ("Han är sjuk idag.", "He is sick today.", None),
    ("Jag har huvudvärk.", "I have a headache.", None),
    ("Vi har gäster ikväll.", "We have guests tonight.", None),
    ("Hon är gravid.", "She is pregnant.", None),
    ("De har ett fint hus.", "They have a nice house.", None),
    ("Jag är rädd för spindlar.", "I am afraid of spiders.", "\"Rädd för\" means \"afraid of.\" \"Rädd om\" means \"careful with/caring about.\""),
    ("Det är viktigt att komma i tid.", "It is important to come on time.", None),
    ("Han har tur.", "He is lucky.", "\"Ha tur\" means \"to be lucky.\" \"Ha otur\" means \"to be unlucky.\""),
    ("Vi är tacksamma.", "We are grateful.", None),
    ("Jag har lust att simma.", "I feel like swimming.", "\"Ha lust\" means \"to feel like/want to.\" Very common in casual Swedish."),
    ("Hon är stressad.", "She is stressed.", None),
    ("De har problem med datorn.", "They have problems with the computer.", None),
    ("Jag är säker på det.", "I am sure of it.", None),
    ("Det är ingen fara.", "There's no danger.", "\"Ingen fara\" is a reassuring phrase meaning \"no worries\" or \"it's fine.\""),
    ("Han har allergi.", "He has allergies.", None),
    ("Vi är nöjda med resultatet.", "We are satisfied with the result.", None),
    ("Jag har erfarenhet.", "I have experience.", None),
    ("Hon är duktig på att laga mat.", "She is good at cooking.", "\"Duktig på\" means \"good at\" — a very common expression in Swedish."),
    ("De är trötta efter resan.", "They are tired after the trip.", None),
    ("Jag har en idé.", "I have an idea.", None),
    ("Det är skönt att vara ledig.", "It's nice to be off.", "\"Skönt\" conveys comfort and relief — a very Swedish sensation word."),
    ("Vi har en stuga i Dalarna.", "We have a cabin in Dalarna.", "Having a \"stuga\" (country cottage) is a Swedish dream. Many families retreat to theirs on weekends."),
    ("Han är modig.", "He is brave.", None),
    ("Jag har semester nästa vecka.", "I have vacation next week.", None),
    ("Hon är i Stockholm.", "She is in Stockholm.", None),
    ("De har två hundar och en katt.", "They have two dogs and a cat.", None),
    ("Jag är intresserad av historia.", "I am interested in history.", None),
    ("Vi har det mysigt.", "We are having a cozy time.", "\"Ha det mysigt\" captures the Swedish concept of coziness — often involving candles, warmth, and togetherness."),
    ("Det är sent.", "It is late.", None),
    ("Han är ensam hemma.", "He is home alone.", None),
    ("Jag har ont i halsen.", "I have a sore throat.", None),
    ("Hon är upptagen.", "She is busy.", None),
    ("Vi har en tradition.", "We have a tradition.", None),
    ("De är ivriga.", "They are eager.", None),
    ("Jag är osäker.", "I am unsure.", None),
    ("Han har kontroll på situationen.", "He has control of the situation.", None),
    ("Vi är på besök.", "We are visiting.", None),
    ("Jag har svårt att sova.", "I have trouble sleeping.", "\"Ha svårt att\" means \"to find it difficult to\" — a very useful expression."),
    ("Det är dags att gå.", "It is time to go.", "\"Det är dags\" means \"it's time.\" Very commonly used in everyday Swedish."),
    ("Hon har dåligt samvete.", "She has a bad conscience.", None),
    ("De är överens.", "They are in agreement.", None),
    ("Jag har ett möte klockan tre.", "I have a meeting at three o'clock.", None),
    ("Han är lång.", "He is tall.", None),
    ("Vi har det lugnt.", "We are taking it easy.", None),
    ("Jag är förkyld.", "I have a cold.", "\"Förkyld\" literally means \"over-cold\" — the Swedish word for having a cold."),
    ("De har en stor familj.", "They have a big family.", None),
    ("Jag är stolt över dig.", "I am proud of you.", None),
    ("Hon har en bra dag.", "She is having a good day.", None),
    ("Det är dyrt att bo i Stockholm.", "It is expensive to live in Stockholm.", None),
    ("Vi är gifta sedan tio år.", "We have been married for ten years.", None),
    ("Han har diabetes.", "He has diabetes.", None),
    ("Jag är vegetarian.", "I am a vegetarian.", None),
    ("De har roligt.", "They are having fun.", "\"Ha roligt\" means \"to have fun.\" \"Roligt\" on its own means \"funny\" or \"fun.\""),
    ("Vi är på semester.", "We are on vacation.", None),
    ("Jag har inga planer.", "I have no plans.", None),
    ("Hon är försenad.", "She is late.", "\"Försenad\" means delayed/late. Very useful for public transport in Sweden!"),
    ("Det är svårt.", "It is difficult.", None),
    ("Han har en bra chef.", "He has a good boss.", None),
    ("Vi är vänner sedan barndomen.", "We have been friends since childhood.", None),
    ("Jag har aldrig varit där.", "I have never been there.", None),
    ("De är överraskade.", "They are surprised.", None),
    ("Jag är pigg idag.", "I feel energetic today.", "\"Pigg\" means alert, energetic, perky — no direct English equivalent. A very Swedish word."),
    ("Hon har en hobby.", "She has a hobby.", None),
    ("Vi är sent ute.", "We are running late.", None),
    ("Det har ingen betydelse.", "It doesn't matter.", None),
    ("Han är praktisk.", "He is practical.", None),
    ("Jag har en dröm.", "I have a dream.", None),
    ("De är inte hemma.", "They are not at home.", None),
    ("Vi har brist på tid.", "We have a shortage of time.", None),
    ("Jag är nöjd.", "I am satisfied.", None),
    ("Hon har feber.", "She has a fever.", None),
    ("Det är lagom.", "It is just right.", "\"Lagom\" is the quintessential Swedish concept — not too much, not too little, just the right amount."),
    ("Han är artig.", "He is polite.", None),
    ("Jag har en känsla av att det blir bra.", "I have a feeling it will be fine.", None),
    ("Vi har hela helgen på oss.", "We have the whole weekend.", None),
    ("De är förväntansfulla.", "They are full of anticipation.", None),
    ("Jag är redo att börja.", "I am ready to start.", None),
    ("Hon har rätt att vara arg.", "She has the right to be angry.", None),
    ("Vi har inga fler frågor.", "We have no more questions.", None),
    ("Jag är vaken.", "I am awake.", None),
    ("Det är underbart väder.", "The weather is wonderful.", None),
    ("Han har ett gott hjärta.", "He has a good heart.", None),
    ("Vi är sena.", "We are late.", None),
]

# I'll continue building data for nodes 04 through 35.
# For brevity in the generator, I'll define core sentence templates and generate variations.

node_04_cards = [
    ("En bok ligger på bordet.", "A book is on the table.", "\"En\" is the indefinite article for common gender nouns (en-words). \"Ett\" is for neuter nouns (ett-words)."),
    ("Ett äpple om dagen.", "An apple a day.", "\"Äpple\" is an ett-word. There's no rule to predict gender — you must learn it with each noun."),
    ("Boken är intressant.", "The book is interesting.", "Definite form adds -en/-n to en-words: \"en bok\" → \"boken\" (the book)."),
    ("Äpplet är rött.", "The apple is red.", "Definite form adds -et/-t to ett-words: \"ett äpple\" → \"äpplet\" (the apple)."),
    ("Jag köpte en ny bil.", "I bought a new car.", None),
    ("Huset är stort.", "The house is big.", "\"Hus\" is an ett-word: \"ett hus\" → \"huset.\" Adjective takes -t form: \"stor\" → \"stort.\""),
    ("En katt sitter i fönstret.", "A cat is sitting in the window.", None),
    ("Barnet sover.", "The child is sleeping.", "\"Barn\" is an ett-word: \"ett barn\" → \"barnet.\""),
    ("Jag har en vän i Malmö.", "I have a friend in Malmö.", None),
    ("Vattnet är kallt.", "The water is cold.", "\"Vatten\" is an ett-word. \"Kallt\" has the -t ending to agree with neuter gender."),
    ("En stol och ett bord.", "A chair and a table.", None),
    ("Flickan springer snabbt.", "The girl runs fast.", "\"Flicka\" becomes \"flickan\" in definite form — the -n ending for en-words ending in -a."),
    ("Pojken äter glass.", "The boy eats ice cream.", None),
    ("Vi har ett rum med utsikt.", "We have a room with a view.", None),
    ("En kopp kaffe, tack.", "A cup of coffee, please.", None),
    ("Telefonen ringer.", "The phone is ringing.", None),
    ("Fönstret är öppet.", "The window is open.", None),
    ("En hund och en katt.", "A dog and a cat.", None),
    ("Skogen är vacker på hösten.", "The forest is beautiful in autumn.", None),
    ("Sjön är djup.", "The lake is deep.", None),
    ("Ett glas vatten, tack.", "A glass of water, please.", None),
    ("Kvinnan väntar på bussen.", "The woman waits for the bus.", None),
    ("Mannen läser tidningen.", "The man reads the newspaper.", None),
    ("En blomma i vasen.", "A flower in the vase.", None),
    ("Köket är rent.", "The kitchen is clean.", None),
    ("Sovrummet är mörkt.", "The bedroom is dark.", None),
    ("En stad i norra Sverige.", "A city in northern Sweden.", None),
    ("Havet är lugnt.", "The sea is calm.", "\"Hav\" is an ett-word: \"ett hav\" → \"havet.\""),
    ("En film på bio.", "A movie at the cinema.", None),
    ("Trädet är högt.", "The tree is tall.", None),
    ("En dator på skrivbordet.", "A computer on the desk.", None),
    ("Problemet är löst.", "The problem is solved.", None),
    ("En dag i solen.", "A day in the sun.", None),
    ("Molnet är stort.", "The cloud is big.", None),
    ("Vi har en fin trädgård.", "We have a nice garden.", None),
    ("Ett land med mycket skog.", "A country with a lot of forest.", None),
    ("Stranden är lång.", "The beach is long.", None),
    ("Berget är imponerande.", "The mountain is impressive.", None),
    ("En bro över älven.", "A bridge over the river.", None),
    ("Museet stänger klockan fem.", "The museum closes at five o'clock.", None),
    ("En kyrka i byn.", "A church in the village.", None),
    ("Torget är fullt av folk.", "The square is full of people.", "\"Torg\" is an ett-word: \"ett torg\" → \"torget.\""),
    ("En nyckel till dörren.", "A key to the door.", None),
    ("Golvet är halt.", "The floor is slippery.", None),
    ("En väg genom skogen.", "A road through the forest.", None),
    ("Taket läcker.", "The roof leaks.", None),
    ("En lampa i hörnet.", "A lamp in the corner.", None),
    ("Priset är högt.", "The price is high.", None),
    ("En present till dig.", "A gift for you.", None),
    ("Svaret är enkelt.", "The answer is simple.", None),
    ("En fråga om tid.", "A question of time.", None),
    ("Vädret är fint.", "The weather is nice.", "\"Väder\" is an ett-word: \"ett väder\" → \"vädret.\""),
    ("En plats i solen.", "A place in the sun.", None),
    ("Mötet börjar snart.", "The meeting starts soon.", None),
    ("Enresa genom Sverige.", "A trip through Sweden.", None),
    ("Jobbet är krävande.", "The job is demanding.", None),
    ("En utmaning varje dag.", "A challenge every day.", None),
    ("Landet är vackert.", "The country is beautiful.", None),
    ("En chans att lära sig.", "A chance to learn.", None),
    ("Livet är kort.", "Life is short.", None),
    ("En vinter i Sverige.", "A winter in Sweden.", None),
    ("Ljuset är starkt.", "The light is strong.", None),
    ("En sommar vid havet.", "A summer by the sea.", None),
    ("Systemet fungerar bra.", "The system works well.", "\"Systemet\" — not to be confused with \"Systembolaget,\" the government-run liquor store."),
    ("En skola nära hemmet.", "A school near home.", None),
    ("Biblioteket är stängt.", "The library is closed.", None),
    ("En park i centrum.", "A park in the center.", None),
    ("Kafét har gott kaffe.", "The café has good coffee.", None),
    ("En butik på gatan.", "A shop on the street.", None),
    ("Hotellet är fullt.", "The hotel is full.", None),
    ("En restaurang vid torget.", "A restaurant by the square.", None),
    ("Tåget är försenat.", "The train is delayed.", None),
    ("En buss till flygplatsen.", "A bus to the airport.", None),
    ("Flygplanet landar snart.", "The airplane is landing soon.", None),
    ("En cykel utanför huset.", "A bicycle outside the house.", None),
    ("Regnet har slutat.", "The rain has stopped.", None),
    ("En sol som skiner.", "A sun that shines.", None),
    ("Snön faller sakta.", "The snow falls slowly.", None),
    ("En vind från havet.", "A wind from the sea.", None),
    ("Mörkret kommer tidigt.", "The darkness comes early.", "In Swedish winters, darkness falls very early — as early as 3 PM in December in Stockholm."),
    ("En stjärna på himlen.", "A star in the sky.", None),
    ("Månen är full ikväll.", "The moon is full tonight.", None),
    ("En regnbåge efter regnet.", "A rainbow after the rain.", None),
    ("Djuret är sällsynt.", "The animal is rare.", None),
    ("En fågel i trädet.", "A bird in the tree.", None),
    ("Fältet är grönt.", "The field is green.", None),
    ("En å rinner genom byn.", "A stream runs through the village.", "\"Å\" is one of the shortest words in Swedish — it means \"stream\" and is also the name of a letter."),
    ("Berget syns på avstånd.", "The mountain is visible from a distance.", None),
    ("En ö i skärgården.", "An island in the archipelago.", None),
    ("Slottet är gammalt.", "The castle is old.", None),
    ("En hamn vid kusten.", "A harbor on the coast.", None),
    ("Tornet är högt.", "The tower is tall.", None),
    ("En bänk i parken.", "A bench in the park.", None),
    ("Altanen är solig.", "The patio is sunny.", None),
    ("En grind framför huset.", "A gate in front of the house.", None),
    ("Taket är rött.", "The roof is red.", "Red wooden houses (\"röda stugor\") are iconic in Swedish countryside, painted with Falu red pigment."),
    ("En skorsten på taket.", "A chimney on the roof.", None),
    ("Garaget är fullt.", "The garage is full.", None),
    ("En trappa upp till lägenheten.", "A staircase up to the apartment.", None),
    ("Pianot behöver stämmas.", "The piano needs tuning.", None),
    ("En gitarr i hörnet.", "A guitar in the corner.", None),
    ("Instrumentet låter fint.", "The instrument sounds nice.", None),
    ("En tavla på väggen.", "A painting on the wall.", None),
    ("Spegeln är trasig.", "The mirror is broken.", None),
    ("En matta på golvet.", "A carpet on the floor.", None),
    ("Skåpet är tomt.", "The cupboard is empty.", None),
    ("En säng med mjuka kuddar.", "A bed with soft pillows.", None),
    ("Ljuset i rummet är varmt.", "The light in the room is warm.", None),
    ("En vas med blommor.", "A vase with flowers.", None),
    ("Fotoalbumet är gammalt.", "The photo album is old.", None),
    ("En klocka på väggen.", "A clock on the wall.", None),
    ("Kylskåpet är tomt.", "The fridge is empty.", None),
    ("En ugn i köket.", "An oven in the kitchen.", None),
    ("Diskmaskinen är full.", "The dishwasher is full.", None),
]

# For the remaining nodes, I will build comprehensive card lists.
# Each node needs 110-115 unique cards.

node_05_cards = [
    ("Idag äter vi pasta.", "Today we eat pasta.", "The V2 rule: the verb MUST be in second position. When a non-subject starts, the verb comes before the subject."),
    ("Igår regnade det hela dagen.", "Yesterday it rained all day.", "\"Igår\" is first, so \"regnade\" (verb) comes second, then \"det\" (subject). This is V2."),
    ("Ofta dricker jag kaffe.", "Often I drink coffee.", "When \"ofta\" starts the sentence, the verb \"dricker\" must come second, pushing \"jag\" after it."),
    ("I Stockholm bor det många människor.", "In Stockholm live many people.", None),
    ("Varje dag går jag till jobbet.", "Every day I walk to work.", None),
    ("Nu börjar det regna.", "Now it's starting to rain.", None),
    ("Sedan 2010 har hon bott i Malmö.", "Since 2010 she has lived in Malmö.", None),
    ("Här kan man köpa biljetter.", "Here you can buy tickets.", None),
    ("Aldrig har jag sett något sådant.", "Never have I seen anything like it.", "Starting with \"aldrig\" creates dramatic emphasis and triggers V2 inversion."),
    ("Kanske kommer han imorgon.", "Maybe he will come tomorrow.", None),
    ("Jag läser en bok varje kväll.", "I read a book every evening.", "Standard SVO order when the subject starts the sentence — no inversion needed."),
    ("I morse åt vi frukost tidigt.", "This morning we ate breakfast early.", None),
    ("Förra veckan reste vi till Kiruna.", "Last week we traveled to Kiruna.", None),
    ("Där borta ligger affären.", "Over there lies the store.", None),
    ("Snart kommer sommaren.", "Soon summer will come.", None),
    ("Ibland går vi ut och äter.", "Sometimes we go out to eat.", None),
    ("På kvällen tittar vi på TV.", "In the evening we watch TV.", None),
    ("I helgen ska vi åka till stugan.", "On the weekend we are going to the cabin.", None),
    ("Efter jobbet tränar jag.", "After work I exercise.", None),
    ("Först äter vi, sedan går vi.", "First we eat, then we go.", None),
    ("Dessutom regnar det.", "Moreover, it's raining.", None),
    ("Även i Sverige snöar det inte alltid.", "Even in Sweden it doesn't always snow.", None),
    ("Redan klockan sex vaknade jag.", "Already at six o'clock I woke up.", None),
    ("Hemma hos oss firar vi alltid jul.", "At our home we always celebrate Christmas.", None),
    ("Under sommaren badar vi i sjön.", "During the summer we swim in the lake.", None),
    ("Plötsligt stannade bussen.", "Suddenly the bus stopped.", None),
    ("Lyckligtvis hittade vi vägen.", "Fortunately we found the way.", None),
    ("Förmodligen kommer det att regna.", "Probably it will rain.", None),
    ("Tyvärr kan jag inte komma.", "Unfortunately I cannot come.", None),
    ("Faktiskt tycker jag om vintern.", "Actually, I like winter.", None),
    ("Egentligen borde vi gå nu.", "Actually, we should go now.", None),
    ("Normalt sett äter vi klockan sex.", "Normally we eat at six.", None),
    ("Framför allt gillar jag fika.", "Above all I like fika.", None),
    ("Till slut hittade vi restaurangen.", "Finally we found the restaurant.", None),
    ("Naturligtvis hjälper jag dig.", "Of course I'll help you.", None),
    ("I Sverige är sommaren kort.", "In Sweden the summer is short.", None),
    ("Mitt i natten vaknade jag.", "In the middle of the night I woke up.", None),
    ("Varför kommer du inte?", "Why aren't you coming?", "In questions with a question word, V2 still applies: question word + verb + subject."),
    ("När börjar filmen?", "When does the movie start?", None),
    ("Vad gör du här?", "What are you doing here?", None),
    ("Hur mår du idag?", "How are you today?", None),
    ("Var ligger biblioteket?", "Where is the library?", None),
    ("Vem har nyckeln?", "Who has the key?", "When the question word IS the subject (\"vem\"), there's no inversion: Vem + verb."),
    ("Vilken film vill du se?", "Which movie do you want to see?", None),
    ("Hur många bor här?", "How many live here?", None),
    ("Varför är affären stängd?", "Why is the store closed?", None),
    ("Så fort jag kom hem somnade jag.", "As soon as I got home I fell asleep.", None),
    ("Ju mer jag läser, desto bättre förstår jag.", "The more I read, the better I understand.", "\"Ju ... desto\" is the Swedish equivalent of \"the more ... the more.\""),
    ("Inte bara regnade det, utan det blåste också.", "Not only did it rain, but it was also windy.", None),
    ("Sällan ser man norrsken i södra Sverige.", "Seldom do you see the northern lights in southern Sweden.", None),
    ("Med glädje hjälper jag dig.", "With pleasure I'll help you.", None),
    ("Bakom huset finns en trädgård.", "Behind the house there is a garden.", None),
    ("Framför skolan stannar bussen.", "In front of the school the bus stops.", None),
    ("Bredvid banken ligger apoteket.", "Next to the bank is the pharmacy.", None),
    ("Utan tvivel är det rätt beslut.", "Without a doubt it's the right decision.", None),
    ("Trots regnet gick vi ut.", "Despite the rain we went out.", None),
    ("Enligt tidningen är det sant.", "According to the newspaper it's true.", None),
    ("I jämförelse med Norge är Sverige större.", "In comparison with Norway, Sweden is larger.", None),
    ("Under helgen arbetar hon.", "During the weekend she works.", None),
    ("På tisdag har vi möte.", "On Tuesday we have a meeting.", None),
    ("Efter middagen dricker vi kaffe.", "After dinner we drink coffee.", None),
    ("Innan lunch måste jag handla.", "Before lunch I must shop.", None),
    ("Jag vet att han bor i Uppsala.", "I know that he lives in Uppsala.", None),
    ("Klockan åtta börjar lektionen.", "At eight o'clock the lesson starts.", None),
    ("Så småningom lärde jag mig.", "Eventually I learned.", None),
    ("Utanför dörren väntar en taxi.", "Outside the door a taxi is waiting.", None),
    ("Innanför grinden leker barnen.", "Inside the gate the children play.", None),
    ("Längs vägen växer blommor.", "Along the road flowers grow.", None),
    ("Genom parken går en stig.", "Through the park runs a path.", None),
    ("Runt sjön finns det vandringsleder.", "Around the lake there are hiking trails.", None),
    ("Nedanför berget ligger en by.", "Below the mountain lies a village.", None),
    ("Ovanför molnen skiner solen.", "Above the clouds the sun shines.", None),
    ("Bland alla elever är hon bäst.", "Among all students she is the best.", None),
    ("Mellan husen finns en gränd.", "Between the houses there is an alley.", None),
    ("Dit åker vi varje sommar.", "There we go every summer.", None),
    ("Härifrån ser man hela staden.", "From here you can see the whole city.", None),
    ("Överallt ser man svenska flaggor.", "Everywhere you see Swedish flags.", None),
    ("Nog kan du stanna lite till.", "Surely you can stay a bit longer.", None),
    ("Knappt hade vi kommit fram förrän det började regna.", "We had barely arrived when it started raining.", None),
    ("Inte förrän imorgon kan jag svara.", "Not until tomorrow can I answer.", None),
    ("Bara på sommaren är det så varmt.", "Only in summer is it this warm.", None),
    ("Särskilt på vintern är det mörkt.", "Especially in winter it is dark.", None),
    ("Allt oftare jobbar folk hemifrån.", "More and more often people work from home.", None),
    ("Fortfarande bor hon i samma stad.", "She still lives in the same city.", None),
    ("Hellre cyklar jag än kör bil.", "I'd rather cycle than drive a car.", None),
    ("Lika gärna kan vi gå.", "We might as well walk.", None),
    ("I alla fall är vi framme nu.", "In any case we are here now.", None),
    ("Å andra sidan har han rätt.", "On the other hand he is right.", None),
    ("Trots allt blev det bra.", "After all it turned out well.", None),
    ("Med andra ord ska vi vänta.", "In other words we should wait.", None),
    ("I samband med flytten bytte hon jobb.", "In connection with the move she changed jobs.", None),
    ("Tack vare dig lyckades vi.", "Thanks to you we succeeded.", None),
    ("På grund av regnet ställdes matchen in.", "Because of the rain the match was cancelled.", None),
    ("I stället för att klaga borde vi agera.", "Instead of complaining we should act.", None),
    ("Under alla omständigheter kommer jag.", "Under all circumstances I will come.", None),
    ("Till en början var det svårt.", "At first it was difficult.", None),
    ("I slutändan spelar det ingen roll.", "In the end it doesn't matter.", None),
    ("Å ena sidan förstår jag dig.", "On one hand I understand you.", None),
    ("Kort sagt fungerar det bra.", "In short it works well.", None),
    ("Som tur var hittade vi biljetten.", "Luckily we found the ticket.", None),
    ("Hur som helst måste vi gå nu.", "Anyway we must go now.", None),
    ("I värsta fall får vi vänta.", "In the worst case we'll have to wait.", None),
    ("I bästa fall är vi framme klockan tre.", "In the best case we'll arrive at three.", None),
    ("Utöver det har vi inga problem.", "Besides that we have no problems.", None),
    ("Med tanke på vädret stannar vi inne.", "Considering the weather we'll stay inside.", None),
    ("Hittills har allt gått bra.", "So far everything has gone well.", None),
    ("Ännu har ingen klagat.", "No one has complained yet.", None),
    ("Senast igår pratade jag med honom.", "Just yesterday I spoke with him.", None),
    ("Sedan dess har jag inte hört något.", "Since then I have not heard anything.", None),
    ("Inom kort får vi besked.", "Shortly we'll get a response.", None),
    ("Numera arbetar hon deltid.", "Nowadays she works part-time.", None),
    ("Under tiden kan du vänta här.", "In the meantime you can wait here.", None),
    ("Lite senare kom resten av gruppen.", "A little later the rest of the group arrived.", None),
    ("Strax före midnatt gick vi hem.", "Just before midnight we went home.", None),
    ("Dagligen promenerar hon i parken.", "Daily she walks in the park.", None),
    ("Visserligen är det dyrt, men det är värt det.", "Admittedly it's expensive, but it's worth it.", None),
]

# I'll now create a large generation script that defines all 35 nodes and outputs the JSON.
# Due to the size, I'll generate remaining nodes programmatically with diverse, natural sentences.

def gen_tags():
    """Generate tags ensuring 'general' is always present and travel/work/family each ~50%."""
    tags = ["general"]
    if random.random() < 0.5:
        tags.append("travel")
    if random.random() < 0.5:
        tags.append("work")
    if random.random() < 0.5:
        tags.append("family")
    return tags

# We'll load all node data from the large data file
# For now, write a stub that writes out what we have and generates the rest

# All remaining node card data will be defined inline below
# Due to Python script size, I'll write a comprehensive data file

print("Script loaded. Building deck...")

# The full card data is stored in a separate file to keep this manageable
# Let me instead write the JSON directly

import sys
sys.exit(0)  # placeholder - real generation happens in the next script
