/** Etymology entry – manually curated. NEVER generated by an LLM at runtime.
 *
 *  Anti-hallucination contract:
 *   - Every entry must be cross-checked against canonical sources
 *     (Wiktionary, Etymonline, RAE for Spanish, etc.)
 *   - `verified: true` is the gate – the UI ignores `verified: false`
 *   - `sources` lists which references back the claim
 *   - The QC script (scripts/etymology/qc.cjs) refuses jargon-laden notes
 *     and unverified entries at build time.
 */
export interface EtymologyEntry {
  /** Lowercased lookup key, e.g. "sangre". May include diacritics. */
  word: string;
  /** Origin language + word, plain text e.g. "Latin sanguis" or "Arabic al-jabr". */
  origin: string;
  /** English (or other) cognates that share the etymological root. */
  cognates?: string[];
  /** Short factual note, no jargon, max 150 chars. */
  note: string;
  /** Manual sign-off – only `true` entries appear in the UI. */
  verified: boolean;
  /** Which references support this entry, e.g. ['wiktionary', 'etymonline']. */
  sources: string[];
}

/** Frozen reference list of source identifiers permitted in entries. */
export const ALLOWED_SOURCES = [
  'wiktionary',
  'etymonline',
  'rae',          // Real Academia Española
  'cnrtl',        // French national centre – for FR (future)
  'duden',        // German (future)
  'turner-cdial', // Turner's Comparative Dictionary of Indo-Aryan
  'vasmer',       // Vasmer's Russian Etymological Dictionary
] as const;
