/**
 * Merge the four Indonesian pilot batches into deck.json + dictionary,
 * then run the local gates (uniqueness, offenders, tags, tips, ids).
 *
 *   npx tsx scripts/tmp/merge-id-pilot.ts          # check only
 *   npx tsx scripts/tmp/merge-id-pilot.ts --write  # write deck + dict
 */
import { readFileSync, writeFileSync } from 'fs';

const ROOT = new URL('../..', import.meta.url).pathname;
const write = process.argv.includes('--write');

interface Card { id: string; target: string; english: string; audio: string; tags: string[]; grammarNode: string; priority: number; grammar?: string }
interface DictEntry { en: string; ipa?: string; pos?: string; lemma?: string }

const cards: Card[] = [];
const dict: Record<string, DictEntry> = {};
for (const b of ['A', 'B', 'C', 'D']) {
  const cs: Card[] = JSON.parse(readFileSync(`${ROOT}scripts/tmp/pilot-id-cards-${b}.json`, 'utf8'));
  cards.push(...cs);
  const d: Record<string, DictEntry> = JSON.parse(readFileSync(`${ROOT}scripts/tmp/pilot-id-dict-${b}.json`, 'utf8'));
  for (const [k, v] of Object.entries(d)) {
    const key = k.toLowerCase();
    if (!dict[key]) dict[key] = v;
  }
}

const problems: string[] = [];

// ids sequential + unique, audio convention, priority
const ids = new Set<string>();
cards.sort((a, b) => a.id.localeCompare(b.id));
cards.forEach((c, i) => {
  if (ids.has(c.id)) problems.push(`dup id ${c.id}`);
  ids.add(c.id);
  const want = `id-${String(i + 1).padStart(4, '0')}`;
  if (c.id !== want) problems.push(`id gap: got ${c.id}, expected ${want}`);
  if (c.audio !== `id-${c.id}.mp3`) problems.push(`${c.id}: audio "${c.audio}"`);
  if (!c.tags?.includes('general')) problems.push(`${c.id}: missing general tag`);
});

// sentence uniqueness
const seen = new Map<string, string>();
for (const c of cards) {
  const norm = c.target.toLowerCase().replace(/[^a-z ]/g, '').trim();
  if (seen.has(norm)) problems.push(`dup sentence: ${c.id} == ${seen.get(norm)}`);
  seen.set(norm, c.id);
}

// register offenders
const off = JSON.parse(readFileSync(`${ROOT}docs/indonesian-register-offenders.json`, 'utf8'));
for (const c of cards) {
  const toks = new Set(c.target.toLowerCase().replace(/[^a-z -]/g, '').split(/\s+/));
  for (const o of off.offenders) {
    if (toks.has(o.word)) problems.push(`${c.id}: offender "${o.word}" (${o.severity})`);
  }
}

// tips
const tips = cards.filter(c => c.grammar);
for (const c of tips) {
  if (c.grammar!.length > 120) problems.push(`${c.id}: tip ${c.grammar!.length} chars`);
}

// dict coverage against merged dict
let missing = 0;
const missingToks = new Set<string>();
for (const c of cards) {
  for (const raw of c.target.split(/\s+/)) {
    const tok = raw.toLowerCase().replace(/[^a-z-]/g, '');
    if (tok && !dict[tok]) { missing++; missingToks.add(tok); }
  }
}
if (missing) problems.push(`${missing} tokens missing from merged dict: ${[...missingToks].slice(0, 15).join(', ')}`);

// tag distribution
const tagCount: Record<string, number> = {};
for (const c of cards) for (const t of c.tags) tagCount[t] = (tagCount[t] || 0) + 1;

console.log(`cards: ${cards.length}, tips: ${tips.length} (${Math.round(tips.length * 100 / cards.length)}%), dict entries: ${Object.keys(dict).length}`);
console.log('tags:', JSON.stringify(tagCount));
if (problems.length) {
  console.log(`\n${problems.length} PROBLEMS:`);
  for (const p of problems.slice(0, 40)) console.log('  ·', p);
}

if (write) {
  if (problems.some(p => !p.startsWith('id gap'))) {
    console.log('\nrefusing to --write with problems present');
    process.exit(1);
  }
  writeFileSync(`${ROOT}src/data/indonesian/deck.json`, JSON.stringify(cards, null, 1) + '\n');
  // splice merged dict into src/data/dictionary/id.ts between markers
  const dictPath = `${ROOT}src/data/dictionary/id.ts`;
  let src = readFileSync(dictPath, 'utf8');
  // keys already present in the seed DICT — skip to avoid duplicate-key errors
  const seedKeys = new Set(
    [...src.matchAll(/^\s{2}['"]([^'"]+)['"]:\s*\{/gm)].map(m => m[1])
  );
  const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  const lines = Object.entries(dict)
    .filter(([k]) => !seedKeys.has(k))
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([k, v]) => {
      const key = k.includes("'") ? `"${k}"` : `'${k}'`;
      const parts = [`en: '${esc(v.en)}'`];
      if (v.ipa) parts.push(`ipa: '${esc(v.ipa)}'`);
      if (v.pos) parts.push(`pos: '${esc(v.pos)}'`);
      if (v.lemma) parts.push(`lemma: '${esc(v.lemma)}'`);
      return `  ${key}: { ${parts.join(', ')} },`;
    });
  const block = `\n  // ── Pilot deck entries (generated by merge-id-pilot.ts) ──\n${lines.join('\n')}\n`;
  src = src.replace(/\n  \/\/ ── Pilot deck entries[\s\S]*?\n};/, '\n};'); // idempotent re-run
  src = src.replace(/\n};\n\nconst clean/, `${block}};\n\nconst clean`);
  writeFileSync(dictPath, src);
  console.log(`\nwrote deck.json (${cards.length} cards) + dictionary (${lines.length} entries spliced)`);
}
