const fs = require('fs');
const path = require('path');

const BASE = '/Users/antoinevj/Documents/GitHub/my-gamified-srs-app/.claude/worktrees/agitated-boyd';

// Word-level alignment mappings for Germanic languages
// These map target-language words to concise English meanings

const DE_DICT = {
  // Articles
  'der': 'the', 'die': 'the', 'das': 'the', 'den': 'the', 'dem': 'the', 'des': 'the',
  'ein': 'a', 'eine': 'a', 'einen': 'a', 'einem': 'a', 'einer': 'a', 'eines': 'a',
  'kein': 'no', 'keine': 'no', 'keinen': 'no', 'keinem': 'no', 'keiner': 'no',
  // Pronouns
  'ich': 'I', 'du': 'you', 'er': 'he', 'sie': 'she/they', 'es': 'it',
  'wir': 'we', 'ihr': 'you (pl)', 'man': 'one',
  'mich': 'me', 'dich': 'you', 'ihn': 'him', 'uns': 'us', 'euch': 'you (pl)',
  'mir': 'to me', 'dir': 'to you', 'ihm': 'to him', 'ihr': 'to her',
  'ihnen': 'to them', 'sich': 'oneself',
  'mein': 'my', 'meine': 'my', 'meinen': 'my', 'meinem': 'my', 'meiner': 'my',
  'dein': 'your', 'deine': 'your', 'deinen': 'your', 'deinem': 'your',
  'sein': 'his', 'seine': 'his', 'seinen': 'his', 'seinem': 'his', 'seiner': 'his',
  'unser': 'our', 'unsere': 'our', 'unseren': 'our', 'unserem': 'our',
  'euer': 'your (pl)', 'eure': 'your (pl)',
  'dieser': 'this', 'diese': 'this', 'dieses': 'this', 'diesem': 'this', 'diesen': 'this',
  'jeder': 'every', 'jede': 'every', 'jedes': 'every', 'jedem': 'every',
  'welcher': 'which', 'welche': 'which', 'welches': 'which',
  'was': 'what', 'wer': 'who', 'wen': 'whom', 'wem': 'to whom',
  'wo': 'where', 'wann': 'when', 'wie': 'how', 'warum': 'why', 'woher': 'from where', 'wohin': 'to where',
  // Prepositions
  'in': 'in', 'im': 'in the', 'ins': 'into the',
  'an': 'at/on', 'am': 'at the', 'ans': 'to the',
  'auf': 'on', 'aus': 'from/out of', 'bei': 'at/near', 'beim': 'at the',
  'mit': 'with', 'nach': 'after/to', 'seit': 'since', 'von': 'from/of', 'vom': 'from the',
  'zu': 'to', 'zum': 'to the', 'zur': 'to the',
  'für': 'for', 'gegen': 'against', 'ohne': 'without', 'um': 'around/at',
  'durch': 'through', 'über': 'over/about', 'unter': 'under', 'vor': 'before/in front',
  'hinter': 'behind', 'neben': 'next to', 'zwischen': 'between',
  'während': 'during', 'wegen': 'because of', 'trotz': 'despite', 'statt': 'instead of',
  'außer': 'except', 'gegenüber': 'opposite',
  // Conjunctions
  'und': 'and', 'oder': 'or', 'aber': 'but', 'sondern': 'but rather',
  'denn': 'because', 'weil': 'because', 'dass': 'that', 'wenn': 'if/when',
  'als': 'as/when/than', 'ob': 'whether', 'obwohl': 'although', 'damit': 'so that',
  'bevor': 'before', 'nachdem': 'after', 'seitdem': 'since', 'sobald': 'as soon as',
  'falls': 'in case', 'indem': 'by (doing)',
  // Adverbs
  'nicht': 'not', 'auch': 'also', 'noch': 'still/yet', 'schon': 'already',
  'immer': 'always', 'nie': 'never', 'oft': 'often', 'manchmal': 'sometimes',
  'hier': 'here', 'dort': 'there', 'da': 'there', 'sehr': 'very',
  'gern': 'gladly', 'gerne': 'gladly', 'vielleicht': 'maybe', 'leider': 'unfortunately',
  'dann': 'then', 'jetzt': 'now', 'heute': 'today', 'morgen': 'tomorrow',
  'gestern': 'yesterday', 'bald': 'soon', 'wieder': 'again', 'zusammen': 'together',
  'allein': 'alone', 'nur': 'only', 'fast': 'almost', 'genug': 'enough',
  'ziemlich': 'quite', 'besonders': 'especially', 'sogar': 'even',
  'eigentlich': 'actually', 'überhaupt': 'at all', 'wirklich': 'really',
  'natürlich': 'of course', 'normalerweise': 'normally', 'trotzdem': 'nevertheless',
  'deshalb': 'therefore', 'außerdem': 'moreover', 'zuerst': 'first',
  'danach': 'afterwards', 'endlich': 'finally', 'plötzlich': 'suddenly',
  'ungefähr': 'approximately', 'mindestens': 'at least', 'höchstens': 'at most',
  'meistens': 'mostly', 'lieber': 'rather/preferably', 'so': 'so',
  // Common verbs (conjugated forms → infinitive meaning)
  'ist': 'to be', 'bin': 'to be', 'bist': 'to be', 'sind': 'to be', 'seid': 'to be',
  'war': 'to be', 'warst': 'to be', 'waren': 'to be', 'wäre': 'would be',
  'hat': 'to have', 'habe': 'to have', 'hast': 'to have', 'haben': 'to have', 'habt': 'to have',
  'hatte': 'to have', 'hätte': 'would have',
  'wird': 'to become', 'werde': 'to become', 'wirst': 'to become', 'werden': 'to become',
  'würde': 'would',
  'kann': 'to be able to', 'kannst': 'to be able to', 'können': 'to be able to', 'konnte': 'could',
  'könnte': 'could',
  'muss': 'to have to', 'musst': 'to have to', 'müssen': 'to have to', 'musste': 'had to',
  'müsste': 'should',
  'soll': 'should', 'sollst': 'should', 'sollen': 'should', 'sollte': 'should',
  'will': 'to want', 'willst': 'to want', 'wollen': 'to want', 'wollte': 'wanted',
  'darf': 'to be allowed', 'darfst': 'to be allowed', 'dürfen': 'to be allowed',
  'mag': 'to like', 'magst': 'to like', 'mögen': 'to like', 'möchte': 'would like',
  'möchtest': 'would like', 'möchten': 'would like',
  'geht': 'to go', 'gehe': 'to go', 'gehst': 'to go', 'gehen': 'to go', 'ging': 'went',
  'gegangen': 'gone',
  'kommt': 'to come', 'komme': 'to come', 'kommst': 'to come', 'kommen': 'to come', 'kam': 'came',
  'gekommen': 'come',
  'macht': 'to make/do', 'mache': 'to make/do', 'machst': 'to make/do', 'machen': 'to make/do',
  'gemacht': 'made/done',
  'gibt': 'to give', 'gebe': 'to give', 'gibst': 'to give', 'geben': 'to give', 'gab': 'gave',
  'gegeben': 'given',
  'sagt': 'to say', 'sage': 'to say', 'sagst': 'to say', 'sagen': 'to say', 'sagte': 'said',
  'gesagt': 'said',
  'nimmt': 'to take', 'nehme': 'to take', 'nimmst': 'to take', 'nehmen': 'to take', 'nahm': 'took',
  'genommen': 'taken',
  'sieht': 'to see', 'sehe': 'to see', 'siehst': 'to see', 'sehen': 'to see', 'sah': 'saw',
  'gesehen': 'seen',
  'weiß': 'to know', 'weißt': 'to know', 'wissen': 'to know', 'wusste': 'knew',
  'kennt': 'to know', 'kenne': 'to know', 'kennst': 'to know', 'kennen': 'to know',
  'findet': 'to find', 'finde': 'to find', 'findest': 'to find', 'finden': 'to find', 'fand': 'found',
  'gefunden': 'found',
  'steht': 'to stand', 'stehe': 'to stand', 'stehen': 'to stand', 'stand': 'stood',
  'liegt': 'to lie/be located', 'liege': 'to lie', 'liegen': 'to lie', 'lag': 'lay',
  'sitzt': 'to sit', 'sitze': 'to sit', 'sitzen': 'to sit', 'saß': 'sat',
  'spricht': 'to speak', 'spreche': 'to speak', 'sprichst': 'to speak', 'sprechen': 'to speak',
  'sprach': 'spoke', 'gesprochen': 'spoken',
  'liest': 'to read', 'lese': 'to read', 'lesen': 'to read', 'las': 'read',
  'gelesen': 'read',
  'schreibt': 'to write', 'schreibe': 'to write', 'schreiben': 'to write', 'schrieb': 'wrote',
  'geschrieben': 'written',
  'arbeitet': 'to work', 'arbeite': 'to work', 'arbeitest': 'to work', 'arbeiten': 'to work',
  'gearbeitet': 'worked',
  'spielt': 'to play', 'spiele': 'to play', 'spielst': 'to play', 'spielen': 'to play',
  'lernt': 'to learn', 'lerne': 'to learn', 'lernst': 'to learn', 'lernen': 'to learn',
  'gelernt': 'learned',
  'kauft': 'to buy', 'kaufe': 'to buy', 'kaufst': 'to buy', 'kaufen': 'to buy',
  'gekauft': 'bought',
  'braucht': 'to need', 'brauche': 'to need', 'brauchst': 'to need', 'brauchen': 'to need',
  'bringt': 'to bring', 'bringe': 'to bring', 'bringst': 'to bring', 'bringen': 'to bring',
  'brachte': 'brought', 'gebracht': 'brought',
  'denkt': 'to think', 'denke': 'to think', 'denkst': 'to think', 'denken': 'to think',
  'dachte': 'thought', 'gedacht': 'thought',
  'glaubt': 'to believe', 'glaube': 'to believe', 'glaubst': 'to believe', 'glauben': 'to believe',
  'hilft': 'to help', 'helfe': 'to help', 'hilfst': 'to help', 'helfen': 'to help',
  'half': 'helped', 'geholfen': 'helped',
  'zeigt': 'to show', 'zeige': 'to show', 'zeigst': 'to show', 'zeigen': 'to show',
  'gezeigt': 'shown',
  'bleibt': 'to stay', 'bleibe': 'to stay', 'bleibst': 'to stay', 'bleiben': 'to stay',
  'blieb': 'stayed', 'geblieben': 'stayed',
  'fährt': 'to drive/go', 'fahre': 'to drive', 'fährst': 'to drive', 'fahren': 'to drive',
  'fuhr': 'drove', 'gefahren': 'driven',
  'fliegt': 'to fly', 'fliege': 'to fly', 'fliegst': 'to fly', 'fliegen': 'to fly',
  'flog': 'flew', 'geflogen': 'flown',
  'läuft': 'to run/walk', 'laufe': 'to run', 'läufst': 'to run', 'laufen': 'to run',
  'lief': 'ran', 'gelaufen': 'run',
  'isst': 'to eat', 'esse': 'to eat', 'essen': 'to eat', 'aß': 'ate', 'gegessen': 'eaten',
  'trinkt': 'to drink', 'trinke': 'to drink', 'trinkst': 'to drink', 'trinken': 'to drink',
  'trank': 'drank', 'getrunken': 'drunk',
  'schläft': 'to sleep', 'schlafe': 'to sleep', 'schläfst': 'to sleep', 'schlafen': 'to sleep',
  'schlief': 'slept', 'geschlafen': 'slept',
  'lebt': 'to live', 'lebe': 'to live', 'lebst': 'to live', 'leben': 'to live',
  'wohnt': 'to live/reside', 'wohne': 'to live', 'wohnst': 'to live', 'wohnen': 'to live',
  'heißt': 'to be called', 'heiße': 'to be called', 'heißen': 'to be called',
  'beginnt': 'to begin', 'beginne': 'to begin', 'beginnst': 'to begin', 'beginnen': 'to begin',
  'begann': 'began', 'begonnen': 'begun',
  'versteht': 'to understand', 'verstehe': 'to understand', 'verstehst': 'to understand',
  'verstehen': 'to understand', 'verstand': 'understood', 'verstanden': 'understood',
  'erzählt': 'to tell', 'erzähle': 'to tell', 'erzählen': 'to tell', 'erzählte': 'told',
  'vergisst': 'to forget', 'vergesse': 'to forget', 'vergessen': 'to forget', 'vergaß': 'forgot',
  'bekommt': 'to receive', 'bekomme': 'to receive', 'bekommen': 'to receive', 'bekam': 'received',
  'gefällt': 'to please', 'gefallen': 'to please',
  'gehört': 'to belong/hear', 'hört': 'to hear', 'höre': 'to hear', 'hören': 'to hear',
  'gehörte': 'belonged',
  'führt': 'to lead', 'führe': 'to lead', 'führen': 'to lead',
  'folgt': 'to follow', 'folge': 'to follow', 'folgen': 'to follow',
  'ruft': 'to call', 'rufe': 'to call', 'rufen': 'to call', 'rief': 'called', 'gerufen': 'called',
  'öffnet': 'to open', 'öffne': 'to open', 'öffnen': 'to open',
  'schließt': 'to close', 'schließe': 'to close', 'schließen': 'to close', 'schloss': 'closed',
  'geschlossen': 'closed',
  'wartet': 'to wait', 'warte': 'to wait', 'wartest': 'to wait', 'warten': 'to wait',
  'freut': 'to please/enjoy', 'freue': 'to enjoy', 'freuen': 'to enjoy',
  'fehlt': 'to be missing', 'fehle': 'to be missing', 'fehlen': 'to be missing',
  'stimmt': 'to be correct', 'stimmen': 'to be correct',
  'passt': 'to fit/suit', 'passen': 'to fit',
  'kostet': 'to cost', 'kosten': 'to cost',
  'bedeutet': 'to mean', 'bedeuten': 'to mean',
  'versucht': 'to try', 'versuche': 'to try', 'versuchen': 'to try',
  'erklärt': 'to explain', 'erkläre': 'to explain', 'erklären': 'to explain',
  'benutzt': 'to use', 'benutze': 'to use', 'benutzen': 'to use',
  'stellt': 'to put/place', 'stelle': 'to put', 'stellen': 'to put',
  'trägt': 'to carry/wear', 'trage': 'to carry', 'tragen': 'to carry',
  'hält': 'to hold', 'halte': 'to hold', 'halten': 'to hold', 'hielt': 'held',
  'gehalten': 'held',
  'fällt': 'to fall', 'falle': 'to fall', 'fallen': 'to fall', 'fiel': 'fell',
  'gefallen': 'fallen/pleased',
  'lässt': 'to let/leave', 'lasse': 'to let', 'lassen': 'to let', 'ließ': 'let',
  'gelassen': 'let',
  'zieht': 'to pull/move', 'ziehe': 'to pull', 'ziehen': 'to pull', 'zog': 'pulled',
  'gezogen': 'pulled',
  'schickt': 'to send', 'schicke': 'to send', 'schicken': 'to send',
  'baut': 'to build', 'baue': 'to build', 'bauen': 'to build',
  'entwickelt': 'to develop', 'entwickeln': 'to develop',
  'bietet': 'to offer', 'biete': 'to offer', 'bieten': 'to offer', 'bot': 'offered',
  'nutzt': 'to use', 'nutze': 'to use', 'nutzen': 'to use',
  'erreicht': 'to reach', 'erreichen': 'to reach',
  'verbessert': 'to improve', 'verbessern': 'to improve',
  'empfiehlt': 'to recommend', 'empfehle': 'to recommend', 'empfehlen': 'to recommend',
  // Common nouns
  'mann': 'man', 'frau': 'woman', 'kind': 'child', 'kinder': 'children',
  'leute': 'people', 'mensch': 'person', 'menschen': 'people',
  'freund': 'friend', 'freundin': 'girlfriend/friend', 'freunde': 'friends',
  'familie': 'family', 'eltern': 'parents', 'mutter': 'mother', 'vater': 'father',
  'bruder': 'brother', 'schwester': 'sister', 'sohn': 'son', 'tochter': 'daughter',
  'haus': 'house', 'wohnung': 'apartment', 'zimmer': 'room', 'küche': 'kitchen',
  'garten': 'garden', 'tür': 'door', 'fenster': 'window',
  'stadt': 'city', 'land': 'country/land', 'straße': 'street', 'platz': 'place/square',
  'weg': 'way/path', 'brücke': 'bridge',
  'schule': 'school', 'universität': 'university', 'klasse': 'class',
  'arbeit': 'work', 'büro': 'office', 'firma': 'company', 'chef': 'boss',
  'tag': 'day', 'nacht': 'night', 'morgen': 'morning', 'abend': 'evening',
  'woche': 'week', 'monat': 'month', 'jahr': 'year', 'zeit': 'time',
  'stunde': 'hour', 'minute': 'minute', 'uhr': 'clock/oclock',
  'auto': 'car', 'bus': 'bus', 'zug': 'train', 'flugzeug': 'airplane',
  'bahn': 'train/railway', 'fahrrad': 'bicycle',
  'essen': 'food', 'trinken': 'drink', 'wasser': 'water', 'brot': 'bread',
  'bier': 'beer', 'wein': 'wine', 'kaffee': 'coffee', 'tee': 'tea',
  'milch': 'milk', 'fleisch': 'meat', 'fisch': 'fish', 'obst': 'fruit',
  'gemüse': 'vegetables', 'kuchen': 'cake', 'reis': 'rice',
  'buch': 'book', 'zeitung': 'newspaper', 'brief': 'letter', 'seite': 'page/side',
  'geld': 'money', 'preis': 'price', 'euro': 'euro',
  'telefon': 'telephone', 'handy': 'cellphone', 'computer': 'computer',
  'musik': 'music', 'film': 'film', 'bild': 'picture', 'foto': 'photo',
  'sport': 'sport', 'spiel': 'game', 'spaß': 'fun',
  'sprache': 'language', 'wort': 'word', 'satz': 'sentence', 'frage': 'question',
  'antwort': 'answer', 'name': 'name', 'beispiel': 'example',
  'problem': 'problem', 'lösung': 'solution', 'idee': 'idea',
  'grund': 'reason', 'ziel': 'goal', 'erfolg': 'success',
  'anfang': 'beginning', 'ende': 'end', 'mitte': 'middle',
  'seite': 'side/page', 'teil': 'part', 'stück': 'piece',
  'farbe': 'color', 'form': 'form/shape', 'größe': 'size',
  'kopf': 'head', 'hand': 'hand', 'auge': 'eye', 'augen': 'eyes',
  'herz': 'heart', 'stimme': 'voice',
  'sonne': 'sun', 'mond': 'moon', 'stern': 'star', 'himmel': 'sky',
  'regen': 'rain', 'schnee': 'snow', 'wind': 'wind', 'wetter': 'weather',
  'baum': 'tree', 'blume': 'flower', 'berg': 'mountain', 'meer': 'sea',
  'fluss': 'river', 'see': 'lake', 'wald': 'forest',
  'tier': 'animal', 'hund': 'dog', 'katze': 'cat', 'vogel': 'bird',
  'tisch': 'table', 'stuhl': 'chair', 'bett': 'bed',
  'arzt': 'doctor', 'ärztin': 'doctor (f)', 'lehrer': 'teacher', 'lehrerin': 'teacher (f)',
  'student': 'student', 'studentin': 'student (f)',
  'polizei': 'police', 'krankenhaus': 'hospital', 'apotheke': 'pharmacy',
  'restaurant': 'restaurant', 'hotel': 'hotel', 'laden': 'shop', 'geschäft': 'shop/business',
  'markt': 'market', 'supermarkt': 'supermarket', 'bank': 'bank',
  'kirche': 'church', 'museum': 'museum', 'bibliothek': 'library', 'park': 'park',
  'flughafen': 'airport', 'bahnhof': 'train station', 'haltestelle': 'stop',
  'reise': 'journey', 'urlaub': 'vacation', 'ferien': 'holidays',
  'gesundheit': 'health', 'krankheit': 'illness',
  'liebe': 'love', 'glück': 'happiness/luck', 'leben': 'life', 'tod': 'death',
  'angst': 'fear', 'hoffnung': 'hope', 'freude': 'joy',
  'kultur': 'culture', 'geschichte': 'history/story', 'kunst': 'art',
  'natur': 'nature', 'umwelt': 'environment', 'energie': 'energy',
  'regierung': 'government', 'politik': 'politics', 'gesellschaft': 'society',
  'recht': 'right/law', 'gesetz': 'law', 'freiheit': 'freedom',
  'sicherheit': 'safety', 'zukunft': 'future', 'vergangenheit': 'past',
  'erfahrung': 'experience', 'möglichkeit': 'possibility', 'gelegenheit': 'opportunity',
  'unterschied': 'difference', 'veränderung': 'change', 'entwicklung': 'development',
  'beziehung': 'relationship', 'verbindung': 'connection', 'bedeutung': 'meaning',
  'entscheidung': 'decision', 'unternehmen': 'company/enterprise',
  // Common adjectives
  'gut': 'good', 'schlecht': 'bad', 'groß': 'big/tall', 'klein': 'small',
  'alt': 'old', 'neu': 'new', 'jung': 'young', 'lang': 'long', 'kurz': 'short',
  'hoch': 'high', 'tief': 'deep', 'breit': 'wide', 'schmal': 'narrow',
  'schnell': 'fast', 'langsam': 'slow', 'leicht': 'easy/light', 'schwer': 'hard/heavy',
  'stark': 'strong', 'schwach': 'weak', 'schön': 'beautiful', 'hässlich': 'ugly',
  'warm': 'warm', 'kalt': 'cold', 'heiß': 'hot', 'kühl': 'cool',
  'hell': 'bright', 'dunkel': 'dark', 'laut': 'loud', 'leise': 'quiet',
  'richtig': 'correct', 'falsch': 'wrong', 'wichtig': 'important', 'möglich': 'possible',
  'nötig': 'necessary', 'fertig': 'finished/ready', 'bereit': 'ready',
  'frei': 'free', 'offen': 'open', 'voll': 'full', 'leer': 'empty',
  'nah': 'near', 'weit': 'far', 'früh': 'early', 'spät': 'late',
  'teuer': 'expensive', 'billig': 'cheap', 'günstig': 'affordable',
  'einfach': 'simple', 'kompliziert': 'complicated', 'interessant': 'interesting',
  'toll': 'great', 'super': 'super', 'wunderbar': 'wonderful', 'fantastisch': 'fantastic',
  'lecker': 'delicious', 'gesund': 'healthy', 'krank': 'sick',
  'müde': 'tired', 'froh': 'happy', 'traurig': 'sad', 'glücklich': 'happy',
  'zufrieden': 'satisfied', 'freundlich': 'friendly', 'nett': 'nice',
  'bekannt': 'known/famous', 'beliebt': 'popular', 'typisch': 'typical',
  'verschieden': 'different', 'ähnlich': 'similar', 'gleich': 'same/equal',
  'ganz': 'whole/quite', 'besonder': 'special', 'bestimmt': 'certain',
  'andere': 'other', 'anderer': 'other', 'anderes': 'other', 'anderen': 'other',
  'erste': 'first', 'erster': 'first', 'erstes': 'first', 'ersten': 'first',
  'letzte': 'last', 'letzter': 'last', 'letztes': 'last', 'letzten': 'last',
  'nächste': 'next', 'nächster': 'next', 'nächstes': 'next', 'nächsten': 'next',
  'beste': 'best', 'bester': 'best', 'bestes': 'best', 'besten': 'best',
  'viel': 'much/many', 'viele': 'many', 'vielen': 'many', 'vieles': 'much',
  'wenig': 'few/little', 'wenige': 'few', 'wenigen': 'few',
  'mehr': 'more', 'weniger': 'less', 'meisten': 'most',
  'alle': 'all', 'aller': 'all', 'alles': 'everything', 'allem': 'all',
  'beide': 'both', 'einige': 'some', 'einigen': 'some',
  'guter': 'good', 'gute': 'good', 'guten': 'good', 'gutem': 'good', 'gutes': 'good',
  'großer': 'big', 'große': 'big', 'großen': 'big', 'großem': 'big', 'großes': 'big',
  'kleiner': 'small', 'kleine': 'small', 'kleinen': 'small', 'kleines': 'small',
  'neuer': 'new', 'neue': 'new', 'neuen': 'new', 'neuem': 'new', 'neues': 'new',
  'alter': 'old', 'alte': 'old', 'alten': 'old', 'altem': 'old', 'altes': 'old',
  'deutscher': 'German', 'deutsche': 'German', 'deutschen': 'German',
  // Misc
  'ja': 'yes', 'nein': 'no', 'bitte': 'please', 'danke': 'thanks',
  'hallo': 'hello', 'tschüss': 'bye', 'guten': 'good',
  'entschuldigung': 'excuse me', 'willkommen': 'welcome',
  'es': 'it', 'etwas': 'something', 'nichts': 'nothing',
  'jemand': 'someone', 'niemand': 'nobody',
  'selbst': 'self', 'einander': 'each other',
  'doch': 'yet/however', 'mal': 'once/time', 'eben': 'just',
  'wohl': 'probably', 'zwar': 'indeed', 'also': 'so/therefore',
  'nämlich': 'namely', 'übrigens': 'by the way',
  'gar': 'at all', 'je': 'ever', 'bereits': 'already',
};

const NL_DICT = {
  // Articles
  'de': 'the', 'het': 'the', 'een': 'a',
  'geen': 'no/none',
  // Pronouns
  'ik': 'I', 'jij': 'you', 'je': 'you', 'hij': 'he', 'zij': 'she/they', 'ze': 'she/they',
  'het': 'it', 'wij': 'we', 'we': 'we', 'jullie': 'you (pl)', 'u': 'you (formal)',
  'mij': 'me', 'me': 'me', 'hem': 'him', 'haar': 'her', 'hen': 'them', 'hun': 'them/their',
  'zich': 'oneself',
  'mijn': 'my', 'jouw': 'your', 'zijn': 'his', 'ons': 'our', 'onze': 'our',
  'jullie': 'your (pl)', 'uw': 'your (formal)',
  'dit': 'this', 'dat': 'that', 'deze': 'this/these', 'die': 'that/those',
  'wat': 'what', 'wie': 'who', 'welk': 'which', 'welke': 'which',
  'waar': 'where', 'wanneer': 'when', 'hoe': 'how', 'waarom': 'why',
  'waarmee': 'with what', 'waarover': 'about what', 'waarvoor': 'for what',
  'iets': 'something', 'niets': 'nothing', 'iemand': 'someone', 'niemand': 'nobody',
  'alles': 'everything', 'iedereen': 'everyone',
  'elk': 'each', 'elke': 'each', 'alle': 'all', 'beiden': 'both',
  'zelf': 'self', 'elkaar': 'each other',
  // Prepositions
  'in': 'in', 'op': 'on', 'aan': 'at/on', 'met': 'with', 'van': 'of/from',
  'voor': 'for/before', 'naar': 'to', 'uit': 'from/out', 'bij': 'at/near',
  'over': 'about/over', 'door': 'through/by', 'om': 'around/at',
  'tussen': 'between', 'onder': 'under', 'boven': 'above',
  'achter': 'behind', 'naast': 'next to', 'tegen': 'against',
  'zonder': 'without', 'tijdens': 'during', 'sinds': 'since',
  'tot': 'until/to', 'na': 'after', 'volgens': 'according to',
  'vanwege': 'because of', 'ondanks': 'despite', 'langs': 'along',
  // Conjunctions
  'en': 'and', 'of': 'or', 'maar': 'but', 'want': 'because',
  'dus': 'so', 'omdat': 'because', 'dat': 'that', 'als': 'if/when/as',
  'toen': 'when/then', 'terwijl': 'while', 'hoewel': 'although',
  'voordat': 'before', 'nadat': 'after', 'zodra': 'as soon as',
  'tenzij': 'unless', 'zodat': 'so that',
  // Adverbs
  'niet': 'not', 'ook': 'also', 'nog': 'still/yet', 'al': 'already',
  'altijd': 'always', 'nooit': 'never', 'vaak': 'often', 'soms': 'sometimes',
  'hier': 'here', 'daar': 'there', 'er': 'there', 'heel': 'very',
  'erg': 'very', 'graag': 'gladly', 'misschien': 'maybe', 'helaas': 'unfortunately',
  'dan': 'then', 'nu': 'now', 'vandaag': 'today', 'morgen': 'tomorrow',
  'gisteren': 'yesterday', 'binnenkort': 'soon', 'weer': 'again',
  'samen': 'together', 'alleen': 'alone', 'maar': 'only/but',
  'bijna': 'almost', 'genoeg': 'enough', 'vrij': 'quite/free',
  'vooral': 'especially', 'zelfs': 'even', 'eigenlijk': 'actually',
  'echt': 'really', 'natuurlijk': 'of course', 'normaal': 'normally',
  'toch': 'yet/still', 'daarom': 'therefore', 'bovendien': 'moreover',
  'eerst': 'first', 'daarna': 'afterwards', 'eindelijk': 'finally',
  'plotseling': 'suddenly', 'ongeveer': 'approximately',
  'minstens': 'at least', 'hoogstens': 'at most', 'meestal': 'mostly',
  'liever': 'rather', 'zo': 'so', 'wel': 'indeed/well',
  'ja': 'yes', 'nee': 'no', 'alsjeblieft': 'please', 'alstublieft': 'please',
  'dank': 'thanks', 'bedankt': 'thanks',
  // Common verbs
  'is': 'to be', 'ben': 'to be', 'bent': 'to be', 'zijn': 'to be', 'was': 'was', 'waren': 'were',
  'heeft': 'to have', 'heb': 'to have', 'hebt': 'to have', 'hebben': 'to have',
  'had': 'had', 'hadden': 'had',
  'wordt': 'to become', 'word': 'to become', 'worden': 'to become', 'werd': 'became',
  'kan': 'to be able to', 'kun': 'to be able to', 'kunt': 'to be able to', 'kunnen': 'to be able to',
  'kon': 'could', 'konden': 'could',
  'moet': 'to have to', 'moeten': 'to have to', 'moest': 'had to',
  'mag': 'to be allowed', 'mogen': 'to be allowed', 'mocht': 'was allowed',
  'wil': 'to want', 'wilt': 'to want', 'willen': 'to want', 'wilde': 'wanted', 'wou': 'wanted',
  'zal': 'will', 'zul': 'will', 'zullen': 'will', 'zou': 'would', 'zouden': 'would',
  'gaat': 'to go', 'ga': 'to go', 'gaan': 'to go', 'ging': 'went', 'gegaan': 'gone',
  'komt': 'to come', 'kom': 'to come', 'komen': 'to come', 'kwam': 'came', 'gekomen': 'come',
  'maakt': 'to make', 'maak': 'to make', 'maken': 'to make', 'maakte': 'made', 'gemaakt': 'made',
  'geeft': 'to give', 'geef': 'to give', 'geven': 'to give', 'gaf': 'gave', 'gegeven': 'given',
  'zegt': 'to say', 'zeg': 'to say', 'zeggen': 'to say', 'zei': 'said', 'gezegd': 'said',
  'neemt': 'to take', 'neem': 'to take', 'nemen': 'to take', 'nam': 'took', 'genomen': 'taken',
  'ziet': 'to see', 'zie': 'to see', 'zien': 'to see', 'zag': 'saw', 'gezien': 'seen',
  'weet': 'to know', 'weten': 'to know', 'wist': 'knew', 'geweten': 'known',
  'kent': 'to know', 'ken': 'to know', 'kennen': 'to know', 'kende': 'knew', 'gekend': 'known',
  'vindt': 'to find', 'vind': 'to find', 'vinden': 'to find', 'vond': 'found', 'gevonden': 'found',
  'staat': 'to stand', 'sta': 'to stand', 'staan': 'to stand', 'stond': 'stood',
  'ligt': 'to lie', 'lig': 'to lie', 'liggen': 'to lie', 'lag': 'lay',
  'zit': 'to sit', 'zitten': 'to sit', 'zat': 'sat',
  'spreekt': 'to speak', 'spreek': 'to speak', 'spreken': 'to speak', 'sprak': 'spoke',
  'leest': 'to read', 'lees': 'to read', 'lezen': 'to read', 'las': 'read',
  'schrijft': 'to write', 'schrijf': 'to write', 'schrijven': 'to write', 'schreef': 'wrote',
  'werkt': 'to work', 'werk': 'to work', 'werken': 'to work', 'werkte': 'worked',
  'speelt': 'to play', 'speel': 'to play', 'spelen': 'to play',
  'leert': 'to learn', 'leer': 'to learn', 'leren': 'to learn',
  'koopt': 'to buy', 'koop': 'to buy', 'kopen': 'to buy', 'kocht': 'bought', 'gekocht': 'bought',
  'denkt': 'to think', 'denk': 'to think', 'denken': 'to think', 'dacht': 'thought',
  'gedacht': 'thought',
  'gelooft': 'to believe', 'geloof': 'to believe', 'geloven': 'to believe',
  'helpt': 'to help', 'help': 'to help', 'helpen': 'to help', 'hielp': 'helped',
  'laat': 'to let/show', 'laten': 'to let', 'liet': 'let',
  'blijft': 'to stay', 'blijf': 'to stay', 'blijven': 'to stay', 'bleef': 'stayed',
  'gebleven': 'stayed',
  'rijdt': 'to drive', 'rijd': 'to drive', 'rijden': 'to drive', 'reed': 'drove',
  'loopt': 'to walk', 'loop': 'to walk', 'lopen': 'to walk', 'liep': 'walked',
  'eet': 'to eat', 'eten': 'to eat', 'at': 'ate', 'gegeten': 'eaten',
  'drinkt': 'to drink', 'drink': 'to drink', 'drinken': 'to drink', 'dronk': 'drank',
  'slaapt': 'to sleep', 'slaap': 'to sleep', 'slapen': 'to sleep', 'sliep': 'slept',
  'woont': 'to live', 'woon': 'to live', 'wonen': 'to live', 'woonde': 'lived',
  'leeft': 'to live', 'leef': 'to live', 'leven': 'to live', 'leefde': 'lived',
  'heet': 'to be called', 'heten': 'to be called',
  'begint': 'to begin', 'begin': 'to begin', 'beginnen': 'to begin', 'begon': 'began',
  'begrijpt': 'to understand', 'begrijp': 'to understand', 'begrijpen': 'to understand',
  'begreep': 'understood',
  'vertelt': 'to tell', 'vertel': 'to tell', 'vertellen': 'to tell', 'vertelde': 'told',
  'vergeet': 'to forget', 'vergeten': 'to forget', 'vergat': 'forgot',
  'krijgt': 'to get', 'krijg': 'to get', 'krijgen': 'to get', 'kreeg': 'got',
  'gekregen': 'gotten',
  'stuurt': 'to send', 'stuur': 'to send', 'sturen': 'to send',
  'bouwt': 'to build', 'bouw': 'to build', 'bouwen': 'to build',
  'biedt': 'to offer', 'bied': 'to offer', 'bieden': 'to offer', 'bood': 'offered',
  'bereikt': 'to reach', 'bereiken': 'to reach',
  'gebruikt': 'to use', 'gebruik': 'to use', 'gebruiken': 'to use',
  'probeert': 'to try', 'probeer': 'to try', 'proberen': 'to try',
  'wacht': 'to wait', 'wachten': 'to wait',
  'kost': 'to cost', 'kosten': 'to cost',
  'betekent': 'to mean', 'betekenen': 'to mean',
  'hoort': 'to hear', 'hoor': 'to hear', 'horen': 'to hear',
  'voelt': 'to feel', 'voel': 'to feel', 'voelen': 'to feel',
  'lijkt': 'to seem', 'lijk': 'to seem', 'lijken': 'to seem', 'leek': 'seemed',
  'valt': 'to fall', 'vallen': 'to fall', 'viel': 'fell',
  'trekt': 'to pull', 'trek': 'to pull', 'trekken': 'to pull', 'trok': 'pulled',
  'brengt': 'to bring', 'breng': 'to bring', 'brengen': 'to bring', 'bracht': 'brought',
  'gebracht': 'brought',
  'noemt': 'to call/name', 'noem': 'to call', 'noemen': 'to call',
  'vraagt': 'to ask', 'vraag': 'to ask', 'vragen': 'to ask', 'vroeg': 'asked',
  'gevraagd': 'asked',
  'kijkt': 'to look', 'kijk': 'to look', 'kijken': 'to look', 'keek': 'looked',
  'praat': 'to talk', 'praten': 'to talk', 'praatte': 'talked',
  'betaalt': 'to pay', 'betaal': 'to pay', 'betalen': 'to pay', 'betaalde': 'paid',
  'opent': 'to open', 'open': 'open', 'openen': 'to open',
  'sluit': 'to close', 'sluiten': 'to close', 'sloot': 'closed',
  // Common nouns
  'man': 'man', 'vrouw': 'woman', 'kind': 'child', 'kinderen': 'children',
  'mensen': 'people', 'mens': 'person',
  'vriend': 'friend', 'vriendin': 'girlfriend/friend', 'vrienden': 'friends',
  'familie': 'family', 'ouders': 'parents', 'moeder': 'mother', 'vader': 'father',
  'broer': 'brother', 'zus': 'sister', 'zoon': 'son', 'dochter': 'daughter',
  'huis': 'house', 'woning': 'dwelling', 'kamer': 'room', 'keuken': 'kitchen',
  'tuin': 'garden', 'deur': 'door', 'raam': 'window',
  'stad': 'city', 'land': 'country', 'straat': 'street',
  'school': 'school', 'universiteit': 'university',
  'werk': 'work', 'kantoor': 'office', 'bedrijf': 'company', 'baas': 'boss',
  'dag': 'day', 'nacht': 'night', 'ochtend': 'morning', 'avond': 'evening',
  'week': 'week', 'maand': 'month', 'jaar': 'year', 'tijd': 'time',
  'uur': 'hour', 'minuut': 'minute',
  'auto': 'car', 'bus': 'bus', 'trein': 'train', 'vliegtuig': 'airplane', 'fiets': 'bicycle',
  'eten': 'food', 'water': 'water', 'brood': 'bread',
  'bier': 'beer', 'wijn': 'wine', 'koffie': 'coffee', 'thee': 'tea', 'melk': 'milk',
  'vlees': 'meat', 'vis': 'fish', 'fruit': 'fruit', 'groente': 'vegetables',
  'boek': 'book', 'krant': 'newspaper', 'brief': 'letter',
  'geld': 'money', 'prijs': 'price',
  'telefoon': 'telephone', 'computer': 'computer',
  'muziek': 'music', 'film': 'film', 'foto': 'photo',
  'sport': 'sport', 'spel': 'game', 'plezier': 'fun',
  'taal': 'language', 'woord': 'word', 'zin': 'sentence', 'vraag': 'question',
  'antwoord': 'answer', 'naam': 'name', 'voorbeeld': 'example',
  'probleem': 'problem', 'oplossing': 'solution', 'idee': 'idea',
  'reden': 'reason', 'doel': 'goal', 'succes': 'success',
  'begin': 'beginning', 'einde': 'end', 'midden': 'middle',
  'kant': 'side', 'deel': 'part', 'stuk': 'piece',
  'kleur': 'color', 'vorm': 'form',
  'hoofd': 'head', 'hand': 'hand', 'oog': 'eye', 'ogen': 'eyes',
  'hart': 'heart', 'stem': 'voice',
  'zon': 'sun', 'maan': 'moon', 'ster': 'star', 'lucht': 'sky/air',
  'regen': 'rain', 'sneeuw': 'snow', 'wind': 'wind', 'weer': 'weather',
  'boom': 'tree', 'bloem': 'flower', 'berg': 'mountain', 'zee': 'sea',
  'rivier': 'river', 'meer': 'lake', 'bos': 'forest',
  'dier': 'animal', 'hond': 'dog', 'kat': 'cat', 'vogel': 'bird',
  'tafel': 'table', 'stoel': 'chair', 'bed': 'bed',
  'arts': 'doctor', 'dokter': 'doctor', 'leraar': 'teacher', 'lerares': 'teacher (f)',
  'student': 'student',
  'politie': 'police', 'ziekenhuis': 'hospital', 'apotheek': 'pharmacy',
  'restaurant': 'restaurant', 'hotel': 'hotel', 'winkel': 'shop',
  'markt': 'market', 'supermarkt': 'supermarket', 'bank': 'bank',
  'kerk': 'church', 'museum': 'museum', 'bibliotheek': 'library', 'park': 'park',
  'luchthaven': 'airport', 'station': 'station', 'halte': 'stop',
  'reis': 'journey', 'vakantie': 'vacation',
  'gezondheid': 'health', 'ziekte': 'illness',
  'liefde': 'love', 'geluk': 'happiness/luck', 'leven': 'life', 'dood': 'death',
  'angst': 'fear', 'hoop': 'hope', 'vreugde': 'joy',
  'cultuur': 'culture', 'geschiedenis': 'history', 'kunst': 'art',
  'natuur': 'nature', 'milieu': 'environment', 'energie': 'energy',
  'regering': 'government', 'politiek': 'politics', 'maatschappij': 'society',
  'recht': 'right/law', 'wet': 'law', 'vrijheid': 'freedom',
  'veiligheid': 'safety', 'toekomst': 'future', 'verleden': 'past',
  'ervaring': 'experience', 'mogelijkheid': 'possibility', 'kans': 'chance',
  'verschil': 'difference', 'verandering': 'change', 'ontwikkeling': 'development',
  'relatie': 'relationship', 'verbinding': 'connection', 'betekenis': 'meaning',
  'beslissing': 'decision',
  // Common adjectives
  'goed': 'good', 'goede': 'good', 'slecht': 'bad', 'slechte': 'bad',
  'groot': 'big', 'grote': 'big', 'klein': 'small', 'kleine': 'small',
  'oud': 'old', 'oude': 'old', 'nieuw': 'new', 'nieuwe': 'new',
  'jong': 'young', 'jonge': 'young', 'lang': 'long/tall', 'lange': 'long/tall',
  'kort': 'short', 'korte': 'short', 'hoog': 'high', 'hoge': 'high',
  'diep': 'deep', 'diepe': 'deep', 'breed': 'wide', 'brede': 'wide',
  'snel': 'fast', 'snelle': 'fast', 'langzaam': 'slow',
  'makkelijk': 'easy', 'moeilijk': 'difficult',
  'sterk': 'strong', 'sterke': 'strong', 'zwak': 'weak',
  'mooi': 'beautiful', 'mooie': 'beautiful', 'lelijk': 'ugly',
  'warm': 'warm', 'warme': 'warm', 'koud': 'cold', 'koude': 'cold',
  'heet': 'hot', 'hete': 'hot',
  'licht': 'light', 'donker': 'dark', 'donkere': 'dark',
  'hard': 'hard/loud', 'zacht': 'soft/quiet',
  'juist': 'correct', 'fout': 'wrong', 'belangrijk': 'important', 'belangrijke': 'important',
  'mogelijk': 'possible', 'nodig': 'necessary', 'klaar': 'ready/done',
  'vrij': 'free', 'vol': 'full', 'volle': 'full', 'leeg': 'empty', 'lege': 'empty',
  'dichtbij': 'nearby', 'ver': 'far', 'vroeg': 'early', 'laat': 'late',
  'duur': 'expensive', 'dure': 'expensive', 'goedkoop': 'cheap', 'goedkope': 'cheap',
  'leuk': 'nice/fun', 'leuke': 'nice/fun', 'lekker': 'delicious/nice',
  'gezond': 'healthy', 'gezonde': 'healthy', 'ziek': 'sick', 'zieke': 'sick',
  'moe': 'tired', 'blij': 'happy', 'blije': 'happy', 'verdrietig': 'sad',
  'gelukkig': 'happy', 'tevreden': 'satisfied', 'vriendelijk': 'friendly',
  'aardig': 'nice', 'aardige': 'nice',
  'bekend': 'known', 'bekende': 'known', 'populair': 'popular',
  'verschillend': 'different', 'verschillende': 'different',
  'hetzelfde': 'the same',
  'heel': 'whole/very', 'hele': 'whole', 'speciaal': 'special', 'speciale': 'special',
  'ander': 'other', 'andere': 'other', 'anderen': 'others',
  'eerste': 'first', 'laatste': 'last', 'volgende': 'next',
  'beste': 'best',
  'veel': 'much/many', 'vele': 'many', 'weinig': 'few/little',
  'meer': 'more', 'minder': 'less', 'meeste': 'most',
  // Misc
  'hallo': 'hello', 'dag': 'hello/day', 'goedemorgen': 'good morning',
  'goedemiddag': 'good afternoon', 'goedenavond': 'good evening',
  'aangenaam': 'pleased', 'kennis': 'knowledge/acquaintance',
  'te': 'to/too', 'er': 'there',
};

const SV_DICT = {
  // Articles/Determiners
  'en': 'a', 'ett': 'a', 'den': 'the', 'det': 'the/it', 'de': 'the',
  'denna': 'this', 'detta': 'this', 'dessa': 'these',
  'ingen': 'no/none', 'inget': 'no/none', 'inga': 'no/none',
  // Pronouns
  'jag': 'I', 'du': 'you', 'han': 'he', 'hon': 'she', 'vi': 'we',
  'ni': 'you (pl)', 'dem': 'them', 'dom': 'they/them',
  'mig': 'me', 'dig': 'you', 'honom': 'him', 'henne': 'her', 'oss': 'us',
  'sig': 'oneself',
  'min': 'my', 'mitt': 'my', 'mina': 'my',
  'din': 'your', 'ditt': 'your', 'dina': 'your',
  'hans': 'his', 'hennes': 'her', 'sin': 'ones own', 'sitt': 'ones own', 'sina': 'ones own',
  'vår': 'our', 'vårt': 'our', 'våra': 'our',
  'er': 'your (pl)', 'ert': 'your (pl)', 'era': 'your (pl)',
  'deras': 'their',
  'vad': 'what', 'vem': 'who', 'vilken': 'which', 'vilket': 'which', 'vilka': 'which',
  'var': 'where', 'när': 'when', 'hur': 'how', 'varför': 'why',
  'vart': 'where to', 'varifrån': 'from where',
  'något': 'something', 'ingenting': 'nothing', 'någon': 'someone', 'några': 'some',
  'alla': 'all/everyone', 'allt': 'everything', 'varje': 'every',
  'själv': 'self', 'varandra': 'each other',
  'man': 'one/you',
  // Prepositions
  'i': 'in', 'på': 'on/at', 'till': 'to', 'från': 'from', 'med': 'with',
  'av': 'of/by', 'för': 'for', 'om': 'about/if', 'vid': 'at/by',
  'mot': 'towards/against', 'efter': 'after', 'under': 'under/during',
  'över': 'over/about', 'mellan': 'between', 'genom': 'through',
  'utan': 'without', 'enligt': 'according to', 'bland': 'among',
  'bakom': 'behind', 'framför': 'in front of', 'bredvid': 'next to',
  'sedan': 'since/then', 'inom': 'within', 'utanför': 'outside',
  'längs': 'along', 'trots': 'despite',
  // Conjunctions
  'och': 'and', 'eller': 'or', 'men': 'but', 'så': 'so',
  'att': 'that/to', 'om': 'if/about', 'när': 'when', 'medan': 'while',
  'fast': 'although', 'fastän': 'although', 'eftersom': 'since/because',
  'innan': 'before', 'tills': 'until', 'för att': 'in order to',
  // Adverbs
  'inte': 'not', 'också': 'also', 'redan': 'already', 'fortfarande': 'still',
  'alltid': 'always', 'aldrig': 'never', 'ofta': 'often', 'ibland': 'sometimes',
  'här': 'here', 'där': 'there', 'mycket': 'very/much', 'väldigt': 'very',
  'gärna': 'gladly', 'kanske': 'maybe', 'tyvärr': 'unfortunately',
  'sedan': 'then/since', 'nu': 'now', 'idag': 'today', 'imorgon': 'tomorrow',
  'igår': 'yesterday', 'snart': 'soon', 'igen': 'again',
  'tillsammans': 'together', 'ensam': 'alone', 'bara': 'only/just',
  'nästan': 'almost', 'tillräckligt': 'enough', 'ganska': 'quite',
  'särskilt': 'especially', 'till och med': 'even', 'egentligen': 'actually',
  'verkligen': 'really', 'förstås': 'of course', 'naturligtvis': 'of course',
  'ändå': 'still/anyway', 'därför': 'therefore', 'dessutom': 'moreover',
  'först': 'first', 'sedan': 'then', 'äntligen': 'finally',
  'plötsligt': 'suddenly', 'ungefär': 'approximately',
  'åtminstone': 'at least', 'mest': 'most', 'hellre': 'rather',
  'ju': 'as you know', 'nog': 'probably/enough', 'väl': 'well/surely',
  'ja': 'yes', 'nej': 'no', 'tack': 'thanks',
  // Common verbs
  'är': 'to be', 'var': 'was/were', 'varit': 'been', 'vara': 'to be',
  'har': 'to have', 'hade': 'had', 'haft': 'had', 'ha': 'to have',
  'blir': 'to become', 'blev': 'became', 'blivit': 'become', 'bli': 'to become',
  'kan': 'to be able to', 'kunde': 'could', 'kunnat': 'been able',
  'ska': 'will/shall', 'skulle': 'would/should',
  'måste': 'must/have to',
  'vill': 'to want', 'ville': 'wanted', 'velat': 'wanted',
  'får': 'to get/may', 'fick': 'got', 'fått': 'gotten', 'få': 'to get',
  'gör': 'to do/make', 'gjorde': 'did/made', 'gjort': 'done/made', 'göra': 'to do',
  'går': 'to go/walk', 'gick': 'went', 'gått': 'gone', 'gå': 'to go',
  'kommer': 'to come', 'kom': 'came', 'kommit': 'come', 'komma': 'to come',
  'tar': 'to take', 'tog': 'took', 'tagit': 'taken', 'ta': 'to take',
  'ger': 'to give', 'gav': 'gave', 'gett': 'given', 'ge': 'to give', 'givit': 'given',
  'ser': 'to see', 'såg': 'saw', 'sett': 'seen', 'se': 'to see',
  'säger': 'to say', 'sa': 'said', 'sagt': 'said', 'säga': 'to say',
  'vet': 'to know', 'visste': 'knew', 'vetat': 'known', 'veta': 'to know',
  'känner': 'to feel/know', 'kände': 'felt/knew', 'känt': 'felt/known',
  'känna': 'to feel/know',
  'tycker': 'to think/feel', 'tyckte': 'thought', 'tyckt': 'thought',
  'tycka': 'to think',
  'tänker': 'to think', 'tänkte': 'thought', 'tänkt': 'thought', 'tänka': 'to think',
  'tror': 'to believe', 'trodde': 'believed', 'trott': 'believed', 'tro': 'to believe',
  'hittar': 'to find', 'hittade': 'found', 'hittat': 'found', 'hitta': 'to find',
  'finns': 'to exist', 'fanns': 'existed', 'funnits': 'existed', 'finnas': 'to exist',
  'står': 'to stand', 'stod': 'stood', 'stått': 'stood', 'stå': 'to stand',
  'ligger': 'to lie', 'låg': 'lay', 'legat': 'lain', 'ligga': 'to lie',
  'sitter': 'to sit', 'satt': 'sat', 'suttit': 'sat', 'sitta': 'to sit',
  'talar': 'to speak', 'talade': 'spoke', 'talat': 'spoken', 'tala': 'to speak',
  'pratar': 'to talk', 'pratade': 'talked', 'pratat': 'talked', 'prata': 'to talk',
  'läser': 'to read', 'läste': 'read', 'läst': 'read', 'läsa': 'to read',
  'skriver': 'to write', 'skrev': 'wrote', 'skrivit': 'written', 'skriva': 'to write',
  'arbetar': 'to work', 'arbetade': 'worked', 'arbetat': 'worked', 'arbeta': 'to work',
  'jobbar': 'to work', 'jobbade': 'worked', 'jobbat': 'worked', 'jobba': 'to work',
  'spelar': 'to play', 'spelade': 'played', 'spelat': 'played', 'spela': 'to play',
  'lär': 'to learn/teach', 'lärde': 'learned', 'lärt': 'learned', 'lära': 'to learn',
  'köper': 'to buy', 'köpte': 'bought', 'köpt': 'bought', 'köpa': 'to buy',
  'behöver': 'to need', 'behövde': 'needed', 'behövt': 'needed', 'behöva': 'to need',
  'hjälper': 'to help', 'hjälpte': 'helped', 'hjälpt': 'helped', 'hjälpa': 'to help',
  'visar': 'to show', 'visade': 'showed', 'visat': 'shown', 'visa': 'to show',
  'stannar': 'to stay', 'stannade': 'stayed', 'stannat': 'stayed', 'stanna': 'to stay',
  'bor': 'to live', 'bodde': 'lived', 'bott': 'lived', 'bo': 'to live',
  'lever': 'to live', 'levde': 'lived', 'levt': 'lived', 'leva': 'to live',
  'heter': 'to be called', 'hette': 'was called', 'hetat': 'been called',
  'börjar': 'to begin', 'började': 'began', 'börjat': 'begun', 'börja': 'to begin',
  'förstår': 'to understand', 'förstod': 'understood', 'förstått': 'understood',
  'förstå': 'to understand',
  'berättar': 'to tell', 'berättade': 'told', 'berättat': 'told', 'berätta': 'to tell',
  'glömmer': 'to forget', 'glömde': 'forgot', 'glömt': 'forgotten', 'glömma': 'to forget',
  'äter': 'to eat', 'åt': 'ate', 'ätit': 'eaten', 'äta': 'to eat',
  'dricker': 'to drink', 'drack': 'drank', 'druckit': 'drunk', 'dricka': 'to drink',
  'sover': 'to sleep', 'sov': 'slept', 'sovit': 'slept', 'sova': 'to sleep',
  'springer': 'to run', 'sprang': 'ran', 'sprungit': 'run', 'springa': 'to run',
  'kör': 'to drive', 'körde': 'drove', 'kört': 'driven', 'köra': 'to drive',
  'flyger': 'to fly', 'flög': 'flew', 'flugit': 'flown', 'flyga': 'to fly',
  'skickar': 'to send', 'skickade': 'sent', 'skickat': 'sent', 'skicka': 'to send',
  'bygger': 'to build', 'byggde': 'built', 'byggt': 'built', 'bygga': 'to build',
  'erbjuder': 'to offer', 'erbjöd': 'offered', 'erbjudit': 'offered',
  'använder': 'to use', 'använde': 'used', 'använt': 'used', 'använda': 'to use',
  'försöker': 'to try', 'försökte': 'tried', 'försökt': 'tried', 'försöka': 'to try',
  'väntar': 'to wait', 'väntade': 'waited', 'väntat': 'waited', 'vänta': 'to wait',
  'kostar': 'to cost', 'kostade': 'cost', 'kostat': 'cost', 'kosta': 'to cost',
  'betyder': 'to mean', 'betydde': 'meant', 'betytt': 'meant', 'betyda': 'to mean',
  'hör': 'to hear', 'hörde': 'heard', 'hört': 'heard', 'höra': 'to hear',
  'lämnar': 'to leave', 'lämnade': 'left', 'lämnat': 'left', 'lämna': 'to leave',
  'öppnar': 'to open', 'öppnade': 'opened', 'öppnat': 'opened', 'öppna': 'to open',
  'stänger': 'to close', 'stängde': 'closed', 'stängt': 'closed', 'stänga': 'to close',
  'följer': 'to follow', 'följde': 'followed', 'följt': 'followed', 'följa': 'to follow',
  'leder': 'to lead', 'ledde': 'led', 'lett': 'led', 'leda': 'to lead',
  'bär': 'to carry', 'bar': 'carried', 'burit': 'carried', 'bära': 'to carry',
  'håller': 'to hold', 'höll': 'held', 'hållit': 'held', 'hålla': 'to hold',
  'faller': 'to fall', 'föll': 'fell', 'fallit': 'fallen', 'falla': 'to fall',
  'drar': 'to pull', 'drog': 'pulled', 'dragit': 'pulled', 'dra': 'to pull',
  'betalar': 'to pay', 'betalade': 'paid', 'betalat': 'paid', 'betala': 'to pay',
  'ringer': 'to call', 'ringde': 'called', 'ringt': 'called', 'ringa': 'to call',
  'frågar': 'to ask', 'frågade': 'asked', 'frågat': 'asked', 'fråga': 'to ask',
  'tittar': 'to look', 'tittade': 'looked', 'tittat': 'looked', 'titta': 'to look',
  'passar': 'to fit/suit', 'passade': 'suited', 'passat': 'suited',
  'gillar': 'to like', 'gillade': 'liked', 'gillat': 'liked', 'gilla': 'to like',
  'älskar': 'to love', 'älskade': 'loved', 'älskat': 'loved', 'älska': 'to love',
  'saknar': 'to miss', 'saknade': 'missed', 'saknat': 'missed', 'sakna': 'to miss',
  'verkar': 'to seem', 'verkade': 'seemed',
  // Common nouns
  'man': 'man', 'kvinna': 'woman', 'barn': 'child', 'barnen': 'the children',
  'människor': 'people', 'människa': 'person',
  'vän': 'friend', 'vänner': 'friends', 'kompis': 'buddy',
  'familj': 'family', 'föräldrar': 'parents', 'mamma': 'mom', 'pappa': 'dad',
  'mor': 'mother', 'far': 'father', 'bror': 'brother', 'syster': 'sister',
  'son': 'son', 'dotter': 'daughter',
  'hus': 'house', 'lägenhet': 'apartment', 'rum': 'room', 'kök': 'kitchen',
  'trädgård': 'garden', 'dörr': 'door', 'fönster': 'window',
  'stad': 'city', 'land': 'country', 'gata': 'street', 'väg': 'road/way',
  'plats': 'place',
  'skola': 'school', 'universitet': 'university',
  'arbete': 'work', 'jobb': 'job', 'kontor': 'office', 'företag': 'company',
  'chef': 'boss',
  'dag': 'day', 'natt': 'night', 'morgon': 'morning', 'kväll': 'evening',
  'vecka': 'week', 'månad': 'month', 'år': 'year', 'tid': 'time',
  'timme': 'hour', 'minut': 'minute', 'klockan': 'oclock',
  'bil': 'car', 'buss': 'bus', 'tåg': 'train', 'flyg': 'flight', 'cykel': 'bicycle',
  'mat': 'food', 'vatten': 'water', 'bröd': 'bread',
  'öl': 'beer', 'vin': 'wine', 'kaffe': 'coffee', 'te': 'tea', 'mjölk': 'milk',
  'kött': 'meat', 'fisk': 'fish', 'frukt': 'fruit', 'grönsaker': 'vegetables',
  'bok': 'book', 'tidning': 'newspaper', 'brev': 'letter',
  'pengar': 'money', 'pris': 'price',
  'telefon': 'telephone', 'dator': 'computer', 'mobil': 'cellphone',
  'musik': 'music', 'film': 'film', 'bild': 'picture', 'foto': 'photo',
  'sport': 'sport', 'spel': 'game',
  'språk': 'language', 'ord': 'word', 'mening': 'sentence/meaning',
  'fråga': 'question', 'svar': 'answer', 'namn': 'name', 'exempel': 'example',
  'problem': 'problem', 'lösning': 'solution', 'idé': 'idea',
  'anledning': 'reason', 'mål': 'goal', 'framgång': 'success',
  'början': 'beginning', 'slut': 'end', 'mitt': 'middle',
  'sida': 'side/page', 'del': 'part', 'bit': 'piece',
  'färg': 'color', 'form': 'form/shape', 'storlek': 'size',
  'huvud': 'head', 'hand': 'hand', 'öga': 'eye', 'ögon': 'eyes',
  'hjärta': 'heart', 'röst': 'voice',
  'sol': 'sun', 'måne': 'moon', 'stjärna': 'star', 'himmel': 'sky',
  'regn': 'rain', 'snö': 'snow', 'vind': 'wind', 'väder': 'weather',
  'träd': 'tree', 'blomma': 'flower', 'berg': 'mountain', 'hav': 'sea',
  'flod': 'river', 'sjö': 'lake', 'skog': 'forest',
  'djur': 'animal', 'hund': 'dog', 'katt': 'cat', 'fågel': 'bird',
  'bord': 'table', 'stol': 'chair', 'säng': 'bed',
  'läkare': 'doctor', 'lärare': 'teacher', 'student': 'student',
  'polis': 'police', 'sjukhus': 'hospital', 'apotek': 'pharmacy',
  'restaurang': 'restaurant', 'hotell': 'hotel', 'affär': 'shop', 'butik': 'shop',
  'marknad': 'market', 'bank': 'bank',
  'kyrka': 'church', 'museum': 'museum', 'bibliotek': 'library', 'park': 'park',
  'flygplats': 'airport', 'station': 'station',
  'resa': 'journey', 'semester': 'vacation',
  'hälsa': 'health', 'sjukdom': 'illness',
  'kärlek': 'love', 'lycka': 'happiness', 'liv': 'life', 'död': 'death',
  'rädsla': 'fear', 'hopp': 'hope', 'glädje': 'joy',
  'kultur': 'culture', 'historia': 'history', 'konst': 'art',
  'natur': 'nature', 'miljö': 'environment', 'energi': 'energy',
  'regering': 'government', 'politik': 'politics', 'samhälle': 'society',
  'rätt': 'right', 'lag': 'law', 'frihet': 'freedom',
  'säkerhet': 'safety', 'framtid': 'future',
  'erfarenhet': 'experience', 'möjlighet': 'possibility', 'chans': 'chance',
  'skillnad': 'difference', 'förändring': 'change', 'utveckling': 'development',
  'förhållande': 'relationship', 'koppling': 'connection', 'beslut': 'decision',
  // Common adjectives
  'bra': 'good', 'dålig': 'bad', 'dåligt': 'bad',
  'stor': 'big', 'stort': 'big', 'stora': 'big',
  'liten': 'small', 'litet': 'small', 'lilla': 'small', 'små': 'small',
  'gammal': 'old', 'gammalt': 'old', 'gamla': 'old',
  'ny': 'new', 'nytt': 'new', 'nya': 'new',
  'ung': 'young', 'ungt': 'young', 'unga': 'young',
  'lång': 'long/tall', 'långt': 'long', 'långa': 'long',
  'kort': 'short', 'korta': 'short',
  'hög': 'high', 'högt': 'high', 'höga': 'high',
  'djup': 'deep', 'djupt': 'deep',
  'snabb': 'fast', 'snabbt': 'fast', 'snabba': 'fast',
  'långsam': 'slow', 'långsamt': 'slow',
  'lätt': 'easy/light', 'svår': 'difficult', 'svårt': 'difficult', 'svåra': 'difficult',
  'stark': 'strong', 'starkt': 'strong', 'starka': 'strong',
  'svag': 'weak', 'svagt': 'weak',
  'vacker': 'beautiful', 'vackert': 'beautiful', 'vackra': 'beautiful',
  'ful': 'ugly', 'fult': 'ugly',
  'varm': 'warm', 'varmt': 'warm', 'varma': 'warm',
  'kall': 'cold', 'kallt': 'cold', 'kalla': 'cold',
  'het': 'hot', 'hett': 'hot',
  'ljus': 'bright/light', 'ljust': 'bright', 'ljusa': 'bright',
  'mörk': 'dark', 'mörkt': 'dark', 'mörka': 'dark',
  'rätt': 'correct/right', 'fel': 'wrong',
  'viktig': 'important', 'viktigt': 'important', 'viktiga': 'important',
  'möjlig': 'possible', 'möjligt': 'possible',
  'nödvändig': 'necessary',
  'fri': 'free', 'fritt': 'free', 'fria': 'free',
  'öppen': 'open', 'öppet': 'open', 'öppna': 'open',
  'full': 'full', 'fullt': 'full',
  'tom': 'empty', 'tomt': 'empty',
  'nära': 'near', 'långt': 'far',
  'tidig': 'early', 'tidigt': 'early', 'sen': 'late', 'sent': 'late',
  'dyr': 'expensive', 'dyrt': 'expensive', 'dyra': 'expensive',
  'billig': 'cheap', 'billigt': 'cheap',
  'enkel': 'simple', 'enkelt': 'simple',
  'intressant': 'interesting', 'intressanta': 'interesting',
  'rolig': 'fun/funny', 'roligt': 'fun', 'roliga': 'fun',
  'god': 'good/tasty', 'gott': 'tasty', 'goda': 'good',
  'frisk': 'healthy', 'sjuk': 'sick', 'sjukt': 'sick',
  'trött': 'tired', 'tröttt': 'tired',
  'glad': 'happy', 'glatt': 'happy', 'glada': 'happy',
  'ledsen': 'sad', 'ledset': 'sad', 'ledsna': 'sad',
  'lycklig': 'happy', 'lyckligt': 'happy',
  'nöjd': 'satisfied', 'nöjda': 'satisfied',
  'vänlig': 'friendly', 'vänligt': 'friendly',
  'trevlig': 'nice', 'trevligt': 'nice', 'trevliga': 'nice',
  'känd': 'known/famous', 'känt': 'known', 'kända': 'known',
  'populär': 'popular', 'populärt': 'popular',
  'olika': 'different', 'liknande': 'similar', 'samma': 'same',
  'hel': 'whole', 'helt': 'whole/completely', 'hela': 'whole',
  'speciell': 'special', 'speciellt': 'special', 'speciella': 'special',
  'annan': 'other', 'annat': 'other', 'andra': 'other',
  'första': 'first', 'sista': 'last', 'nästa': 'next',
  'bästa': 'best', 'bättre': 'better',
  'mycket': 'much/many', 'många': 'many', 'lite': 'little',
  'mer': 'more', 'mindre': 'less', 'mest': 'most', 'flest': 'most',
  'svensk': 'Swedish', 'svenska': 'Swedish',
  // Misc
  'hej': 'hello', 'god': 'good', 'tack': 'thanks',
  'ursäkta': 'excuse me', 'välkommen': 'welcome',
};

function cleanWord(w) {
  return w.toLowerCase().replace(/[.,!?;:"""''()[\]{}\-––…·\/\\«»¡¿]/g, '').trim();
}

function processLanguage(deckPath, dict, langCode) {
  const deck = JSON.parse(fs.readFileSync(deckPath, 'utf8'));
  const alignments = {};
  let matched = 0;
  let total = 0;

  for (const card of deck) {
    const words = card.target.split(/\s+/);
    for (const raw of words) {
      const w = cleanWord(raw);
      if (!w || w.length === 0) continue;
      total++;

      const meaning = dict[w];
      if (meaning) {
        matched++;
        if (!alignments[w]) alignments[w] = [];
        alignments[w].push({ en: meaning, card: String(card.id) });
      } else {
        // Try without trailing 's' for Swedish genitive, etc.
        // Still record the word even without translation
        if (!alignments[w]) alignments[w] = [];
        alignments[w].push({ en: '?', card: String(card.id) });
      }
    }
  }

  console.log(`${langCode}: ${deck.length} cards, ${total} word tokens, ${matched} matched (${(matched/total*100).toFixed(1)}%), ${Object.keys(alignments).length} unique words`);
  return { alignments };
}

// Process all three
const deResult = processLanguage(
  path.join(BASE, 'src/data/german/deck.json'),
  DE_DICT, 'DE'
);
fs.writeFileSync(
  path.join(BASE, 'scripts/output/de-alignments.json'),
  JSON.stringify(deResult, null, 2)
);

const nlResult = processLanguage(
  path.join(BASE, 'src/data/dutch/deck.json'),
  NL_DICT, 'NL'
);
fs.writeFileSync(
  path.join(BASE, 'scripts/output/nl-alignments.json'),
  JSON.stringify(nlResult, null, 2)
);

const svResult = processLanguage(
  path.join(BASE, 'src/data/swedish/deck.json'),
  SV_DICT, 'SV'
);
fs.writeFileSync(
  path.join(BASE, 'scripts/output/sv-alignments.json'),
  JSON.stringify(svResult, null, 2)
);

console.log('Done! Files written to scripts/output/');
