import { lookupWord as luFr } from '../src/data/dictionary/fr';
import { lookupWord as luNl } from '../src/data/dictionary/nl';
import { lookupWord as luEs } from '../src/data/dictionary/es';
import { lookupWord as luIt } from '../src/data/dictionary/it';
import { lookupWord as luDe } from '../src/data/dictionary/de';
console.log('FR:');
console.log('  addition:', JSON.stringify(luFr('addition')));
console.log('  facture:', JSON.stringify(luFr('facture')));
console.log('  note:', JSON.stringify(luFr('note')));
console.log('NL:');
console.log('  rekening:', JSON.stringify(luNl('rekening')));
console.log('  factuur:', JSON.stringify(luNl('factuur')));
console.log('ES:');
console.log('  cuenta:', JSON.stringify(luEs('cuenta')));
console.log('  factura:', JSON.stringify(luEs('factura')));
console.log('IT:');
console.log('  conto:', JSON.stringify(luIt('conto')));
console.log('  fattura:', JSON.stringify(luIt('fattura')));
console.log('DE:');
console.log('  Rechnung:', JSON.stringify(luDe('Rechnung')));
console.log('  rechnung:', JSON.stringify(luDe('rechnung')));
