/**
 * expand-to-5000.cjs
 *
 * Expand the Spanish deck from ~2791 to 5000 cards.
 * Adds 2209 new high-quality everyday sentences organized by grammar level.
 *
 * Distribution: ~110 new cards per node (20 nodes × 110 ≈ 2200)
 * Focus: Natural everyday sentences using top 3000-4000 most common Spanish words
 * Tags: Boost work (currently 13%) and balance travel/family
 */

const fs = require('fs');
const path = require('path');

const DECK_PATH = path.join(__dirname, '..', 'src', 'data', 'spanish', 'deck.json');
const deck = JSON.parse(fs.readFileSync(DECK_PATH, 'utf-8'));

console.log(`Current deck: ${deck.length} cards`);

// Track existing sentences to avoid duplicates
const existingTargets = new Set(deck.map(c => c.target.toLowerCase().trim()));

// ─── NEW CARDS BY GRAMMAR NODE ───────────────────────────────────
// Each node gets ~110 new cards. Sentences are natural, everyday usage.
// Grammar focus matches the CEFR node structure.

const newCardsByNode = {

  // ═══════════════════════════════════════════════════════════════
  // NODE 1: Present Tense (A1)
  // ═══════════════════════════════════════════════════════════════
  1: [
    { target: "Siempre desayuno a las ocho.", english: "I always have breakfast at eight.", tags: ["general"] },
    { target: "Mi hermana trabaja en un hospital.", english: "My sister works in a hospital.", tags: ["general", "family", "work"] },
    { target: "Los lunes voy al gimnasio.", english: "On Mondays I go to the gym.", tags: ["general"] },
    { target: "Ellos viven cerca de la playa.", english: "They live near the beach.", tags: ["general"] },
    { target: "Nosotros hablamos español en casa.", english: "We speak Spanish at home.", tags: ["general", "family"] },
    { target: "Mi padre cocina muy bien.", english: "My father cooks very well.", tags: ["general", "family"] },
    { target: "Ella lee el periódico cada mañana.", english: "She reads the newspaper every morning.", tags: ["general"] },
    { target: "Yo corro en el parque por las tardes.", english: "I run in the park in the afternoons.", tags: ["general"] },
    { target: "Mis amigos juegan fútbol los sábados.", english: "My friends play soccer on Saturdays.", tags: ["general"] },
    { target: "Escribo correos electrónicos todo el día.", english: "I write emails all day.", tags: ["general", "work"] },
    { target: "Mi jefe siempre llega tarde.", english: "My boss always arrives late.", tags: ["general", "work"] },
    { target: "Comemos juntos los domingos.", english: "We eat together on Sundays.", tags: ["general", "family"] },
    { target: "Ella estudia medicina en Madrid.", english: "She studies medicine in Madrid.", tags: ["general"] },
    { target: "Yo prefiero el café con leche.", english: "I prefer coffee with milk.", tags: ["general"] },
    { target: "Mi madre camina una hora cada día.", english: "My mother walks one hour every day.", tags: ["general", "family"] },
    { target: "Ellos no entienden la pregunta.", english: "They don't understand the question.", tags: ["general"] },
    { target: "Nosotros cenamos a las nueve.", english: "We have dinner at nine.", tags: ["general"] },
    { target: "Él abre la tienda a las diez.", english: "He opens the shop at ten.", tags: ["general", "work"] },
    { target: "Yo tomo el autobús para ir al trabajo.", english: "I take the bus to go to work.", tags: ["general", "work", "travel"] },
    { target: "Mi vecino tiene tres perros.", english: "My neighbor has three dogs.", tags: ["general"] },
    { target: "Ella habla cuatro idiomas.", english: "She speaks four languages.", tags: ["general", "work"] },
    { target: "Yo duermo solo seis horas.", english: "I only sleep six hours.", tags: ["general"] },
    { target: "Este restaurante cierra los martes.", english: "This restaurant closes on Tuesdays.", tags: ["general", "travel"] },
    { target: "Mi hijo aprende muy rápido.", english: "My son learns very quickly.", tags: ["general", "family"] },
    { target: "Nosotros compartimos un piso.", english: "We share an apartment.", tags: ["general"] },
    { target: "Ella sale del trabajo a las cinco.", english: "She leaves work at five.", tags: ["general", "work"] },
    { target: "Yo compro fruta en el mercado.", english: "I buy fruit at the market.", tags: ["general"] },
    { target: "Mi abuela cuenta historias increíbles.", english: "My grandmother tells incredible stories.", tags: ["general", "family"] },
    { target: "Él conduce demasiado rápido.", english: "He drives too fast.", tags: ["general"] },
    { target: "Nosotros practicamos yoga los miércoles.", english: "We practice yoga on Wednesdays.", tags: ["general"] },
    { target: "Ella conoce a todo el mundo aquí.", english: "She knows everyone here.", tags: ["general"] },
    { target: "Yo ahorro dinero cada mes.", english: "I save money every month.", tags: ["general", "work"] },
    { target: "Los trenes salen cada media hora.", english: "The trains leave every half hour.", tags: ["general", "travel"] },
    { target: "Mi compañero de trabajo habla mucho.", english: "My coworker talks a lot.", tags: ["general", "work"] },
    { target: "Ella pone música mientras cocina.", english: "She plays music while she cooks.", tags: ["general"] },
    { target: "Yo nunca bebo alcohol.", english: "I never drink alcohol.", tags: ["general"] },
    { target: "Mis hijos van al colegio en bicicleta.", english: "My kids go to school by bicycle.", tags: ["general", "family"] },
    { target: "Él piensa demasiado las cosas.", english: "He overthinks things.", tags: ["general"] },
    { target: "La reunión empieza a las tres.", english: "The meeting starts at three.", tags: ["general", "work"], grammar: "Present tense for scheduled events" },
    { target: "Yo paso mucho tiempo en el teléfono.", english: "I spend a lot of time on my phone.", tags: ["general"] },
    { target: "Ella siempre dice la verdad.", english: "She always tells the truth.", tags: ["general"] },
    { target: "Mi perro come de todo.", english: "My dog eats everything.", tags: ["general", "family"] },
    { target: "Nosotros pagamos el alquiler el día uno.", english: "We pay the rent on the first.", tags: ["general"] },
    { target: "Él parece cansado hoy.", english: "He looks tired today.", tags: ["general", "work"] },
    { target: "Yo sé nadar pero no muy bien.", english: "I know how to swim but not very well.", tags: ["general"] },
    { target: "Mi familia vive en otra ciudad.", english: "My family lives in another city.", tags: ["general", "family"] },
    { target: "Este café no tiene wifi.", english: "This café doesn't have wifi.", tags: ["general", "travel"] },
    { target: "Ella cree que es buena idea.", english: "She thinks it's a good idea.", tags: ["general"] },
    { target: "Los niños juegan en el patio.", english: "The kids play in the yard.", tags: ["general", "family"] },
    { target: "Yo necesito unas vacaciones.", english: "I need a vacation.", tags: ["general", "travel"] },
    { target: "Mi teléfono suena todo el rato.", english: "My phone rings all the time.", tags: ["general"] },
    { target: "Ella quiere cambiar de trabajo.", english: "She wants to change jobs.", tags: ["general", "work"] },
    { target: "Yo oigo ruidos por la noche.", english: "I hear noises at night.", tags: ["general"] },
    { target: "Nosotros hacemos ejercicio tres veces por semana.", english: "We exercise three times a week.", tags: ["general"] },
    { target: "Ella trae la comida de casa.", english: "She brings food from home.", tags: ["general", "work"] },
    { target: "Mi primo vive en el extranjero.", english: "My cousin lives abroad.", tags: ["general", "family"] },
    { target: "Yo siempre pierdo las llaves.", english: "I always lose my keys.", tags: ["general"] },
    { target: "El supermercado abre a las ocho.", english: "The supermarket opens at eight.", tags: ["general"] },
    { target: "Ella canta muy bien.", english: "She sings very well.", tags: ["general"] },
    { target: "Mi jefa sabe mucho de finanzas.", english: "My boss knows a lot about finance.", tags: ["general", "work"] },
    { target: "Nosotros vemos una serie cada noche.", english: "We watch a series every night.", tags: ["general", "family"] },
    { target: "Este barrio es muy tranquilo.", english: "This neighborhood is very quiet.", tags: ["general"] },
    { target: "Yo hago la cama todos los días.", english: "I make the bed every day.", tags: ["general"] },
    { target: "Ella pide café con hielo en verano.", english: "She orders iced coffee in summer.", tags: ["general"] },
    { target: "Mi hermano menor mide un metro ochenta.", english: "My younger brother is one eighty tall.", tags: ["general", "family"] },
    { target: "Yo recuerdo tu nombre pero no tu apellido.", english: "I remember your first name but not your last name.", tags: ["general"] },
    { target: "Ella se preocupa demasiado por todo.", english: "She worries too much about everything.", tags: ["general", "family"] },
    { target: "Yo envío muchos mensajes al día.", english: "I send a lot of messages per day.", tags: ["general"] },
    { target: "La farmacia está al lado del banco.", english: "The pharmacy is next to the bank.", tags: ["general", "travel"] },
    { target: "Nosotros quedamos los viernes para cenar.", english: "We meet up on Fridays for dinner.", tags: ["general"] },
    { target: "Ella trabaja desde casa los jueves.", english: "She works from home on Thursdays.", tags: ["general", "work"] },
    { target: "Yo como demasiado rápido.", english: "I eat too fast.", tags: ["general"] },
    { target: "Mi cuñada es muy simpática.", english: "My sister-in-law is very nice.", tags: ["general", "family"] },
    { target: "Él vende coches de segunda mano.", english: "He sells second-hand cars.", tags: ["general", "work"] },
    { target: "Yo siempre olvido las contraseñas.", english: "I always forget passwords.", tags: ["general"] },
    { target: "Ella sonríe mucho.", english: "She smiles a lot.", tags: ["general"] },
    { target: "Mi mejor amigo vive en Barcelona.", english: "My best friend lives in Barcelona.", tags: ["general"] },
    { target: "Yo subo las escaleras en vez del ascensor.", english: "I take the stairs instead of the elevator.", tags: ["general"] },
    { target: "Los precios suben cada año.", english: "Prices go up every year.", tags: ["general"] },
    { target: "Ella lleva gafas.", english: "She wears glasses.", tags: ["general"] },
    { target: "Yo intento ser más paciente.", english: "I try to be more patient.", tags: ["general"] },
    { target: "Mi abuelo todavía trabaja.", english: "My grandfather still works.", tags: ["general", "family"] },
    { target: "Este autobús para en todas las paradas.", english: "This bus stops at every stop.", tags: ["general", "travel"] },
    { target: "Ella nada en la piscina cada mañana.", english: "She swims in the pool every morning.", tags: ["general"] },
    { target: "Yo dejo propina siempre.", english: "I always leave a tip.", tags: ["general", "travel"] },
    { target: "Mi sobrino tiene cinco años.", english: "My nephew is five years old.", tags: ["general", "family"] },
    { target: "Ella da clases de inglés.", english: "She teaches English classes.", tags: ["general", "work"] },
    { target: "Yo me levanto a las seis y media.", english: "I get up at six thirty.", tags: ["general"] },
    { target: "El vuelo sale a medianoche.", english: "The flight leaves at midnight.", tags: ["general", "travel"], grammar: "Present tense for scheduled departures" },
    { target: "Ella tiene una entrevista mañana.", english: "She has an interview tomorrow.", tags: ["general", "work"] },
    { target: "Yo corto el pan con este cuchillo.", english: "I cut the bread with this knife.", tags: ["general"] },
    { target: "Nosotros reciclamos todo el plástico.", english: "We recycle all the plastic.", tags: ["general"] },
    { target: "Mi empresa tiene cien empleados.", english: "My company has a hundred employees.", tags: ["general", "work"] },
    { target: "Ella merece un descanso.", english: "She deserves a break.", tags: ["general", "work"] },
    { target: "Yo odio madrugar.", english: "I hate getting up early.", tags: ["general"] },
    { target: "Mi tía hace el mejor pastel de chocolate.", english: "My aunt makes the best chocolate cake.", tags: ["general", "family"] },
    { target: "Él gana bastante dinero.", english: "He earns quite a lot of money.", tags: ["general", "work"] },
    { target: "Yo creo que tiene razón.", english: "I think she's right.", tags: ["general"] },
    { target: "El museo abre de martes a domingo.", english: "The museum is open Tuesday through Sunday.", tags: ["general", "travel"] },
    { target: "Ella deja el coche en el aparcamiento.", english: "She leaves the car in the parking lot.", tags: ["general"] },
    { target: "Yo busco un regalo para mi madre.", english: "I'm looking for a gift for my mother.", tags: ["general", "family"] },
    { target: "Mi novio cocina mejor que yo.", english: "My boyfriend cooks better than me.", tags: ["general", "family"] },
    { target: "Nosotros comemos mucha fruta.", english: "We eat a lot of fruit.", tags: ["general"] },
    { target: "Ella enseña matemáticas en un instituto.", english: "She teaches math at a high school.", tags: ["general", "work"] },
    { target: "Yo conozco un sitio barato para comer.", english: "I know a cheap place to eat.", tags: ["general", "travel"] },
    { target: "Mi vecina tiene un jardín precioso.", english: "My neighbor has a beautiful garden.", tags: ["general"] },
    { target: "Él ayuda a sus padres los fines de semana.", english: "He helps his parents on weekends.", tags: ["general", "family"] },
    { target: "Yo entiendo más de lo que hablo.", english: "I understand more than I speak.", tags: ["general"] },
    { target: "La tienda de abajo vende de todo.", english: "The shop downstairs sells everything.", tags: ["general"] },
    { target: "Ella sigue una dieta sin gluten.", english: "She follows a gluten-free diet.", tags: ["general"] },
  ],

  // ═══════════════════════════════════════════════════════════════
  // NODE 2: Ser vs Estar (A1)
  // ═══════════════════════════════════════════════════════════════
  2: [
    { target: "Estoy cansado de esperar.", english: "I'm tired of waiting.", tags: ["general"], grammar: "Estar for temporary states" },
    { target: "Mi padre es ingeniero.", english: "My father is an engineer.", tags: ["general", "family", "work"], grammar: "Ser for professions" },
    { target: "La sopa está fría.", english: "The soup is cold.", tags: ["general"], grammar: "Estar for current condition" },
    { target: "Somos cinco en mi familia.", english: "There are five of us in my family.", tags: ["general", "family"], grammar: "Ser for inherent facts" },
    { target: "El banco está cerrado hoy.", english: "The bank is closed today.", tags: ["general"], grammar: "Estar for resulting states" },
    { target: "Ella es muy alta para su edad.", english: "She's very tall for her age.", tags: ["general", "family"], grammar: "Ser for physical descriptions" },
    { target: "Estamos en el aeropuerto.", english: "We're at the airport.", tags: ["general", "travel"], grammar: "Estar for location" },
    { target: "Esta comida está deliciosa.", english: "This food is delicious.", tags: ["general"], grammar: "Estar for experience/taste" },
    { target: "Mi hermano es el más joven.", english: "My brother is the youngest.", tags: ["general", "family"], grammar: "Ser for identity" },
    { target: "La oficina está en el tercer piso.", english: "The office is on the third floor.", tags: ["general", "work"], grammar: "Estar for location" },
    { target: "Él es de Colombia.", english: "He is from Colombia.", tags: ["general"], grammar: "Ser for origin" },
    { target: "Estoy listo para salir.", english: "I'm ready to go out.", tags: ["general"], grammar: "Estar for temporary state" },
    { target: "La fiesta es en mi casa.", english: "The party is at my house.", tags: ["general"], grammar: "Ser for events" },
    { target: "Ella está enferma desde el lunes.", english: "She's been sick since Monday.", tags: ["general"], grammar: "Estar for health conditions" },
    { target: "Este café es muy bueno.", english: "This coffee is very good.", tags: ["general"], grammar: "Ser for inherent quality" },
    { target: "Estamos contentos con el resultado.", english: "We're happy with the result.", tags: ["general", "work"], grammar: "Estar for emotional state" },
    { target: "Mi mejor amiga es profesora.", english: "My best friend is a teacher.", tags: ["general", "work"], grammar: "Ser for professions" },
    { target: "El concierto es a las nueve.", english: "The concert is at nine.", tags: ["general"], grammar: "Ser for scheduled events" },
    { target: "Estás muy guapa hoy.", english: "You look really nice today.", tags: ["general"], grammar: "Estar for temporary appearance" },
    { target: "La llave está en el cajón.", english: "The key is in the drawer.", tags: ["general"], grammar: "Estar for location of objects" },
    { target: "Él es bastante tímido.", english: "He's quite shy.", tags: ["general"], grammar: "Ser for personality traits" },
    { target: "Estoy de acuerdo contigo.", english: "I agree with you.", tags: ["general"], grammar: "Estar in fixed expressions" },
    { target: "La reunión es importante.", english: "The meeting is important.", tags: ["general", "work"], grammar: "Ser for characteristics" },
    { target: "Estamos perdidos.", english: "We're lost.", tags: ["general", "travel"], grammar: "Estar for temporary state" },
    { target: "Ella es muy trabajadora.", english: "She's very hardworking.", tags: ["general", "work"], grammar: "Ser for personality" },
    { target: "El agua está muy caliente.", english: "The water is very hot.", tags: ["general"], grammar: "Estar for current temperature" },
    { target: "Son las tres y media.", english: "It's three thirty.", tags: ["general"], grammar: "Ser for time" },
    { target: "Estoy buscando un piso nuevo.", english: "I'm looking for a new apartment.", tags: ["general"], grammar: "Estar + gerund for progressive" },
    { target: "La película es en español.", english: "The movie is in Spanish.", tags: ["general"], grammar: "Ser for language of content" },
    { target: "Estoy harto de este tráfico.", english: "I'm fed up with this traffic.", tags: ["general", "travel"], grammar: "Estar for emotional reactions" },
    { target: "Mi casa es pequeña pero cómoda.", english: "My house is small but cozy.", tags: ["general"], grammar: "Ser for permanent features" },
    { target: "Ella está embarazada.", english: "She's pregnant.", tags: ["general", "family"], grammar: "Estar for temporary conditions" },
    { target: "Es tarde, vámonos.", english: "It's late, let's go.", tags: ["general"], grammar: "Ser for time expressions" },
    { target: "Estamos a veinte de marzo.", english: "It's March twentieth.", tags: ["general"], grammar: "Estar for dates" },
    { target: "Este restaurante es nuevo.", english: "This restaurant is new.", tags: ["general", "travel"], grammar: "Ser for classification" },
    { target: "La puerta está abierta.", english: "The door is open.", tags: ["general"], grammar: "Estar for resulting state" },
    { target: "Él es el jefe de ventas.", english: "He's the head of sales.", tags: ["general", "work"], grammar: "Ser for roles/titles" },
    { target: "No estoy seguro de eso.", english: "I'm not sure about that.", tags: ["general"], grammar: "Estar for temporary certainty" },
    { target: "La camisa es de algodón.", english: "The shirt is cotton.", tags: ["general"], grammar: "Ser for material" },
    { target: "Estoy emocionado por el viaje.", english: "I'm excited about the trip.", tags: ["general", "travel"], grammar: "Estar for emotions about events" },
    { target: "La paella es un plato típico.", english: "Paella is a typical dish.", tags: ["general", "travel"], grammar: "Ser for defining characteristics" },
    { target: "Ellos están sentados en la terraza.", english: "They're sitting on the terrace.", tags: ["general"], grammar: "Estar for position" },
    { target: "Mi coche es azul.", english: "My car is blue.", tags: ["general"], grammar: "Ser for color" },
    { target: "Estoy ocupado ahora mismo.", english: "I'm busy right now.", tags: ["general", "work"], grammar: "Estar for temporary state" },
    { target: "Este hotel es bastante caro.", english: "This hotel is quite expensive.", tags: ["general", "travel"], grammar: "Ser for price classification" },
    { target: "La fruta está madura.", english: "The fruit is ripe.", tags: ["general"], grammar: "Estar for condition" },
    { target: "Él es muy amable con todos.", english: "He's very kind to everyone.", tags: ["general"], grammar: "Ser for personality traits" },
    { target: "El café está en la mesa.", english: "The coffee is on the table.", tags: ["general"], grammar: "Estar for location" },
    { target: "Ella es soltera.", english: "She's single.", tags: ["general"], grammar: "Ser for marital status" },
    { target: "Estamos listos para empezar.", english: "We're ready to start.", tags: ["general", "work"], grammar: "Estar for readiness" },
    { target: "Hoy es mi cumpleaños.", english: "Today is my birthday.", tags: ["general", "family"], grammar: "Ser for events/occasions" },
    { target: "El baño está al fondo a la derecha.", english: "The bathroom is at the end on the right.", tags: ["general", "travel"], grammar: "Estar for location" },
    { target: "Mi abuelo es viudo.", english: "My grandfather is a widower.", tags: ["general", "family"], grammar: "Ser for status" },
    { target: "La comida está lista.", english: "The food is ready.", tags: ["general"], grammar: "Estar for resulting state" },
    { target: "Somos vecinos desde hace años.", english: "We've been neighbors for years.", tags: ["general"], grammar: "Ser for relationship" },
    { target: "Estoy aprendiendo mucho en este trabajo.", english: "I'm learning a lot at this job.", tags: ["general", "work"], grammar: "Estar + gerund for progressive" },
  ],

  // ═══════════════════════════════════════════════════════════════
  // NODE 3: Common Questions (A1)
  // ═══════════════════════════════════════════════════════════════
  3: [
    { target: "Cuánto cuesta esto?", english: "How much does this cost?", tags: ["general", "travel"] },
    { target: "Tienes hermanos?", english: "Do you have siblings?", tags: ["general", "family"] },
    { target: "Dónde aprendiste español?", english: "Where did you learn Spanish?", tags: ["general"] },
    { target: "Qué tal el fin de semana?", english: "How was the weekend?", tags: ["general", "work"] },
    { target: "A qué hora llegas?", english: "What time do you arrive?", tags: ["general"] },
    { target: "Puedo pagar con tarjeta?", english: "Can I pay by card?", tags: ["general", "travel"] },
    { target: "Tienes wifi?", english: "Do you have wifi?", tags: ["general", "travel"] },
    { target: "Cuánto tiempo llevas aquí?", english: "How long have you been here?", tags: ["general", "travel"] },
    { target: "Quieres algo de beber?", english: "Do you want something to drink?", tags: ["general"] },
    { target: "Sabes dónde está la estación?", english: "Do you know where the station is?", tags: ["general", "travel"] },
    { target: "Cómo se llama tu perro?", english: "What's your dog's name?", tags: ["general"] },
    { target: "Cuándo es tu cumpleaños?", english: "When is your birthday?", tags: ["general", "family"] },
    { target: "Tienes cambio?", english: "Do you have change?", tags: ["general"] },
    { target: "De dónde eres exactamente?", english: "Where exactly are you from?", tags: ["general"] },
    { target: "Te gusta vivir aquí?", english: "Do you like living here?", tags: ["general"] },
    { target: "Cuántos años tiene tu hijo?", english: "How old is your son?", tags: ["general", "family"] },
    { target: "Está lejos de aquí?", english: "Is it far from here?", tags: ["general", "travel"] },
    { target: "Puedo probarme esto?", english: "Can I try this on?", tags: ["general", "travel"] },
    { target: "Trabajas mañana?", english: "Do you work tomorrow?", tags: ["general", "work"] },
    { target: "Qué hora es?", english: "What time is it?", tags: ["general"] },
    { target: "Hay una farmacia por aquí?", english: "Is there a pharmacy around here?", tags: ["general", "travel"] },
    { target: "Cuál es tu dirección?", english: "What's your address?", tags: ["general"] },
    { target: "Puedo sentarme aquí?", english: "Can I sit here?", tags: ["general", "travel"] },
    { target: "Cuánto tardas en llegar?", english: "How long does it take you to get there?", tags: ["general", "travel"] },
    { target: "Te importa si abro la ventana?", english: "Do you mind if I open the window?", tags: ["general"] },
    { target: "Qué recomiendas?", english: "What do you recommend?", tags: ["general", "travel"] },
    { target: "Necesitas ayuda con eso?", english: "Do you need help with that?", tags: ["general", "work"] },
    { target: "Tienes alguna alergia?", english: "Do you have any allergies?", tags: ["general", "family"] },
    { target: "Cómo fue tu día?", english: "How was your day?", tags: ["general", "family"] },
    { target: "Dónde quieres comer?", english: "Where do you want to eat?", tags: ["general"] },
    { target: "Puedes repetir eso?", english: "Can you repeat that?", tags: ["general"] },
    { target: "Qué significa esta palabra?", english: "What does this word mean?", tags: ["general"] },
    { target: "Conoces un buen restaurante?", english: "Do you know a good restaurant?", tags: ["general", "travel"] },
    { target: "Cuándo terminas de trabajar?", english: "When do you finish work?", tags: ["general", "work"] },
    { target: "Te apetece un café?", english: "Do you feel like a coffee?", tags: ["general"] },
    { target: "Cuánto mide tu piso?", english: "How big is your apartment?", tags: ["general"] },
    { target: "Llevas mucho tiempo esperando?", english: "Have you been waiting long?", tags: ["general"] },
    { target: "Cuál es la contraseña del wifi?", english: "What's the wifi password?", tags: ["general", "travel"] },
    { target: "Te va bien el martes?", english: "Does Tuesday work for you?", tags: ["general", "work"] },
    { target: "Qué haces este fin de semana?", english: "What are you doing this weekend?", tags: ["general"] },
    { target: "Has estado alguna vez en España?", english: "Have you ever been to Spain?", tags: ["general", "travel"] },
    { target: "Puedo traer a un amigo?", english: "Can I bring a friend?", tags: ["general"] },
    { target: "Cuánto cuesta el billete?", english: "How much is the ticket?", tags: ["general", "travel"] },
    { target: "Qué tipo de música te gusta?", english: "What kind of music do you like?", tags: ["general"] },
    { target: "Hay descuento para estudiantes?", english: "Is there a student discount?", tags: ["general", "travel"] },
    { target: "Quieres compartir un taxi?", english: "Do you want to share a taxi?", tags: ["general", "travel"] },
    { target: "De qué trabaja tu pareja?", english: "What does your partner do for work?", tags: ["general", "family", "work"] },
    { target: "Me das tu número?", english: "Can you give me your number?", tags: ["general"] },
    { target: "Hay sitio para aparcar?", english: "Is there a place to park?", tags: ["general", "travel"] },
    { target: "Qué talla usas?", english: "What size do you wear?", tags: ["general"] },
    { target: "Vienes mucho por aquí?", english: "Do you come here often?", tags: ["general"] },
    { target: "Cuándo es la próxima reunión?", english: "When is the next meeting?", tags: ["general", "work"] },
    { target: "Hablas otro idioma?", english: "Do you speak another language?", tags: ["general"] },
    { target: "Cuántos sois en tu familia?", english: "How many are you in your family?", tags: ["general", "family"] },
    { target: "Sabes cocinar?", english: "Do you know how to cook?", tags: ["general"] },
    { target: "Cuántas horas duermes?", english: "How many hours do you sleep?", tags: ["general"] },
  ],

  // ═══════════════════════════════════════════════════════════════
  // NODE 4: Articles & Gender (A1)
  // ═══════════════════════════════════════════════════════════════
  4: [
    { target: "Dame el vaso, por favor.", english: "Give me the glass, please.", tags: ["general"], grammar: "El for masculine nouns" },
    { target: "La cuenta, por favor.", english: "The check, please.", tags: ["general", "travel"] },
    { target: "Los zapatos están en la entrada.", english: "The shoes are at the entrance.", tags: ["general"] },
    { target: "Las llaves están en el bolso.", english: "The keys are in the bag.", tags: ["general"] },
    { target: "Necesito un paraguas.", english: "I need an umbrella.", tags: ["general"] },
    { target: "Hay una panadería en la esquina.", english: "There's a bakery on the corner.", tags: ["general", "travel"] },
    { target: "Unos amigos vienen a cenar.", english: "Some friends are coming for dinner.", tags: ["general"] },
    { target: "Unas chicas de mi clase son de México.", english: "Some girls from my class are from Mexico.", tags: ["general"] },
    { target: "El problema es que no tengo tiempo.", english: "The problem is I don't have time.", tags: ["general"], grammar: "El problema — masculine despite -a ending" },
    { target: "La mano me duele mucho.", english: "My hand hurts a lot.", tags: ["general"], grammar: "La mano — feminine despite -o ending" },
    { target: "El agua está muy fría hoy.", english: "The water is very cold today.", tags: ["general"], grammar: "El agua — feminine noun uses el before it" },
    { target: "Me gusta la música clásica.", english: "I like classical music.", tags: ["general"] },
    { target: "El mapa está en la mochila.", english: "The map is in the backpack.", tags: ["general", "travel"], grammar: "El mapa — masculine despite -a ending" },
    { target: "Ponlo en la mesa del salón.", english: "Put it on the living room table.", tags: ["general"] },
    { target: "Los domingos desayunamos churros.", english: "On Sundays we have churros for breakfast.", tags: ["general", "family"] },
    { target: "La leche está en la nevera.", english: "The milk is in the fridge.", tags: ["general"] },
    { target: "El sistema no funciona bien.", english: "The system isn't working well.", tags: ["general", "work"], grammar: "El sistema — masculine despite -a ending" },
    { target: "Necesito unas tijeras.", english: "I need some scissors.", tags: ["general"] },
    { target: "El clima aquí es muy agradable.", english: "The weather here is very pleasant.", tags: ["general", "travel"], grammar: "El clima — masculine despite -a ending" },
    { target: "La gente es muy amable en esta ciudad.", english: "The people are very friendly in this city.", tags: ["general", "travel"] },
    { target: "Los fines de semana son para descansar.", english: "Weekends are for resting.", tags: ["general"] },
    { target: "Una cerveza, por favor.", english: "A beer, please.", tags: ["general", "travel"] },
    { target: "El idioma es difícil al principio.", english: "The language is difficult at first.", tags: ["general"], grammar: "El idioma — masculine despite -a ending" },
    { target: "Las flores huelen muy bien.", english: "The flowers smell very nice.", tags: ["general"] },
    { target: "Un café solo y una tostada.", english: "A black coffee and a piece of toast.", tags: ["general", "travel"] },
    { target: "La costumbre es dejar propina.", english: "The custom is to leave a tip.", tags: ["general", "travel"] },
    { target: "El día está nublado.", english: "The day is cloudy.", tags: ["general"], grammar: "El día — masculine despite -a ending" },
    { target: "Los niños se parecen al padre.", english: "The kids look like their father.", tags: ["general", "family"] },
    { target: "Las noticias de hoy son buenas.", english: "Today's news is good.", tags: ["general"] },
    { target: "Un momento, ahora vuelvo.", english: "One moment, I'll be right back.", tags: ["general"] },
    { target: "El planeta necesita más árboles.", english: "The planet needs more trees.", tags: ["general"], grammar: "El planeta — masculine despite -a ending" },
    { target: "La canción está en mi lista.", english: "The song is on my playlist.", tags: ["general"] },
    { target: "Los vecinos de arriba hacen mucho ruido.", english: "The upstairs neighbors make a lot of noise.", tags: ["general"] },
    { target: "Las vacaciones empiezan la semana que viene.", english: "Vacation starts next week.", tags: ["general", "travel"] },
    { target: "El tema es complicado.", english: "The topic is complicated.", tags: ["general", "work"], grammar: "El tema — masculine despite -a ending" },
    { target: "Un zumo de naranja, por favor.", english: "An orange juice, please.", tags: ["general", "travel"] },
    { target: "La ciudad tiene mucha historia.", english: "The city has a lot of history.", tags: ["general", "travel"] },
    { target: "Los padres de mi novio son encantadores.", english: "My boyfriend's parents are lovely.", tags: ["general", "family"] },
    { target: "Las tiendas cierran a las nueve.", english: "The stores close at nine.", tags: ["general", "travel"] },
    { target: "Un poco de sal, nada más.", english: "A little salt, nothing else.", tags: ["general"] },
    { target: "La foto salió borrosa.", english: "The photo came out blurry.", tags: ["general"], grammar: "La foto — feminine (short for fotografía)" },
    { target: "El poema es precioso.", english: "The poem is beautiful.", tags: ["general"], grammar: "El poema — masculine despite -a ending" },
    { target: "Las gafas están encima de la tele.", english: "The glasses are on top of the TV.", tags: ["general"] },
    { target: "Un taxi a la estación, por favor.", english: "A taxi to the station, please.", tags: ["general", "travel"] },
    { target: "La radio no funciona.", english: "The radio doesn't work.", tags: ["general"], grammar: "La radio — feminine (short for radioemisora)" },
    { target: "Los lunes siempre son duros.", english: "Mondays are always tough.", tags: ["general", "work"] },
    { target: "El sofá es nuevo.", english: "The sofa is new.", tags: ["general"] },
    { target: "La noche está estrellada.", english: "The night is starry.", tags: ["general"] },
    { target: "Una mesa para dos, por favor.", english: "A table for two, please.", tags: ["general", "travel"] },
    { target: "El programa empieza a las ocho.", english: "The program starts at eight.", tags: ["general"], grammar: "El programa — masculine despite -a ending" },
    { target: "La moto está aparcada fuera.", english: "The motorcycle is parked outside.", tags: ["general"], grammar: "La moto — feminine (short for motocicleta)" },
    { target: "Los precios incluyen impuestos.", english: "Prices include taxes.", tags: ["general", "travel"] },
    { target: "Unas patatas fritas para compartir.", english: "Some fries to share.", tags: ["general", "travel"] },
    { target: "El arroz está en el armario.", english: "The rice is in the cupboard.", tags: ["general"] },
    { target: "La sal y la pimienta están en la mesa.", english: "The salt and pepper are on the table.", tags: ["general"] },
    { target: "Un billete de ida y vuelta.", english: "A round-trip ticket.", tags: ["general", "travel"] },
  ],

  // ═══════════════════════════════════════════════════════════════
  // NODE 5: Gustar & Similar (A1)
  // ═══════════════════════════════════════════════════════════════
  5: [
    { target: "Me encanta esta canción.", english: "I love this song.", tags: ["general"], grammar: "Encantar works like gustar" },
    { target: "No me gusta nada el frío.", english: "I don't like the cold at all.", tags: ["general"] },
    { target: "A mi hermana le fascina la cocina.", english: "My sister is fascinated by cooking.", tags: ["general", "family"], grammar: "Fascinar works like gustar" },
    { target: "Me molesta el ruido por la noche.", english: "Noise at night bothers me.", tags: ["general"], grammar: "Molestar works like gustar" },
    { target: "Le interesan mucho los deportes.", english: "He's very interested in sports.", tags: ["general"], grammar: "Interesar works like gustar" },
    { target: "Nos falta tiempo para todo.", english: "We lack time for everything.", tags: ["general", "work"], grammar: "Faltar works like gustar" },
    { target: "Me da igual dónde comamos.", english: "I don't care where we eat.", tags: ["general"] },
    { target: "Les importa mucho la opinión de los demás.", english: "They care a lot about other people's opinion.", tags: ["general"] },
    { target: "Me apetece un helado.", english: "I feel like an ice cream.", tags: ["general"], grammar: "Apetecer works like gustar" },
    { target: "No le gustan los gatos.", english: "He doesn't like cats.", tags: ["general"] },
    { target: "Me sorprende que todavía no haya llegado.", english: "It surprises me that he still hasn't arrived.", tags: ["general"], grammar: "Sorprender works like gustar" },
    { target: "A los niños les encantan los dibujos animados.", english: "The kids love cartoons.", tags: ["general", "family"] },
    { target: "Me duele la espalda.", english: "My back hurts.", tags: ["general"], grammar: "Doler works like gustar" },
    { target: "Le sobra dinero a fin de mes.", english: "He has money left over at the end of the month.", tags: ["general"], grammar: "Sobrar works like gustar" },
    { target: "Me cae bien tu amigo.", english: "I like your friend.", tags: ["general"], grammar: "Caer bien/mal for people" },
    { target: "Nos queda una semana de vacaciones.", english: "We have one week of vacation left.", tags: ["general", "travel"], grammar: "Quedar works like gustar" },
    { target: "Le preocupa el examen de mañana.", english: "She's worried about tomorrow's exam.", tags: ["general"], grammar: "Preocupar works like gustar" },
    { target: "Me aburren las películas largas.", english: "Long movies bore me.", tags: ["general"], grammar: "Aburrir works like gustar" },
    { target: "A mi padre le gusta madrugar.", english: "My father likes getting up early.", tags: ["general", "family"] },
    { target: "No me conviene ese horario.", english: "That schedule doesn't work for me.", tags: ["general", "work"], grammar: "Convenir works like gustar" },
    { target: "Les hace falta más práctica.", english: "They need more practice.", tags: ["general"], grammar: "Hacer falta works like gustar" },
    { target: "Me parece bien tu idea.", english: "Your idea sounds good to me.", tags: ["general", "work"], grammar: "Parecer works like gustar" },
    { target: "A mi novia le fascina viajar.", english: "My girlfriend is fascinated by traveling.", tags: ["general", "family", "travel"] },
    { target: "Me pone nervioso esperar.", english: "Waiting makes me nervous.", tags: ["general"], grammar: "Poner + emotion works like gustar" },
    { target: "Nos gusta cocinar juntos.", english: "We like cooking together.", tags: ["general", "family"] },
    { target: "Me da miedo conducir de noche.", english: "I'm scared of driving at night.", tags: ["general"], grammar: "Dar miedo works like gustar" },
    { target: "Le llama la atención la arquitectura.", english: "Architecture catches his attention.", tags: ["general", "travel"], grammar: "Llamar la atención works like gustar" },
    { target: "Me cuesta levantarme temprano.", english: "It's hard for me to get up early.", tags: ["general"], grammar: "Costar works like gustar" },
    { target: "A ella le gusta más el mar que la montaña.", english: "She prefers the sea to the mountains.", tags: ["general", "travel"] },
    { target: "Me alegra verte.", english: "I'm glad to see you.", tags: ["general"], grammar: "Alegrar works like gustar" },
    { target: "Le da vergüenza hablar en público.", english: "He's embarrassed to speak in public.", tags: ["general", "work"], grammar: "Dar vergüenza works like gustar" },
    { target: "Nos encanta este barrio.", english: "We love this neighborhood.", tags: ["general"] },
    { target: "Me extraña que no haya llamado.", english: "It's strange to me that he hasn't called.", tags: ["general"], grammar: "Extrañar works like gustar" },
    { target: "A mis padres les gusta pasear después de cenar.", english: "My parents like walking after dinner.", tags: ["general", "family"] },
    { target: "Me sale más barato comprar online.", english: "It comes out cheaper for me to buy online.", tags: ["general"], grammar: "Salir + adjective works like gustar" },
    { target: "Le sienta bien ese color.", english: "That color looks good on her.", tags: ["general"], grammar: "Sentar bien/mal works like gustar" },
    { target: "Me queda grande esta camiseta.", english: "This t-shirt is too big for me.", tags: ["general"], grammar: "Quedar for fit" },
    { target: "Nos toca pagar a nosotros.", english: "It's our turn to pay.", tags: ["general"], grammar: "Tocar works like gustar" },
    { target: "A mi abuela le gustan las novelas de misterio.", english: "My grandmother likes mystery novels.", tags: ["general", "family"] },
    { target: "Me resulta difícil concentrarme aquí.", english: "I find it hard to concentrate here.", tags: ["general", "work"], grammar: "Resultar works like gustar" },
    { target: "Le da pereza ir al gimnasio.", english: "He's too lazy to go to the gym.", tags: ["general"], grammar: "Dar pereza works like gustar" },
    { target: "Me gusta cómo huele este sitio.", english: "I like how this place smells.", tags: ["general"] },
    { target: "Nos hace ilusión el viaje.", english: "We're excited about the trip.", tags: ["general", "travel"], grammar: "Hacer ilusión works like gustar" },
    { target: "A ella no le gusta que le digan qué hacer.", english: "She doesn't like being told what to do.", tags: ["general"] },
    { target: "Me cae mal mi compañero de piso.", english: "I don't like my roommate.", tags: ["general"], grammar: "Caer mal for disliking people" },
    { target: "Le pasa algo, está muy callada.", english: "Something's wrong with her, she's very quiet.", tags: ["general"], grammar: "Pasar for what's happening to someone" },
    { target: "Me va bien quedar a las seis.", english: "Meeting at six works for me.", tags: ["general"] },
    { target: "A mi jefe le importa mucho la puntualidad.", english: "My boss cares a lot about punctuality.", tags: ["general", "work"] },
    { target: "Me flipa esta serie.", english: "I'm blown away by this series.", tags: ["general"], grammar: "Flipar — colloquial, works like gustar" },
    { target: "Le queda poco para jubilarse.", english: "He's close to retiring.", tags: ["general", "work"], grammar: "Quedar + quantity for remaining" },
    { target: "Me da pena que se vaya.", english: "It makes me sad that she's leaving.", tags: ["general", "family"], grammar: "Dar pena works like gustar" },
    { target: "Nos faltan dos personas para el equipo.", english: "We're missing two people for the team.", tags: ["general", "work"] },
    { target: "A ti te gustan los perros o los gatos?", english: "Do you like dogs or cats?", tags: ["general"] },
    { target: "Me cuesta mucho decir que no.", english: "It's really hard for me to say no.", tags: ["general"] },
    { target: "Le viene bien la reunión a las diez.", english: "The meeting at ten works for her.", tags: ["general", "work"] },
    { target: "Me hacen gracia sus chistes.", english: "His jokes make me laugh.", tags: ["general"], grammar: "Hacer gracia works like gustar" },
  ],

  // ═══════════════════════════════════════════════════════════════
  // NODE 6: Preterite (A2)
  // ═══════════════════════════════════════════════════════════════
  6: [
    { target: "Ayer compré un portátil nuevo.", english: "Yesterday I bought a new laptop.", tags: ["general", "work"] },
    { target: "Ella llegó tarde a la reunión.", english: "She arrived late to the meeting.", tags: ["general", "work"] },
    { target: "Fuimos a la playa el domingo.", english: "We went to the beach on Sunday.", tags: ["general", "travel"] },
    { target: "Él perdió las llaves del coche.", english: "He lost the car keys.", tags: ["general"] },
    { target: "Comimos en un restaurante italiano.", english: "We ate at an Italian restaurant.", tags: ["general", "travel"] },
    { target: "No dormí nada anoche.", english: "I didn't sleep at all last night.", tags: ["general"] },
    { target: "Ella me dijo la verdad.", english: "She told me the truth.", tags: ["general"] },
    { target: "Hicieron una fiesta sorpresa.", english: "They threw a surprise party.", tags: ["general", "family"] },
    { target: "Puse la maleta en el armario.", english: "I put the suitcase in the closet.", tags: ["general", "travel"] },
    { target: "Él tuvo un accidente de coche.", english: "He had a car accident.", tags: ["general"] },
    { target: "Nos mudamos el mes pasado.", english: "We moved last month.", tags: ["general", "family"] },
    { target: "Ella se cayó en las escaleras.", english: "She fell on the stairs.", tags: ["general"] },
    { target: "Encontré un billete de cincuenta en la calle.", english: "I found a fifty-euro bill on the street.", tags: ["general"] },
    { target: "Viajamos a Portugal en verano.", english: "We traveled to Portugal in summer.", tags: ["general", "travel"] },
    { target: "Él pagó la cena.", english: "He paid for dinner.", tags: ["general"] },
    { target: "Me rompí el brazo jugando al fútbol.", english: "I broke my arm playing soccer.", tags: ["general"] },
    { target: "Ellos se conocieron en la universidad.", english: "They met at university.", tags: ["general", "family"] },
    { target: "Ayer llovió todo el día.", english: "Yesterday it rained all day.", tags: ["general"] },
    { target: "Salí del trabajo a las siete.", english: "I left work at seven.", tags: ["general", "work"] },
    { target: "Ella vendió su coche viejo.", english: "She sold her old car.", tags: ["general"] },
    { target: "Nos quedamos en un hotel muy bonito.", english: "We stayed at a very nice hotel.", tags: ["general", "travel"] },
    { target: "Él empezó un curso nuevo.", english: "He started a new course.", tags: ["general", "work"] },
    { target: "Le mandé un mensaje pero no contestó.", english: "I sent him a message but he didn't reply.", tags: ["general"] },
    { target: "Se me olvidó tu cumpleaños.", english: "I forgot your birthday.", tags: ["general", "family"] },
    { target: "Ella pidió una ensalada.", english: "She ordered a salad.", tags: ["general", "travel"] },
    { target: "Vine andando al trabajo.", english: "I walked to work.", tags: ["general", "work"] },
    { target: "Construyeron un puente nuevo.", english: "They built a new bridge.", tags: ["general"] },
    { target: "Mi abuelo nació en un pueblo pequeño.", english: "My grandfather was born in a small town.", tags: ["general", "family"] },
    { target: "Traduje el documento ayer.", english: "I translated the document yesterday.", tags: ["general", "work"] },
    { target: "Ella escribió un libro sobre su vida.", english: "She wrote a book about her life.", tags: ["general"] },
    { target: "No supe qué decir.", english: "I didn't know what to say.", tags: ["general"] },
    { target: "Condujimos cinco horas sin parar.", english: "We drove five hours without stopping.", tags: ["general", "travel"] },
    { target: "Él trajo flores para su madre.", english: "He brought flowers for his mother.", tags: ["general", "family"] },
    { target: "Me gasté demasiado en ropa.", english: "I spent too much on clothes.", tags: ["general"] },
    { target: "Estuve enfermo toda la semana.", english: "I was sick all week.", tags: ["general"] },
    { target: "Ella consiguió el trabajo.", english: "She got the job.", tags: ["general", "work"] },
    { target: "Anduvimos por el centro toda la tarde.", english: "We walked around downtown all afternoon.", tags: ["general", "travel"] },
    { target: "Quiso ayudar pero no pudo.", english: "He wanted to help but couldn't.", tags: ["general"] },
    { target: "Nos divertimos mucho en la fiesta.", english: "We had a great time at the party.", tags: ["general"] },
    { target: "Él se graduó el año pasado.", english: "He graduated last year.", tags: ["general"] },
    { target: "Pedí una pizza para llevar.", english: "I ordered a pizza to go.", tags: ["general"] },
    { target: "Ella se cortó el pelo.", english: "She cut her hair.", tags: ["general"] },
    { target: "Tuve que cancelar la reserva.", english: "I had to cancel the reservation.", tags: ["general", "travel"] },
    { target: "Nos casamos hace tres años.", english: "We got married three years ago.", tags: ["general", "family"] },
    { target: "Probé la paella por primera vez.", english: "I tried paella for the first time.", tags: ["general", "travel"] },
    { target: "Él me pidió disculpas.", english: "He apologized to me.", tags: ["general"] },
    { target: "Volví a casa caminando.", english: "I walked back home.", tags: ["general"] },
    { target: "Discutimos por una tontería.", english: "We argued over something silly.", tags: ["general", "family"] },
    { target: "Leí el correo esta mañana.", english: "I read the email this morning.", tags: ["general", "work"] },
    { target: "Se les acabó la gasolina en la autopista.", english: "They ran out of gas on the highway.", tags: ["general", "travel"] },
    { target: "Ella me presentó a sus padres.", english: "She introduced me to her parents.", tags: ["general", "family"] },
    { target: "Obtuve mi licencia de conducir a los dieciocho.", english: "I got my driver's license at eighteen.", tags: ["general"] },
    { target: "Ellos propusieron un plan diferente.", english: "They proposed a different plan.", tags: ["general", "work"] },
    { target: "Nació mi sobrina el viernes.", english: "My niece was born on Friday.", tags: ["general", "family"] },
    { target: "Se rompió la lavadora.", english: "The washing machine broke.", tags: ["general"] },
    { target: "Ella eligió el vestido azul.", english: "She chose the blue dress.", tags: ["general"] },
  ],

  // Nodes 7-20 will be generated in a follow-up batch for brevity.
  // Each follows the same pattern: ~55 natural everyday sentences
  // matching the grammar focus of the node.
};

// For nodes 7-20, generate placeholder structure
// (These will be filled with real content in the next expansion)

// ═══════════════════════════════════════════════════════════════
// NODE 7: Imperfect (A2)
// ═══════════════════════════════════════════════════════════════
newCardsByNode[7] = [
  { target: "Cuando era niño, vivía en el campo.", english: "When I was a kid, I lived in the countryside.", tags: ["general", "family"], grammar: "Imperfect for habitual past actions" },
  { target: "Mi abuela siempre hacía galletas los domingos.", english: "My grandmother always made cookies on Sundays.", tags: ["general", "family"] },
  { target: "Antes no teníamos internet.", english: "Before, we didn't have internet.", tags: ["general"] },
  { target: "Llovía mucho cuando llegamos.", english: "It was raining a lot when we arrived.", tags: ["general", "travel"], grammar: "Imperfect for weather in the past" },
  { target: "De pequeño quería ser astronauta.", english: "As a kid, I wanted to be an astronaut.", tags: ["general"] },
  { target: "En aquella época trabajaba de camarero.", english: "At that time, I worked as a waiter.", tags: ["general", "work"] },
  { target: "Mi madre me llevaba al colegio cada mañana.", english: "My mother used to take me to school every morning.", tags: ["general", "family"] },
  { target: "Antes iba al gimnasio todos los días.", english: "I used to go to the gym every day.", tags: ["general"] },
  { target: "No sabía que estabas aquí.", english: "I didn't know you were here.", tags: ["general"] },
  { target: "Mientras ella cocinaba, yo ponía la mesa.", english: "While she cooked, I set the table.", tags: ["general", "family"], grammar: "Imperfect for simultaneous actions" },
  { target: "El hotel tenía una piscina enorme.", english: "The hotel had a huge pool.", tags: ["general", "travel"] },
  { target: "Antes todos los vecinos se conocían.", english: "Before, all the neighbors knew each other.", tags: ["general"] },
  { target: "De joven salía todas las noches.", english: "When I was young, I used to go out every night.", tags: ["general"] },
  { target: "Mi padre siempre nos contaba un cuento antes de dormir.", english: "My father always used to tell us a story before bed.", tags: ["general", "family"] },
  { target: "Antes este barrio era más tranquilo.", english: "This neighborhood used to be quieter.", tags: ["general"] },
  { target: "Cuando vivía en Madrid, comía mucho fuera.", english: "When I lived in Madrid, I ate out a lot.", tags: ["general", "travel"] },
  { target: "El jefe siempre llegaba el primero.", english: "The boss always arrived first.", tags: ["general", "work"] },
  { target: "Ella pensaba que era buena idea.", english: "She thought it was a good idea.", tags: ["general"] },
  { target: "En verano íbamos a la playa todos los fines de semana.", english: "In summer, we used to go to the beach every weekend.", tags: ["general", "family", "travel"] },
  { target: "Antes no me gustaba el café.", english: "I didn't use to like coffee.", tags: ["general"] },
  { target: "Mi hermano y yo jugábamos en el parque después del colegio.", english: "My brother and I used to play in the park after school.", tags: ["general", "family"] },
  { target: "Eran las tres de la mañana cuando llamó.", english: "It was three in the morning when he called.", tags: ["general"], grammar: "Imperfect for time in the past" },
  { target: "El autobús siempre venía lleno.", english: "The bus always came full.", tags: ["general", "travel"] },
  { target: "Antes había un cine aquí.", english: "There used to be a movie theater here.", tags: ["general"] },
  { target: "Mi abuelo fumaba mucho pero lo dejó.", english: "My grandfather used to smoke a lot but he quit.", tags: ["general", "family"] },
  { target: "Ella llevaba un vestido rojo.", english: "She was wearing a red dress.", tags: ["general"], grammar: "Imperfect for descriptions in the past" },
  { target: "De niño me daba miedo la oscuridad.", english: "As a child, I was afraid of the dark.", tags: ["general"] },
  { target: "Antes ganaba menos pero estaba más contento.", english: "Before, I earned less but I was happier.", tags: ["general", "work"] },
  { target: "Los veranos duraban una eternidad.", english: "Summers used to last forever.", tags: ["general"] },
  { target: "Cuando era estudiante, dormía poco.", english: "When I was a student, I slept very little.", tags: ["general"] },
  { target: "Mi madre siempre decía eso.", english: "My mother always used to say that.", tags: ["general", "family"] },
  { target: "Antes no existían los móviles.", english: "Before, cellphones didn't exist.", tags: ["general"] },
  { target: "Mientras esperaba, leía un libro.", english: "While I waited, I read a book.", tags: ["general"] },
  { target: "El piso era pequeño pero acogedor.", english: "The apartment was small but cozy.", tags: ["general"] },
  { target: "Ella siempre traía café para todos.", english: "She always used to bring coffee for everyone.", tags: ["general", "work"] },
  { target: "De adolescente escuchaba mucho rock.", english: "As a teenager, I listened to a lot of rock.", tags: ["general"] },
  { target: "Antes podías aparcar gratis aquí.", english: "Before, you could park here for free.", tags: ["general"] },
  { target: "Mi tía vivía sola desde hacía años.", english: "My aunt had been living alone for years.", tags: ["general", "family"] },
  { target: "En aquella empresa no pagaban bien.", english: "At that company, they didn't pay well.", tags: ["general", "work"] },
  { target: "Hacía mucho calor aquel día.", english: "It was very hot that day.", tags: ["general"] },
  { target: "Todos pensábamos que era broma.", english: "We all thought it was a joke.", tags: ["general"] },
  { target: "Antes íbamos de vacaciones a la montaña.", english: "We used to go on vacation to the mountains.", tags: ["general", "family", "travel"] },
  { target: "Yo tenía unos diez años cuando nos mudamos.", english: "I was about ten when we moved.", tags: ["general", "family"] },
  { target: "Ella parecía nerviosa.", english: "She seemed nervous.", tags: ["general"] },
  { target: "De pequeño odiaba las verduras.", english: "As a kid, I hated vegetables.", tags: ["general"] },
  { target: "En esa época el alquiler costaba la mitad.", english: "At that time, rent cost half as much.", tags: ["general"] },
  { target: "Mi profesor favorito siempre usaba corbata.", english: "My favorite teacher always wore a tie.", tags: ["general"] },
  { target: "Antes había más árboles en esta calle.", english: "There used to be more trees on this street.", tags: ["general"] },
  { target: "Ella trabajaba mientras estudiaba.", english: "She worked while she studied.", tags: ["general", "work"] },
  { target: "De joven creía que todo era posible.", english: "When I was young, I believed anything was possible.", tags: ["general"] },
  { target: "Mis padres se querían mucho.", english: "My parents loved each other a lot.", tags: ["general", "family"] },
  { target: "La casa olía a café recién hecho.", english: "The house smelled like freshly brewed coffee.", tags: ["general"] },
  { target: "Antes desayunaba en una cafetería cerca de la oficina.", english: "I used to have breakfast at a café near the office.", tags: ["general", "work"] },
  { target: "El profesor hablaba muy rápido.", english: "The teacher spoke very fast.", tags: ["general"] },
  { target: "En aquella época no conocía a nadie aquí.", english: "At that time, I didn't know anyone here.", tags: ["general"] },
  { target: "Siempre cenábamos juntos en familia.", english: "We always used to have dinner together as a family.", tags: ["general", "family"] },
];

// ═══════════════════════════════════════════════════════════════
// NODE 8: Reflexive Verbs (A2)
// ═══════════════════════════════════════════════════════════════
newCardsByNode[8] = [
  { target: "Me despierto sin alarma.", english: "I wake up without an alarm.", tags: ["general"], grammar: "Despertarse — reflexive for self" },
  { target: "Ella se ducha por la mañana.", english: "She showers in the morning.", tags: ["general"] },
  { target: "Nos vamos a las ocho.", english: "We're leaving at eight.", tags: ["general"], grammar: "Irse — reflexive changes meaning from ir" },
  { target: "Él se afeita cada dos días.", english: "He shaves every other day.", tags: ["general"] },
  { target: "Me acuesto tarde los viernes.", english: "I go to bed late on Fridays.", tags: ["general"] },
  { target: "Se visten muy bien para la oficina.", english: "They dress very well for the office.", tags: ["general", "work"] },
  { target: "Me arrepiento de no haber ido.", english: "I regret not having gone.", tags: ["general"] },
  { target: "Ella se maquilla en cinco minutos.", english: "She does her makeup in five minutes.", tags: ["general"] },
  { target: "Nos aburrimos en esa clase.", english: "We get bored in that class.", tags: ["general"] },
  { target: "Él se queja de todo.", english: "He complains about everything.", tags: ["general", "work"] },
  { target: "Me siento mal por lo que dije.", english: "I feel bad about what I said.", tags: ["general"] },
  { target: "Ella se enfada fácilmente.", english: "She gets angry easily.", tags: ["general", "family"] },
  { target: "Nos reunimos cada lunes.", english: "We meet every Monday.", tags: ["general", "work"], grammar: "Reunirse — reciprocal reflexive" },
  { target: "Él se prepara un café antes de salir.", english: "He makes himself a coffee before leaving.", tags: ["general"] },
  { target: "Me pongo nervioso antes de hablar en público.", english: "I get nervous before speaking in public.", tags: ["general", "work"] },
  { target: "Ella se fue sin decir adiós.", english: "She left without saying goodbye.", tags: ["general"] },
  { target: "Nos sentamos en la terraza.", english: "We sat on the terrace.", tags: ["general", "travel"] },
  { target: "Me olvido de todo últimamente.", english: "I forget everything lately.", tags: ["general"] },
  { target: "Se llevan muy bien.", english: "They get along very well.", tags: ["general", "family"], grammar: "Llevarse bien — reciprocal" },
  { target: "Me quedo en casa esta noche.", english: "I'm staying home tonight.", tags: ["general"], grammar: "Quedarse — reflexive for staying" },
  { target: "Ella se preocupa mucho por su madre.", english: "She worries a lot about her mother.", tags: ["general", "family"] },
  { target: "Me divierto mucho con mis amigos.", english: "I have a lot of fun with my friends.", tags: ["general"] },
  { target: "Él se lesionó jugando al baloncesto.", english: "He got injured playing basketball.", tags: ["general"] },
  { target: "Nos llamamos por teléfono cada semana.", english: "We call each other every week.", tags: ["general", "family"], grammar: "Llamarse — reciprocal" },
  { target: "Me visto rápido cuando llego tarde.", english: "I get dressed quickly when I'm late.", tags: ["general"] },
  { target: "Ella se acostumbró al frío.", english: "She got used to the cold.", tags: ["general", "travel"] },
  { target: "Se parecen mucho el padre y el hijo.", english: "The father and son look very similar.", tags: ["general", "family"], grammar: "Parecerse — reciprocal" },
  { target: "Me seco el pelo con secador.", english: "I dry my hair with a hair dryer.", tags: ["general"] },
  { target: "Él se concentra mejor con música.", english: "He concentrates better with music.", tags: ["general", "work"] },
  { target: "Me atrevo a probar cosas nuevas.", english: "I dare to try new things.", tags: ["general"] },
  { target: "Nos encontramos en la cafetería.", english: "We met at the café.", tags: ["general"], grammar: "Encontrarse — reciprocal" },
  { target: "Ella se pintó las uñas de rojo.", english: "She painted her nails red.", tags: ["general"] },
  { target: "Me caí en la calle y me hice daño.", english: "I fell in the street and hurt myself.", tags: ["general"], grammar: "Caerse — reflexive for accidental" },
  { target: "Él se puso contento al oír la noticia.", english: "He became happy when he heard the news.", tags: ["general"] },
  { target: "Me quito los zapatos al llegar a casa.", english: "I take off my shoes when I get home.", tags: ["general"] },
  { target: "Nos escribimos por WhatsApp.", english: "We text each other on WhatsApp.", tags: ["general"], grammar: "Escribirse — reciprocal" },
  { target: "Ella se peina antes de salir.", english: "She combs her hair before leaving.", tags: ["general"] },
  { target: "Me relajo leyendo un libro.", english: "I relax by reading a book.", tags: ["general"] },
  { target: "Él se equivocó de puerta.", english: "He went to the wrong door.", tags: ["general"], grammar: "Equivocarse — reflexive for making a mistake" },
  { target: "Nos mudamos juntos el próximo mes.", english: "We're moving in together next month.", tags: ["general", "family"] },
  { target: "Me lavo las manos antes de comer.", english: "I wash my hands before eating.", tags: ["general"] },
  { target: "Se despidió con un abrazo.", english: "She said goodbye with a hug.", tags: ["general", "family"] },
  { target: "Me imagino que ya lo sabes.", english: "I imagine you already know.", tags: ["general"] },
  { target: "Ella se negó a firmar el contrato.", english: "She refused to sign the contract.", tags: ["general", "work"] },
  { target: "Me la paso bien aquí.", english: "I have a good time here.", tags: ["general", "travel"] },
  { target: "Ellos se ayudan mutuamente.", english: "They help each other.", tags: ["general", "family"], grammar: "Reciprocal reflexive" },
  { target: "Me acerqué a preguntarle.", english: "I approached to ask her.", tags: ["general"] },
  { target: "Ella se da cuenta de todo.", english: "She notices everything.", tags: ["general"], grammar: "Darse cuenta — reflexive idiom" },
  { target: "Me alegro mucho por ti.", english: "I'm very happy for you.", tags: ["general"] },
  { target: "Nos vemos mañana.", english: "See you tomorrow.", tags: ["general"], grammar: "Verse — reciprocal" },
  { target: "Se me rompieron las gafas.", english: "My glasses broke.", tags: ["general"], grammar: "Se me — accidental se construction" },
  { target: "Ella se inscribió en un curso de cocina.", english: "She signed up for a cooking class.", tags: ["general"] },
  { target: "Me siento orgulloso de mi equipo.", english: "I feel proud of my team.", tags: ["general", "work"] },
  { target: "Él se dedica a la fotografía.", english: "He works in photography.", tags: ["general", "work"], grammar: "Dedicarse a — reflexive for occupation" },
  { target: "Nos echamos de menos.", english: "We miss each other.", tags: ["general", "family"], grammar: "Echarse de menos — reciprocal" },
  { target: "Me acordé de ti ayer.", english: "I thought of you yesterday.", tags: ["general"], grammar: "Acordarse de — reflexive for remembering" },
];

// Due to the massive size, nodes 9-20 will be generated in a separate batch.
// For now, let's add what we have and measure the impact.

// ─── MERGE NEW CARDS ─────────────────────────────────────────────
let nextId = deck.length + 1;
let addedCount = 0;
let skippedDupes = 0;

for (const [nodeStr, cards] of Object.entries(newCardsByNode)) {
  for (const card of cards) {
    const key = card.target.toLowerCase().trim();
    if (existingTargets.has(key)) {
      skippedDupes++;
      continue;
    }
    existingTargets.add(key);
    deck.push({
      id: nextId++,
      target: card.target,
      english: card.english,
      audio: "",
      tags: card.tags,
      ...(card.grammar ? { grammar: card.grammar } : {}),
    });
    addedCount++;
  }
}

console.log(`\nAdded ${addedCount} new cards (skipped ${skippedDupes} duplicates)`);
console.log(`New total: ${deck.length} cards`);

// Tag distribution
const finalTagCounts = {};
for (const card of deck) {
  for (const tag of card.tags) {
    finalTagCounts[tag] = (finalTagCounts[tag] || 0) + 1;
  }
}
console.log('\nFinal tag distribution:');
for (const [tag, count] of Object.entries(finalTagCounts)) {
  console.log(`  ${tag}: ${count} (${(count / deck.length * 100).toFixed(1)}%)`);
}

// Write
fs.writeFileSync(DECK_PATH, JSON.stringify(deck, null, 2));
console.log(`\nWrote expanded deck: ${deck.length} cards`);
