/**
 * expand-c1c2.cjs
 *
 * Adds ~1300 new cards to reach 26-node coverage (A1→C2).
 * - ~300 cards to backfill B2 nodes 16-20 (currently ~55/node, need ~115)
 * - ~150 cards to backfill underpopulated B1/A2 nodes
 * - ~450 cards for C1 nodes 21-23
 * - ~300 cards for C2 nodes 24-26
 *
 * Tags always include "general" + contextual goals.
 * ~30% of cards include grammar explanations.
 */

const fs = require('fs');
const path = require('path');

const DECK_PATH = path.join(__dirname, '..', 'src', 'data', 'spanish', 'deck.json');
const deck = JSON.parse(fs.readFileSync(DECK_PATH, 'utf-8'));

console.log(`Current deck: ${deck.length} cards`);

const existingTargets = new Set(deck.map(c => c.target.toLowerCase().trim()));
let nextId = Math.max(...deck.map(c => c.id)) + 1;
let added = 0;
let dupes = 0;

function addCards(cards) {
  for (const c of cards) {
    const key = c.target.toLowerCase().trim();
    if (existingTargets.has(key)) { dupes++; continue; }
    existingTargets.add(key);
    deck.push({
      id: nextId++,
      target: c.target,
      english: c.english,
      audio: '',
      ...(c.grammar ? { grammar: c.grammar } : {}),
      tags: c.tags || ['general'],
      grammarNode: c.grammarNode || ''
    });
    added++;
  }
}

// ═══════════════════════════════════════════════════════════════
// B2 BACKFILL — Nodes 16-20 (~60 cards each = ~300 total)
// ═══════════════════════════════════════════════════════════════

// NODE 16: Imperfect Subjunctive
addCards([
  { target: "Si tuviera más dinero, viajaría por todo el mundo.", english: "If I had more money, I would travel around the world.", tags: ["general", "travel"], grammar: "Si + imperfect subjunctive triggers conditional main clause." },
  { target: "Ojalá pudiera quedarme más tiempo.", english: "I wish I could stay longer.", tags: ["general", "travel"] },
  { target: "Me pidió que le ayudara con la mudanza.", english: "He asked me to help him with the move.", tags: ["general"] },
  { target: "Si fuera posible, cambiaría de trabajo mañana.", english: "If it were possible, I would change jobs tomorrow.", tags: ["general", "work"] },
  { target: "Dudaba que ellos supieran la verdad.", english: "I doubted they knew the truth.", tags: ["general"] },
  { target: "Si no lloviera, iríamos a la playa.", english: "If it weren't raining, we would go to the beach.", tags: ["general", "travel"] },
  { target: "Quería que mi hijo estudiara medicina.", english: "I wanted my son to study medicine.", tags: ["general", "family"], grammar: "Quería que + imperfect subjunctive for past wishes about others." },
  { target: "Si yo fuera tú, aceptaría la oferta.", english: "If I were you, I would accept the offer.", tags: ["general", "work"] },
  { target: "Era necesario que llegáramos temprano.", english: "It was necessary that we arrived early.", tags: ["general", "work"] },
  { target: "Ojalá hubiera más tiempo para descansar.", english: "I wish there were more time to rest.", tags: ["general"] },
  { target: "Si pudiera elegir, viviría junto al mar.", english: "If I could choose, I would live by the sea.", tags: ["general"] },
  { target: "Le pedí que me llamara cuando llegara.", english: "I asked him to call me when he arrived.", tags: ["general"] },
  { target: "Si no tuviera que trabajar, estaría en la playa.", english: "If I didn't have to work, I would be at the beach.", tags: ["general", "work", "travel"] },
  { target: "Esperaba que todo saliera bien.", english: "I was hoping everything would turn out well.", tags: ["general"] },
  { target: "Si supieras lo que pasó, no lo creerías.", english: "If you knew what happened, you wouldn't believe it.", tags: ["general"] },
  { target: "Necesitaba que alguien me explicara el proceso.", english: "I needed someone to explain the process to me.", tags: ["general", "work"] },
  { target: "Si viviera más cerca, vendría todos los días.", english: "If I lived closer, I would come every day.", tags: ["general", "work"] },
  { target: "No creía que fuera tan difícil.", english: "I didn't think it would be so difficult.", tags: ["general"] },
  { target: "Si tuviera un jardín, plantaría tomates.", english: "If I had a garden, I would plant tomatoes.", tags: ["general", "family"] },
  { target: "Ojalá mi familia viviera más cerca.", english: "I wish my family lived closer.", tags: ["general", "family"] },
  { target: "Si hablara mejor español, conseguiría ese puesto.", english: "If I spoke better Spanish, I would get that position.", tags: ["general", "work"], grammar: "Si + imperfect subjunctive for hypothetical present situations." },
  { target: "Quería que nos reuniéramos antes del viernes.", english: "I wanted us to meet before Friday.", tags: ["general", "work"] },
  { target: "Si no existiera internet, la vida sería muy diferente.", english: "If the internet didn't exist, life would be very different.", tags: ["general"] },
  { target: "Me sorprendió que nadie supiera la respuesta.", english: "It surprised me that nobody knew the answer.", tags: ["general"] },
  { target: "Si pudiera retroceder en el tiempo, haría todo igual.", english: "If I could go back in time, I would do everything the same.", tags: ["general"] },
  { target: "Era importante que todos participaran en la reunión.", english: "It was important that everyone participated in the meeting.", tags: ["general", "work"] },
  { target: "Si tuviera más experiencia, solicitaría ese empleo.", english: "If I had more experience, I would apply for that job.", tags: ["general", "work"] },
  { target: "No pensaba que fuera a llover hoy.", english: "I didn't think it was going to rain today.", tags: ["general", "travel"] },
  { target: "Si ganara la lotería, donaría la mitad.", english: "If I won the lottery, I would donate half.", tags: ["general"] },
  { target: "Le sugerí que hablara con su jefe directamente.", english: "I suggested that he talk to his boss directly.", tags: ["general", "work"] },
  { target: "Si tuviera vacaciones, visitaría a mi abuela.", english: "If I had vacation, I would visit my grandmother.", tags: ["general", "family", "travel"] },
  { target: "Ojalá pudiéramos vernos más a menudo.", english: "I wish we could see each other more often.", tags: ["general", "family"] },
  { target: "Si hiciera buen tiempo, comeríamos en el jardín.", english: "If the weather were nice, we would eat in the garden.", tags: ["general", "family"] },
  { target: "No esperaba que me ofrecieran el puesto.", english: "I didn't expect them to offer me the position.", tags: ["general", "work"] },
  { target: "Si conociera a alguien allí, me sentiría más cómodo.", english: "If I knew someone there, I would feel more comfortable.", tags: ["general", "travel"] },
  { target: "Quería que los niños se acostaran temprano.", english: "I wanted the children to go to bed early.", tags: ["general", "family"] },
  { target: "Si pudiera cocinar mejor, invitaría a más gente.", english: "If I could cook better, I would invite more people.", tags: ["general", "family"] },
  { target: "Era probable que cancelaran el vuelo.", english: "It was likely they would cancel the flight.", tags: ["general", "travel"] },
  { target: "Si trabajara menos, pasaría más tiempo con mi familia.", english: "If I worked less, I would spend more time with my family.", tags: ["general", "work", "family"] },
  { target: "Dudaba que el tren llegara a tiempo.", english: "I doubted the train would arrive on time.", tags: ["general", "travel"] },
  { target: "Si no tuviera miedo, saltaría en paracaídas.", english: "If I weren't afraid, I would go skydiving.", tags: ["general"] },
  { target: "Me recomendó que tomara el autobús de las ocho.", english: "He recommended I take the eight o'clock bus.", tags: ["general", "travel"] },
  { target: "Si fuera más joven, aprendería otro idioma.", english: "If I were younger, I would learn another language.", tags: ["general"] },
  { target: "No quería que mi madre se preocupara.", english: "I didn't want my mother to worry.", tags: ["general", "family"] },
  { target: "Si me dieran a elegir, preferiría el azul.", english: "If they let me choose, I would prefer the blue one.", tags: ["general"] },
  { target: "Esperaba que el problema se resolviera pronto.", english: "I was hoping the problem would be resolved soon.", tags: ["general", "work"] },
  { target: "Si supiera conducir, alquilaría un coche.", english: "If I knew how to drive, I would rent a car.", tags: ["general", "travel"] },
  { target: "Le dije que viniera cuando pudiera.", english: "I told him to come when he could.", tags: ["general"] },
  { target: "Si tuviera un hermano, no me sentiría tan solo.", english: "If I had a brother, I wouldn't feel so alone.", tags: ["general", "family"] },
  { target: "Ojalá los precios bajaran un poco.", english: "I wish prices would go down a little.", tags: ["general"] },
  { target: "Si me pagaran más, no buscaría otro trabajo.", english: "If they paid me more, I wouldn't look for another job.", tags: ["general", "work"] },
  { target: "No creía que tuviera tanta importancia.", english: "I didn't think it had so much importance.", tags: ["general"] },
  { target: "Si estuviera de vacaciones, estaría durmiendo ahora.", english: "If I were on vacation, I would be sleeping right now.", tags: ["general", "travel"] },
  { target: "Quería que todo el mundo se divirtiera en la fiesta.", english: "I wanted everyone to have fun at the party.", tags: ["general", "family"] },
  { target: "Si tuviera tu número, te habría llamado.", english: "If I had your number, I would have called you.", tags: ["general"] },
  { target: "Era necesario que firmáramos el contrato hoy.", english: "It was necessary for us to sign the contract today.", tags: ["general", "work"], grammar: "Era necesario que + imperfect subjunctive for past impersonal obligations." },
  { target: "Si hiciera más ejercicio, me sentiría mejor.", english: "If I exercised more, I would feel better.", tags: ["general"] },
  { target: "Le pedí que no dijera nada a nadie.", english: "I asked him not to say anything to anyone.", tags: ["general"] },
  { target: "Si pudiera cambiar algo de mi vida, no cambiaría nada.", english: "If I could change something about my life, I wouldn't change anything.", tags: ["general"] },
  { target: "Ojalá existiera una solución más sencilla.", english: "I wish a simpler solution existed.", tags: ["general", "work"] },
]);

// NODE 17: Complex Conditionals
addCards([
  { target: "Si hubiera estudiado más, habría aprobado el examen.", english: "If I had studied more, I would have passed the exam.", tags: ["general"], grammar: "Si + pluperfect subjunctive + conditional perfect = past contrary-to-fact." },
  { target: "Si hubiéramos salido antes, habríamos llegado a tiempo.", english: "If we had left earlier, we would have arrived on time.", tags: ["general", "travel"] },
  { target: "Si no me hubieras avisado, habría perdido el vuelo.", english: "If you hadn't warned me, I would have missed the flight.", tags: ["general", "travel"] },
  { target: "Si hubiera llovido, nos habríamos quedado en casa.", english: "If it had rained, we would have stayed home.", tags: ["general"] },
  { target: "Si me hubieran ofrecido ese trabajo, lo habría aceptado.", english: "If they had offered me that job, I would have accepted it.", tags: ["general", "work"] },
  { target: "Si hubiera sabido la verdad, habría actuado de otra manera.", english: "If I had known the truth, I would have acted differently.", tags: ["general"] },
  { target: "De haber tenido tiempo, habría ido a visitarte.", english: "Had I had time, I would have gone to visit you.", tags: ["general", "family"], grammar: "De haber + participle is an alternative to si hubiera + participle." },
  { target: "Si nos hubiéramos conocido antes, habríamos sido grandes amigos.", english: "If we had met earlier, we would have been great friends.", tags: ["general"] },
  { target: "Si hubiera hecho la reserva, tendríamos mesa ahora.", english: "If I had made the reservation, we would have a table now.", tags: ["general", "travel"], grammar: "Mixed conditional: past condition + present result." },
  { target: "Si no hubiera nevado, habríamos ido a la montaña.", english: "If it hadn't snowed, we would have gone to the mountain.", tags: ["general", "travel"] },
  { target: "Si hubieras escuchado mis consejos, no estarías en esta situación.", english: "If you had listened to my advice, you wouldn't be in this situation.", tags: ["general"] },
  { target: "Si hubiera ahorrado más, ahora podría comprar un coche.", english: "If I had saved more, I could buy a car now.", tags: ["general"] },
  { target: "De no haber sido por ti, no lo habría conseguido.", english: "If it hadn't been for you, I wouldn't have made it.", tags: ["general"] },
  { target: "Si me hubieran dicho antes, habría preparado algo especial.", english: "If they had told me sooner, I would have prepared something special.", tags: ["general", "family"] },
  { target: "Si hubiera leído las instrucciones, no habría roto la máquina.", english: "If I had read the instructions, I wouldn't have broken the machine.", tags: ["general", "work"] },
  { target: "Si hubiéramos reservado con anticipación, habría sido más barato.", english: "If we had booked in advance, it would have been cheaper.", tags: ["general", "travel"] },
  { target: "Si no hubiera comido tanto, no me sentiría mal ahora.", english: "If I hadn't eaten so much, I wouldn't feel bad now.", tags: ["general"] },
  { target: "Si te hubieras levantado temprano, habrías visto el amanecer.", english: "If you had gotten up early, you would have seen the sunrise.", tags: ["general", "travel"] },
  { target: "Si hubiera traído paraguas, no estaría empapado.", english: "If I had brought an umbrella, I wouldn't be soaked.", tags: ["general"] },
  { target: "De haberlo sabido, no habría venido.", english: "Had I known, I wouldn't have come.", tags: ["general"] },
  { target: "Si hubiera nacido en otro país, mi vida sería completamente diferente.", english: "If I had been born in another country, my life would be completely different.", tags: ["general"] },
  { target: "Si no me hubiera mudado, seguiría viviendo con mis padres.", english: "If I hadn't moved, I would still be living with my parents.", tags: ["general", "family"] },
  { target: "Si hubieras venido a la fiesta, te habrías divertido mucho.", english: "If you had come to the party, you would have had a lot of fun.", tags: ["general"] },
  { target: "Si hubiera invertido en esa empresa, ahora sería rico.", english: "If I had invested in that company, I would now be rich.", tags: ["general", "work"] },
  { target: "Si no hubiera conocido a mi esposa, mi vida habría sido muy distinta.", english: "If I hadn't met my wife, my life would have been very different.", tags: ["general", "family"] },
  { target: "De haber podido, me habría quedado una semana más.", english: "If I could have, I would have stayed one more week.", tags: ["general", "travel"] },
  { target: "Si hubiera prestado atención, habría entendido la explicación.", english: "If I had paid attention, I would have understood the explanation.", tags: ["general"] },
  { target: "Si no se hubiera roto el ascensor, habríamos subido por ahí.", english: "If the elevator hadn't broken, we would have gone up that way.", tags: ["general"] },
  { target: "Si hubieras pedido ayuda, alguien te habría ayudado.", english: "If you had asked for help, someone would have helped you.", tags: ["general", "work"] },
  { target: "Si hubiera tenido más confianza, habría hablado en la reunión.", english: "If I had had more confidence, I would have spoken in the meeting.", tags: ["general", "work"] },
  { target: "Si no hubieran cancelado el concierto, habríamos ido.", english: "If they hadn't cancelled the concert, we would have gone.", tags: ["general"] },
  { target: "Si hubiéramos comprado la casa, ahora tendríamos hipoteca.", english: "If we had bought the house, we would now have a mortgage.", tags: ["general", "family"] },
  { target: "Si me hubiera preparado mejor, la entrevista habría ido bien.", english: "If I had prepared better, the interview would have gone well.", tags: ["general", "work"] },
  { target: "Si no hubiera llovido tanto, la cosecha habría sido mejor.", english: "If it hadn't rained so much, the harvest would have been better.", tags: ["general"] },
  { target: "De haber llegado antes, habríamos encontrado sitio.", english: "Had we arrived earlier, we would have found a seat.", tags: ["general", "travel"] },
  { target: "Si hubiera aprendido a cocinar antes, no habría gastado tanto en restaurantes.", english: "If I had learned to cook sooner, I wouldn't have spent so much on restaurants.", tags: ["general"] },
  { target: "Si hubiéramos tomado otro camino, no habríamos visto el accidente.", english: "If we had taken another route, we wouldn't have seen the accident.", tags: ["general", "travel"] },
  { target: "Si hubiera dormido más, no estaría tan cansado.", english: "If I had slept more, I wouldn't be so tired.", tags: ["general"] },
  { target: "Si le hubieras dicho la verdad, te habría perdonado.", english: "If you had told him the truth, he would have forgiven you.", tags: ["general", "family"] },
  { target: "Si no hubiera aceptado ese trabajo, nunca habría conocido a mis mejores amigos.", english: "If I hadn't accepted that job, I would never have met my best friends.", tags: ["general", "work"] },
]);

// NODE 18: Passive & Impersonal
addCards([
  { target: "Se habla español en más de veinte países.", english: "Spanish is spoken in more than twenty countries.", tags: ["general", "travel"], grammar: "Se + 3rd person verb = impersonal/passive construction." },
  { target: "El edificio fue construido en el siglo diecinueve.", english: "The building was constructed in the nineteenth century.", tags: ["general", "travel"] },
  { target: "Se necesitan voluntarios para el evento.", english: "Volunteers are needed for the event.", tags: ["general", "work"] },
  { target: "La carta fue enviada ayer por la mañana.", english: "The letter was sent yesterday morning.", tags: ["general", "work"] },
  { target: "Se prohíbe fumar en esta zona.", english: "Smoking is prohibited in this area.", tags: ["general", "travel"] },
  { target: "Los resultados fueron publicados esta mañana.", english: "The results were published this morning.", tags: ["general", "work"] },
  { target: "Se busca un apartamento cerca del centro.", english: "An apartment near the center is being sought.", tags: ["general"] },
  { target: "El proyecto fue aprobado por el comité.", english: "The project was approved by the committee.", tags: ["general", "work"], grammar: "Ser + participle = true passive, often with por + agent." },
  { target: "Se recomienda llegar con treinta minutos de antelación.", english: "It is recommended to arrive thirty minutes early.", tags: ["general", "travel", "work"] },
  { target: "La reunión fue cancelada sin previo aviso.", english: "The meeting was cancelled without prior notice.", tags: ["general", "work"] },
  { target: "Se venden frutas y verduras frescas aquí.", english: "Fresh fruits and vegetables are sold here.", tags: ["general"] },
  { target: "El acuerdo fue firmado por ambas partes.", english: "The agreement was signed by both parties.", tags: ["general", "work"] },
  { target: "Se dice que va a nevar esta semana.", english: "It is said it's going to snow this week.", tags: ["general"] },
  { target: "La decisión fue tomada de forma unánime.", english: "The decision was made unanimously.", tags: ["general", "work"] },
  { target: "Se aceptan tarjetas de crédito y débito.", english: "Credit and debit cards are accepted.", tags: ["general", "travel"] },
  { target: "El puente fue diseñado por un arquitecto famoso.", english: "The bridge was designed by a famous architect.", tags: ["general", "travel"] },
  { target: "Se cree que el problema empezó hace meses.", english: "It is believed the problem started months ago.", tags: ["general"] },
  { target: "Las ventanas fueron rotas durante la tormenta.", english: "The windows were broken during the storm.", tags: ["general"] },
  { target: "Se espera que la situación mejore pronto.", english: "It is expected that the situation will improve soon.", tags: ["general", "work"] },
  { target: "El informe fue redactado por todo el equipo.", english: "The report was drafted by the entire team.", tags: ["general", "work"] },
  { target: "Se permite entrar con mascotas en este parque.", english: "Pets are allowed in this park.", tags: ["general", "travel"] },
  { target: "La ciudad fue fundada hace quinientos años.", english: "The city was founded five hundred years ago.", tags: ["general", "travel"] },
  { target: "Se sabe que el ejercicio es bueno para la salud.", english: "It is known that exercise is good for health.", tags: ["general"] },
  { target: "Los documentos fueron entregados a tiempo.", english: "The documents were delivered on time.", tags: ["general", "work"] },
  { target: "Se ruega silencio en la biblioteca.", english: "Silence is requested in the library.", tags: ["general"] },
  { target: "La nueva ley fue aprobada el mes pasado.", english: "The new law was approved last month.", tags: ["general"] },
  { target: "Se ofrecen cursos gratuitos para todos.", english: "Free courses are offered for everyone.", tags: ["general", "work"] },
  { target: "El premio fue otorgado al mejor empleado.", english: "The award was given to the best employee.", tags: ["general", "work"] },
  { target: "Se nota que has trabajado mucho en esto.", english: "You can tell you've worked a lot on this.", tags: ["general", "work"] },
  { target: "Los paquetes fueron entregados esta mañana.", english: "The packages were delivered this morning.", tags: ["general"] },
  { target: "Se alquilan habitaciones por semana o por mes.", english: "Rooms are rented by the week or month.", tags: ["general", "travel"] },
  { target: "La carretera fue reparada después del terremoto.", english: "The road was repaired after the earthquake.", tags: ["general"] },
  { target: "Se puede ver el mar desde esta ventana.", english: "The sea can be seen from this window.", tags: ["general", "travel"] },
  { target: "El mensaje fue leído por todos los empleados.", english: "The message was read by all employees.", tags: ["general", "work"] },
  { target: "Se comenta que van a abrir un nuevo restaurante.", english: "It's being said they're going to open a new restaurant.", tags: ["general"] },
  { target: "La exposición fue inaugurada por la alcaldesa.", english: "The exhibition was inaugurated by the mayor.", tags: ["general", "travel"] },
  { target: "Se requiere experiencia previa para este puesto.", english: "Previous experience is required for this position.", tags: ["general", "work"] },
  { target: "El contrato fue renovado por un año más.", english: "The contract was renewed for one more year.", tags: ["general", "work"] },
  { target: "Se oye música desde el parque.", english: "Music can be heard from the park.", tags: ["general"] },
  { target: "La propuesta fue rechazada por la mayoría.", english: "The proposal was rejected by the majority.", tags: ["general", "work"] },
]);

// NODE 19: Advanced Connectors
addCards([
  { target: "A pesar de la lluvia, decidimos salir a caminar.", english: "Despite the rain, we decided to go for a walk.", tags: ["general"], grammar: "A pesar de + noun = despite/in spite of." },
  { target: "No solo habla español, sino que también domina el francés.", english: "Not only does he speak Spanish, but he also masters French.", tags: ["general"], grammar: "No solo...sino que también = not only...but also." },
  { target: "Siempre que pueda, iré a visitarte.", english: "Whenever I can, I will go visit you.", tags: ["general", "family"] },
  { target: "En cuanto termine el proyecto, me tomaré unas vacaciones.", english: "As soon as I finish the project, I will take a vacation.", tags: ["general", "work", "travel"] },
  { target: "Ya que no puedes venir, te enviaré las fotos.", english: "Since you can't come, I'll send you the photos.", tags: ["general"] },
  { target: "A medida que pasa el tiempo, las cosas mejoran.", english: "As time goes by, things improve.", tags: ["general"] },
  { target: "Tanto mi hermano como yo somos alérgicos al polen.", english: "Both my brother and I are allergic to pollen.", tags: ["general", "family"] },
  { target: "Por más que lo intente, no logro entenderlo.", english: "No matter how hard I try, I can't manage to understand it.", tags: ["general"], grammar: "Por más que + subjunctive = no matter how much." },
  { target: "Dado que no hay suficiente presupuesto, el viaje se canceló.", english: "Given that there isn't enough budget, the trip was cancelled.", tags: ["general", "work"] },
  { target: "A menos que llegues antes de las ocho, no habrá sitio.", english: "Unless you arrive before eight, there won't be a seat.", tags: ["general", "travel"] },
  { target: "En vez de quejarte, busca una solución.", english: "Instead of complaining, look for a solution.", tags: ["general", "work"] },
  { target: "Mientras tanto, puedes ir preparando la mesa.", english: "In the meantime, you can set the table.", tags: ["general", "family"] },
  { target: "A fin de cuentas, lo importante es estar juntos.", english: "At the end of the day, the important thing is being together.", tags: ["general", "family"] },
  { target: "Por un lado quiero ir, pero por otro lado tengo miedo.", english: "On one hand I want to go, but on the other hand I'm afraid.", tags: ["general"] },
  { target: "Sin embargo, creo que deberíamos intentarlo.", english: "However, I think we should try.", tags: ["general", "work"] },
  { target: "Puesto que ya estamos todos, podemos empezar.", english: "Since we're all here now, we can start.", tags: ["general", "work"] },
  { target: "Ni siquiera me llamó para avisarme.", english: "He didn't even call me to let me know.", tags: ["general"] },
  { target: "Es decir, tendremos que buscar otra opción.", english: "That is to say, we'll have to look for another option.", tags: ["general", "work"] },
  { target: "Con tal de que me avises antes, no hay problema.", english: "As long as you let me know beforehand, there's no problem.", tags: ["general"] },
  { target: "En lugar de tomar un taxi, fuimos caminando.", english: "Instead of taking a taxi, we walked.", tags: ["general", "travel"] },
  { target: "Aparte de ser inteligente, es muy trabajador.", english: "Besides being intelligent, he is very hardworking.", tags: ["general", "work"] },
  { target: "A pesar de todo, seguimos adelante con el plan.", english: "Despite everything, we moved forward with the plan.", tags: ["general", "work"] },
  { target: "De modo que no queda otra opción más que esperar.", english: "So there's no other option but to wait.", tags: ["general"] },
  { target: "Aun así, no me arrepiento de mi decisión.", english: "Even so, I don't regret my decision.", tags: ["general"] },
  { target: "Siempre y cuando cumplas tu parte, yo cumpliré la mía.", english: "As long as you do your part, I'll do mine.", tags: ["general", "work"] },
  { target: "En primer lugar, debemos analizar los datos.", english: "First of all, we must analyze the data.", tags: ["general", "work"] },
  { target: "Debido a la falta de personal, cerraron temprano.", english: "Due to the lack of staff, they closed early.", tags: ["general", "work"] },
  { target: "Por lo tanto, la reunión se ha pospuesto.", english: "Therefore, the meeting has been postponed.", tags: ["general", "work"], grammar: "Por lo tanto = therefore, formal consequence connector." },
  { target: "A diferencia de su hermano, ella es muy extrovertida.", english: "Unlike her brother, she is very extroverted.", tags: ["general", "family"] },
  { target: "Al fin y al cabo, todos cometemos errores.", english: "After all, we all make mistakes.", tags: ["general"] },
  { target: "No obstante, los resultados fueron positivos.", english: "Nevertheless, the results were positive.", tags: ["general", "work"] },
  { target: "En caso de emergencia, llame al número indicado.", english: "In case of emergency, call the number indicated.", tags: ["general", "travel"] },
  { target: "Así como tú me ayudaste, yo te ayudaré.", english: "Just as you helped me, I will help you.", tags: ["general", "family"] },
  { target: "Con respecto al presupuesto, necesitamos más fondos.", english: "Regarding the budget, we need more funds.", tags: ["general", "work"] },
  { target: "A propósito, ¿has visto a María últimamente?", english: "By the way, have you seen María lately?", tags: ["general"] },
  { target: "En conclusión, el proyecto fue un éxito total.", english: "In conclusion, the project was a total success.", tags: ["general", "work"] },
  { target: "Antes de que te vayas, quiero decirte algo.", english: "Before you leave, I want to tell you something.", tags: ["general"] },
  { target: "Por consiguiente, debemos tomar medidas inmediatas.", english: "Consequently, we must take immediate measures.", tags: ["general", "work"] },
  { target: "Tal como te dije, la situación es complicada.", english: "Just as I told you, the situation is complicated.", tags: ["general"] },
  { target: "Después de todo, lo más importante es la salud.", english: "After all, the most important thing is health.", tags: ["general", "family"] },
]);

// NODE 20: Mixed Advanced
addCards([
  { target: "Si hubiera sabido que era tan lejos, habría tomado un taxi.", english: "If I had known it was so far, I would have taken a taxi.", tags: ["general", "travel"] },
  { target: "Lo que más me molesta es que no me lo hayan dicho antes.", english: "What bothers me the most is that they didn't tell me before.", tags: ["general", "work"], grammar: "Lo que + subjunctive for emotional reactions about events." },
  { target: "A pesar de que llovía, la boda se celebró al aire libre.", english: "Despite the fact that it was raining, the wedding was held outdoors.", tags: ["general", "family"] },
  { target: "Se dice que el nuevo director fue elegido por unanimidad.", english: "It is said that the new director was chosen unanimously.", tags: ["general", "work"] },
  { target: "Ojalá hubiera más gente como tú en el mundo.", english: "I wish there were more people like you in the world.", tags: ["general"] },
  { target: "No solo fue cancelado el evento, sino que también perdimos el depósito.", english: "Not only was the event cancelled, but we also lost the deposit.", tags: ["general", "work"] },
  { target: "Si me lo hubieras pedido, te habría acompañado sin dudarlo.", english: "If you had asked me, I would have accompanied you without hesitation.", tags: ["general", "family"] },
  { target: "Por mucho que se esfuerze, la situación no mejora.", english: "No matter how much he tries, the situation doesn't improve.", tags: ["general"] },
  { target: "Es imprescindible que todos los documentos sean revisados antes del lunes.", english: "It is essential that all documents be reviewed before Monday.", tags: ["general", "work"] },
  { target: "De no haber sido por su ayuda, nunca habría terminado a tiempo.", english: "Had it not been for his help, I never would have finished on time.", tags: ["general", "work"] },
  { target: "Cuanto más practico, mejor me siento con el idioma.", english: "The more I practice, the better I feel with the language.", tags: ["general"], grammar: "Cuanto más...mejor = the more...the better, comparative correlation." },
  { target: "Se espera que las negociaciones concluyan esta semana.", english: "It is expected that negotiations will conclude this week.", tags: ["general", "work"] },
  { target: "Aunque hubiera tenido más tiempo, el resultado habría sido el mismo.", english: "Even if I had had more time, the result would have been the same.", tags: ["general"] },
  { target: "Ni siquiera sabía que existiera esa posibilidad.", english: "I didn't even know that possibility existed.", tags: ["general"] },
  { target: "Lo importante no es cuánto ganas, sino cómo lo gastas.", english: "The important thing isn't how much you earn, but how you spend it.", tags: ["general", "work"] },
  { target: "Si bien el precio es alto, la calidad lo justifica.", english: "Although the price is high, the quality justifies it.", tags: ["general"] },
  { target: "Habría preferido que me consultaran antes de tomar la decisión.", english: "I would have preferred them to consult me before making the decision.", tags: ["general", "work"] },
  { target: "Sea como sea, debemos encontrar una solución antes del viernes.", english: "Be that as it may, we must find a solution before Friday.", tags: ["general", "work"] },
  { target: "Por más que intenté convencerla, no cambió de opinión.", english: "No matter how much I tried to convince her, she didn't change her mind.", tags: ["general", "family"] },
  { target: "Se rumorea que la empresa será vendida a un grupo extranjero.", english: "It's rumored that the company will be sold to a foreign group.", tags: ["general", "work"] },
  { target: "A menos que encontremos financiación, el proyecto se cancelará.", english: "Unless we find funding, the project will be cancelled.", tags: ["general", "work"] },
  { target: "Cuanto antes lo terminemos, mejor será para todos.", english: "The sooner we finish it, the better it will be for everyone.", tags: ["general", "work"] },
  { target: "Lo que debería haberse hecho desde el principio fue escuchar a la gente.", english: "What should have been done from the beginning was to listen to the people.", tags: ["general"] },
  { target: "Pese a las dificultades, lograron completar la misión.", english: "Despite the difficulties, they managed to complete the mission.", tags: ["general", "work"] },
  { target: "Si la empresa no hubiera invertido en tecnología, se habría quedado atrás.", english: "If the company hadn't invested in technology, it would have fallen behind.", tags: ["general", "work"] },
  { target: "No es que no quiera ir, es que no puedo.", english: "It's not that I don't want to go, it's that I can't.", tags: ["general"], grammar: "No es que + subjunctive...es que + indicative = it's not that...it's that." },
  { target: "Dado que se habían agotado las entradas, nos quedamos en casa.", english: "Given that the tickets had sold out, we stayed home.", tags: ["general"] },
  { target: "Habría sido mejor si hubiéramos hablado antes.", english: "It would have been better if we had talked earlier.", tags: ["general"] },
  { target: "Cuanto más leo sobre el tema, más preguntas tengo.", english: "The more I read about the topic, the more questions I have.", tags: ["general"] },
  { target: "Se estima que más de un millón de personas fueron afectadas.", english: "It is estimated that more than a million people were affected.", tags: ["general"] },
]);

console.log(`After B2 backfill: added ${added} cards (${dupes} dupes skipped)`);

// ═══════════════════════════════════════════════════════════════
// A2/B1 BACKFILL — ~150 cards for underpopulated nodes
// ═══════════════════════════════════════════════════════════════

// NODE 08: Reflexive Verbs (underpopulated)
addCards([
  { target: "Me despierto todos los días a las seis de la mañana.", english: "I wake up every day at six in the morning.", tags: ["general", "work"] },
  { target: "Mi hija se viste sola desde los cuatro años.", english: "My daughter has been dressing herself since she was four.", tags: ["general", "family"], grammar: "Vestirse is reflexive — the person dresses themselves." },
  { target: "Nos divertimos mucho en la fiesta de anoche.", english: "We had a lot of fun at last night's party.", tags: ["general"] },
  { target: "¿A qué hora te acuestas normalmente?", english: "What time do you normally go to bed?", tags: ["general"] },
  { target: "Se preocupa demasiado por todo.", english: "He worries too much about everything.", tags: ["general", "family"] },
  { target: "Me arrepiento de no haber estudiado más.", english: "I regret not having studied more.", tags: ["general"] },
  { target: "Se quejaron del ruido durante toda la noche.", english: "They complained about the noise all night.", tags: ["general", "travel"] },
  { target: "Nos sentamos en la primera fila del cine.", english: "We sat in the first row of the cinema.", tags: ["general"] },
  { target: "Te pareces mucho a tu madre.", english: "You look a lot like your mother.", tags: ["general", "family"] },
  { target: "Me di cuenta de que había olvidado las llaves.", english: "I realized I had forgotten the keys.", tags: ["general"], grammar: "Darse cuenta de = to realize, a common reflexive expression." },
  { target: "Se despidió de todos antes de irse.", english: "He said goodbye to everyone before leaving.", tags: ["general", "work"] },
  { target: "Nos mudamos a esta ciudad hace cinco años.", english: "We moved to this city five years ago.", tags: ["general", "family"] },
  { target: "Se enamoraron durante un viaje a París.", english: "They fell in love during a trip to Paris.", tags: ["general", "travel"] },
  { target: "Me aburro cuando no tengo nada que hacer.", english: "I get bored when I have nothing to do.", tags: ["general"] },
  { target: "Se duchó rápidamente y salió corriendo.", english: "He showered quickly and ran out.", tags: ["general"] },
  { target: "Nos reunimos todos los domingos para comer en familia.", english: "We get together every Sunday for a family meal.", tags: ["general", "family"] },
  { target: "Me puse nerviosa antes de la presentación.", english: "I got nervous before the presentation.", tags: ["general", "work"] },
  { target: "Se cayó por las escaleras y se rompió el brazo.", english: "He fell down the stairs and broke his arm.", tags: ["general"] },
  { target: "Te equivocaste de dirección; era al revés.", english: "You went the wrong way; it was the opposite direction.", tags: ["general", "travel"] },
  { target: "Me quedo en casa cuando hace mucho frío.", english: "I stay home when it's very cold.", tags: ["general"] },
  { target: "Se enfadó porque nadie le avisó del cambio.", english: "He got angry because nobody warned him about the change.", tags: ["general", "work"] },
  { target: "Nos conocimos en la universidad hace diez años.", english: "We met at university ten years ago.", tags: ["general"] },
  { target: "Me olvidé de comprar leche en el supermercado.", english: "I forgot to buy milk at the supermarket.", tags: ["general"] },
  { target: "Se acostumbró rápidamente al nuevo horario.", english: "He quickly got used to the new schedule.", tags: ["general", "work"] },
  { target: "Me siento muy orgullosa de mis hijos.", english: "I feel very proud of my children.", tags: ["general", "family"] },
]);

// NODE 09: Por vs Para (underpopulated)
addCards([
  { target: "Compré estas flores para mi madre.", english: "I bought these flowers for my mother.", tags: ["general", "family"], grammar: "Para + recipient = intended for someone." },
  { target: "Estuvimos caminando por la playa durante horas.", english: "We were walking along the beach for hours.", tags: ["general", "travel"] },
  { target: "Para ser principiante, hablas muy bien.", english: "For a beginner, you speak very well.", tags: ["general"] },
  { target: "Lo hice por ti, no por mí.", english: "I did it for you, not for me.", tags: ["general", "family"], grammar: "Por = because of/on behalf of (motivation), para = intended for (purpose)." },
  { target: "Necesito terminarlo para el viernes.", english: "I need to finish it by Friday.", tags: ["general", "work"] },
  { target: "Pasamos por el parque de camino a casa.", english: "We passed through the park on the way home.", tags: ["general"] },
  { target: "Para mí, lo más importante es la familia.", english: "For me, the most important thing is family.", tags: ["general", "family"] },
  { target: "Gracias por invitarme a tu fiesta.", english: "Thank you for inviting me to your party.", tags: ["general"] },
  { target: "Salimos para el aeropuerto a las cinco.", english: "We left for the airport at five.", tags: ["general", "travel"] },
  { target: "Trabajo por la noche y duermo por el día.", english: "I work at night and sleep during the day.", tags: ["general", "work"] },
  { target: "Este regalo es para tu cumpleaños.", english: "This gift is for your birthday.", tags: ["general", "family"] },
  { target: "Por favor, pásame la sal.", english: "Please pass me the salt.", tags: ["general"] },
  { target: "Estudio español para poder comunicarme mejor.", english: "I study Spanish to be able to communicate better.", tags: ["general"], grammar: "Para + infinitive = in order to (purpose)." },
  { target: "Pagué veinte euros por la camiseta.", english: "I paid twenty euros for the shirt.", tags: ["general"] },
  { target: "Para llegar al centro, toma la segunda a la derecha.", english: "To get to the center, take the second right.", tags: ["general", "travel"] },
  { target: "Lo cambiaron por otro modelo más nuevo.", english: "They exchanged it for another newer model.", tags: ["general"] },
  { target: "Para ser honesto, no me gustó la película.", english: "To be honest, I didn't like the movie.", tags: ["general"] },
  { target: "Por suerte, encontramos el hotel fácilmente.", english: "Luckily, we found the hotel easily.", tags: ["general", "travel"] },
  { target: "Trabaja para una empresa internacional.", english: "She works for an international company.", tags: ["general", "work"] },
  { target: "Nos quedamos en casa por el mal tiempo.", english: "We stayed home because of the bad weather.", tags: ["general"] },
  { target: "Para mejorar, necesitas practicar todos los días.", english: "To improve, you need to practice every day.", tags: ["general"] },
  { target: "Lo hago por amor, no por obligación.", english: "I do it out of love, not out of obligation.", tags: ["general", "family"] },
  { target: "¿Para qué sirve este botón?", english: "What is this button for?", tags: ["general", "work"] },
  { target: "Fueron multados por exceso de velocidad.", english: "They were fined for speeding.", tags: ["general", "travel"] },
  { target: "Tenemos comida para tres días.", english: "We have food for three days.", tags: ["general", "travel"] },
]);

// NODE 12: Commands (underpopulated)
addCards([
  { target: "Ven aquí, por favor.", english: "Come here, please.", tags: ["general", "family"] },
  { target: "No toques eso, es peligroso.", english: "Don't touch that, it's dangerous.", tags: ["general", "family"], grammar: "Negative tú commands use the subjunctive form." },
  { target: "Dime la verdad, ¿qué pasó?", english: "Tell me the truth, what happened?", tags: ["general", "family"] },
  { target: "Cierra la puerta cuando salgas.", english: "Close the door when you leave.", tags: ["general"] },
  { target: "No se preocupe, todo va a salir bien.", english: "Don't worry, everything will turn out fine.", tags: ["general", "work"], grammar: "Negative usted commands also use the subjunctive form." },
  { target: "Haz tu tarea antes de jugar.", english: "Do your homework before playing.", tags: ["general", "family"] },
  { target: "Por favor, envíeme el informe antes del mediodía.", english: "Please send me the report before noon.", tags: ["general", "work"] },
  { target: "Siéntense, por favor; la reunión va a comenzar.", english: "Please sit down; the meeting is about to start.", tags: ["general", "work"] },
  { target: "No dejes la ropa en el suelo.", english: "Don't leave the clothes on the floor.", tags: ["general", "family"] },
  { target: "Sal de casa a las ocho para llegar a tiempo.", english: "Leave the house at eight to arrive on time.", tags: ["general", "work"] },
  { target: "Prueba este plato; está delicioso.", english: "Try this dish; it's delicious.", tags: ["general", "travel"] },
  { target: "No corras por los pasillos del hospital.", english: "Don't run in the hospital hallways.", tags: ["general"] },
  { target: "Llámame cuando llegues al hotel.", english: "Call me when you arrive at the hotel.", tags: ["general", "travel", "family"] },
  { target: "Ponga la maleta en el compartimento de arriba.", english: "Put the suitcase in the overhead compartment.", tags: ["general", "travel"] },
  { target: "No te olvides de traer los documentos.", english: "Don't forget to bring the documents.", tags: ["general", "work"] },
  { target: "Escucha con atención lo que te voy a decir.", english: "Listen carefully to what I'm going to tell you.", tags: ["general"] },
  { target: "Espere un momento, por favor.", english: "Wait a moment, please.", tags: ["general", "travel"] },
  { target: "No grites, que los vecinos están durmiendo.", english: "Don't shout, the neighbors are sleeping.", tags: ["general", "family"] },
  { target: "Pon la mesa; la cena está casi lista.", english: "Set the table; dinner is almost ready.", tags: ["general", "family"] },
  { target: "Abra la ventana, por favor; hace mucho calor.", english: "Open the window, please; it's very hot.", tags: ["general"] },
  { target: "No te preocupes por eso; yo me encargo.", english: "Don't worry about that; I'll take care of it.", tags: ["general", "work"] },
  { target: "Deja de hablar y escucha.", english: "Stop talking and listen.", tags: ["general"] },
  { target: "Sigue recto y gira a la izquierda.", english: "Go straight and turn left.", tags: ["general", "travel"], grammar: "Sigue is an affirmative tú command of seguir (irregular)." },
  { target: "No se vaya todavía; necesito hablar con usted.", english: "Don't leave yet; I need to talk to you.", tags: ["general", "work"] },
  { target: "Trae una chaqueta por si hace frío.", english: "Bring a jacket in case it's cold.", tags: ["general", "travel"] },
]);

// NODE 15: Relative Clauses (underpopulated)
addCards([
  { target: "El problema al que nos enfrentamos es muy complejo.", english: "The problem we face is very complex.", tags: ["general", "work"], grammar: "Al que = a + el + que, preposition + relative pronoun." },
  { target: "Hay días en los que todo parece salir mal.", english: "There are days when everything seems to go wrong.", tags: ["general"] },
  { target: "La manera en que lo dijo me hizo pensar.", english: "The way he said it made me think.", tags: ["general"] },
  { target: "El momento en que la vi, supe que era especial.", english: "The moment I saw her, I knew she was special.", tags: ["general"] },
  { target: "Las personas a quienes les conté el secreto son de confianza.", english: "The people I told the secret to are trustworthy.", tags: ["general"] },
  { target: "Lo único que me falta es un poco de paciencia.", english: "The only thing I lack is a bit of patience.", tags: ["general"] },
  { target: "El trabajo por el que tanto luché finalmente dio frutos.", english: "The work I fought so hard for finally bore fruit.", tags: ["general", "work"] },
  { target: "La casa en la que crecimos ya no existe.", english: "The house we grew up in no longer exists.", tags: ["general", "family"] },
  { target: "Todo lo que necesitas está en esa caja.", english: "Everything you need is in that box.", tags: ["general"] },
  { target: "El país al que quiero viajar es Japón.", english: "The country I want to travel to is Japan.", tags: ["general", "travel"] },
  { target: "Las razones por las que renunció no están claras.", english: "The reasons he resigned aren't clear.", tags: ["general", "work"] },
  { target: "La persona de la que te hablé viene mañana.", english: "The person I told you about is coming tomorrow.", tags: ["general"] },
  { target: "El lugar donde nos conocimos ya cerró.", english: "The place where we met has already closed.", tags: ["general"] },
  { target: "Lo que más echo de menos es la comida de mi abuela.", english: "What I miss the most is my grandmother's cooking.", tags: ["general", "family"] },
  { target: "El equipo con el que trabajo es excelente.", english: "The team I work with is excellent.", tags: ["general", "work"] },
  { target: "La excusa que me dio no era creíble.", english: "The excuse he gave me was not believable.", tags: ["general"] },
  { target: "El barco en el que viajamos era enorme.", english: "The boat we traveled on was enormous.", tags: ["general", "travel"] },
  { target: "La idea que propusiste ayer fue la mejor.", english: "The idea you proposed yesterday was the best.", tags: ["general", "work"] },
  { target: "Lo que quiero saber es si podemos contar contigo.", english: "What I want to know is if we can count on you.", tags: ["general", "work"] },
  { target: "La época en la que vivimos está llena de cambios.", english: "The era we live in is full of changes.", tags: ["general"] },
  { target: "El curso al que me apunté empieza el lunes.", english: "The course I signed up for starts on Monday.", tags: ["general", "work"] },
  { target: "Las calles por las que caminamos eran muy estrechas.", english: "The streets we walked through were very narrow.", tags: ["general", "travel"] },
  { target: "El motivo por el cual no vine fue una emergencia familiar.", english: "The reason I didn't come was a family emergency.", tags: ["general", "family"], grammar: "Por el cual = for which, more formal than por el que." },
  { target: "La única cosa que me preocupa es tu salud.", english: "The only thing that worries me is your health.", tags: ["general", "family"] },
  { target: "El aeropuerto desde el que salimos estaba muy lejos.", english: "The airport we departed from was very far away.", tags: ["general", "travel"] },
]);

console.log(`After A2/B1 backfill: total added ${added} (${dupes} dupes)`);

// ═══════════════════════════════════════════════════════════════
// C1 NODES 21-23 (~150 cards each = ~450 total)
// ═══════════════════════════════════════════════════════════════

// NODE 21: Subjunctive Nuances
addCards([
  { target: "No creo que sea tan fácil como parece.", english: "I don't think it's as easy as it seems.", tags: ["general"], grammar: "No creo que + subjunctive — negated belief triggers subjunctive." },
  { target: "Aunque tenga razón, debería ser más amable.", english: "Even if he's right, he should be kinder.", tags: ["general"] },
  { target: "Como si fuera la primera vez que lo hace.", english: "As if it were the first time he's doing it.", tags: ["general"], grammar: "Como si always takes imperfect subjunctive." },
  { target: "El hecho de que no haya venido me preocupa.", english: "The fact that he hasn't come worries me.", tags: ["general"], grammar: "El hecho de que + subjunctive for factual statements that trigger emotion." },
  { target: "Sea como sea, tenemos que terminar hoy.", english: "Be that as it may, we have to finish today.", tags: ["general", "work"] },
  { target: "Por más que estudie, no aprueba el examen.", english: "No matter how much she studies, she doesn't pass the exam.", tags: ["general"], grammar: "Por más que + subjunctive = no matter how much." },
  { target: "No es que no quiera ayudarte, es que no puedo.", english: "It's not that I don't want to help you, it's that I can't.", tags: ["general"] },
  { target: "Que yo sepa, nadie ha confirmado la reserva.", english: "As far as I know, nobody has confirmed the reservation.", tags: ["general", "travel"], grammar: "Que yo sepa = as far as I know, set subjunctive phrase." },
  { target: "A pesar de que llueva, iremos a la excursión.", english: "Even though it may rain, we will go on the excursion.", tags: ["general", "travel"] },
  { target: "Dudo que encuentres algo mejor a ese precio.", english: "I doubt you'll find anything better at that price.", tags: ["general"] },
  { target: "No existe nadie que pueda resolver esto solo.", english: "There's nobody who can solve this alone.", tags: ["general", "work"] },
  { target: "Quienquiera que haya dicho eso, se equivoca.", english: "Whoever said that is wrong.", tags: ["general"], grammar: "Quienquiera que + subjunctive = whoever." },
  { target: "Hagas lo que hagas, te voy a apoyar.", english: "Whatever you do, I'm going to support you.", tags: ["general", "family"] },
  { target: "No hay nada que me haga cambiar de opinión.", english: "There is nothing that will make me change my mind.", tags: ["general"] },
  { target: "Aunque parezca mentira, lo logré sin ayuda.", english: "Hard as it may be to believe, I did it without help.", tags: ["general", "work"] },
  { target: "Es posible que tengamos que cambiar el plan.", english: "It's possible we may have to change the plan.", tags: ["general", "work"] },
  { target: "Dondequiera que vayas, lleva tu pasaporte.", english: "Wherever you go, take your passport.", tags: ["general", "travel"], grammar: "Dondequiera que + subjunctive = wherever." },
  { target: "Necesito a alguien que hable tres idiomas.", english: "I need someone who speaks three languages.", tags: ["general", "work"] },
  { target: "No creo que hayan entendido bien las instrucciones.", english: "I don't think they understood the instructions well.", tags: ["general", "work"] },
  { target: "Por mucho que lo niegue, todos sabemos la verdad.", english: "No matter how much he denies it, we all know the truth.", tags: ["general"] },
  { target: "A menos que cambie de actitud, perderá a sus amigos.", english: "Unless he changes his attitude, he'll lose his friends.", tags: ["general"] },
  { target: "Es fundamental que todos estén de acuerdo.", english: "It's essential that everyone agrees.", tags: ["general", "work"] },
  { target: "Antes de que digas nada, déjame explicar.", english: "Before you say anything, let me explain.", tags: ["general"] },
  { target: "Ojalá hubiera prestado más atención en clase.", english: "I wish I had paid more attention in class.", tags: ["general"] },
  { target: "Por muy inteligente que sea, necesita estudiar más.", english: "However intelligent he may be, he needs to study more.", tags: ["general"], grammar: "Por muy + adjective + que + subjunctive = however much." },
  { target: "No digo que esté mal, solo digo que se puede mejorar.", english: "I'm not saying it's bad, I'm just saying it can be improved.", tags: ["general", "work"] },
  { target: "Comoquiera que se mire, fue una mala decisión.", english: "However you look at it, it was a bad decision.", tags: ["general"] },
  { target: "Busco un lugar donde pueda trabajar en silencio.", english: "I'm looking for a place where I can work in silence.", tags: ["general", "work"] },
  { target: "No es que sea difícil, es que requiere tiempo.", english: "It's not that it's difficult, it's that it requires time.", tags: ["general"] },
  { target: "Siempre que necesites algo, llámame.", english: "Whenever you need something, call me.", tags: ["general", "family"] },
  { target: "Aunque no lo creas, me encanta madrugar.", english: "Believe it or not, I love getting up early.", tags: ["general"] },
  { target: "Es una lástima que no puedas venir a la boda.", english: "It's a shame you can't come to the wedding.", tags: ["general", "family"] },
  { target: "Con tal de que seas feliz, yo estaré bien.", english: "As long as you're happy, I'll be fine.", tags: ["general", "family"] },
  { target: "Que yo recuerde, nunca hemos tenido ese problema.", english: "As far as I remember, we've never had that problem.", tags: ["general", "work"] },
  { target: "No conozco a nadie que haya estado en la Antártida.", english: "I don't know anyone who has been to Antarctica.", tags: ["general", "travel"] },
  { target: "Pase lo que pase, estaremos juntos.", english: "Whatever happens, we'll be together.", tags: ["general", "family"], grammar: "Pase lo que pase = reduplicative subjunctive for 'whatever happens'." },
  { target: "Es improbable que acepten nuestra propuesta.", english: "It's unlikely they'll accept our proposal.", tags: ["general", "work"] },
  { target: "Aunque hubiera sabido la verdad, no habría dicho nada.", english: "Even if I had known the truth, I wouldn't have said anything.", tags: ["general"] },
  { target: "Quien quiera participar, que levante la mano.", english: "Whoever wants to participate, raise your hand.", tags: ["general", "work"] },
  { target: "No niego que tenga talento, pero le falta disciplina.", english: "I don't deny he has talent, but he lacks discipline.", tags: ["general"] },
  { target: "Dudo mucho que lleguen a un acuerdo pronto.", english: "I very much doubt they'll reach an agreement soon.", tags: ["general", "work"] },
  { target: "Por poco que duerma, siempre se levanta de buen humor.", english: "However little he sleeps, he always wakes up in a good mood.", tags: ["general"] },
  { target: "Es mejor que lo hablemos en persona.", english: "It's better that we discuss it in person.", tags: ["general", "work"] },
  { target: "Sin que nadie se diera cuenta, salió de la habitación.", english: "Without anyone noticing, he left the room.", tags: ["general"] },
  { target: "Puede que tengas razón, pero no estoy convencido.", english: "You may be right, but I'm not convinced.", tags: ["general"] },
  { target: "No me molesta que vengan tarde, me molesta que no avisen.", english: "It doesn't bother me that they come late; it bothers me that they don't let me know.", tags: ["general", "work"] },
  { target: "Suponiendo que todo salga bien, acabaremos en mayo.", english: "Assuming everything goes well, we'll finish in May.", tags: ["general", "work"] },
  { target: "El que no corra riesgos nunca ganará nada.", english: "He who doesn't take risks will never win anything.", tags: ["general"] },
  { target: "Quiero un apartamento que tenga balcón y mucha luz.", english: "I want an apartment that has a balcony and lots of light.", tags: ["general"] },
  { target: "Aunque no te guste, es la verdad.", english: "Even if you don't like it, it's the truth.", tags: ["general"] },
]);

// NODE 22: Verb Phrases (llevar+gerund, acabar de, ponerse a, etc.)
addCards([
  { target: "Llevo tres años estudiando español.", english: "I've been studying Spanish for three years.", tags: ["general"], grammar: "Llevar + time + gerund = to have been doing something for [duration]." },
  { target: "Acabo de llegar; dame un minuto.", english: "I just arrived; give me a minute.", tags: ["general"], grammar: "Acabar de + infinitive = to have just done something." },
  { target: "Se puso a llorar cuando recibió la noticia.", english: "She started to cry when she received the news.", tags: ["general", "family"], grammar: "Ponerse a + infinitive = to suddenly start doing something." },
  { target: "Dejó de fumar hace cinco años.", english: "He stopped smoking five years ago.", tags: ["general"], grammar: "Dejar de + infinitive = to stop doing something." },
  { target: "Volvió a llamarme a las diez de la noche.", english: "He called me again at ten at night.", tags: ["general"], grammar: "Volver a + infinitive = to do something again." },
  { target: "Sigue lloviendo desde esta mañana.", english: "It's been raining since this morning.", tags: ["general"] },
  { target: "Anda buscando trabajo desde que lo despidieron.", english: "He's been looking for a job since they fired him.", tags: ["general", "work"], grammar: "Andar + gerund = to go around doing something (habitual/ongoing)." },
  { target: "Llevo dos horas esperando el autobús.", english: "I've been waiting for the bus for two hours.", tags: ["general", "travel"] },
  { target: "Acabamos de mudarnos a un apartamento nuevo.", english: "We just moved to a new apartment.", tags: ["general", "family"] },
  { target: "Se puso a gritar sin ninguna razón.", english: "He started shouting for no reason.", tags: ["general"] },
  { target: "Dejé de ir al gimnasio porque me lesioné.", english: "I stopped going to the gym because I got injured.", tags: ["general"] },
  { target: "Volvió a nevar después de dos semanas sin nieve.", english: "It snowed again after two weeks without snow.", tags: ["general"] },
  { target: "Sigo pensando que fue una buena decisión.", english: "I still think it was a good decision.", tags: ["general"], grammar: "Seguir + gerund = to keep/continue doing something." },
  { target: "Anda diciendo por ahí que va a renunciar.", english: "He's going around saying he's going to resign.", tags: ["general", "work"] },
  { target: "Llevan viviendo en esa casa más de veinte años.", english: "They've been living in that house for more than twenty years.", tags: ["general", "family"] },
  { target: "Acabo de enterarme de que cerraron la tienda.", english: "I just found out they closed the store.", tags: ["general"] },
  { target: "El bebé se puso a llorar a mitad de la noche.", english: "The baby started crying in the middle of the night.", tags: ["general", "family"] },
  { target: "Dejaron de fabricar ese modelo hace años.", english: "They stopped manufacturing that model years ago.", tags: ["general"] },
  { target: "Volveremos a intentarlo mañana con más calma.", english: "We'll try again tomorrow more calmly.", tags: ["general", "work"] },
  { target: "Sigue trabajando en la misma empresa desde que era joven.", english: "He's still working at the same company since he was young.", tags: ["general", "work"] },
  { target: "Llevo toda la semana sin dormir bien.", english: "I've gone the whole week without sleeping well.", tags: ["general"] },
  { target: "Acaban de anunciar que el vuelo está retrasado.", english: "They just announced that the flight is delayed.", tags: ["general", "travel"] },
  { target: "Cuando vio el resultado, se puso a saltar de alegría.", english: "When he saw the result, he started jumping for joy.", tags: ["general"] },
  { target: "No dejo de pensar en lo que me dijiste.", english: "I can't stop thinking about what you told me.", tags: ["general"] },
  { target: "Han vuelto a subir los precios de la gasolina.", english: "Gas prices have gone up again.", tags: ["general"] },
  { target: "Seguimos esperando una respuesta del banco.", english: "We're still waiting for a response from the bank.", tags: ["general", "work"] },
  { target: "Llevo meses intentando aprender a tocar la guitarra.", english: "I've been trying to learn to play the guitar for months.", tags: ["general"] },
  { target: "Acababa de sentarme cuando sonó el teléfono.", english: "I had just sat down when the phone rang.", tags: ["general"] },
  { target: "Se pusieron a discutir en medio del restaurante.", english: "They started arguing in the middle of the restaurant.", tags: ["general"] },
  { target: "Está a punto de empezar la película.", english: "The movie is about to start.", tags: ["general"], grammar: "Estar a punto de + infinitive = to be about to do something." },
  { target: "No deja de hablar ni un segundo.", english: "He doesn't stop talking for even a second.", tags: ["general"] },
  { target: "Vuelvo a repetir: es muy importante que lleguen a tiempo.", english: "I repeat again: it's very important that they arrive on time.", tags: ["general", "work"] },
  { target: "Sigue nevando; no podremos salir hoy.", english: "It keeps snowing; we won't be able to go out today.", tags: ["general", "travel"] },
  { target: "Anda preocupado por los resultados del examen.", english: "He's been worried about the exam results.", tags: ["general"] },
  { target: "Llevo un rato intentando llamarte.", english: "I've been trying to call you for a while.", tags: ["general"] },
  { target: "Acabo de hablar con el médico y todo está bien.", english: "I just spoke with the doctor and everything is fine.", tags: ["general", "family"] },
  { target: "El niño se puso a correr en cuanto vio el parque.", english: "The child started running as soon as he saw the park.", tags: ["general", "family"] },
  { target: "Dejamos de vernos cuando ella se mudó al extranjero.", english: "We stopped seeing each other when she moved abroad.", tags: ["general"] },
  { target: "Si vuelves a llegar tarde, tendremos un problema.", english: "If you're late again, we'll have a problem.", tags: ["general", "work"] },
  { target: "Lleva toda la vida dedicándose a la enseñanza.", english: "He has spent his whole life dedicated to teaching.", tags: ["general", "work"] },
  { target: "Estaba a punto de salir cuando empezó a llover.", english: "I was about to leave when it started raining.", tags: ["general"] },
  { target: "Seguiremos luchando hasta conseguir nuestro objetivo.", english: "We'll keep fighting until we achieve our goal.", tags: ["general", "work"] },
  { target: "Andan diciendo que van a cerrar la fábrica.", english: "They're going around saying they're going to close the factory.", tags: ["general", "work"] },
  { target: "Llevo sin comer desde esta mañana.", english: "I haven't eaten since this morning.", tags: ["general"] },
  { target: "Acabó de leer el libro y me lo prestó.", english: "He finished reading the book and lent it to me.", tags: ["general"] },
  { target: "De repente se puso a cantar en medio de la calle.", english: "Suddenly he started singing in the middle of the street.", tags: ["general"] },
  { target: "No dejes de practicar o perderás lo aprendido.", english: "Don't stop practicing or you'll lose what you've learned.", tags: ["general"] },
  { target: "Hemos vuelto a cometer el mismo error.", english: "We've made the same mistake again.", tags: ["general", "work"] },
  { target: "El perro sigue ladrando aunque ya no hay nadie.", english: "The dog keeps barking even though there's nobody there.", tags: ["general"] },
  { target: "Llevamos horas conduciendo sin parar.", english: "We've been driving for hours without stopping.", tags: ["general", "travel"] },
]);

// NODE 23: Reported Speech
addCards([
  { target: "Dijo que vendría a las ocho.", english: "He said he would come at eight.", tags: ["general"], grammar: "Direct → indirect: 'vendré' becomes 'vendría' (tense backshift)." },
  { target: "Me preguntó si quería ir al cine.", english: "He asked me if I wanted to go to the movies.", tags: ["general"] },
  { target: "Le dije que no podía ir porque tenía trabajo.", english: "I told him I couldn't go because I had work.", tags: ["general", "work"] },
  { target: "Nos contó que había vivido en Japón durante tres años.", english: "He told us he had lived in Japan for three years.", tags: ["general", "travel"], grammar: "Vivió → había vivido (preterite backshifts to pluperfect)." },
  { target: "Me pidió que le ayudara con la mudanza.", english: "She asked me to help her with the move.", tags: ["general"] },
  { target: "Según él, el proyecto estaría listo para el viernes.", english: "According to him, the project would be ready by Friday.", tags: ["general", "work"] },
  { target: "Le explicó que no había podido terminar a tiempo.", english: "He explained to her that he hadn't been able to finish on time.", tags: ["general", "work"] },
  { target: "Me aseguró que todo estaba bajo control.", english: "He assured me that everything was under control.", tags: ["general", "work"] },
  { target: "Preguntó cuándo habíamos llegado.", english: "He asked when we had arrived.", tags: ["general", "travel"] },
  { target: "Le respondí que aún no habíamos decidido.", english: "I replied that we hadn't decided yet.", tags: ["general"] },
  { target: "Comentó que su madre había estado enferma esa semana.", english: "He mentioned that his mother had been sick that week.", tags: ["general", "family"] },
  { target: "Me advirtió que tuviera cuidado con el hielo.", english: "He warned me to be careful with the ice.", tags: ["general", "travel"], grammar: "Advirtió que + subjunctive for indirect commands/warnings." },
  { target: "Dijo que se iba de vacaciones al día siguiente.", english: "She said she was going on vacation the next day.", tags: ["general", "travel"], grammar: "'Mañana' becomes 'al día siguiente' in reported speech." },
  { target: "Me prometió que no volvería a llegar tarde.", english: "He promised me he wouldn't be late again.", tags: ["general", "work"] },
  { target: "Le informaron de que su vuelo había sido cancelado.", english: "They informed her that her flight had been cancelled.", tags: ["general", "travel"] },
  { target: "Reconoció que se había equivocado.", english: "He admitted he had been wrong.", tags: ["general"] },
  { target: "Me sugirió que tomara el tren en vez del autobús.", english: "He suggested I take the train instead of the bus.", tags: ["general", "travel"] },
  { target: "Según la profesora, el examen sería más difícil que el anterior.", english: "According to the teacher, the exam would be harder than the previous one.", tags: ["general"] },
  { target: "Afirmó que nunca había visto algo así.", english: "He stated he had never seen anything like that.", tags: ["general"] },
  { target: "Me recordó que tenía que entregar el informe esa semana.", english: "She reminded me I had to submit the report that week.", tags: ["general", "work"], grammar: "'Esta semana' becomes 'esa semana' in reported speech (demonstrative shift)." },
  { target: "Le pregunté si había estado alguna vez en Sudamérica.", english: "I asked him if he had ever been to South America.", tags: ["general", "travel"] },
  { target: "Insistió en que nos quedáramos a cenar.", english: "She insisted we stay for dinner.", tags: ["general", "family"] },
  { target: "Dijeron que el problema se resolvería en unos días.", english: "They said the problem would be resolved in a few days.", tags: ["general", "work"] },
  { target: "Me confesó que siempre había querido ser músico.", english: "He confessed to me that he had always wanted to be a musician.", tags: ["general"] },
  { target: "Nos comunicaron que las oficinas cerrarían a las tres.", english: "They informed us that the offices would close at three.", tags: ["general", "work"] },
  { target: "Le pregunté por qué no había venido a la reunión.", english: "I asked him why he hadn't come to the meeting.", tags: ["general", "work"] },
  { target: "Me contó que de pequeño quería ser astronauta.", english: "He told me that as a child he wanted to be an astronaut.", tags: ["general", "family"] },
  { target: "Según los vecinos, el ruido venía del tercer piso.", english: "According to the neighbors, the noise was coming from the third floor.", tags: ["general"] },
  { target: "Le rogó que no le abandonara.", english: "He begged her not to leave him.", tags: ["general"] },
  { target: "Mencionó que su hermana acababa de tener un bebé.", english: "She mentioned that her sister had just had a baby.", tags: ["general", "family"] },
  { target: "Me explicaron que el proceso tardaría varios meses.", english: "They explained to me that the process would take several months.", tags: ["general", "work"] },
  { target: "Preguntó si podíamos enviarle los documentos por correo.", english: "He asked if we could send him the documents by email.", tags: ["general", "work"] },
  { target: "Nos avisó de que habría retrasos en el servicio.", english: "He warned us there would be delays in the service.", tags: ["general", "travel"] },
  { target: "Dijo que lo pensaría y me daría una respuesta.", english: "She said she would think about it and give me an answer.", tags: ["general"] },
  { target: "Según mis padres, antes aquí todo era campo.", english: "According to my parents, before, all this was countryside.", tags: ["general", "family"] },
  { target: "Le exigieron que presentara los documentos de inmediato.", english: "They demanded he present the documents immediately.", tags: ["general", "work"] },
  { target: "Me aseguró que el paquete llegaría antes del viernes.", english: "He assured me the package would arrive before Friday.", tags: ["general"] },
  { target: "Comentaron que la obra del teatro había sido magnífica.", english: "They commented that the theater play had been magnificent.", tags: ["general"] },
  { target: "Negó que hubiera tenido algo que ver con el problema.", english: "He denied having had anything to do with the problem.", tags: ["general", "work"] },
  { target: "Me recomendó que leyera ese libro cuanto antes.", english: "She recommended I read that book as soon as possible.", tags: ["general"] },
  { target: "Según el periódico, la economía mejoraría el próximo trimestre.", english: "According to the newspaper, the economy would improve next quarter.", tags: ["general", "work"] },
  { target: "Le conté que había estado pensando en cambiar de carrera.", english: "I told her I had been thinking about changing careers.", tags: ["general", "work"] },
  { target: "Me preguntaron si sabía dónde estaba la estación.", english: "They asked me if I knew where the station was.", tags: ["general", "travel"] },
  { target: "Nos dijeron que la cena estaría lista en media hora.", english: "They told us dinner would be ready in half an hour.", tags: ["general", "family"] },
  { target: "Juró que no había tocado nada.", english: "He swore he hadn't touched anything.", tags: ["general"] },
  { target: "Según el médico, debería descansar al menos una semana.", english: "According to the doctor, he should rest for at least a week.", tags: ["general"] },
  { target: "Me dijo que aquella había sido la mejor decisión de su vida.", english: "She told me that had been the best decision of her life.", tags: ["general"], grammar: "'Esa/esta' becomes 'aquella' in reported speech (distal demonstrative)." },
  { target: "Le informé de que su solicitud había sido aprobada.", english: "I informed him that his application had been approved.", tags: ["general", "work"] },
  { target: "Aseguró que no sabía nada del asunto.", english: "He assured that he knew nothing about the matter.", tags: ["general"] },
  { target: "Me reprochó que no le hubiera llamado antes.", english: "She reproached me for not having called her sooner.", tags: ["general", "family"] },
]);

console.log(`After C1 nodes: total added ${added} (${dupes} dupes)`);

// ═══════════════════════════════════════════════════════════════
// C2 NODES 24-26 (~100 cards each = ~300 total)
// ═══════════════════════════════════════════════════════════════

// NODE 24: Register & Style
addCards([
  { target: "Cabe destacar que los resultados superaron las expectativas.", english: "It is worth noting that the results exceeded expectations.", tags: ["general", "work"], grammar: "Cabe + infinitive = it is fitting/possible to (formal register)." },
  { target: "De haber sabido las consecuencias, no habría aceptado.", english: "Had I known the consequences, I would not have accepted.", tags: ["general"], grammar: "De haber + participle = formal alternative to si hubiera + participle." },
  { target: "Habrá salido ya; siempre se va a esta hora.", english: "He must have left already; he always leaves at this time.", tags: ["general", "work"], grammar: "Future tense for probability/conjecture about the present." },
  { target: "En virtud de lo expuesto, se solicita la aprobación del proyecto.", english: "By virtue of the foregoing, approval of the project is requested.", tags: ["general", "work"] },
  { target: "Dicho esto, pasemos al siguiente punto del orden del día.", english: "That said, let's move on to the next item on the agenda.", tags: ["general", "work"] },
  { target: "Habría unos doscientos invitados en la ceremonia.", english: "There must have been about two hundred guests at the ceremony.", tags: ["general"], grammar: "Conditional for conjecture about the past." },
  { target: "No bien hubo terminado de hablar, estalló un aplauso.", english: "No sooner had he finished speaking than applause broke out.", tags: ["general"], grammar: "Hubo + participle = pretérito anterior, very formal/literary." },
  { target: "Cabe señalar que esta medida beneficiará a miles de personas.", english: "It should be noted that this measure will benefit thousands of people.", tags: ["general", "work"] },
  { target: "Será mejor que nos vayamos antes de que oscurezca.", english: "It'll be better for us to leave before it gets dark.", tags: ["general", "travel"] },
  { target: "En lo que respecta a la financiación, aún hay cuestiones pendientes.", english: "With regard to financing, there are still outstanding issues.", tags: ["general", "work"] },
  { target: "De no ser por su intervención, el acuerdo habría fracasado.", english: "Were it not for his intervention, the agreement would have failed.", tags: ["general", "work"] },
  { target: "Serán las cinco de la tarde, más o menos.", english: "It must be about five in the afternoon.", tags: ["general"] },
  { target: "A tenor de los resultados, cabe esperar mejoras significativas.", english: "In light of the results, significant improvements can be expected.", tags: ["general", "work"] },
  { target: "Hubo de reconocer que su posición era insostenible.", english: "He had to acknowledge that his position was unsustainable.", tags: ["general"] },
  { target: "En lo sucesivo, las solicitudes deberán presentarse por escrito.", english: "Henceforth, applications must be submitted in writing.", tags: ["general", "work"] },
  { target: "¿Quién será a estas horas? Habrá pasado algo.", english: "Who could it be at this hour? Something must have happened.", tags: ["general"] },
  { target: "Cabe la posibilidad de que el evento se celebre al aire libre.", english: "There is a possibility that the event will be held outdoors.", tags: ["general"] },
  { target: "De haberse enterado antes, habríamos actuado de otra manera.", english: "Had we found out earlier, we would have acted differently.", tags: ["general", "work"] },
  { target: "En aras de la transparencia, publicaremos todos los datos.", english: "In the interest of transparency, we will publish all the data.", tags: ["general", "work"] },
  { target: "Tendría unos treinta años cuando empezó la empresa.", english: "He must have been about thirty when he started the company.", tags: ["general", "work"] },
  { target: "Huelga decir que su contribución fue fundamental.", english: "Needless to say, his contribution was fundamental.", tags: ["general", "work"], grammar: "Huelga decir que = needless to say (very formal register)." },
  { target: "De no mediar circunstancias excepcionales, el plazo es inamovible.", english: "Barring exceptional circumstances, the deadline is firm.", tags: ["general", "work"] },
  { target: "En lo tocante a la seguridad, se han tomado todas las medidas necesarias.", english: "Regarding safety, all necessary measures have been taken.", tags: ["general", "work"] },
  { target: "Habrán sido las tres cuando llegamos al pueblo.", english: "It must have been about three when we arrived at the town.", tags: ["general", "travel"] },
  { target: "Cabe preguntarse si esta política es realmente efectiva.", english: "One might ask whether this policy is truly effective.", tags: ["general"] },
  { target: "De haberlo pensado mejor, no habría firmado el contrato.", english: "Had I thought it over more carefully, I wouldn't have signed the contract.", tags: ["general", "work"] },
  { target: "A mi juicio, la propuesta carece de fundamento.", english: "In my judgment, the proposal lacks foundation.", tags: ["general", "work"] },
  { target: "Estará cansado después de un viaje tan largo.", english: "He must be tired after such a long trip.", tags: ["general", "travel"] },
  { target: "Conviene recordar que las normas son de obligado cumplimiento.", english: "It is worth remembering that the rules are mandatory.", tags: ["general", "work"] },
  { target: "De no resolverse pronto, el conflicto podría agravarse.", english: "If not resolved soon, the conflict could worsen.", tags: ["general"] },
  { target: "En resumidas cuentas, la inversión resultó rentable.", english: "In short, the investment turned out to be profitable.", tags: ["general", "work"] },
  { target: "No habrá dormido nada con tanto ruido.", english: "He can't have slept at all with so much noise.", tags: ["general"] },
  { target: "A la luz de estos datos, debemos reconsiderar nuestra estrategia.", english: "In light of this data, we must reconsider our strategy.", tags: ["general", "work"] },
  { target: "Una vez hubo concluido la ceremonia, los invitados pasaron al salón.", english: "Once the ceremony had concluded, the guests moved to the hall.", tags: ["general"] },
  { target: "Procede, pues, analizar las causas del problema.", english: "It is therefore appropriate to analyze the causes of the problem.", tags: ["general", "work"] },
  { target: "Habría unas cincuenta personas en la sala.", english: "There must have been about fifty people in the room.", tags: ["general"] },
  { target: "Con arreglo a la normativa vigente, se procederá al archivo del expediente.", english: "In accordance with current regulations, the file will be archived.", tags: ["general", "work"] },
  { target: "De no haber mediado su intervención, las consecuencias habrían sido graves.", english: "Had he not intervened, the consequences would have been serious.", tags: ["general"] },
  { target: "Valga como ejemplo el caso de las energías renovables.", english: "The case of renewable energy serves as an example.", tags: ["general"] },
  { target: "Dado el contexto actual, conviene actuar con prudencia.", english: "Given the current context, it is advisable to act with caution.", tags: ["general", "work"] },
]);

// NODE 25: Idiomatic Fluency
addCards([
  { target: "No hay mal que por bien no venga.", english: "Every cloud has a silver lining.", tags: ["general"], grammar: "Spanish proverb using double negative + subjunctive." },
  { target: "Me costó un ojo de la cara.", english: "It cost me an arm and a leg.", tags: ["general"] },
  { target: "Está lloviendo a cántaros.", english: "It's raining cats and dogs.", tags: ["general", "travel"] },
  { target: "No me vengas con esas; dime la verdad.", english: "Don't give me that; tell me the truth.", tags: ["general", "family"] },
  { target: "Más vale tarde que nunca.", english: "Better late than never.", tags: ["general"] },
  { target: "Meter la pata es algo que todos hacemos de vez en cuando.", english: "Putting your foot in it is something we all do from time to time.", tags: ["general"], grammar: "Meter la pata = to put one's foot in it (make a blunder)." },
  { target: "Ese trabajo me tiene hasta las narices.", english: "That job has me fed up to here.", tags: ["general", "work"] },
  { target: "En boca cerrada no entran moscas.", english: "Silence is golden. (Literally: Flies don't enter a closed mouth.)", tags: ["general"] },
  { target: "No le des más vueltas; ya está decidido.", english: "Don't overthink it; it's already decided.", tags: ["general", "work"] },
  { target: "Le echó una mano con las maletas.", english: "He gave him a hand with the suitcases.", tags: ["general", "travel"] },
  { target: "Quien mucho abarca, poco aprieta.", english: "Jack of all trades, master of none.", tags: ["general"] },
  { target: "Se quedó de piedra cuando se enteró de la noticia.", english: "He was dumbfounded when he heard the news.", tags: ["general"] },
  { target: "Eso es pan comido; lo termino en cinco minutos.", english: "That's a piece of cake; I'll finish it in five minutes.", tags: ["general", "work"], grammar: "Pan comido = piece of cake (very easy)." },
  { target: "No te andes con rodeos y dime qué quieres.", english: "Don't beat around the bush and tell me what you want.", tags: ["general"] },
  { target: "Más vale prevenir que curar.", english: "An ounce of prevention is worth a pound of cure.", tags: ["general"] },
  { target: "Tiene mucha mano izquierda para resolver conflictos.", english: "He's very tactful when it comes to resolving conflicts.", tags: ["general", "work"] },
  { target: "No me tomes el pelo; sé que no es verdad.", english: "Don't pull my leg; I know it's not true.", tags: ["general", "family"] },
  { target: "A quien madruga, Dios le ayuda.", english: "The early bird catches the worm.", tags: ["general"] },
  { target: "Me quedé en blanco durante el examen.", english: "My mind went blank during the exam.", tags: ["general"] },
  { target: "Ese negocio fue viento en popa desde el principio.", english: "That business went smoothly from the start.", tags: ["general", "work"], grammar: "Viento en popa = smooth sailing (literally: wind at the stern)." },
  { target: "Ojos que no ven, corazón que no siente.", english: "Out of sight, out of mind.", tags: ["general"] },
  { target: "Estoy entre la espada y la pared.", english: "I'm between a rock and a hard place.", tags: ["general", "work"] },
  { target: "Hablando del rey de Roma, ahí viene Juan.", english: "Speak of the devil, here comes Juan.", tags: ["general"] },
  { target: "Me pilló por sorpresa; no me lo esperaba para nada.", english: "It caught me by surprise; I didn't expect it at all.", tags: ["general"] },
  { target: "Cada maestrillo tiene su librillo.", english: "Everyone has their own way of doing things.", tags: ["general"] },
  { target: "No pierdas la cabeza por una tontería así.", english: "Don't lose your head over something so silly.", tags: ["general", "family"] },
  { target: "Aquí hay gato encerrado; algo no cuadra.", english: "Something fishy is going on; something doesn't add up.", tags: ["general"], grammar: "Hay gato encerrado = something fishy (literally: there's a locked-up cat)." },
  { target: "Después de la tormenta, siempre sale el sol.", english: "After the storm, the sun always comes out.", tags: ["general"] },
  { target: "Me dejó plantado; esperé una hora y no vino.", english: "He stood me up; I waited an hour and he didn't come.", tags: ["general"] },
  { target: "Eso es harina de otro costal; no tiene nada que ver.", english: "That's a different kettle of fish; it has nothing to do with it.", tags: ["general"] },
  { target: "No hay que ahogarse en un vaso de agua.", english: "You shouldn't make a mountain out of a molehill.", tags: ["general"] },
  { target: "Me lo contó con pelos y señales.", english: "He told me in great detail.", tags: ["general"] },
  { target: "Tirar la toalla no es una opción.", english: "Throwing in the towel is not an option.", tags: ["general", "work"] },
  { target: "Dime con quién andas y te diré quién eres.", english: "Tell me who your friends are and I'll tell you who you are.", tags: ["general"] },
  { target: "Me lo pasé bomba en la fiesta de anoche.", english: "I had a blast at last night's party.", tags: ["general"] },
  { target: "No muerdas la mano que te da de comer.", english: "Don't bite the hand that feeds you.", tags: ["general", "work"] },
  { target: "Le puso los puntos sobre las íes al nuevo empleado.", english: "She set things straight with the new employee.", tags: ["general", "work"] },
  { target: "Ir al grano es lo mejor en una reunión de trabajo.", english: "Getting to the point is best in a work meeting.", tags: ["general", "work"], grammar: "Ir al grano = to get to the point." },
  { target: "Ese chiquillo es un terremoto; no para ni un segundo.", english: "That little kid is a whirlwind; he doesn't stop for a second.", tags: ["general", "family"] },
  { target: "Se le fue la lengua y contó el secreto.", english: "He let it slip and told the secret.", tags: ["general"] },
  { target: "Tener un as bajo la manga siempre es útil.", english: "Having an ace up your sleeve is always useful.", tags: ["general", "work"] },
  { target: "No todo lo que brilla es oro.", english: "All that glitters is not gold.", tags: ["general"] },
  { target: "Se lo tomó a pecho y se enfadó muchísimo.", english: "He took it to heart and got very angry.", tags: ["general"] },
  { target: "Le dieron gato por liebre en esa tienda.", english: "They ripped him off at that store.", tags: ["general"], grammar: "Dar gato por liebre = to deceive/rip off (pass cat for hare)." },
  { target: "Cuando el río suena, agua lleva.", english: "Where there's smoke, there's fire.", tags: ["general"] },
  { target: "Tuve que morder la lengua para no decir lo que pensaba.", english: "I had to bite my tongue to not say what I was thinking.", tags: ["general", "work"] },
  { target: "Es un buen tipo, pero a veces se pasa de la raya.", english: "He's a good guy, but sometimes he goes too far.", tags: ["general"] },
  { target: "Me tienes en ascuas; dime qué pasó.", english: "You're keeping me in suspense; tell me what happened.", tags: ["general"] },
  { target: "Al mal tiempo, buena cara.", english: "Keep a stiff upper lip. (Literally: To bad weather, a good face.)", tags: ["general"] },
  { target: "Lo siento, metí la pata; no debí haber dicho eso.", english: "I'm sorry, I put my foot in it; I shouldn't have said that.", tags: ["general", "family"] },
]);

// NODE 26: Complex Syntax
addCards([
  { target: "Terminada la reunión, todos se dirigieron a la salida.", english: "Once the meeting was over, everyone headed for the exit.", tags: ["general", "work"], grammar: "Absolute participial clause: participle + noun = 'once X was done'." },
  { target: "Lo que resulta difícil de entender es por qué nadie dijo nada antes.", english: "What is hard to understand is why nobody said anything before.", tags: ["general", "work"] },
  { target: "El que no haya presentado la documentación antes del plazo establecido quedará excluido del proceso.", english: "Whoever has not submitted the documentation before the established deadline will be excluded from the process.", tags: ["general", "work"] },
  { target: "Resueltos los problemas técnicos, se procedió a la inauguración del sistema.", english: "Once the technical problems were resolved, the system inauguration proceeded.", tags: ["general", "work"] },
  { target: "Considerando que los plazos son ajustados, convendría empezar cuanto antes.", english: "Considering that the deadlines are tight, it would be advisable to start as soon as possible.", tags: ["general", "work"] },
  { target: "El haber vivido en varios países le dio una perspectiva única.", english: "Having lived in several countries gave him a unique perspective.", tags: ["general", "travel"], grammar: "Nominalized infinitive: el + infinitive functions as a noun (subject)." },
  { target: "Abierta la convocatoria, los candidatos disponen de treinta días para presentar su solicitud.", english: "With the call for applications open, candidates have thirty days to submit their application.", tags: ["general", "work"] },
  { target: "No es sino trabajando todos juntos como lograremos superar esta crisis.", english: "It is only by working all together that we will manage to overcome this crisis.", tags: ["general", "work"], grammar: "No es sino + gerund + como = it is only by... that (emphatic cleft)." },
  { target: "Vistas las circunstancias, la dirección ha decidido aplazar el proyecto.", english: "Given the circumstances, management has decided to postpone the project.", tags: ["general", "work"] },
  { target: "Lo difícil no es empezar, sino mantener la constancia a lo largo del tiempo.", english: "The hard part isn't starting, but maintaining consistency over time.", tags: ["general"] },
  { target: "Cuantos más obstáculos encontraba, más decidido estaba a conseguirlo.", english: "The more obstacles he encountered, the more determined he was to achieve it.", tags: ["general"] },
  { target: "Dicho lo cual, paso a presentar las conclusiones del estudio.", english: "That being said, I will now present the conclusions of the study.", tags: ["general", "work"] },
  { target: "El que quiera entender la situación actual deberá remontarse a los orígenes del conflicto.", english: "Anyone who wants to understand the current situation will have to go back to the origins of the conflict.", tags: ["general"] },
  { target: "Llegados a este punto, no queda más remedio que tomar una decisión drástica.", english: "Having reached this point, there's no choice but to make a drastic decision.", tags: ["general", "work"], grammar: "Llegados a este punto = absolute participial, 'having reached this point'." },
  { target: "No solo resulta costoso, sino que, además, requiere una infraestructura de la que carecemos.", english: "Not only is it costly, but it also requires infrastructure that we lack.", tags: ["general", "work"] },
  { target: "Supuesto que todo vaya según lo previsto, la entrega se realizará en junio.", english: "Assuming everything goes as planned, delivery will take place in June.", tags: ["general", "work"] },
  { target: "Lo cierto es que, pese a los esfuerzos realizados, los resultados han sido insuficientes.", english: "The truth is that, despite the efforts made, the results have been insufficient.", tags: ["general", "work"] },
  { target: "Cumplidos los requisitos, se procederá a la evaluación de las candidaturas.", english: "Once the requirements are met, the evaluation of candidacies will proceed.", tags: ["general", "work"] },
  { target: "No es tanto el qué se dice como el cómo se dice.", english: "It's not so much what is said as how it is said.", tags: ["general"] },
  { target: "El vivir lejos de la familia es algo a lo que nunca me he acostumbrado.", english: "Living far from family is something I've never gotten used to.", tags: ["general", "family"] },
  { target: "Hechas las presentaciones, comenzó la negociación.", english: "Once the introductions were made, the negotiation began.", tags: ["general", "work"] },
  { target: "Es precisamente por eso por lo que debemos actuar con cautela.", english: "That is precisely why we must act with caution.", tags: ["general", "work"], grammar: "Es por eso por lo que = it's because of that that (cleft sentence)." },
  { target: "Habiendo analizado todas las opciones, concluimos que la primera era la más viable.", english: "Having analyzed all the options, we concluded that the first was the most viable.", tags: ["general", "work"] },
  { target: "Sea cual sea el resultado, lo importante es haberlo intentado.", english: "Whatever the result may be, the important thing is having tried.", tags: ["general"] },
  { target: "El no haber previsto este escenario nos ha puesto en una situación complicada.", english: "Not having foreseen this scenario has put us in a complicated situation.", tags: ["general", "work"] },
  { target: "Sentados a la mesa, repasaron uno por uno los puntos del acuerdo.", english: "Seated at the table, they reviewed the points of the agreement one by one.", tags: ["general", "work"] },
  { target: "Lo que en un principio parecía sencillo resultó ser mucho más complicado de lo esperado.", english: "What initially seemed simple turned out to be much more complicated than expected.", tags: ["general", "work"] },
  { target: "Es mediante la educación como se transforman las sociedades.", english: "It is through education that societies are transformed.", tags: ["general"] },
  { target: "Cuanto mayor es la responsabilidad, mayor es la presión.", english: "The greater the responsibility, the greater the pressure.", tags: ["general", "work"] },
  { target: "Analizada la situación, se optó por una estrategia más conservadora.", english: "Once the situation was analyzed, a more conservative strategy was chosen.", tags: ["general", "work"] },
  { target: "Lo realmente preocupante no es el problema en sí, sino la falta de respuesta.", english: "What is truly worrying is not the problem itself, but the lack of response.", tags: ["general"] },
  { target: "Es solo cuando pierdes algo cuando te das cuenta de su valor.", english: "It is only when you lose something that you realize its value.", tags: ["general"] },
  { target: "Agotadas todas las vías de negociación, recurrieron a los tribunales.", english: "Having exhausted all avenues of negotiation, they turned to the courts.", tags: ["general", "work"] },
  { target: "El saber escuchar es tan importante como el saber hablar.", english: "Knowing how to listen is as important as knowing how to speak.", tags: ["general"] },
  { target: "Puesto en contexto, el comentario no resultaba tan ofensivo.", english: "Put in context, the comment wasn't so offensive.", tags: ["general"] },
  { target: "No fue hasta que se lo explicaron tres veces que lo entendió.", english: "It wasn't until they explained it to him three times that he understood.", tags: ["general"] },
  { target: "Cuantas más personas participen, más enriquecedor será el debate.", english: "The more people participate, the more enriching the debate will be.", tags: ["general", "work"] },
  { target: "Concluida la fase de pruebas, el producto se lanzará al mercado.", english: "Once the testing phase is concluded, the product will be launched on the market.", tags: ["general", "work"] },
  { target: "Lo paradójico del asunto es que quienes más se quejan son quienes menos trabajan.", english: "The paradox of the matter is that those who complain the most are those who work the least.", tags: ["general", "work"] },
  { target: "Fue en aquel preciso instante cuando comprendí que todo había cambiado.", english: "It was at that precise moment that I understood everything had changed.", tags: ["general"] },
]);

// ═══════════════════════════════════════════════════════════════
// SUMMARY
// ═══════════════════════════════════════════════════════════════

console.log(`\nTotal new cards added: ${added}`);
console.log(`Duplicates skipped: ${dupes}`);
console.log(`New deck size: ${deck.length}`);

// Write updated deck
fs.writeFileSync(DECK_PATH, JSON.stringify(deck, null, 2) + '\n');
console.log(`\nDeck saved to ${DECK_PATH}`);

// Distribution summary
const dist = {};
for (const c of deck) {
  const node = c.grammarNode || 'unassigned';
  dist[node] = (dist[node] || 0) + 1;
}
console.log('\nDistribution by grammarNode:');
Object.entries(dist).sort().forEach(([k, v]) => console.log(`  ${k}: ${v}`));
