/**
 * fill-family.cjs
 *
 * Add ~430 NEW Spanish family-tagged flashcards to the deck.
 * All cards are genuinely about family life, home, and relationships.
 *
 * Distribution across grammar levels (roughly equal):
 *   ~108 A1: Simple present, ser/estar, basic questions, articles
 *   ~108 A2: Past tenses, reflexives, object pronouns, por/para
 *   ~108 B1: Subjunctive, future, conditional, commands, relative clauses
 *   ~108 B2: Imperfect subjunctive, conditionals II/III, passive, advanced connectors
 *
 * Every card: { target, english, tags: ["general", "family"] }
 * ~15% include a grammar field.
 */

const fs = require('fs');
const path = require('path');

const DECK_PATH = path.join(__dirname, '..', 'src', 'data', 'spanish', 'deck.json');
const deck = JSON.parse(fs.readFileSync(DECK_PATH, 'utf-8'));

console.log(`Current deck: ${deck.length} cards`);

// Track existing sentences to avoid duplicates
const existingTargets = new Set(deck.map(c => c.target.toLowerCase().trim()));

// ─── NEW FAMILY CARDS ──────────────────────────────────────────

const T = ["general", "family"];

const newCards = [

  // ═══════════════════════════════════════════════════════════════
  // A1 — Simple present, ser/estar, basic questions, articles (~108)
  // ═══════════════════════════════════════════════════════════════
  { target: "Mi madre cocina muy bien.", english: "My mother cooks very well.", tags: T },
  { target: "¿Cuántos hermanos tienes?", english: "How many siblings do you have?", tags: T, grammar: "¿Cuántos? = how many? Agrees in gender: cuántos/cuántas" },
  { target: "Tengo dos hermanas y un hermano.", english: "I have two sisters and one brother.", tags: T },
  { target: "Mi padre trabaja mucho.", english: "My father works a lot.", tags: T },
  { target: "La casa de mis padres es grande.", english: "My parents' house is big.", tags: T },
  { target: "Mi abuela vive cerca de nosotros.", english: "My grandmother lives close to us.", tags: T },
  { target: "¿Cómo se llama tu hermana?", english: "What is your sister's name?", tags: T },
  { target: "Los domingos comemos en familia.", english: "On Sundays we eat as a family.", tags: T, grammar: "Los domingos = on Sundays (definite article + day = habitual)" },
  { target: "Mi hijo tiene tres años.", english: "My son is three years old.", tags: T, grammar: "Tener + años = to be X years old (Spanish uses 'have' not 'be')" },
  { target: "La cocina está limpia.", english: "The kitchen is clean.", tags: T },
  { target: "Mi hermano es más alto que yo.", english: "My brother is taller than me.", tags: T },
  { target: "Hay juguetes en el suelo.", english: "There are toys on the floor.", tags: T, grammar: "Hay = there is/there are (invariable, same for singular and plural)" },
  { target: "¿Dónde están las llaves de casa?", english: "Where are the house keys?", tags: T },
  { target: "Mi tía tiene un gato muy gordo.", english: "My aunt has a very fat cat.", tags: T },
  { target: "El bebé duerme en su cuna.", english: "The baby sleeps in his crib.", tags: T, grammar: "Dormir: stem-changing verb (o→ue): duermo, duermes, duerme" },
  { target: "Mis primos viven en otra ciudad.", english: "My cousins live in another city.", tags: T },
  { target: "La cena está lista.", english: "Dinner is ready.", tags: T, grammar: "Estar for temporary states/results: la cena está lista (it's ready now)" },
  { target: "Mi abuelo lee el periódico por la mañana.", english: "My grandfather reads the newspaper in the morning.", tags: T },
  { target: "Necesitamos leche y pan.", english: "We need milk and bread.", tags: T },
  { target: "¿Quién hace la compra en tu casa?", english: "Who does the grocery shopping at your house?", tags: T },
  { target: "El perro quiere salir al jardín.", english: "The dog wants to go out to the garden.", tags: T },
  { target: "Mi hija juega con sus muñecas.", english: "My daughter plays with her dolls.", tags: T },
  { target: "Vivimos en un piso pequeño.", english: "We live in a small apartment.", tags: T, grammar: "Piso = apartment (Spain). In Latin America: departamento or apartamento" },
  { target: "¿Tu familia es grande o pequeña?", english: "Is your family big or small?", tags: T },
  { target: "Mi madre es profesora.", english: "My mother is a teacher.", tags: T, grammar: "Ser for professions: soy/es + profession (no article needed)" },
  { target: "El gato está encima de la mesa.", english: "The cat is on top of the table.", tags: T },
  { target: "Mi hermana tiene un bebé.", english: "My sister has a baby.", tags: T },
  { target: "Cenamos a las nueve.", english: "We have dinner at nine.", tags: T },
  { target: "¿Hay leche en la nevera?", english: "Is there milk in the fridge?", tags: T },
  { target: "Los niños ven la tele después de cenar.", english: "The kids watch TV after dinner.", tags: T },
  { target: "Mi familia es muy unida.", english: "My family is very close.", tags: T },
  { target: "El cuarto de los niños es azul.", english: "The kids' room is blue.", tags: T },
  { target: "Mi padre tiene cincuenta años.", english: "My father is fifty years old.", tags: T },
  { target: "¿A qué hora desayunáis?", english: "What time do you all have breakfast?", tags: T, grammar: "Vosotros form: desayunáis. Used in Spain; Latin America uses ustedes (desayunan)" },
  { target: "Mi hermano juega al fútbol los sábados.", english: "My brother plays soccer on Saturdays.", tags: T },
  { target: "La abuela hace galletas riquísimas.", english: "Grandma makes delicious cookies.", tags: T },
  { target: "Mi tío tiene una casa en el campo.", english: "My uncle has a house in the countryside.", tags: T },
  { target: "Los niños comen mucha fruta.", english: "The kids eat a lot of fruit.", tags: T },
  { target: "Mi primo es muy gracioso.", english: "My cousin is very funny.", tags: T },
  { target: "¿Cuántos años tiene tu hija?", english: "How old is your daughter?", tags: T },
  { target: "Mi marido llega tarde del trabajo.", english: "My husband arrives late from work.", tags: T },
  { target: "Hay ropa en la lavadora.", english: "There are clothes in the washing machine.", tags: T },
  { target: "El salón es la habitación más grande.", english: "The living room is the biggest room.", tags: T },
  { target: "Mi sobrina empieza el colegio este año.", english: "My niece starts school this year.", tags: T },
  { target: "¿Vives con tus padres?", english: "Do you live with your parents?", tags: T, grammar: "Tus = your (informal plural possessive). Compare: tu padre, tus padres" },
  { target: "Mi suegra cocina arroz con pollo.", english: "My mother-in-law cooks rice with chicken.", tags: T },
  { target: "El baño está al final del pasillo.", english: "The bathroom is at the end of the hallway.", tags: T },
  { target: "Mi cuñada vive en el mismo barrio.", english: "My sister-in-law lives in the same neighborhood.", tags: T },
  { target: "Los fines de semana descansamos en casa.", english: "On weekends we rest at home.", tags: T },
  { target: "Mi perro se llama Lucas.", english: "My dog's name is Lucas.", tags: T },
  { target: "¿Tienes mascota?", english: "Do you have a pet?", tags: T },
  { target: "El abuelo toma café con leche.", english: "Grandpa drinks coffee with milk.", tags: T },
  { target: "Mi hermana menor es muy tímida.", english: "My younger sister is very shy.", tags: T },
  { target: "Desayunamos juntos todos los días.", english: "We have breakfast together every day.", tags: T },
  { target: "La casa tiene tres habitaciones.", english: "The house has three bedrooms.", tags: T },
  { target: "Mi madre es la mejor cocinera.", english: "My mother is the best cook.", tags: T },
  { target: "¿Quién recoge a los niños del colegio?", english: "Who picks up the kids from school?", tags: T },
  { target: "Mi familia cena junta los viernes.", english: "My family has dinner together on Fridays.", tags: T },
  { target: "El bebé tiene hambre.", english: "The baby is hungry.", tags: T, grammar: "Tener hambre = to be hungry (literally 'to have hunger')" },
  { target: "Mi padre es muy cariñoso.", english: "My father is very affectionate.", tags: T },
  { target: "Hay un parque cerca de casa.", english: "There is a park near home.", tags: T },
  { target: "¿Cuántos hijos tienes?", english: "How many children do you have?", tags: T },
  { target: "Mi hermano come de todo.", english: "My brother eats everything.", tags: T },
  { target: "La casa huele a comida.", english: "The house smells like food.", tags: T, grammar: "Oler: stem-changing (o→hue): huelo, hueles, huele (adds h before ue)" },
  { target: "Mi abuela tiene un huerto.", english: "My grandmother has a vegetable garden.", tags: T },
  { target: "Los vecinos son muy simpáticos.", english: "The neighbors are very friendly.", tags: T },
  { target: "¿Cómo está tu madre?", english: "How is your mother?", tags: T },
  { target: "Mi padre siempre llega a las siete.", english: "My father always arrives at seven.", tags: T },
  { target: "Hay fotos de la familia en la pared.", english: "There are family photos on the wall.", tags: T },
  { target: "Mi hermana estudia en la universidad.", english: "My sister studies at university.", tags: T },
  { target: "Nuestra casa tiene un balcón pequeño.", english: "Our house has a small balcony.", tags: T },
  { target: "El gato come tres veces al día.", english: "The cat eats three times a day.", tags: T },
  { target: "Mi sobrino aprende a leer.", english: "My nephew is learning to read.", tags: T },
  { target: "¿Qué cenamos hoy?", english: "What are we having for dinner today?", tags: T },
  { target: "Mi abuelo camina por el parque todas las tardes.", english: "My grandfather walks in the park every afternoon.", tags: T },
  { target: "La lavadora no funciona.", english: "The washing machine doesn't work.", tags: T },
  { target: "Mi hijo dibuja muy bien.", english: "My son draws very well.", tags: T },
  { target: "Vivimos en una casa con jardín.", english: "We live in a house with a garden.", tags: T },
  { target: "Mi tía habla mucho por teléfono.", english: "My aunt talks a lot on the phone.", tags: T },
  { target: "¿Es tu padre español?", english: "Is your father Spanish?", tags: T, grammar: "Ser for nationality and origin: Es español, es francesa" },
  { target: "El niño no quiere comer verdura.", english: "The boy doesn't want to eat vegetables.", tags: T },
  { target: "Mi hermano mayor tiene treinta años.", english: "My older brother is thirty years old.", tags: T },
  { target: "¿Dónde están los niños?", english: "Where are the kids?", tags: T },
  { target: "La terraza es perfecta para cenar en verano.", english: "The terrace is perfect for dinner in summer.", tags: T },
  { target: "Mi mujer prepara el almuerzo.", english: "My wife prepares lunch.", tags: T },
  { target: "El perro ladra cuando alguien llega.", english: "The dog barks when someone arrives.", tags: T, grammar: "Cuando + present indicative for habitual actions (not subjunctive)" },
  { target: "Mi hijo necesita zapatos nuevos.", english: "My son needs new shoes.", tags: T },
  { target: "¿Tu abuela vive sola?", english: "Does your grandmother live alone?", tags: T },
  { target: "La habitación del bebé es muy pequeña.", english: "The baby's room is very small.", tags: T },
  { target: "Mi familia vive en Madrid.", english: "My family lives in Madrid.", tags: T },
  { target: "Tengo una hija y dos hijos.", english: "I have one daughter and two sons.", tags: T },
  { target: "El abuelo cuenta chistes muy buenos.", english: "Grandpa tells very good jokes.", tags: T },
  { target: "La ropa está en el armario.", english: "The clothes are in the closet.", tags: T },
  { target: "¿Quién pasea al perro?", english: "Who walks the dog?", tags: T },
  { target: "Mi prima viene a cenar esta noche.", english: "My cousin is coming for dinner tonight.", tags: T },
  { target: "Los platos están en el fregadero.", english: "The dishes are in the sink.", tags: T },
  { target: "Mi padre sabe arreglar todo.", english: "My father knows how to fix everything.", tags: T },
  { target: "¿Tienes hermanos mayores?", english: "Do you have older siblings?", tags: T },
  { target: "El niño tiene sueño.", english: "The boy is sleepy.", tags: T, grammar: "Tener sueño = to be sleepy (literally 'to have sleep')" },
  { target: "Mi madre riega las plantas por la mañana.", english: "My mother waters the plants in the morning.", tags: T },
  { target: "Mi suegro es muy generoso.", english: "My father-in-law is very generous.", tags: T },
  { target: "La cuna está junto a nuestra cama.", english: "The crib is next to our bed.", tags: T },
  { target: "Mi hermana y yo compartimos habitación.", english: "My sister and I share a room.", tags: T },
  { target: "Comemos pasta los miércoles.", english: "We eat pasta on Wednesdays.", tags: T },
  { target: "¿A qué hora se acuestan los niños?", english: "What time do the kids go to bed?", tags: T },
  { target: "Mi familia es de cuatro personas.", english: "My family is four people.", tags: T },
  { target: "El jardín necesita agua.", english: "The garden needs water.", tags: T },
  { target: "Mi hijo pequeño ya camina.", english: "My little son already walks.", tags: T },

  // ═══════════════════════════════════════════════════════════════
  // A2 — Past tenses, reflexives, object pronouns, por/para (~108)
  // ═══════════════════════════════════════════════════════════════
  { target: "Mi abuela nos visitó el domingo.", english: "My grandmother visited us on Sunday.", tags: T },
  { target: "Los niños se acostaron temprano.", english: "The kids went to bed early.", tags: T, grammar: "Acostarse = reflexive verb: se acostaron (they went to bed)" },
  { target: "Mi madre me llamó por teléfono ayer.", english: "My mother called me on the phone yesterday.", tags: T },
  { target: "Ayer lavé toda la ropa.", english: "Yesterday I washed all the clothes.", tags: T },
  { target: "Los niños se despertaron a las seis.", english: "The kids woke up at six.", tags: T, grammar: "Despertarse = reflexive (to wake up). Preterite: se despertaron" },
  { target: "Mi padre nos llevó al parque.", english: "My father took us to the park.", tags: T },
  { target: "Compré un regalo para mi madre.", english: "I bought a gift for my mother.", tags: T, grammar: "Para = for (intended recipient)" },
  { target: "El bebé se durmió en mis brazos.", english: "The baby fell asleep in my arms.", tags: T },
  { target: "Mi hermana se mudó a Barcelona.", english: "My sister moved to Barcelona.", tags: T },
  { target: "Le di un abrazo a mi abuela.", english: "I gave my grandmother a hug.", tags: T, grammar: "Le = indirect object pronoun (to her). Dar: di (preterite yo form)" },
  { target: "Los niños se bañaron después de jugar.", english: "The kids bathed after playing.", tags: T },
  { target: "Mi tío nos trajo fruta del pueblo.", english: "My uncle brought us fruit from the village.", tags: T },
  { target: "Preparé la cena mientras mi mujer bañaba al bebé.", english: "I made dinner while my wife bathed the baby.", tags: T },
  { target: "Mi hijo se cayó en el parque.", english: "My son fell down in the park.", tags: T },
  { target: "Le leí un cuento antes de dormir.", english: "I read him a story before bed.", tags: T },
  { target: "Mis padres se conocieron en la universidad.", english: "My parents met at university.", tags: T },
  { target: "El abuelo se sentó en su sillón favorito.", english: "Grandpa sat down in his favorite armchair.", tags: T },
  { target: "Le compré flores a mi madre por su cumpleaños.", english: "I bought my mother flowers for her birthday.", tags: T },
  { target: "Mi hermano me ayudó con la mudanza.", english: "My brother helped me with the move.", tags: T },
  { target: "Los niños se vistieron solos esta mañana.", english: "The kids dressed themselves this morning.", tags: T, grammar: "Vestirse = to get dressed (reflexive): se vistieron" },
  { target: "Mi hija se enfadó porque no le dejé ver la tele.", english: "My daughter got angry because I didn't let her watch TV.", tags: T },
  { target: "Pasamos la Navidad en casa de los abuelos.", english: "We spent Christmas at the grandparents' house.", tags: T, grammar: "En casa de = at someone's house (no article needed)" },
  { target: "Mi padre pintó la habitación del bebé.", english: "My father painted the baby's room.", tags: T },
  { target: "Los vecinos nos invitaron a una barbacoa.", english: "The neighbors invited us to a barbecue.", tags: T },
  { target: "Mi hijo perdió su mochila en el colegio.", english: "My son lost his backpack at school.", tags: T },
  { target: "Se me olvidó recoger a los niños.", english: "I forgot to pick up the kids.", tags: T, grammar: "Se me olvidó = it slipped my mind (accidental se construction)" },
  { target: "Le preparé un pastel de chocolate a mi hija.", english: "I made my daughter a chocolate cake.", tags: T },
  { target: "Los niños se pelearon por un juguete.", english: "The kids fought over a toy.", tags: T },
  { target: "Mi abuela nos enseñó a hacer tortilla.", english: "My grandmother taught us how to make tortilla.", tags: T },
  { target: "Me desperté temprano para preparar el desayuno.", english: "I woke up early to make breakfast.", tags: T },
  { target: "Mi hermana se cortó el pelo muy corto.", english: "My sister cut her hair very short.", tags: T },
  { target: "Le conté a mi madre lo que pasó.", english: "I told my mother what happened.", tags: T },
  { target: "Mi padre nos recogió en el aeropuerto.", english: "My father picked us up at the airport.", tags: T, grammar: "Nos = us (direct object pronoun placed before conjugated verb)" },
  { target: "Los niños se divirtieron mucho en la fiesta.", english: "The kids had a lot of fun at the party.", tags: T, grammar: "Divertirse: stem-changing in preterite (e→i): se divirtieron" },
  { target: "Mi tía se casó en junio.", english: "My aunt got married in June.", tags: T },
  { target: "Le regalé un libro a mi hermano.", english: "I gave my brother a book as a gift.", tags: T },
  { target: "El perro se escapó del jardín.", english: "The dog escaped from the garden.", tags: T },
  { target: "Mi madre se levantó muy temprano para cocinar.", english: "My mother got up very early to cook.", tags: T },
  { target: "Le dije a mi hijo que hiciera los deberes.", english: "I told my son to do his homework.", tags: T },
  { target: "Mi hermana me prestó su vestido.", english: "My sister lent me her dress.", tags: T },
  { target: "Los abuelos se quedaron a dormir en casa.", english: "The grandparents stayed to sleep over.", tags: T },
  { target: "Mi primo se rompió el brazo jugando.", english: "My cousin broke his arm playing.", tags: T, grammar: "Romperse = reflexive for body parts: se rompió el brazo" },
  { target: "Hicimos una fiesta para el cumpleaños de papá.", english: "We threw a party for dad's birthday.", tags: T },
  { target: "Mi cuñado nos invitó a cenar.", english: "My brother-in-law invited us to dinner.", tags: T },
  { target: "El bebé se rió por primera vez.", english: "The baby laughed for the first time.", tags: T },
  { target: "Le puse el pijama al niño.", english: "I put the boy's pajamas on.", tags: T },
  { target: "Mi padre se jubiló el año pasado.", english: "My father retired last year.", tags: T, grammar: "Jubilarse = to retire (reflexive): se jubiló" },
  { target: "Los niños se subieron al árbol.", english: "The kids climbed the tree.", tags: T },
  { target: "Mi madre nos hizo sopa porque teníamos frío.", english: "My mother made us soup because we were cold.", tags: T },
  { target: "Le lavé la cara al bebé.", english: "I washed the baby's face.", tags: T },
  { target: "Mi hermano se fue de casa a los veinte años.", english: "My brother left home at twenty.", tags: T },
  { target: "Nos sentamos todos a cenar a las ocho.", english: "We all sat down to dinner at eight.", tags: T },
  { target: "Mi hija se puso el abrigo y salió al jardín.", english: "My daughter put on her coat and went out to the garden.", tags: T },
  { target: "Le canté una canción al bebé para dormirlo.", english: "I sang the baby a song to put him to sleep.", tags: T },
  { target: "Los primos jugaron en el jardín toda la tarde.", english: "The cousins played in the garden all afternoon.", tags: T },
  { target: "Mi abuelo me contó cómo conoció a mi abuela.", english: "My grandfather told me how he met my grandmother.", tags: T },
  { target: "Me acosté tarde porque el niño tenía fiebre.", english: "I went to bed late because the boy had a fever.", tags: T },
  { target: "Le quité los zapatos al niño antes de entrar.", english: "I took the boy's shoes off before going in.", tags: T },
  { target: "Mi madre nos esperaba en la puerta.", english: "My mother was waiting for us at the door.", tags: T },
  { target: "Mi padre se enfadó con nosotros.", english: "My father got angry with us.", tags: T },
  { target: "Los niños se lavaron los dientes antes de dormir.", english: "The kids brushed their teeth before bed.", tags: T },
  { target: "Le peiné el pelo a mi hija.", english: "I combed my daughter's hair.", tags: T },
  { target: "Mi hermana se quedó embarazada.", english: "My sister got pregnant.", tags: T },
  { target: "Celebramos el cumpleaños de mi madre en un restaurante.", english: "We celebrated my mother's birthday at a restaurant.", tags: T },
  { target: "Mi padre me enseñó a montar en bici.", english: "My father taught me to ride a bike.", tags: T },
  { target: "El gato se escondió debajo de la cama.", english: "The cat hid under the bed.", tags: T },
  { target: "Me levanté a las tres porque el bebé lloraba.", english: "I got up at three because the baby was crying.", tags: T },
  { target: "Le compré un helado a mi sobrina.", english: "I bought my niece an ice cream.", tags: T },
  { target: "Los niños se aburrieron en la cena.", english: "The kids got bored at dinner.", tags: T },
  { target: "Mi madre me abrazó al verme.", english: "My mother hugged me when she saw me.", tags: T },
  { target: "Fuimos a buscar un árbol de Navidad.", english: "We went to find a Christmas tree.", tags: T },
  { target: "Mi hermano y yo nos peleábamos de pequeños.", english: "My brother and I used to fight as kids.", tags: T, grammar: "Imperfect for habitual past: nos peleábamos = we used to fight" },
  { target: "Le dejé mi coche a mi cuñado.", english: "I lent my car to my brother-in-law.", tags: T },
  { target: "Mi hija se portó muy bien en la boda.", english: "My daughter behaved very well at the wedding.", tags: T },
  { target: "Los niños hicieron un dibujo para la abuela.", english: "The kids made a drawing for grandma.", tags: T },
  { target: "Mi padre se durmió en el sofá viendo la tele.", english: "My father fell asleep on the couch watching TV.", tags: T },
  { target: "Le traje un peluche a mi sobrino.", english: "I brought my nephew a stuffed animal.", tags: T },
  { target: "Mi madre se preocupó mucho cuando llegué tarde.", english: "My mother worried a lot when I arrived late.", tags: T },
  { target: "Nos reunimos toda la familia por Año Nuevo.", english: "The whole family got together for New Year's.", tags: T, grammar: "Reunirse = to get together (reflexive). Preterite: nos reunimos" },
  { target: "Mi tío nos contó una historia muy divertida.", english: "My uncle told us a very funny story.", tags: T },
  { target: "Mi hijo se manchó la camiseta con chocolate.", english: "My son stained his shirt with chocolate.", tags: T },
  { target: "Les compré regalos a todos mis sobrinos.", english: "I bought gifts for all my nieces and nephews.", tags: T },
  { target: "El perro se comió el zapato del niño.", english: "The dog ate the boy's shoe.", tags: T },
  { target: "Mi abuela se alegró mucho de vernos.", english: "My grandmother was very happy to see us.", tags: T },
  { target: "Les preparé tortitas para desayunar.", english: "I made them pancakes for breakfast.", tags: T },
  { target: "Mi hermana se fue a vivir al extranjero.", english: "My sister went to live abroad.", tags: T },
  { target: "Le hicimos una tarta sorpresa a mamá.", english: "We made mom a surprise cake.", tags: T },
  { target: "El vecino nos ayudó a montar la estantería.", english: "The neighbor helped us assemble the bookshelf.", tags: T },
  { target: "Mi hijo aprendió a nadar este verano.", english: "My son learned to swim this summer.", tags: T },
  { target: "Fui al mercado por mi madre.", english: "I went to the market for my mother.", tags: T, grammar: "Por = on behalf of: fui por mi madre (I went in her place)" },
  { target: "Mi padre me regaló su reloj viejo.", english: "My father gave me his old watch.", tags: T },
  { target: "Los niños se escondieron detrás del sofá.", english: "The kids hid behind the couch.", tags: T },
  { target: "Mi cuñada nos trajo un postre casero.", english: "My sister-in-law brought us a homemade dessert.", tags: T },
  { target: "Le puse un nombre bonito a mi gata.", english: "I gave my cat a pretty name.", tags: T },
  { target: "Mi madre se enfadó porque no lavé los platos.", english: "My mother got angry because I didn't wash the dishes.", tags: T },
  { target: "Los abuelos cuidaron a los niños el sábado.", english: "The grandparents looked after the kids on Saturday.", tags: T },
  { target: "Mi hermano me despertó muy temprano.", english: "My brother woke me up very early.", tags: T },
  { target: "Mi padre nos enseñó a pescar en el río.", english: "My father taught us to fish in the river.", tags: T },
  { target: "La vecina se ofreció a cuidar al gato.", english: "The neighbor offered to look after the cat.", tags: T },
  { target: "Mi hija se disfrazó de princesa.", english: "My daughter dressed up as a princess.", tags: T },
  { target: "Le corté las uñas al bebé con mucho cuidado.", english: "I trimmed the baby's nails very carefully.", tags: T },
  { target: "Mis padres se mudaron al campo cuando se jubilaron.", english: "My parents moved to the countryside when they retired.", tags: T },
  { target: "El perro se puso muy contento al vernos.", english: "The dog got very happy when he saw us.", tags: T },
  { target: "Mi madre nos preparó empanadas para el viaje.", english: "My mother made us empanadas for the trip.", tags: T },
  { target: "Los niños se quedaron dormidos en el coche.", english: "The kids fell asleep in the car.", tags: T },

  // ═══════════════════════════════════════════════════════════════
  // B1 — Subjunctive, future, conditional, commands, relative clauses (~108)
  // ═══════════════════════════════════════════════════════════════
  { target: "Quiero que los niños coman más verdura.", english: "I want the kids to eat more vegetables.", tags: T, grammar: "Subjunctive after quiero que: coman (not comen)" },
  { target: "La casa donde crecí ya no existe.", english: "The house where I grew up no longer exists.", tags: T },
  { target: "Espero que mi hijo apruebe el examen.", english: "I hope my son passes the exam.", tags: T },
  { target: "Dudo que los niños se duerman pronto.", english: "I doubt the kids will fall asleep soon.", tags: T },
  { target: "El vecino que nos ayudó es fontanero.", english: "The neighbor who helped us is a plumber.", tags: T },
  { target: "No creo que mi madre venga este fin de semana.", english: "I don't think my mother is coming this weekend.", tags: T },
  { target: "Me alegro de que estéis todos bien.", english: "I'm glad you're all well.", tags: T, grammar: "Alegrarse de que + subjunctive: estéis (vosotros form)" },
  { target: "Si tenemos tiempo, visitaremos a los abuelos.", english: "If we have time, we'll visit the grandparents.", tags: T },
  { target: "Es necesario que los niños hagan los deberes.", english: "It's necessary for the kids to do their homework.", tags: T },
  { target: "La vecina que cuida a mis hijos es encantadora.", english: "The neighbor who watches my kids is lovely.", tags: T },
  { target: "Ojalá que el bebé duerma toda la noche.", english: "I hope the baby sleeps through the night.", tags: T },
  { target: "Me encantaría que vinieras a la cena de Navidad.", english: "I'd love for you to come to Christmas dinner.", tags: T },
  { target: "Recoge tu habitación antes de salir.", english: "Clean up your room before going out.", tags: T, grammar: "Imperative tú: recoge (recoger)" },
  { target: "No dejes los zapatos en la entrada.", english: "Don't leave your shoes at the entrance.", tags: T, grammar: "Negative tú imperative uses subjunctive: no dejes (not no deja)" },
  { target: "Llama a tu abuela, que es su cumpleaños.", english: "Call your grandmother, it's her birthday.", tags: T },
  { target: "Mi padre me dijo que estudiara más.", english: "My father told me to study more.", tags: T },
  { target: "El pediatra recomendó que el niño descansara.", english: "The pediatrician recommended that the boy rest.", tags: T },
  { target: "Pon la mesa, que ya casi está la cena.", english: "Set the table, dinner is almost ready.", tags: T },
  { target: "No me gusta que los niños coman tantas chuches.", english: "I don't like the kids eating so many sweets.", tags: T },
  { target: "Es importante que hablemos con nuestros hijos.", english: "It's important that we talk to our kids.", tags: T },
  { target: "Haré la compra después de recoger a los niños.", english: "I'll do the grocery shopping after picking up the kids.", tags: T },
  { target: "Cuando los niños crezcan, entenderán.", english: "When the kids grow up, they'll understand.", tags: T, grammar: "Cuando + subjunctive for future events: crezcan (not crecen)" },
  { target: "Si mi madre se entera, se va a preocupar.", english: "If my mother finds out, she's going to worry.", tags: T },
  { target: "Te he dicho mil veces que no corras por la casa.", english: "I've told you a thousand times not to run around the house.", tags: T },
  { target: "El juguete que le compramos ya se ha roto.", english: "The toy we bought him has already broken.", tags: T },
  { target: "Me gustaría que mis padres vivieran más cerca.", english: "I'd like my parents to live closer.", tags: T },
  { target: "No quiero que los niños vean tanta televisión.", english: "I don't want the kids to watch so much television.", tags: T },
  { target: "Baja la voz, que el bebé está dormido.", english: "Keep your voice down, the baby is sleeping.", tags: T },
  { target: "La profesora pidió que los padres asistieran a la reunión.", english: "The teacher asked that the parents attend the meeting.", tags: T },
  { target: "Es probable que mi hermana se mude el mes que viene.", english: "It's likely that my sister will move next month.", tags: T },
  { target: "Tendremos que cambiar al niño de colegio.", english: "We'll have to change the boy's school.", tags: T },
  { target: "Si no llueve, comeremos en el jardín.", english: "If it doesn't rain, we'll eat in the garden.", tags: T },
  { target: "La casa en la que vivíamos era muy vieja.", english: "The house we used to live in was very old.", tags: T },
  { target: "Apaga la luz cuando salgas de la habitación.", english: "Turn off the light when you leave the room.", tags: T },
  { target: "Necesito que alguien cuide al bebé esta tarde.", english: "I need someone to watch the baby this afternoon.", tags: T },
  { target: "Quiero que vengas a la fiesta de cumpleaños.", english: "I want you to come to the birthday party.", tags: T },
  { target: "Mi madre insiste en que comamos más pescado.", english: "My mother insists that we eat more fish.", tags: T },
  { target: "Dile a tu hermano que venga a cenar.", english: "Tell your brother to come to dinner.", tags: T },
  { target: "Me preocupa que mi hija no coma lo suficiente.", english: "I'm worried that my daughter doesn't eat enough.", tags: T },
  { target: "El colegio donde van mis hijos es bilingüe.", english: "The school my kids go to is bilingual.", tags: T },
  { target: "Dejaremos la puerta abierta para que entre el aire.", english: "We'll leave the door open so the air comes in.", tags: T },
  { target: "Lávate las manos antes de comer.", english: "Wash your hands before eating.", tags: T, grammar: "Reflexive imperative tú: lávate (lavarse)" },
  { target: "No creo que el niño tenga fiebre.", english: "I don't think the boy has a fever.", tags: T },
  { target: "Te lo digo para que no te preocupes.", english: "I'm telling you so you don't worry.", tags: T, grammar: "Para que + subjunctive = so that" },
  { target: "Mi abuela quiere que la visitemos más a menudo.", english: "My grandmother wants us to visit her more often.", tags: T },
  { target: "Cuelga el abrigo en la entrada.", english: "Hang your coat in the entryway.", tags: T },
  { target: "No hace falta que grites, te estoy escuchando.", english: "There's no need to shout, I'm listening.", tags: T },
  { target: "El perro al que rescatamos es muy cariñoso.", english: "The dog we rescued is very affectionate.", tags: T },
  { target: "Volveremos temprano para acostar a los niños.", english: "We'll come back early to put the kids to bed.", tags: T },
  { target: "Habrá que comprar una cama más grande para el niño.", english: "We'll need to buy a bigger bed for the boy.", tags: T, grammar: "Habrá que + infinitive = it will be necessary to (impersonal future)" },
  { target: "Si mi hermana viene, prepararé su plato favorito.", english: "If my sister comes, I'll make her favorite dish.", tags: T },
  { target: "Es mejor que los niños jueguen fuera.", english: "It's better for the kids to play outside.", tags: T },
  { target: "Quita los pies de la mesa.", english: "Take your feet off the table.", tags: T },
  { target: "No hagas tanto ruido, que el abuelo descansa.", english: "Don't make so much noise, grandpa is resting.", tags: T },
  { target: "Busco una canguro que tenga experiencia con bebés.", english: "I'm looking for a babysitter who has experience with babies.", tags: T, grammar: "Subjunctive in relative clause: tenga (unknown/desired person)" },
  { target: "Sacaré al perro cuando pare de llover.", english: "I'll take the dog out when it stops raining.", tags: T },
  { target: "No quiero que mis hijos repitan mis errores.", english: "I don't want my kids to repeat my mistakes.", tags: T },
  { target: "Me sorprende que los niños estén tan tranquilos.", english: "I'm surprised the kids are so quiet.", tags: T },
  { target: "Tus hermanos vendrán a la barbacoa, ¿verdad?", english: "Your siblings will come to the barbecue, right?", tags: T },
  { target: "Es raro que el perro no haya comido nada.", english: "It's strange that the dog hasn't eaten anything.", tags: T },
  { target: "Cuando mi hija sea mayor, quiere ser veterinaria.", english: "When my daughter grows up, she wants to be a vet.", tags: T },
  { target: "No permitas que el niño cruce la calle solo.", english: "Don't let the boy cross the street alone.", tags: T },
  { target: "Mis padres nos regalarán un viaje de aniversario.", english: "My parents will give us a trip for our anniversary.", tags: T },
  { target: "No comas tantas galletas antes de cenar.", english: "Don't eat so many cookies before dinner.", tags: T },
  { target: "Siento que no puedas venir al bautizo.", english: "I'm sorry you can't come to the baptism.", tags: T },
  { target: "Cerrad la puerta con llave al salir.", english: "Lock the door when you leave.", tags: T, grammar: "Imperative vosotros: cerrad (cerrar)" },
  { target: "Mi madre me aconseja que ahorre más.", english: "My mother advises me to save more.", tags: T },
  { target: "La mujer que conocí es la madre de un compañero.", english: "The woman I met is a classmate's mother.", tags: T },
  { target: "Si el bebé llora, dale el chupete.", english: "If the baby cries, give him the pacifier.", tags: T },
  { target: "Hace falta que organicemos la fiesta de cumpleaños.", english: "We need to organize the birthday party.", tags: T },
  { target: "Es una lástima que no puedas venir a la comunión.", english: "It's a shame you can't come to the communion.", tags: T },
  { target: "El parque donde juegan los niños está muy cuidado.", english: "The park where the kids play is well maintained.", tags: T },
  { target: "No creo que haya suficiente comida para todos.", english: "I don't think there's enough food for everyone.", tags: T },
  { target: "Cuando termines los deberes, podrás jugar.", english: "When you finish your homework, you can play.", tags: T },
  { target: "Me molesta que dejes la toalla mojada en la cama.", english: "It bothers me that you leave the wet towel on the bed.", tags: T },
  { target: "Prométeme que cuidarás de tu hermano pequeño.", english: "Promise me you'll take care of your little brother.", tags: T },
  { target: "Es importante que los niños aprendan a compartir.", english: "It's important for kids to learn to share.", tags: T },
  { target: "El restaurante donde celebramos la boda era precioso.", english: "The restaurant where we held the wedding was beautiful.", tags: T },
  { target: "No dejes que el perro se suba al sofá.", english: "Don't let the dog get on the couch.", tags: T },
  { target: "Si viene mucha gente, necesitaremos más sillas.", english: "If a lot of people come, we'll need more chairs.", tags: T },
  { target: "Ojalá mi madre se recupere pronto.", english: "I hope my mother recovers soon.", tags: T },
  { target: "Date prisa, que llegamos tarde al colegio.", english: "Hurry up, we're late for school.", tags: T, grammar: "Date prisa — reflexive imperative: darse prisa (to hurry up)" },
  { target: "No es normal que el bebé llore tanto.", english: "It's not normal for the baby to cry so much.", tags: T },
  { target: "Temo que mi padre esté enfermo.", english: "I'm afraid my father is sick.", tags: T },
  { target: "Cuando seas mayor, entenderás por qué lo hacemos.", english: "When you're older, you'll understand why we do it.", tags: T, grammar: "Ser in subjunctive: seas (when talking about future states)" },
  { target: "No creo que los niños necesiten tantos juguetes.", english: "I don't think kids need so many toys.", tags: T },
  { target: "Es posible que nos mudemos el año que viene.", english: "It's possible we'll move next year.", tags: T },
  { target: "Llévate una chaqueta por si refresca.", english: "Take a jacket in case it gets cool.", tags: T },
  { target: "Quiero que te portes bien en casa de la abuela.", english: "I want you to behave at grandma's house.", tags: T },
  { target: "No creo que sea buena idea dejarles solos.", english: "I don't think it's a good idea to leave them alone.", tags: T },
  { target: "Me alegra que tu hijo haya aprobado todo.", english: "I'm glad your son passed everything.", tags: T },
  { target: "El profesor sugiere que el niño lea más en casa.", english: "The teacher suggests the boy read more at home.", tags: T },
  { target: "No toques el horno, que quema.", english: "Don't touch the oven, it burns.", tags: T },
  { target: "Es mejor que los niños se acuesten antes de las diez.", english: "It's better for the kids to go to bed before ten.", tags: T },
  { target: "Si hace buen tiempo, iremos al zoo con los niños.", english: "If the weather is nice, we'll go to the zoo with the kids.", tags: T },
  { target: "Quiero que mi familia esté presente en mi graduación.", english: "I want my family to be present at my graduation.", tags: T },
  { target: "No creo que el gatito tenga más de dos meses.", english: "I don't think the kitten is more than two months old.", tags: T },
  { target: "Puede que mis padres vengan a vernos en Semana Santa.", english: "My parents might come see us at Easter.", tags: T, grammar: "Puede que + subjunctive = maybe, it's possible that" },
  { target: "Deja de pegarle a tu hermana.", english: "Stop hitting your sister.", tags: T },
  { target: "Es fundamental que haya comunicación en la pareja.", english: "It's essential that there be communication in a couple.", tags: T },
  { target: "El día que mis hijos se vayan de casa, lloraré mucho.", english: "The day my kids leave home, I'll cry a lot.", tags: T },
  { target: "No quiero que salgas sin abrigo con este frío.", english: "I don't want you going out without a coat in this cold.", tags: T },
  { target: "Es increíble que ya hayan pasado diez años desde la boda.", english: "It's incredible that ten years have already passed since the wedding.", tags: T, grammar: "Present perfect subjunctive: hayan pasado (haber subjunctive + past participle)" },
  { target: "Acuéstate ya, mañana hay colegio.", english: "Go to bed now, there's school tomorrow.", tags: T },
  { target: "Espero que la tarta de cumpleaños salga bien.", english: "I hope the birthday cake turns out well.", tags: T },

  // ═══════════════════════════════════════════════════════════════
  // B2 — Imperfect subjunctive, conditionals II/III, passive, advanced connectors (~108)
  // ═══════════════════════════════════════════════════════════════
  { target: "Si mi abuelo viviera, estaría orgulloso.", english: "If my grandfather were alive, he'd be proud.", tags: T, grammar: "Type II conditional: si + imperfect subjunctive (viviera) + conditional (estaría)" },
  { target: "A pesar de las peleas, nos queremos mucho.", english: "Despite the arguments, we love each other a lot.", tags: T },
  { target: "Si hubiéramos llegado antes, habríamos visto al bebé despierto.", english: "If we had arrived earlier, we would have seen the baby awake.", tags: T },
  { target: "Por mucho que le insista, mi hijo no quiere comer brócoli.", english: "No matter how much I insist, my son won't eat broccoli.", tags: T, grammar: "Por mucho que + subjunctive = no matter how much" },
  { target: "La cena fue preparada por mi cuñada.", english: "Dinner was prepared by my sister-in-law.", tags: T, grammar: "Passive with ser: fue preparada (past participle agrees with subject)" },
  { target: "Ojalá hubiera pasado más tiempo con mis abuelos.", english: "I wish I had spent more time with my grandparents.", tags: T },
  { target: "Si mi madre no me hubiera animado, no habría estudiado medicina.", english: "If my mother hadn't encouraged me, I wouldn't have studied medicine.", tags: T },
  { target: "No es que no quiera a mis suegros, es que necesito mi espacio.", english: "It's not that I don't love my in-laws, I just need my space.", tags: T },
  { target: "Si tuviéramos más espacio, adoptaríamos otro gato.", english: "If we had more space, we'd adopt another cat.", tags: T },
  { target: "Habríamos ido a la playa si los niños no hubieran estado enfermos.", english: "We would have gone to the beach if the kids hadn't been sick.", tags: T },
  { target: "A fin de cuentas, lo único que importa es que estemos juntos.", english: "At the end of the day, the only thing that matters is being together.", tags: T },
  { target: "Si mi hermana viviera más cerca, la veríamos cada semana.", english: "If my sister lived closer, we'd see her every week.", tags: T },
  { target: "La decisión fue tomada por toda la familia.", english: "The decision was made by the whole family.", tags: T, grammar: "Ser + past participle passive: fue tomada (agrees with la decisión)" },
  { target: "Cuanto más crecen los niños, más independientes se vuelven.", english: "The more the kids grow, the more independent they become.", tags: T, grammar: "Cuanto más... más... = the more... the more..." },
  { target: "Si no fuera por mi madre, no sabría cocinar.", english: "If it weren't for my mother, I wouldn't know how to cook.", tags: T },
  { target: "A pesar de la distancia, llamo a mis padres cada día.", english: "Despite the distance, I call my parents every day.", tags: T, grammar: "A pesar de = despite, in spite of (+ noun or infinitive)" },
  { target: "Si hubiera escuchado a mi padre, me habría ahorrado muchos problemas.", english: "If I had listened to my father, I would have saved myself many problems.", tags: T },
  { target: "El hecho de que tengamos hijos no significa que no podamos salir.", english: "The fact that we have kids doesn't mean we can't go out.", tags: T },
  { target: "Me habría gustado que mis hijos conocieran a su bisabuelo.", english: "I would have liked my kids to have met their great-grandfather.", tags: T },
  { target: "Si el niño se portara mejor, le dejaríamos quedarse hasta tarde.", english: "If the boy behaved better, we'd let him stay up late.", tags: T },
  { target: "Siempre y cuando los niños estén contentos, lo demás es secundario.", english: "As long as the kids are happy, everything else is secondary.", tags: T, grammar: "Siempre y cuando + subjunctive = as long as, provided that" },
  { target: "Si hubiéramos comprado la casa más grande, tendríamos sitio para todos.", english: "If we had bought the bigger house, we'd have room for everyone.", tags: T },
  { target: "Por más que lo intento, no consigo que mi hijo ordene su cuarto.", english: "No matter how much I try, I can't get my son to tidy his room.", tags: T },
  { target: "Las fotos fueron sacadas por mi cuñado en la boda.", english: "The photos were taken by my brother-in-law at the wedding.", tags: T },
  { target: "Si no hubiera llovido, habríamos hecho la fiesta en el jardín.", english: "If it hadn't rained, we would have had the party in the garden.", tags: T },
  { target: "Con tal de que los niños duerman bien, no me importa acostarme tarde.", english: "As long as the kids sleep well, I don't mind going to bed late.", tags: T },
  { target: "Si mi padre supiera usar el móvil, le haríamos videollamadas.", english: "If my father knew how to use the phone, we'd video call him.", tags: T },
  { target: "Aunque nos cueste reconocerlo, nuestros hijos ya no son pequeños.", english: "Even though it's hard for us to admit, our kids aren't little anymore.", tags: T },
  { target: "De haber tenido más hijos, habríamos necesitado una casa más grande.", english: "Had we had more kids, we would have needed a bigger house.", tags: T, grammar: "De + infinitive = si + pluperfect subjunctive (formal alternative)" },
  { target: "Si mis abuelos me vieran ahora, no me reconocerían.", english: "If my grandparents saw me now, they wouldn't recognize me.", tags: T },
  { target: "Siendo madre, entiendo mejor lo que pasó mi madre.", english: "Being a mother, I understand better what my mother went through.", tags: T },
  { target: "A menos que el niño mejore, no irá al colegio mañana.", english: "Unless the boy gets better, he won't go to school tomorrow.", tags: T, grammar: "A menos que + subjunctive = unless" },
  { target: "Si no hubiéramos mudado de ciudad, mis hijos tendrían otros amigos.", english: "If we hadn't moved cities, my kids would have other friends.", tags: T },
  { target: "Dicho sea de paso, la receta de mi abuela es mucho mejor.", english: "By the way, my grandmother's recipe is much better.", tags: T },
  { target: "Si mi marido cocinara más a menudo, yo tendría más tiempo libre.", english: "If my husband cooked more often, I'd have more free time.", tags: T },
  { target: "Las tareas del hogar fueron repartidas entre todos.", english: "The household chores were divided among everyone.", tags: T },
  { target: "Por mucho que discutamos, al final siempre nos reconciliamos.", english: "No matter how much we argue, in the end we always make up.", tags: T },
  { target: "Si hubieras venido al bautizo, habrías visto lo grande que está.", english: "If you had come to the baptism, you would have seen how big he is.", tags: T },
  { target: "En lo que respecta a la crianza, cada familia es diferente.", english: "When it comes to parenting, every family is different.", tags: T },
  { target: "Si tuviera más paciencia, sería mejor padre.", english: "If I had more patience, I'd be a better father.", tags: T },
  { target: "Habiendo crecido con cuatro hermanos, estoy acostumbrado al ruido.", english: "Having grown up with four siblings, I'm used to noise.", tags: T },
  { target: "No es que no confíe en mis hijos, sino que me preocupo por ellos.", english: "It's not that I don't trust my kids, but rather that I worry about them.", tags: T, grammar: "No es que + subjunctive, sino que + indicative = it's not that... but rather..." },
  { target: "Si la abuela pudiera viajar, vendría a visitarnos.", english: "If grandma could travel, she'd come visit us.", tags: T },
  { target: "La habitación del niño fue decorada con motivos marinos.", english: "The boy's room was decorated with a nautical theme.", tags: T },
  { target: "Aunque parezca mentira, los niños prefieren la fruta al chocolate.", english: "Hard as it is to believe, the kids prefer fruit to chocolate.", tags: T },
  { target: "Si hubiera sabido que estabas embarazada, te habría ayudado más.", english: "If I had known you were pregnant, I would have helped you more.", tags: T },
  { target: "Pase lo que pase, siempre seré tu madre.", english: "Whatever happens, I'll always be your mother.", tags: T },
  { target: "Si mis padres no hubieran emigrado, yo no habría nacido aquí.", english: "If my parents hadn't emigrated, I wouldn't have been born here.", tags: T },
  { target: "Antes de que los niños lleguen, quiero tener la casa limpia.", english: "Before the kids arrive, I want to have the house clean.", tags: T, grammar: "Antes de que always takes subjunctive: lleguen" },
  { target: "Si pudiéramos permitírnoslo, contrataríamos a alguien para limpiar.", english: "If we could afford it, we'd hire someone to clean.", tags: T },
  { target: "Sea como sea la situación, la familia tiene que estar unida.", english: "Whatever the situation, the family has to stick together.", tags: T },
  { target: "Si mi hermano no hubiera insistido, no habríamos hecho la fiesta.", english: "If my brother hadn't insisted, we wouldn't have thrown the party.", tags: T },
  { target: "El pastel fue hecho por los niños con ayuda de la abuela.", english: "The cake was made by the kids with grandma's help.", tags: T },
  { target: "Cuanto antes aprendan a compartir, mejor.", english: "The sooner they learn to share, the better.", tags: T },
  { target: "Si viviera solo, no cocinaría tan a menudo.", english: "If I lived alone, I wouldn't cook so often.", tags: T },
  { target: "A condición de que todos colaboren, la mudanza será fácil.", english: "Provided everyone helps out, the move will be easy.", tags: T, grammar: "A condición de que + subjunctive = on the condition that" },
  { target: "Si mis hijos me hubieran hecho caso, no se habrían perdido.", english: "If my kids had listened to me, they wouldn't have gotten lost.", tags: T },
  { target: "No habría sido posible sin la ayuda de toda la familia.", english: "It wouldn't have been possible without the whole family's help.", tags: T },
  { target: "Aun cuando no estemos de acuerdo, nos respetamos.", english: "Even when we don't agree, we respect each other.", tags: T, grammar: "Aun cuando + subjunctive = even when/even if" },
  { target: "Si hubiéramos tenido gemelos, no sé cómo habríamos sobrevivido.", english: "If we had had twins, I don't know how we would have survived.", tags: T },
  { target: "Dado que los niños están de vacaciones, pasamos más tiempo juntos.", english: "Given that the kids are on vacation, we spend more time together.", tags: T, grammar: "Dado que = given that, since (formal connector + indicative)" },
  { target: "Si pudiera retroceder en el tiempo, disfrutaría más de su infancia.", english: "If I could go back in time, I'd enjoy their childhood more.", tags: T },
  { target: "La comida fue servida en el jardín para toda la familia.", english: "The food was served in the garden for the whole family.", tags: T },
  { target: "Por más que mi madre se empeñe, los tiempos han cambiado.", english: "No matter how much my mother insists, times have changed.", tags: T },
  { target: "Si no fuera tan cabezota, se llevaría mejor con su hermana.", english: "If he weren't so stubborn, he'd get along better with his sister.", tags: T },
  { target: "Habría preferido que me lo dijeras antes de contárselo a mamá.", english: "I would have preferred you told me before telling mom.", tags: T },
  { target: "A no ser que mi suegra cambie de opinión, la cena será en su casa.", english: "Unless my mother-in-law changes her mind, dinner will be at her house.", tags: T },
  { target: "Si los niños no estuvieran tan cansados, iríamos al cine.", english: "If the kids weren't so tired, we'd go to the movies.", tags: T },
  { target: "La mesa fue puesta por los niños para sorprender a sus padres.", english: "The table was set by the kids to surprise their parents.", tags: T },
  { target: "En caso de que el bebé se despierte, dale el biberón.", english: "In case the baby wakes up, give him the bottle.", tags: T, grammar: "En caso de que + subjunctive = in case" },
  { target: "Si nos hubiéramos organizado mejor, la fiesta habría sido perfecta.", english: "If we had organized better, the party would have been perfect.", tags: T },
  { target: "Ni que fueras su madre para hablarle así.", english: "It's not like you're his mother to talk to him like that.", tags: T, grammar: "Ni que + imperfect subjunctive = it's not as if / as though" },
  { target: "El álbum de fotos fue encontrado en el desván por mi hermana.", english: "The photo album was found in the attic by my sister.", tags: T },
  { target: "Con que los niños se porten bien en la cena, me conformo.", english: "As long as the kids behave at dinner, I'll be satisfied.", tags: T },
  { target: "Si hubiéramos escuchado al abuelo, habríamos tomado el camino corto.", english: "If we had listened to grandpa, we would have taken the short route.", tags: T },
  { target: "Sea cual sea la decisión, la tomaremos en familia.", english: "Whatever the decision, we'll make it as a family.", tags: T },
  { target: "De no ser por el apoyo de mi familia, no lo habría conseguido.", english: "Were it not for my family's support, I wouldn't have made it.", tags: T },
  { target: "Si mi hijo tuviera más confianza en sí mismo, se atrevería a hablar en público.", english: "If my son had more self-confidence, he'd dare to speak in public.", tags: T },
  { target: "Las cortinas fueron elegidas por mi madre para combinar con el sofá.", english: "The curtains were chosen by my mother to match the couch.", tags: T },
  { target: "A pesar de ser tan diferentes, mis hermanos se llevan genial.", english: "Despite being so different, my siblings get along great.", tags: T },
  { target: "Si pudiera elegir, pasaría todas las tardes jugando con mis hijos.", english: "If I could choose, I'd spend every afternoon playing with my kids.", tags: T },
  { target: "Habríamos cenado en casa si hubieran avisado con tiempo.", english: "We would have had dinner at home if they had let us know in time.", tags: T },
  { target: "El jardín fue diseñado por mi padre cuando se jubiló.", english: "The garden was designed by my father when he retired.", tags: T },
  { target: "Por mucho que crezcan, siempre serán mis niños pequeños.", english: "No matter how much they grow, they'll always be my little kids.", tags: T },
  { target: "Si la bisabuela levantara la cabeza, no reconocería la casa.", english: "If great-grandma could see this, she wouldn't recognize the house.", tags: T, grammar: "Levantar la cabeza = idiomatic: if they could see (from beyond)" },
  { target: "Digas lo que digas, tu madre siempre tiene razón.", english: "Whatever you say, your mother is always right.", tags: T },
  { target: "Si no hubiera insistido mi mujer, nunca habríamos comprado esta casa.", english: "If my wife hadn't insisted, we would never have bought this house.", tags: T },
  { target: "Haga lo que haga mi hija, siempre la apoyaré.", english: "Whatever my daughter does, I'll always support her.", tags: T, grammar: "Haga lo que haga = whatever she does (reduplicative subjunctive)" },
  { target: "Si mi abuela hubiera conocido a mis hijos, habría sido muy feliz.", english: "If my grandmother had met my kids, she would have been very happy.", tags: T },
  { target: "Sin que nadie se diera cuenta, el niño se comió todos los bombones.", english: "Without anyone noticing, the boy ate all the chocolates.", tags: T, grammar: "Sin que + subjunctive = without (someone doing something)" },
  { target: "Si mis padres no nos hubieran inculcado esos valores, seríamos distintos.", english: "If our parents hadn't instilled those values in us, we'd be different.", tags: T },
  { target: "Lejos de ser perfecta, nuestra familia tiene sus propios encantos.", english: "Far from being perfect, our family has its own charm.", tags: T },
  { target: "Si fuera hija única, me habría sentido muy sola de pequeña.", english: "If I were an only child, I would have felt very lonely as a kid.", tags: T },
  { target: "Se espera que los invitados lleguen a las ocho para la cena familiar.", english: "The guests are expected to arrive at eight for the family dinner.", tags: T },
  { target: "Si tuviéramos una casa más grande, montaríamos un cuarto de juegos.", english: "If we had a bigger house, we'd set up a playroom.", tags: T },
  { target: "Salvo que mi suegra cambie los planes, cenaremos en casa.", english: "Unless my mother-in-law changes the plans, we'll have dinner at home.", tags: T },
  { target: "Si el abuelo pudiera vernos ahora, se sentiría orgulloso.", english: "If grandpa could see us now, he'd feel proud.", tags: T },
  { target: "La crianza de los hijos fue compartida entre los dos.", english: "The raising of the children was shared between both.", tags: T },
  { target: "Si no hubiera sido tan estricto, mis hijos me tendrían más confianza.", english: "If I hadn't been so strict, my kids would trust me more.", tags: T },
  { target: "Aunque la casa fuera más pequeña, lo importante era estar juntos.", english: "Even if the house were smaller, the important thing was being together.", tags: T },
  { target: "El álbum fue organizado por mi madre con mucho cariño.", english: "The album was organized by my mother with a lot of love.", tags: T },
  { target: "Habríamos tenido más hijos si la situación económica lo hubiera permitido.", english: "We would have had more kids if the financial situation had allowed it.", tags: T },
  { target: "Si mi hijo fuera más responsable, le dejaríamos salir más.", english: "If my son were more responsible, we'd let him go out more.", tags: T },
  { target: "A pesar de las dificultades, sacamos adelante a la familia.", english: "Despite the difficulties, we raised the family.", tags: T, grammar: "Sacar adelante = to raise/support (through hardship)" },
  { target: "Si hubiéramos sabido lo difícil que es ser padres, nos habríamos preparado mejor.", english: "If we had known how hard it is to be parents, we would have prepared better.", tags: T },
  { target: "Mientras los niños no molesten, pueden quedarse en el salón.", english: "As long as the kids don't bother anyone, they can stay in the living room.", tags: T },
  { target: "Las normas de la casa fueron establecidas desde el principio.", english: "The house rules were established from the beginning.", tags: T },
  { target: "Si mi hermana no viviera tan lejos, nos veríamos cada semana.", english: "If my sister didn't live so far away, we'd see each other every week.", tags: T },
  { target: "Es como si mi madre tuviera un sexto sentido con los niños.", english: "It's as if my mother had a sixth sense with kids.", tags: T, grammar: "Como si + imperfect subjunctive = as if" },
  { target: "De haber sabido que era niña, habríamos decorado la habitación de rosa.", english: "Had we known it was a girl, we would have decorated the room in pink.", tags: T },
];

// ─── DEDUP AND ASSIGN IDS ─────────────────────────────────────

let maxId = Math.max(...deck.map(c => c.id));
let added = 0;
let skipped = 0;

for (const card of newCards) {
  const key = card.target.toLowerCase().trim();
  if (existingTargets.has(key)) {
    skipped++;
    continue;
  }
  existingTargets.add(key);
  maxId++;
  deck.push({
    id: maxId,
    target: card.target,
    english: card.english,
    audio: "",
    tags: card.tags,
    ...(card.grammar ? { grammar: card.grammar } : {})
  });
  added++;
}

// ─── WRITE BACK ────────────────────────────────────────────────

fs.writeFileSync(DECK_PATH, JSON.stringify(deck, null, 2) + '\n', 'utf-8');

console.log(`\n=== fill-family.cjs results ===`);
console.log(`Defined:  ${newCards.length} new family cards`);
console.log(`Added:    ${added}`);
console.log(`Skipped:  ${skipped} (duplicates)`);
console.log(`New deck: ${deck.length} cards (max ID: ${maxId})`);

// Count family cards
const familyCount = deck.filter(c => c.tags.includes('family')).length;
console.log(`Family cards total: ${familyCount}`);

// Count grammar notes in new cards
const grammarCount = newCards.filter(c => c.grammar).length;
console.log(`Cards with grammar notes: ${grammarCount} / ${newCards.length} (${(grammarCount/newCards.length*100).toFixed(1)}%)`);
