/**
 * fill-work.cjs
 *
 * Add ~520 NEW work-tagged Spanish flashcards to the deck.
 * All cards are about workplace/professional situations:
 * meetings, emails, coworkers, boss, deadlines, presentations,
 * salary, contracts, interviews, commuting, office supplies,
 * scheduling, clients, projects, etc.
 *
 * Distribution:
 *   ~130 A1 cards (simple present, ser/estar, basic questions, articles)
 *   ~130 A2 cards (past tenses, reflexives, object pronouns, por/para)
 *   ~130 B1 cards (subjunctive, future, conditional, commands, relative clauses)
 *   ~130 B2 cards (imperfect subjunctive, conditionals II/III, passive, advanced connectors)
 *
 * Every card: { target, english, tags: ["general", "work"] }
 * ~15% include a grammar field.
 */

const fs = require('fs');
const path = require('path');

const DECK_PATH = path.join(__dirname, '..', 'src', 'data', 'spanish', 'deck.json');
const deck = JSON.parse(fs.readFileSync(DECK_PATH, 'utf-8'));

console.log(`Current deck: ${deck.length} cards`);

// Track existing sentences to avoid duplicates
const existingTargets = new Set(deck.map(c => c.target.toLowerCase().trim()));

// ─── Helper ─────────────────────────────────────────────────────
const W = ["general", "work"];

// ─── A1 CARDS (~130) ────────────────────────────────────────────
const a1Cards = [
  { target: "Trabajo en una oficina grande.", english: "I work in a big office.", tags: W, grammar: "Trabajar (to work) — regular -ar verb. Trabajo = I work." },
  { target: "¿A qué hora es la reunión?", english: "What time is the meeting?", tags: W },
  { target: "Mi jefe es muy amable.", english: "My boss is very kind.", tags: W, grammar: "Ser for permanent traits: es amable = is kind." },
  { target: "Tengo una entrevista mañana.", english: "I have an interview tomorrow.", tags: W },
  { target: "La oficina está en el centro.", english: "The office is downtown.", tags: W, grammar: "Estar for location: está en el centro." },
  { target: "Necesito un bolígrafo.", english: "I need a pen.", tags: W },
  { target: "¿Dónde está la impresora?", english: "Where is the printer?", tags: W },
  { target: "Trabajo de lunes a viernes.", english: "I work from Monday to Friday.", tags: W },
  { target: "Mi compañero de trabajo es español.", english: "My coworker is Spanish.", tags: W },
  { target: "La reunión es a las diez.", english: "The meeting is at ten.", tags: W, grammar: "Ser for scheduled events: La reunión es a las diez." },
  { target: "¿Tienes el número de teléfono de la empresa?", english: "Do you have the company's phone number?", tags: W },
  { target: "El correo electrónico es importante.", english: "Email is important.", tags: W },
  { target: "Soy el nuevo empleado.", english: "I am the new employee.", tags: W },
  { target: "¿Cuántas personas trabajan aquí?", english: "How many people work here?", tags: W },
  { target: "La empresa es grande.", english: "The company is big.", tags: W },
  { target: "Hoy tengo mucho trabajo.", english: "Today I have a lot of work.", tags: W },
  { target: "¿Quién es tu jefe?", english: "Who is your boss?", tags: W },
  { target: "El contrato es de un año.", english: "The contract is for one year.", tags: W },
  { target: "Necesito hablar con el director.", english: "I need to talk to the director.", tags: W },
  { target: "¿Hay una sala de reuniones?", english: "Is there a meeting room?", tags: W, grammar: "Hay = there is / there are. Invariable form." },
  { target: "Mi sueldo es bueno.", english: "My salary is good.", tags: W },
  { target: "Trabajo en equipo.", english: "I work in a team.", tags: W },
  { target: "La secretaria está en la recepción.", english: "The secretary is at the reception.", tags: W },
  { target: "¿Cuánto es tu sueldo?", english: "How much is your salary?", tags: W },
  { target: "Tengo una reunión a las tres.", english: "I have a meeting at three.", tags: W },
  { target: "El horario es de nueve a cinco.", english: "The schedule is from nine to five.", tags: W },
  { target: "Ella es la directora del departamento.", english: "She is the head of the department.", tags: W },
  { target: "Estoy muy ocupado hoy.", english: "I am very busy today.", tags: W, grammar: "Estar for temporary states: estoy ocupado = I am busy (right now)." },
  { target: "¿Dónde está mi escritorio?", english: "Where is my desk?", tags: W },
  { target: "El proyecto es interesante.", english: "The project is interesting.", tags: W },
  { target: "Necesito un ordenador nuevo.", english: "I need a new computer.", tags: W },
  { target: "¿Cuál es tu puesto?", english: "What is your position?", tags: W },
  { target: "El plazo es el viernes.", english: "The deadline is Friday.", tags: W },
  { target: "Trabajo ocho horas al día.", english: "I work eight hours a day.", tags: W },
  { target: "La cafetería está abajo.", english: "The cafeteria is downstairs.", tags: W },
  { target: "¿Tienes experiencia?", english: "Do you have experience?", tags: W },
  { target: "Mi empresa tiene muchos clientes.", english: "My company has many clients.", tags: W },
  { target: "Estoy en una reunión.", english: "I'm in a meeting.", tags: W },
  { target: "El informe está en tu escritorio.", english: "The report is on your desk.", tags: W },
  { target: "¿Cuándo es la presentación?", english: "When is the presentation?", tags: W },
  { target: "Tengo que enviar un correo.", english: "I have to send an email.", tags: W, grammar: "Tener que + infinitive = to have to do something." },
  { target: "¿A qué hora empieza el turno?", english: "What time does the shift start?", tags: W },
  { target: "La reunión es en la sala tres.", english: "The meeting is in room three.", tags: W },
  { target: "Necesitamos más papel para la impresora.", english: "We need more paper for the printer.", tags: W },
  { target: "¿Quién es el responsable del proyecto?", english: "Who is in charge of the project?", tags: W },
  { target: "El jefe está de vacaciones.", english: "The boss is on vacation.", tags: W },
  { target: "Trabajo desde casa los viernes.", english: "I work from home on Fridays.", tags: W },
  { target: "¿Hay café en la cocina?", english: "Is there coffee in the kitchen?", tags: W },
  { target: "El ascensor está roto.", english: "The elevator is broken.", tags: W },
  { target: "Mi oficina es pequeña pero cómoda.", english: "My office is small but comfortable.", tags: W },
  { target: "¿Cuántos departamentos tiene la empresa?", english: "How many departments does the company have?", tags: W },
  { target: "La impresora no funciona.", english: "The printer doesn't work.", tags: W },
  { target: "Somos un equipo de diez personas.", english: "We are a team of ten people.", tags: W },
  { target: "El parking está lleno.", english: "The parking lot is full.", tags: W },
  { target: "¿Tienes la contraseña del wifi?", english: "Do you have the wifi password?", tags: W },
  { target: "Hoy es mi primer día de trabajo.", english: "Today is my first day of work.", tags: W },
  { target: "El despacho del director está al fondo.", english: "The director's office is at the end.", tags: W },
  { target: "Tenemos una reunión cada lunes.", english: "We have a meeting every Monday.", tags: W },
  { target: "Mi contrato es temporal.", english: "My contract is temporary.", tags: W },
  { target: "Necesito imprimir este documento.", english: "I need to print this document.", tags: W },
  { target: "¿Dónde está la sala de descanso?", english: "Where is the break room?", tags: W },
  { target: "El tren al trabajo tarda treinta minutos.", english: "The train to work takes thirty minutes.", tags: W },
  { target: "Hoy hay mucho tráfico.", english: "There's a lot of traffic today.", tags: W },
  { target: "¿Cuánto dura la pausa para comer?", english: "How long is the lunch break?", tags: W },
  { target: "Tengo dos monitores en mi escritorio.", english: "I have two monitors on my desk.", tags: W },
  { target: "¿Puedo usar esta sala?", english: "Can I use this room?", tags: W, grammar: "Poder + infinitive for asking permission: ¿Puedo usar...?" },
  { target: "La empresa está cerca del metro.", english: "The company is near the metro.", tags: W },
  { target: "Soy becario en esta empresa.", english: "I'm an intern at this company.", tags: W },
  { target: "La conexión a internet es lenta.", english: "The internet connection is slow.", tags: W },
  { target: "¿Hay un código de vestimenta?", english: "Is there a dress code?", tags: W },
  { target: "El teléfono no para de sonar.", english: "The phone won't stop ringing.", tags: W },
  { target: "Trabajo en el departamento de ventas.", english: "I work in the sales department.", tags: W },
  { target: "Mi compañera está enferma hoy.", english: "My coworker is sick today.", tags: W },
  { target: "¿Cuándo es la fecha límite?", english: "When is the deadline?", tags: W },
  { target: "Necesito unas grapas.", english: "I need some staples.", tags: W },
  { target: "El edificio tiene cinco pisos.", english: "The building has five floors.", tags: W },
  { target: "¿Dónde firmo?", english: "Where do I sign?", tags: W },
  { target: "La empresa ofrece seguro médico.", english: "The company offers health insurance.", tags: W },
  { target: "Estamos en la planta baja.", english: "We are on the ground floor.", tags: W },
  { target: "Hay una videoconferencia a las once.", english: "There's a video conference at eleven.", tags: W },
  { target: "Soy el encargado del almacén.", english: "I'm the warehouse manager.", tags: W },
  { target: "¿Cuál es la dirección de la oficina?", english: "What is the office address?", tags: W },
  { target: "El aire acondicionado está muy frío.", english: "The air conditioning is very cold.", tags: W },
  { target: "Mi turno empieza a las siete.", english: "My shift starts at seven.", tags: W },
  { target: "Tenemos un problema con el servidor.", english: "We have a problem with the server.", tags: W },
  { target: "¿Hay aparcamiento para empleados?", english: "Is there employee parking?", tags: W },
  { target: "La fotocopiadora está al final del pasillo.", english: "The photocopier is at the end of the hallway.", tags: W },
  { target: "Hablo con clientes todos los días.", english: "I talk to clients every day.", tags: W },
  { target: "¿Dónde pongo mis cosas?", english: "Where do I put my things?", tags: W },
  { target: "Necesito pedir un día libre.", english: "I need to request a day off.", tags: W },
  { target: "El almuerzo es de una a dos.", english: "Lunch is from one to two.", tags: W },
  { target: "Mi jefa es muy exigente.", english: "My boss is very demanding.", tags: W },
  { target: "¿Hay alguien en recepción?", english: "Is there anyone at reception?", tags: W },
  { target: "Tengo que terminar esto hoy.", english: "I have to finish this today.", tags: W },
  { target: "El contrato incluye vacaciones pagadas.", english: "The contract includes paid vacation.", tags: W },
  { target: "¿Cuál es el número de extensión?", english: "What is the extension number?", tags: W },
  { target: "Nuestra oficina tiene buena vista.", english: "Our office has a nice view.", tags: W },
  { target: "La empresa busca empleados nuevos.", english: "The company is looking for new employees.", tags: W },
  { target: "Trabajo en recursos humanos.", english: "I work in human resources.", tags: W },
  { target: "¿Necesitas ayuda con algo?", english: "Do you need help with something?", tags: W },
  { target: "El autobús al trabajo pasa cada quince minutos.", english: "The bus to work comes every fifteen minutes.", tags: W },
  { target: "Soy ingeniero de software.", english: "I'm a software engineer.", tags: W, grammar: "In Spanish, no article before professions: Soy ingeniero (not Soy un ingeniero)." },
  { target: "La empresa está en el centro de la ciudad.", english: "The company is in the city center.", tags: W },
  { target: "¿Hay una máquina de café?", english: "Is there a coffee machine?", tags: W },
  { target: "Necesitamos contratar más gente.", english: "We need to hire more people.", tags: W },
  { target: "Mis compañeros son simpáticos.", english: "My coworkers are nice.", tags: W },
  { target: "El correo está en tu bandeja de entrada.", english: "The email is in your inbox.", tags: W },
  { target: "¿Cuándo cobro?", english: "When do I get paid?", tags: W },
  { target: "Hoy tengo el día muy largo.", english: "Today is going to be a very long day.", tags: W },
  { target: "La reunión dura una hora.", english: "The meeting lasts one hour.", tags: W },
  { target: "¿Tienes un minuto?", english: "Do you have a minute?", tags: W },
  { target: "Voy al trabajo en bicicleta.", english: "I go to work by bike.", tags: W },
  { target: "El ordenador está encendido.", english: "The computer is on.", tags: W },
  { target: "Hay mucho ruido en la oficina.", english: "There is a lot of noise in the office.", tags: W },
  { target: "Quiero un café antes de la reunión.", english: "I want a coffee before the meeting.", tags: W },
  { target: "¿Cuántos clientes tenemos?", english: "How many clients do we have?", tags: W },
  { target: "Soy contable.", english: "I'm an accountant.", tags: W },
  { target: "La reunión es obligatoria.", english: "The meeting is mandatory.", tags: W },
  { target: "¿Hay un cargador por aquí?", english: "Is there a charger around here?", tags: W },
  { target: "Mi mesa está al lado de la ventana.", english: "My desk is next to the window.", tags: W },
  { target: "La empresa tiene oficinas en tres ciudades.", english: "The company has offices in three cities.", tags: W },
  { target: "Cojo el metro para ir al trabajo.", english: "I take the metro to go to work.", tags: W },
  { target: "El departamento de marketing es grande.", english: "The marketing department is big.", tags: W },
  { target: "¿Qué hora es? Tengo una llamada.", english: "What time is it? I have a call.", tags: W },
  { target: "La empresa cierra en agosto.", english: "The company closes in August.", tags: W },
  { target: "Estoy en periodo de prueba.", english: "I'm on a probation period.", tags: W },
  { target: "El wifi no funciona bien.", english: "The wifi isn't working well.", tags: W },
  { target: "¿Quién tiene la llave de la oficina?", english: "Who has the office key?", tags: W },
  { target: "Hay una nueva política de teletrabajo.", english: "There is a new remote work policy.", tags: W },
  { target: "Soy abogada.", english: "I'm a lawyer.", tags: W },
  { target: "El horario es flexible.", english: "The schedule is flexible.", tags: W },
  { target: "Tengo que llamar a un cliente.", english: "I have to call a client.", tags: W },
  { target: "Necesito unas tijeras y cinta adhesiva.", english: "I need scissors and tape.", tags: W },
  { target: "¿Dónde está el dispensador de agua?", english: "Where is the water cooler?", tags: W },
  { target: "El portátil está en la taquilla.", english: "The laptop is in the locker.", tags: W },
  { target: "Soy diseñador gráfico.", english: "I'm a graphic designer.", tags: W },
  { target: "La empresa tiene un comedor.", english: "The company has a dining hall.", tags: W },
  { target: "¿Cuántos pisos tiene el edificio?", english: "How many floors does the building have?", tags: W },
  { target: "Los lunes son los días más difíciles.", english: "Mondays are the hardest days.", tags: W },
  { target: "¿Hay reunión esta tarde?", english: "Is there a meeting this afternoon?", tags: W },
];

// ─── A2 CARDS (~130) ────────────────────────────────────────────
const a2Cards = [
  { target: "Terminé el informe ayer.", english: "I finished the report yesterday.", tags: W, grammar: "Pretérito: terminé (I finished). Regular -ar past tense." },
  { target: "Me preparé para la presentación.", english: "I prepared for the presentation.", tags: W, grammar: "Reflexive past: me preparé (I prepared myself)." },
  { target: "El jefe me llamó a su despacho.", english: "The boss called me to his office.", tags: W },
  { target: "Ayer tuvimos una reunión muy larga.", english: "Yesterday we had a very long meeting.", tags: W },
  { target: "Le envié el documento por correo.", english: "I sent him the document by email.", tags: W, grammar: "Le = to him/her (indirect object pronoun). Envié = I sent." },
  { target: "¿Ya terminaste el proyecto?", english: "Did you already finish the project?", tags: W },
  { target: "No pude asistir a la reunión.", english: "I couldn't attend the meeting.", tags: W },
  { target: "Mi compañero me ayudó con el informe.", english: "My coworker helped me with the report.", tags: W },
  { target: "La entrevista fue muy bien.", english: "The interview went very well.", tags: W },
  { target: "Trabajé hasta las nueve de la noche.", english: "I worked until nine at night.", tags: W },
  { target: "¿Quién te dijo eso?", english: "Who told you that?", tags: W },
  { target: "Me contrataron la semana pasada.", english: "They hired me last week.", tags: W },
  { target: "El cliente canceló la reunión.", english: "The client canceled the meeting.", tags: W },
  { target: "Perdí los archivos por un error.", english: "I lost the files because of an error.", tags: W },
  { target: "Nos mudamos a una oficina nueva.", english: "We moved to a new office.", tags: W, grammar: "Reflexive mudarse = to move (locations). Nos mudamos = we moved." },
  { target: "Le pedí un aumento a mi jefe.", english: "I asked my boss for a raise.", tags: W },
  { target: "¿Te gusta tu trabajo?", english: "Do you like your work?", tags: W, grammar: "Gustar construction: Te gusta = it pleases you = you like it." },
  { target: "Me acostumbré al horario nuevo.", english: "I got used to the new schedule.", tags: W },
  { target: "Encontré un error en el presupuesto.", english: "I found an error in the budget.", tags: W },
  { target: "Se canceló la videoconferencia.", english: "The video conference was canceled.", tags: W },
  { target: "El director nos felicitó por el trabajo.", english: "The director congratulated us on the work.", tags: W },
  { target: "¿Recibiste mi correo?", english: "Did you get my email?", tags: W },
  { target: "Me levanté temprano para la reunión.", english: "I got up early for the meeting.", tags: W },
  { target: "No me pagaron las horas extra.", english: "They didn't pay me for overtime.", tags: W },
  { target: "La empresa creció mucho este año.", english: "The company grew a lot this year.", tags: W },
  { target: "Le expliqué el problema al cliente.", english: "I explained the problem to the client.", tags: W },
  { target: "Firmé el contrato ayer por la tarde.", english: "I signed the contract yesterday afternoon.", tags: W },
  { target: "Nos dieron un día libre.", english: "They gave us a day off.", tags: W },
  { target: "¿Cuánto tiempo trabajaste allí?", english: "How long did you work there?", tags: W },
  { target: "Me despidieron sin aviso.", english: "They fired me without notice.", tags: W },
  { target: "El jefe se enfadó con nosotros.", english: "The boss got angry with us.", tags: W },
  { target: "Le presenté mi renuncia al director.", english: "I submitted my resignation to the director.", tags: W },
  { target: "Aprendí mucho en ese puesto.", english: "I learned a lot in that position.", tags: W },
  { target: "Me ofrecieron un puesto mejor.", english: "They offered me a better position.", tags: W },
  { target: "¿Te preparaste para la entrevista?", english: "Did you prepare for the interview?", tags: W },
  { target: "El proyecto se retrasó dos semanas.", english: "The project was delayed by two weeks.", tags: W },
  { target: "La jefa me pidió el informe para hoy.", english: "The boss asked me for the report for today.", tags: W },
  { target: "Hablé con el departamento de ventas.", english: "I spoke with the sales department.", tags: W },
  { target: "Se me olvidó enviar el correo.", english: "I forgot to send the email.", tags: W, grammar: "Se me olvidó: accidental se construction — 'it slipped my mind'." },
  { target: "No encontré el archivo en el servidor.", english: "I didn't find the file on the server.", tags: W },
  { target: "Me quedé hasta tarde para terminar.", english: "I stayed late to finish.", tags: W },
  { target: "Le pasé tu número al cliente.", english: "I gave your number to the client.", tags: W },
  { target: "¿Ya le dijiste al jefe?", english: "Did you already tell the boss?", tags: W },
  { target: "Empecé a trabajar aquí en enero.", english: "I started working here in January.", tags: W },
  { target: "La reunión empezó tarde por el tráfico.", english: "The meeting started late because of traffic.", tags: W },
  { target: "Me inscribí en un curso de formación.", english: "I enrolled in a training course.", tags: W },
  { target: "El cliente no contestó mi llamada.", english: "The client didn't answer my call.", tags: W },
  { target: "Tuve que repetir la presentación.", english: "I had to repeat the presentation.", tags: W },
  { target: "Me cambiaron de departamento.", english: "They transferred me to another department.", tags: W },
  { target: "El equipo cumplió con el plazo.", english: "The team met the deadline.", tags: W },
  { target: "¿Te gustó la entrevista?", english: "Did you like the interview?", tags: W },
  { target: "Imprimí veinte copias del informe.", english: "I printed twenty copies of the report.", tags: W },
  { target: "No me avisaron del cambio de horario.", english: "They didn't tell me about the schedule change.", tags: W },
  { target: "Me reuní con el equipo de diseño.", english: "I met with the design team.", tags: W },
  { target: "Le mandé el presupuesto al cliente.", english: "I sent the budget to the client.", tags: W },
  { target: "El contrato se venció el mes pasado.", english: "The contract expired last month.", tags: W },
  { target: "Me estresé mucho con ese proyecto.", english: "I got very stressed with that project.", tags: W },
  { target: "¿Hablaste con recursos humanos?", english: "Did you talk to human resources?", tags: W },
  { target: "El ascensor se rompió esta mañana.", english: "The elevator broke this morning.", tags: W },
  { target: "Me asignaron un proyecto nuevo.", english: "They assigned me a new project.", tags: W },
  { target: "Lo solucioné yo solo.", english: "I solved it by myself.", tags: W, grammar: "Lo = it (direct object). Yo solo = by myself." },
  { target: "El jefe nos invitó a comer.", english: "The boss invited us to lunch.", tags: W },
  { target: "Dejé el trabajo el año pasado.", english: "I left the job last year.", tags: W },
  { target: "Estuve en una conferencia toda la semana.", english: "I was at a conference all week.", tags: W, grammar: "Estuve = pretérito of estar. For temporary past location." },
  { target: "Me quejé del ruido en la oficina.", english: "I complained about the noise in the office.", tags: W },
  { target: "No me gustó cómo fue la reunión.", english: "I didn't like how the meeting went.", tags: W },
  { target: "Se rompió mi ordenador en la peor semana.", english: "My computer broke during the worst week.", tags: W },
  { target: "La empresa me pagó el curso.", english: "The company paid for my course.", tags: W },
  { target: "Llegué tarde por culpa del tráfico.", english: "I arrived late because of traffic.", tags: W, grammar: "Por culpa de = because of (blaming). Llegué = I arrived." },
  { target: "Le di mi opinión al director.", english: "I gave my opinion to the director.", tags: W },
  { target: "El jefe nos mandó un mensaje urgente.", english: "The boss sent us an urgent message.", tags: W },
  { target: "Antes trabajaba en una fábrica.", english: "I used to work in a factory.", tags: W, grammar: "Imperfecto: trabajaba = I used to work / I was working." },
  { target: "Cuando era joven, quería ser médico.", english: "When I was young, I wanted to be a doctor.", tags: W },
  { target: "Siempre llegaba puntual al trabajo.", english: "I always arrived on time to work.", tags: W },
  { target: "Mi antiguo jefe era muy estricto.", english: "My former boss was very strict.", tags: W },
  { target: "En mi empresa anterior ganaba menos.", english: "In my previous company I earned less.", tags: W },
  { target: "De niño soñaba con ser astronauta.", english: "As a kid I dreamed of being an astronaut.", tags: W },
  { target: "Mientras hablaba por teléfono, llegó el jefe.", english: "While I was talking on the phone, the boss arrived.", tags: W, grammar: "Imperfecto (hablaba) for ongoing action + pretérito (llegó) for interruption." },
  { target: "La oficina antigua era más pequeña.", english: "The old office was smaller.", tags: W },
  { target: "Antes no teníamos teletrabajo.", english: "Before, we didn't have remote work.", tags: W },
  { target: "Cuando empecé, no sabía usar el sistema.", english: "When I started, I didn't know how to use the system.", tags: W },
  { target: "El proyecto me lo explicó María.", english: "María explained the project to me.", tags: W, grammar: "Me lo: double object pronouns — me (to me) + lo (it)." },
  { target: "Esa idea se la propuse yo.", english: "I was the one who proposed that idea.", tags: W },
  { target: "Te lo mando por correo ahora.", english: "I'll send it to you by email now.", tags: W },
  { target: "Nos lo confirmaron esta mañana.", english: "They confirmed it to us this morning.", tags: W },
  { target: "Se lo dije al jefe, pero no me escuchó.", english: "I told the boss, but he didn't listen to me.", tags: W },
  { target: "¿Puedes pasármelo por correo?", english: "Can you send it to me by email?", tags: W },
  { target: "La propuesta se la envié al director ayer.", english: "I sent the proposal to the director yesterday.", tags: W },
  { target: "Ese tema lo tratamos en la reunión pasada.", english: "We discussed that topic in the last meeting.", tags: W },
  { target: "No se lo digas a nadie todavía.", english: "Don't tell anyone yet.", tags: W },
  { target: "Me lo dieron todo por escrito.", english: "They gave me everything in writing.", tags: W },
  { target: "¿Ya te lo aprobaron?", english: "Did they already approve it for you?", tags: W },
  { target: "El cliente está contento con los resultados.", english: "The client is happy with the results.", tags: W },
  { target: "Por eso cambié de empresa.", english: "That's why I changed companies.", tags: W },
  { target: "Estudié administración de empresas.", english: "I studied business administration.", tags: W },
  { target: "No tenía experiencia cuando empecé.", english: "I had no experience when I started.", tags: W },
  { target: "Me adapté rápido al nuevo puesto.", english: "I adapted quickly to the new position.", tags: W },
  { target: "El proyecto anterior fue un éxito.", english: "The previous project was a success.", tags: W },
  { target: "Le pregunté al jefe sobre las vacaciones.", english: "I asked the boss about the vacation.", tags: W },
  { target: "Me cambiaron el turno sin preguntarme.", english: "They changed my shift without asking me.", tags: W },
  { target: "Ayer hubo un problema con el sistema.", english: "Yesterday there was a problem with the system.", tags: W, grammar: "Hubo = pretérito of haber (there was/were). Singular form even for plurals." },
  { target: "Me di cuenta del error a tiempo.", english: "I noticed the error in time.", tags: W },
  { target: "El fin de semana trabajé desde casa.", english: "I worked from home on the weekend.", tags: W },
  { target: "No me dejaron salir temprano.", english: "They didn't let me leave early.", tags: W },
  { target: "Mi primer trabajo fue de camarero.", english: "My first job was as a waiter.", tags: W },
  { target: "La empresa nos dio un bonus en diciembre.", english: "The company gave us a bonus in December.", tags: W },
  { target: "Fui a una feria de empleo la semana pasada.", english: "I went to a job fair last week.", tags: W },
  { target: "Nos reunimos con el equipo cada martes.", english: "We meet with the team every Tuesday.", tags: W },
  { target: "Le pedí a mi compañero que me cubriera.", english: "I asked my coworker to cover for me.", tags: W },
  { target: "¿Cuándo te ascendieron?", english: "When did they promote you?", tags: W },
  { target: "El candidato no cumplía los requisitos.", english: "The candidate didn't meet the requirements.", tags: W },
  { target: "Me presenté a una oferta de empleo.", english: "I applied for a job offer.", tags: W },
  { target: "El proveedor nos envió la factura equivocada.", english: "The supplier sent us the wrong invoice.", tags: W },
  { target: "Cambié de carrera a los treinta.", english: "I changed careers at thirty.", tags: W },
  { target: "Me aburría mucho en ese trabajo.", english: "I used to get very bored at that job.", tags: W },
  { target: "El equipo de ventas superó los objetivos.", english: "The sales team exceeded the goals.", tags: W },
  { target: "Lo hice todo por la empresa.", english: "I did everything for the company.", tags: W },
  { target: "Solicité el puesto por internet.", english: "I applied for the position online.", tags: W },
  { target: "Me pidieron tres referencias.", english: "They asked me for three references.", tags: W },
  { target: "El empleado nuevo aprendió rápido.", english: "The new employee learned fast.", tags: W },
  { target: "Ayer no había nadie en la oficina.", english: "Yesterday there was nobody in the office.", tags: W },
  { target: "Me tocó organizar el evento de empresa.", english: "I had to organize the company event.", tags: W },
  { target: "El lunes pasado llegué muy temprano.", english: "Last Monday I arrived very early.", tags: W },
  { target: "No me renovaron el contrato.", english: "They didn't renew my contract.", tags: W },
  { target: "Me invitaron a una entrevista en otra ciudad.", english: "They invited me to an interview in another city.", tags: W },
  { target: "Actualicé mi perfil de LinkedIn.", english: "I updated my LinkedIn profile.", tags: W },
  { target: "El compañero nuevo se presentó al equipo.", english: "The new colleague introduced himself to the team.", tags: W, grammar: "Reflexive presentarse = to introduce oneself." },
  { target: "No me dejaron usar el teléfono personal.", english: "They didn't let me use my personal phone.", tags: W },
  { target: "Esa semana tuve tres entrevistas seguidas.", english: "That week I had three interviews in a row.", tags: W },
  { target: "Me inscribí en la bolsa de empleo.", english: "I registered at the job center.", tags: W },
];

// ─── B1 CARDS (~130) ────────────────────────────────────────────
const b1Cards = [
  { target: "Espero que el jefe apruebe el proyecto.", english: "I hope the boss approves the project.", tags: W, grammar: "Subjunctive after esperar que: apruebe (not aprueba)." },
  { target: "La empresa donde trabajo tiene buen ambiente.", english: "The company where I work has a good atmosphere.", tags: W, grammar: "Relative clause: donde = where." },
  { target: "Ojalá me den el ascenso.", english: "I hope they give me the promotion.", tags: W },
  { target: "Es importante que llegues a tiempo.", english: "It's important that you arrive on time.", tags: W, grammar: "Subjunctive after es importante que: llegues." },
  { target: "Dudo que terminen el proyecto hoy.", english: "I doubt they'll finish the project today.", tags: W },
  { target: "El informe que escribí tiene veinte páginas.", english: "The report that I wrote has twenty pages.", tags: W },
  { target: "Necesito que me envíes el archivo.", english: "I need you to send me the file.", tags: W, grammar: "Subjunctive after necesitar que: envíes." },
  { target: "La reunión será mañana a las diez.", english: "The meeting will be tomorrow at ten.", tags: W },
  { target: "¿Podrías ayudarme con este informe?", english: "Could you help me with this report?", tags: W, grammar: "Conditional for polite requests: podrías = could you." },
  { target: "Si tengo tiempo, terminaré el informe hoy.", english: "If I have time, I'll finish the report today.", tags: W },
  { target: "Me alegro de que te hayan ascendido.", english: "I'm glad they promoted you.", tags: W },
  { target: "Buscan a alguien que hable tres idiomas.", english: "They're looking for someone who speaks three languages.", tags: W, grammar: "Subjunctive after indefinite antecedent: que hable." },
  { target: "El mes que viene habrá cambios en la empresa.", english: "Next month there will be changes in the company.", tags: W },
  { target: "No creo que nos suban el sueldo.", english: "I don't think they'll raise our salary.", tags: W },
  { target: "Envíame el presupuesto antes del viernes.", english: "Send me the budget before Friday.", tags: W, grammar: "Imperative with pronoun: envía + me = envíame." },
  { target: "Cuando acabe la reunión, te llamo.", english: "When the meeting ends, I'll call you.", tags: W },
  { target: "Sería mejor posponer la presentación.", english: "It would be better to postpone the presentation.", tags: W },
  { target: "No dejes los documentos en la impresora.", english: "Don't leave the documents at the printer.", tags: W },
  { target: "Me gustaría cambiar de departamento.", english: "I would like to change departments.", tags: W },
  { target: "Avísame cuando llegue el cliente.", english: "Let me know when the client arrives.", tags: W },
  { target: "Es probable que cierren esa sucursal.", english: "It's likely they'll close that branch.", tags: W },
  { target: "Tendrás que quedarte hasta tarde.", english: "You'll have to stay late.", tags: W },
  { target: "El director quiere que presentemos los resultados.", english: "The director wants us to present the results.", tags: W },
  { target: "No es necesario que vengas mañana.", english: "It's not necessary for you to come tomorrow.", tags: W },
  { target: "Si llueve, trabajaré desde casa.", english: "If it rains, I'll work from home.", tags: W },
  { target: "Haz una copia del contrato, por favor.", english: "Make a copy of the contract, please.", tags: W, grammar: "Imperative tú form of hacer: haz." },
  { target: "Me sorprende que no hayan respondido.", english: "I'm surprised they haven't responded.", tags: W },
  { target: "Llamaré al proveedor mañana a primera hora.", english: "I'll call the supplier first thing tomorrow.", tags: W },
  { target: "No creo que sea buena idea.", english: "I don't think it's a good idea.", tags: W },
  { target: "Pon los archivos en la carpeta compartida.", english: "Put the files in the shared folder.", tags: W, grammar: "Imperative tú form of poner: pon." },
  { target: "El proyecto que me asignaron es muy complejo.", english: "The project they assigned me is very complex.", tags: W },
  { target: "Ojalá contraten a más gente.", english: "I hope they hire more people.", tags: W },
  { target: "Quiero que todo esté listo para el lunes.", english: "I want everything to be ready by Monday.", tags: W },
  { target: "Si aceptas la oferta, empezarás en febrero.", english: "If you accept the offer, you'll start in February.", tags: W },
  { target: "Revisa el documento antes de enviarlo.", english: "Review the document before sending it.", tags: W },
  { target: "Me han dicho que van a reestructurar.", english: "They told me they're going to restructure.", tags: W },
  { target: "Sería útil tener un asistente.", english: "It would be useful to have an assistant.", tags: W },
  { target: "No te olvides de enviar el acta de la reunión.", english: "Don't forget to send the meeting minutes.", tags: W },
  { target: "Espero que la entrevista vaya bien.", english: "I hope the interview goes well.", tags: W },
  { target: "Los clientes que vienen mañana son de Alemania.", english: "The clients coming tomorrow are from Germany.", tags: W },
  { target: "Cuando cambie de trabajo, me mudaré.", english: "When I change jobs, I'll move.", tags: W },
  { target: "Te recomiendo que actualices tu currículum.", english: "I recommend you update your resume.", tags: W },
  { target: "No es posible que nos entreguen antes del jueves.", english: "It's not possible for them to deliver before Thursday.", tags: W },
  { target: "Confirma la reserva de la sala de reuniones.", english: "Confirm the meeting room reservation.", tags: W },
  { target: "Mi jefe quiere que trabaje los sábados.", english: "My boss wants me to work on Saturdays.", tags: W },
  { target: "Si no me pagan más, buscaré otro trabajo.", english: "If they don't pay me more, I'll look for another job.", tags: W },
  { target: "Habré terminado el informe para las cinco.", english: "I will have finished the report by five.", tags: W, grammar: "Future perfect: habré terminado = I will have finished." },
  { target: "Es una lástima que no queden plazas.", english: "It's a shame there are no spots left.", tags: W },
  { target: "Me gustaría que me explicaras el proceso.", english: "I'd like you to explain the process to me.", tags: W },
  { target: "El candidato que entrevistamos ayer era muy bueno.", english: "The candidate we interviewed yesterday was very good.", tags: W },
  { target: "Dile al equipo que la reunión se pospone.", english: "Tell the team the meeting is postponed.", tags: W },
  { target: "Si mejora la economía, contrataremos más.", english: "If the economy improves, we'll hire more.", tags: W },
  { target: "Sal de la oficina antes de las ocho.", english: "Leave the office before eight.", tags: W, grammar: "Imperative tú of salir: sal." },
  { target: "No permitiré que me traten mal.", english: "I won't allow them to treat me badly.", tags: W },
  { target: "Lo haré en cuanto tenga un momento.", english: "I'll do it as soon as I have a moment.", tags: W, grammar: "En cuanto + subjunctive for future events: tenga (not tengo)." },
  { target: "La persona que buscan debe tener experiencia.", english: "The person they're looking for must have experience.", tags: W },
  { target: "Antes de que firmes, lee bien el contrato.", english: "Before you sign, read the contract carefully.", tags: W },
  { target: "Tendré los datos listos para la reunión.", english: "I'll have the data ready for the meeting.", tags: W },
  { target: "Es posible que cambien las condiciones.", english: "It's possible they'll change the conditions.", tags: W },
  { target: "Si necesitas algo, dime.", english: "If you need anything, tell me.", tags: W },
  { target: "No creo que el presupuesto sea suficiente.", english: "I don't think the budget is enough.", tags: W },
  { target: "Cuando termine mi contrato, me iré al extranjero.", english: "When my contract ends, I'll go abroad.", tags: W },
  { target: "Me preocupa que no cumplamos el plazo.", english: "I'm worried we won't meet the deadline.", tags: W },
  { target: "Prepara una propuesta para el cliente.", english: "Prepare a proposal for the client.", tags: W },
  { target: "El puesto que ofrecen tiene buen sueldo.", english: "The position they're offering has a good salary.", tags: W },
  { target: "Ojalá mejoren las condiciones de trabajo.", english: "I hope they improve the working conditions.", tags: W },
  { target: "Me iré de la empresa si no hay cambios.", english: "I'll leave the company if there are no changes.", tags: W },
  { target: "Sería conveniente agendar una reunión.", english: "It would be convenient to schedule a meeting.", tags: W },
  { target: "No te vayas sin guardar los cambios.", english: "Don't leave without saving the changes.", tags: W, grammar: "Negative tú command of irse: no te vayas." },
  { target: "Quiero que alguien revise este contrato.", english: "I want someone to review this contract.", tags: W },
  { target: "Cuando haya una vacante, te aviso.", english: "When there's an opening, I'll let you know.", tags: W },
  { target: "Ten cuidado con esos datos confidenciales.", english: "Be careful with that confidential data.", tags: W, grammar: "Imperative tú of tener: ten." },
  { target: "Si obtienen la inversión, expandirán el negocio.", english: "If they get the investment, they'll expand the business.", tags: W },
  { target: "No creo que nos den vacaciones en julio.", english: "I don't think they'll give us vacation in July.", tags: W },
  { target: "Deberías hablar con tu supervisor.", english: "You should talk to your supervisor.", tags: W },
  { target: "Es necesario que todos firmen el acuerdo.", english: "It's necessary for everyone to sign the agreement.", tags: W },
  { target: "Me molesta que no avisen con tiempo.", english: "It bothers me that they don't give notice in time.", tags: W },
  { target: "Habrán tomado la decisión para el martes.", english: "They will have made the decision by Tuesday.", tags: W },
  { target: "Dudo que acepten nuestra propuesta.", english: "I doubt they'll accept our proposal.", tags: W },
  { target: "El jefe que teníamos antes era más flexible.", english: "The boss we had before was more flexible.", tags: W },
  { target: "Ten paciencia, el proceso tarda.", english: "Be patient, the process takes time.", tags: W },
  { target: "Me gustaría saber cuándo anunciarán los resultados.", english: "I'd like to know when they'll announce the results.", tags: W },
  { target: "No le digas nada hasta que sea oficial.", english: "Don't tell him anything until it's official.", tags: W },
  { target: "El equipo que lidera Juan está en primer lugar.", english: "The team Juan leads is in first place.", tags: W },
  { target: "Si consigo ese puesto, ganaré el doble.", english: "If I get that position, I'll earn double.", tags: W },
  { target: "Imprime las etiquetas para el envío.", english: "Print the labels for the shipment.", tags: W },
  { target: "Nos reuniremos con el cliente el jueves.", english: "We'll meet with the client on Thursday.", tags: W },
  { target: "Habremos acabado para cuando llegue el director.", english: "We'll have finished by the time the director arrives.", tags: W },
  { target: "Es mejor que esperemos a tener más información.", english: "It's better for us to wait until we have more information.", tags: W },
  { target: "Sería genial que nos dieran un bonus.", english: "It would be great if they gave us a bonus.", tags: W },
  { target: "Trae los informes a mi despacho.", english: "Bring the reports to my office.", tags: W, grammar: "Imperative tú of traer: trae." },
  { target: "El departamento que más ha crecido es marketing.", english: "The department that has grown the most is marketing.", tags: W },
  { target: "Cuando asciendan a alguien, espero que sea justo.", english: "When they promote someone, I hope it's fair.", tags: W },
  { target: "Si pudieras elegir, ¿qué puesto querrías?", english: "If you could choose, which position would you want?", tags: W },
  { target: "Los datos que necesitas están en esta carpeta.", english: "The data you need is in this folder.", tags: W },
  { target: "Ojalá el jefe entienda nuestra posición.", english: "I hope the boss understands our position.", tags: W },
  { target: "Leeré tu propuesta esta tarde.", english: "I'll read your proposal this afternoon.", tags: W },
  { target: "No creo que haya suficiente presupuesto.", english: "I don't think there's enough budget.", tags: W },
  { target: "Deberías pedir esa promoción.", english: "You should ask for that promotion.", tags: W },
  { target: "Me sorprendería que lo rechazaran.", english: "I'd be surprised if they rejected it.", tags: W },
  { target: "Dile que venga a la reunión a las cuatro.", english: "Tell him to come to the meeting at four.", tags: W },
  { target: "El salario que ofrecen no está mal.", english: "The salary they're offering isn't bad.", tags: W },
  { target: "Espero que la negociación salga bien.", english: "I hope the negotiation goes well.", tags: W },
  { target: "Será difícil encontrar un reemplazo.", english: "It will be hard to find a replacement.", tags: W },
  { target: "Dudo que logremos reducir los costes tanto.", english: "I doubt we'll manage to reduce costs that much.", tags: W },
  { target: "Necesitaré tu ayuda con la auditoría.", english: "I'll need your help with the audit.", tags: W },
  { target: "El empleado que contraten debe saber inglés.", english: "The employee they hire must know English.", tags: W },
  { target: "Te mandaré el enlace cuando lo tenga.", english: "I'll send you the link when I have it.", tags: W },
  { target: "Es urgente que resolvamos este problema.", english: "It's urgent that we solve this problem.", tags: W },
  { target: "Si renovamos el contrato, podremos seguir.", english: "If we renew the contract, we'll be able to continue.", tags: W },
  { target: "¿Podrías reenviarme ese correo?", english: "Could you forward me that email?", tags: W },
  { target: "Cuando tenga la respuesta, te informaré.", english: "When I have the answer, I'll let you know.", tags: W },
  { target: "Espero que no cancelen la formación.", english: "I hope they don't cancel the training.", tags: W },
  { target: "No quiero que se enteren antes de tiempo.", english: "I don't want them to find out too soon.", tags: W },
  { target: "Si me contratan, empiezo el mes que viene.", english: "If they hire me, I start next month.", tags: W },
  { target: "Es raro que no hayan convocado la reunión.", english: "It's odd they haven't called the meeting.", tags: W },
  { target: "El equipo que formamos consiguió muy buenos resultados.", english: "The team we formed achieved very good results.", tags: W },
  { target: "Me gustaría que me trasladaran a la sede de Madrid.", english: "I'd like them to transfer me to the Madrid office.", tags: W },
  { target: "Si nos organizamos bien, acabaremos a tiempo.", english: "If we organize well, we'll finish on time.", tags: W },
  { target: "Deberías negociar un mejor horario.", english: "You should negotiate a better schedule.", tags: W },
];

// ─── B2 CARDS (~130) ────────────────────────────────────────────
const b2Cards = [
  { target: "Si hubiera preparado mejor la entrevista, me habrían contratado.", english: "If I had prepared better for the interview, they would have hired me.", tags: W, grammar: "Conditional III: Si + pluperfect subjunctive, conditional perfect." },
  { target: "El contrato fue firmado por ambas partes.", english: "The contract was signed by both parties.", tags: W, grammar: "Passive voice: ser + past participle (fue firmado)." },
  { target: "De haber sabido, no habría aceptado el puesto.", english: "Had I known, I wouldn't have accepted the position.", tags: W, grammar: "De + infinitive compound as alternative to si clause." },
  { target: "A pesar de que el sueldo era bajo, acepté la oferta.", english: "Despite the salary being low, I accepted the offer.", tags: W },
  { target: "Si tuviera más experiencia, me ascenderían.", english: "If I had more experience, they would promote me.", tags: W, grammar: "Conditional II: Si + imperfect subjunctive, conditional." },
  { target: "La propuesta fue rechazada por la junta directiva.", english: "The proposal was rejected by the board of directors.", tags: W },
  { target: "No habría dimitido si me hubieran escuchado.", english: "I wouldn't have resigned if they had listened to me.", tags: W },
  { target: "Es fundamental que se respeten los plazos.", english: "It's essential that deadlines are respected.", tags: W },
  { target: "Aunque me ofrecieran el doble, no volvería.", english: "Even if they offered me double, I wouldn't go back.", tags: W, grammar: "Aunque + imperfect subjunctive for hypothetical concession." },
  { target: "La decisión fue tomada sin consultarnos.", english: "The decision was made without consulting us.", tags: W },
  { target: "Si no fuera por el equipo, ya habría renunciado.", english: "If it weren't for the team, I would have already resigned.", tags: W },
  { target: "El proyecto habría sido un éxito de no ser por los recortes.", english: "The project would have been a success if not for the cuts.", tags: W },
  { target: "Dado que no cumplieron el contrato, tomaremos medidas legales.", english: "Given that they didn't fulfill the contract, we'll take legal action.", tags: W },
  { target: "Los empleados fueron informados mediante un comunicado oficial.", english: "The employees were informed through an official statement.", tags: W },
  { target: "Si pudiera elegir, trabajaría solo cuatro días.", english: "If I could choose, I would work only four days.", tags: W },
  { target: "La empresa habría quebrado de no ser por la inversión.", english: "The company would have gone bankrupt if not for the investment.", tags: W },
  { target: "Por mucho que se esfuerce, no logrará el ascenso.", english: "No matter how hard he tries, he won't get the promotion.", tags: W, grammar: "Por mucho que + subjunctive: concessive with emphasis." },
  { target: "Los resultados fueron presentados ante el consejo de administración.", english: "The results were presented to the board of directors.", tags: W },
  { target: "Si me hubieran avisado antes, habría podido asistir.", english: "If they had told me earlier, I could have attended.", tags: W },
  { target: "No obstante, la empresa sigue siendo competitiva.", english: "Nevertheless, the company remains competitive.", tags: W },
  { target: "Si fuéramos más eficientes, reduciríamos costes.", english: "If we were more efficient, we would reduce costs.", tags: W },
  { target: "La factura fue emitida con un error de cálculo.", english: "The invoice was issued with a calculation error.", tags: W },
  { target: "Aun cuando nos ofrecieran un descuento, no aceptaríamos.", english: "Even if they offered us a discount, we wouldn't accept.", tags: W },
  { target: "Los datos fueron analizados por el departamento de finanzas.", english: "The data was analyzed by the finance department.", tags: W },
  { target: "Si hubiera negociado mejor, tendría mejores condiciones.", english: "If I had negotiated better, I would have better conditions.", tags: W, grammar: "Mixed conditional: Si + pluperfect subj + conditional (present result)." },
  { target: "Siempre y cuando cumplan los objetivos, recibirán el bonus.", english: "As long as they meet the targets, they'll receive the bonus.", tags: W },
  { target: "El puesto fue cubierto por un candidato interno.", english: "The position was filled by an internal candidate.", tags: W },
  { target: "Si la empresa invirtiera en formación, mejoraríamos.", english: "If the company invested in training, we would improve.", tags: W },
  { target: "Habría aceptado la oferta si las condiciones hubieran sido mejores.", english: "I would have accepted the offer if the conditions had been better.", tags: W },
  { target: "Pese a los recortes, lograron mantener la plantilla.", english: "Despite the cuts, they managed to keep the staff.", tags: W },
  { target: "El contrato habría sido renovado si no fuera por los cambios.", english: "The contract would have been renewed if it weren't for the changes.", tags: W },
  { target: "Con tal de que acepten las condiciones, firmaremos mañana.", english: "Provided they accept the conditions, we'll sign tomorrow.", tags: W, grammar: "Con tal de que + subjunctive: conditional conjunction." },
  { target: "Las negociaciones fueron llevadas a cabo por el equipo legal.", english: "The negotiations were carried out by the legal team.", tags: W },
  { target: "Si hubiéramos lanzado antes, habríamos dominado el mercado.", english: "If we had launched earlier, we would have dominated the market.", tags: W },
  { target: "En caso de que surja algún problema, contacta con soporte.", english: "In case any problem comes up, contact support.", tags: W },
  { target: "La empresa fue adquirida por un grupo multinacional.", english: "The company was acquired by a multinational group.", tags: W },
  { target: "Si yo dirigiera esta empresa, cambiaría muchas cosas.", english: "If I ran this company, I would change many things.", tags: W },
  { target: "De no haber sido por el plazo, habríamos hecho un mejor trabajo.", english: "If it hadn't been for the deadline, we would have done a better job.", tags: W },
  { target: "A fin de que todos estén informados, enviaré un resumen.", english: "So that everyone is informed, I'll send a summary.", tags: W },
  { target: "Las quejas fueron atendidas por el departamento de atención al cliente.", english: "The complaints were handled by the customer service department.", tags: W },
  { target: "Si tuviéramos más presupuesto, contrataríamos a dos personas más.", english: "If we had more budget, we would hire two more people.", tags: W },
  { target: "La reunión habría sido más productiva con una agenda clara.", english: "The meeting would have been more productive with a clear agenda.", tags: W },
  { target: "Mientras no se solucione el problema, no avanzaremos.", english: "As long as the problem isn't solved, we won't make progress.", tags: W },
  { target: "El informe fue revisado y aprobado por tres departamentos.", english: "The report was reviewed and approved by three departments.", tags: W },
  { target: "Si no hubiera llovido, habríamos llegado a tiempo a la conferencia.", english: "If it hadn't rained, we would have arrived on time to the conference.", tags: W },
  { target: "Es imprescindible que se cumplan las normas de seguridad.", english: "It is essential that safety regulations are followed.", tags: W },
  { target: "Habríamos cerrado el trato si el precio hubiera sido razonable.", english: "We would have closed the deal if the price had been reasonable.", tags: W },
  { target: "A menos que bajen el precio, no compraremos.", english: "Unless they lower the price, we won't buy.", tags: W, grammar: "A menos que + subjunctive: negative conditional." },
  { target: "Las metas fueron establecidas al comienzo del trimestre.", english: "The goals were set at the beginning of the quarter.", tags: W },
  { target: "Si pudiera retroceder en el tiempo, habría estudiado otra carrera.", english: "If I could go back in time, I would have studied a different career.", tags: W },
  { target: "Dicho esto, el rendimiento del equipo ha mejorado.", english: "That said, the team's performance has improved.", tags: W },
  { target: "Si hubiera más transparencia, los empleados estarían más contentos.", english: "If there were more transparency, the employees would be happier.", tags: W },
  { target: "La sede fue trasladada a las afueras de la ciudad.", english: "The headquarters was relocated to the outskirts of the city.", tags: W },
  { target: "Aunque el mercado estuviera en crisis, seguiríamos adelante.", english: "Even if the market were in crisis, we would carry on.", tags: W },
  { target: "Los gastos fueron reducidos en un veinte por ciento.", english: "Expenses were reduced by twenty percent.", tags: W },
  { target: "Si me lo hubieran propuesto antes, habría dicho que sí.", english: "If they had proposed it to me earlier, I would have said yes.", tags: W },
  { target: "Es preciso que todos los empleados completen la formación.", english: "It's necessary for all employees to complete the training.", tags: W },
  { target: "El premio fue otorgado al empleado del mes.", english: "The award was given to the employee of the month.", tags: W },
  { target: "Si el director estuviera aquí, tomaría otra decisión.", english: "If the director were here, he would make a different decision.", tags: W },
  { target: "A no ser que cambien las condiciones, no firmaré.", english: "Unless the conditions change, I won't sign.", tags: W },
  { target: "Los nuevos procedimientos fueron implementados la semana pasada.", english: "The new procedures were implemented last week.", tags: W },
  { target: "Si nos hubiéramos diversificado antes, no tendríamos estos problemas.", english: "If we had diversified earlier, we wouldn't have these problems.", tags: W },
  { target: "De cara a la próxima temporada, debemos replantear la estrategia.", english: "Looking ahead to next season, we should rethink the strategy.", tags: W },
  { target: "Si la competencia bajara los precios, perderíamos clientes.", english: "If the competition lowered prices, we would lose clients.", tags: W },
  { target: "El plan fue elaborado tras meses de investigación.", english: "The plan was drawn up after months of research.", tags: W },
  { target: "Si hubiera delegado mejor, no estaría tan agotado.", english: "If I had delegated better, I wouldn't be so exhausted.", tags: W },
  { target: "No solo subieron los precios, sino que también redujeron la calidad.", english: "Not only did they raise prices, but they also reduced quality.", tags: W, grammar: "No solo... sino que también: correlative connectors." },
  { target: "La política de teletrabajo fue aprobada por unanimidad.", english: "The remote work policy was approved unanimously.", tags: W },
  { target: "Si tuviera su formación, optaría a ese puesto.", english: "If I had his qualifications, I would apply for that position.", tags: W },
  { target: "Ni siquiera habría considerado esa oferta.", english: "I wouldn't have even considered that offer.", tags: W },
  { target: "A pesar de los obstáculos, el equipo cumplió los objetivos.", english: "Despite the obstacles, the team met the targets.", tags: W },
  { target: "El salario fue negociado directamente con la dirección.", english: "The salary was negotiated directly with management.", tags: W },
  { target: "Si pudiéramos automatizar ese proceso, ahorraríamos tiempo.", english: "If we could automate that process, we would save time.", tags: W },
  { target: "Habría sido más eficiente si hubiéramos usado el software nuevo.", english: "It would have been more efficient if we had used the new software.", tags: W },
  { target: "Sea cual sea tu decisión, la respetaré.", english: "Whatever your decision, I'll respect it.", tags: W, grammar: "Sea cual sea: subjunctive reduplication for 'whatever it may be'." },
  { target: "Los despidos fueron anunciados sin previo aviso.", english: "The layoffs were announced without prior notice.", tags: W },
  { target: "Si yo estuviera en tu lugar, pediría un traslado.", english: "If I were in your place, I would request a transfer.", tags: W },
  { target: "De no haberse fusionado, ambas empresas habrían cerrado.", english: "Had they not merged, both companies would have closed.", tags: W },
  { target: "Independientemente de lo que digan, la decisión ya está tomada.", english: "Regardless of what they say, the decision has already been made.", tags: W },
  { target: "La auditoría fue realizada por una firma externa.", english: "The audit was carried out by an external firm.", tags: W },
  { target: "Si nos hubieran dado más recursos, los resultados habrían sido otros.", english: "If they had given us more resources, the results would have been different.", tags: W },
  { target: "Tanto si aceptan como si no, seguiremos con el plan.", english: "Whether they accept or not, we'll continue with the plan.", tags: W, grammar: "Tanto si... como si: whether... or. Uses indicative or subjunctive." },
  { target: "La estrategia fue diseñada para aumentar la cuota de mercado.", english: "The strategy was designed to increase market share.", tags: W },
  { target: "Si el proyecto hubiera ido bien, me habrían dado una promoción.", english: "If the project had gone well, they would have given me a promotion.", tags: W },
  { target: "Por más que intenten convencerme, no cambiaré de opinión.", english: "No matter how much they try to convince me, I won't change my mind.", tags: W },
  { target: "Fue entonces cuando decidí emprender por mi cuenta.", english: "It was then that I decided to start my own business.", tags: W },
  { target: "Las inversiones fueron aprobadas tras un largo debate.", english: "The investments were approved after a long debate.", tags: W },
  { target: "Si hubiera un sindicato fuerte, las condiciones serían mejores.", english: "If there were a strong union, conditions would be better.", tags: W },
  { target: "Más allá de los resultados económicos, el equipo está motivado.", english: "Beyond the financial results, the team is motivated.", tags: W },
  { target: "El proceso de selección fue gestionado por una consultora.", english: "The selection process was managed by a consulting firm.", tags: W },
  { target: "Si supiera programar, no necesitaría contratar a nadie.", english: "If I knew how to code, I wouldn't need to hire anyone.", tags: W },
  { target: "Habríamos evitado el problema si hubiéramos leído las condiciones.", english: "We would have avoided the problem if we had read the conditions.", tags: W },
  { target: "Puesto que ya se firmó el acuerdo, no hay marcha atrás.", english: "Since the agreement has already been signed, there's no going back.", tags: W },
  { target: "Los beneficios fueron repartidos entre los accionistas.", english: "The profits were distributed among the shareholders.", tags: W },
  { target: "Si me dieran a elegir, preferiría el puesto en Barcelona.", english: "If they let me choose, I would prefer the position in Barcelona.", tags: W },
  { target: "No habría llegado tan lejos sin el apoyo de mi equipo.", english: "I wouldn't have gotten this far without my team's support.", tags: W },
  { target: "Si bien el informe es completo, falta el análisis financiero.", english: "Although the report is complete, the financial analysis is missing.", tags: W, grammar: "Si bien: formal concessive connector = although." },
  { target: "Las entrevistas fueron realizadas durante la primera semana de marzo.", english: "The interviews were conducted during the first week of March.", tags: W },
  { target: "Si las ventas cayeran un diez por ciento, tendríamos pérdidas.", english: "If sales dropped ten percent, we would have losses.", tags: W },
  { target: "De habérmelo dicho, habría preparado otra presentación.", english: "Had you told me, I would have prepared a different presentation.", tags: W },
  { target: "En virtud del acuerdo, ambas partes se comprometen a cumplir.", english: "By virtue of the agreement, both parties commit to compliance.", tags: W },
  { target: "Los empleados fueron formados en el uso del nuevo sistema.", english: "The employees were trained in the use of the new system.", tags: W },
  { target: "Si la reunión no hubiera durado tanto, habríamos acabado antes.", english: "If the meeting hadn't lasted so long, we would have finished earlier.", tags: W },
  { target: "Es improbable que acepten esas condiciones.", english: "It's unlikely they'll accept those conditions.", tags: W },
  { target: "La fusión fue anunciada en una rueda de prensa.", english: "The merger was announced at a press conference.", tags: W },
  { target: "Si contáramos con más financiación, abriríamos otra sede.", english: "If we had more funding, we would open another office.", tags: W },
  { target: "Habría renunciado de no ser por las responsabilidades familiares.", english: "I would have resigned if it weren't for family responsibilities.", tags: W },
  { target: "En lo que respecta a los plazos, estamos al día.", english: "As far as deadlines are concerned, we're on track.", tags: W },
  { target: "Los cambios fueron bien recibidos por la mayoría del personal.", english: "The changes were well received by most of the staff.", tags: W },
  { target: "Si hubiera más comunicación, habría menos malentendidos.", english: "If there were more communication, there would be fewer misunderstandings.", tags: W },
  { target: "No fue sino hasta que renuncié que valoraron mi trabajo.", english: "It wasn't until I resigned that they valued my work.", tags: W },
  { target: "Las condiciones laborales fueron mejoradas tras la negociación.", english: "The working conditions were improved after the negotiation.", tags: W },
  { target: "Si redujéramos los plazos de entrega, seríamos más competitivos.", english: "If we reduced delivery times, we would be more competitive.", tags: W },
  { target: "No habríamos perdido la cuenta si hubiéramos reaccionado a tiempo.", english: "We wouldn't have lost the account if we had reacted in time.", tags: W },
  { target: "Comoquiera que sea, debemos presentar los resultados el lunes.", english: "Be that as it may, we must present the results on Monday.", tags: W },
  { target: "La indemnización fue calculada según los años de servicio.", english: "The severance was calculated based on years of service.", tags: W },
  { target: "Si me nombraran director, lo primero que haría sería reorganizar.", english: "If they named me director, the first thing I'd do would be to reorganize.", tags: W },
  { target: "De haberlo pensado mejor, no habría firmado ese contrato.", english: "Had I thought about it more, I wouldn't have signed that contract.", tags: W },
  { target: "La reestructuración fue necesaria para la supervivencia de la empresa.", english: "The restructuring was necessary for the company's survival.", tags: W },
  { target: "Si pudiera volver a empezar, elegiría otra profesión.", english: "If I could start over, I would choose a different profession.", tags: W },
  { target: "Habida cuenta de la situación, se tomaron medidas extraordinarias.", english: "Given the situation, extraordinary measures were taken.", tags: W, grammar: "Habida cuenta de: formal connector meaning 'given' or 'considering'." },
  { target: "La expansión internacional fue clave para el crecimiento de la empresa.", english: "International expansion was key to the company's growth.", tags: W },
  { target: "Si no fuera por la burocracia, todo iría más rápido.", english: "If it weren't for the bureaucracy, everything would go faster.", tags: W },
  { target: "No habría sido posible sin la colaboración de todos.", english: "It wouldn't have been possible without everyone's collaboration.", tags: W },
  { target: "Así las cosas, la empresa decidió cerrar la filial.", english: "As things stood, the company decided to close the subsidiary.", tags: W },
  { target: "Los informes fueron archivados según el protocolo establecido.", english: "The reports were filed according to the established protocol.", tags: W },
  { target: "Si hubiera estudiado derecho laboral, habría detectado la cláusula.", english: "If I had studied labor law, I would have caught the clause.", tags: W },
  { target: "La jornada laboral fue reducida a treinta y cinco horas semanales.", english: "The workweek was reduced to thirty-five hours.", tags: W },
  { target: "Si la empresa hubiera invertido en innovación, no estaríamos así.", english: "If the company had invested in innovation, we wouldn't be in this situation.", tags: W },
  { target: "No obstante lo anterior, el balance general es positivo.", english: "Notwithstanding the above, the overall balance is positive.", tags: W },
  { target: "Si me hubieran incluido en la reunión, habría aportado ideas.", english: "If they had included me in the meeting, I would have contributed ideas.", tags: W },
  { target: "La marca fue registrada a nombre de la empresa matriz.", english: "The brand was registered under the parent company's name.", tags: W },
  { target: "De no ser por el seguro, la empresa habría asumido pérdidas enormes.", english: "If it weren't for insurance, the company would have taken enormous losses.", tags: W },
  { target: "Si reorganizáramos la cadena de suministro, seríamos más ágiles.", english: "If we reorganized the supply chain, we would be more agile.", tags: W },
  { target: "Las nuevas normativas fueron publicadas en el boletín oficial.", english: "The new regulations were published in the official gazette.", tags: W },
];

// ─── Combine all cards ──────────────────────────────────────────
const allNewCards = [...a1Cards, ...a2Cards, ...b1Cards, ...b2Cards];

console.log(`\nNew cards defined: ${allNewCards.length}`);
console.log(`  A1: ${a1Cards.length}`);
console.log(`  A2: ${a2Cards.length}`);
console.log(`  B1: ${b1Cards.length}`);
console.log(`  B2: ${b2Cards.length}`);

// ─── Dedup against existing deck ────────────────────────────────
const deduped = allNewCards.filter(c => {
  const key = c.target.toLowerCase().trim();
  if (existingTargets.has(key)) {
    console.log(`  SKIP (dup): ${c.target}`);
    return false;
  }
  existingTargets.add(key); // also dedup within batch
  return true;
});

console.log(`\nAfter dedup: ${deduped.length} cards to add (${allNewCards.length - deduped.length} duplicates skipped)`);

// ─── Assign IDs and append ──────────────────────────────────────
let maxId = Math.max(...deck.map(c => c.id));
console.log(`Max existing ID: ${maxId}`);

const cardsToAdd = deduped.map((c, i) => ({
  id: maxId + 1 + i,
  target: c.target,
  english: c.english,
  audio: "",
  tags: c.tags,
  ...(c.grammar ? { grammar: c.grammar } : {}),
}));

const newDeck = [...deck, ...cardsToAdd];
fs.writeFileSync(DECK_PATH, JSON.stringify(newDeck, null, 2) + '\n', 'utf-8');

// ─── Stats ──────────────────────────────────────────────────────
const withGrammar = cardsToAdd.filter(c => c.grammar).length;
console.log(`\nDone! Added ${cardsToAdd.length} new work cards.`);
console.log(`  With grammar notes: ${withGrammar} (${(100 * withGrammar / cardsToAdd.length).toFixed(1)}%)`);
console.log(`  New deck size: ${newDeck.length}`);
console.log(`  ID range: ${cardsToAdd[0]?.id} – ${cardsToAdd[cardsToAdd.length - 1]?.id}`);

// Tag distribution in new deck
const tagCounts = { general: 0, work: 0, travel: 0, family: 0 };
newDeck.forEach(c => c.tags.forEach(t => { if (tagCounts[t] !== undefined) tagCounts[t]++; }));
console.log(`\nTag distribution (full deck):`);
Object.entries(tagCounts).forEach(([tag, count]) => {
  console.log(`  ${tag}: ${count} (${(100 * count / newDeck.length).toFixed(1)}%)`);
});
