#!/usr/bin/env python3
"""
Fix Swedish dictionary:
1. Correct POS tags (especially verbs wrongly tagged as 'n')
2. Add English translations for self-translated entries
3. Fix obvious misclassifications
"""

import re
import sys

INPUT = 'src/data/dictionary/sv.ts'

# ── Large translation map for common Swedish words ──────────────────
TRANSLATIONS = {
    # Common words
    'absolut': 'absolutely',
    'adress': 'address',
    'advent': 'Advent',
    'adventskalendern': 'the Advent calendar',
    'aftonbrisen': 'the evening breeze',
    'akta': 'to watch out/be careful',
    'aktiviteterna': 'the activities',
    'aktuella': 'current/relevant',
    'albumet': 'the album',
    'alkohol': 'alcohol',
    'all': 'all',
    'allas': 'everyone\'s',
    'alldeles': 'completely/quite',
    'allergi': 'allergy',
    'allergisk': 'allergic',
    'allihopa': 'all of you/everyone',
    'allmänhet': 'the public/general',
    'allmänt': 'generally',
    'alls': 'at all',
    'allteftersom': 'as/depending on',
    'allting': 'everything',
    'alltnog': 'all the same',
    'allvar': 'seriousness',
    'allvarlig': 'serious',
    'allvarligt': 'seriously',
    'altan': 'patio/terrace',
    'alternativ': 'alternative',
    'an': 'on',
    'analys': 'analysis',
    'analysen': 'the analysis',
    'analysram': 'analytical framework',
    'andades': 'breathed',
    'andar': 'breathes',
    'andetag': 'breath',
    'anförtrodde': 'entrusted',
    'angeläget': 'urgent/pressing',
    'angenäm': 'pleasant',
    'angreppssättet': 'the approach',
    'angående': 'regarding/concerning',
    'anhåller': 'requests/detains',
    'aning': 'idea/hunch',
    'anka': 'duck',
    'ankommer': 'arrives/depends',
    'anledningen': 'the reason',
    'anletsdrag': 'facial features',
    'anlitade': 'hired',
    'anlände': 'arrived',
    'anländer': 'arrives',
    'anlänt': 'arrived (supine)',
    'anmäla': 'to report/register',
    'anmälde': 'reported',
    'anmäler': 'reports',
    'anmärkningsvärt': 'remarkably',
    'annorlunda': 'differently/different',
    'anser': 'considers/believes',
    'anses': 'is considered',
    'ansiktet': 'the face',
    'anställda': 'employees/employed',
    'ansvaret': 'the responsibility',
    'ansåg': 'considered/deemed',
    'ansökan': 'application',
    'antagligen': 'probably',
    'antagna': 'adopted/accepted',
    'antar': 'assumes/adopts',
    'anteckningar': 'notes',
    'antog': 'assumed/adopted',
    'antogs': 'was adopted',
    'antydde': 'hinted/suggested',
    'användes': 'was used',
    'används': 'is used',
    'apoteket': 'the pharmacy',
    'app': 'app',
    'appen': 'the app',
    'arbetar': 'works',
    'arbetslivet': 'working life',
    'arbetsvillkoren': 'working conditions',
    'arga': 'angry',
    'argumentet': 'the argument',
    'arkitektur': 'architecture',
    'arlanda': 'Arlanda',
    'armen': 'the arm',
    'artikeln': 'the article',
    'artist': 'artist',
    'artisterna': 'the artists',
    'atmosfär': 'atmosphere',
    'automatiskt': 'automatically',
    'avbröt': 'interrupted',
    'avdelning': 'department',
    'avdelningar': 'departments',
    'avdelningarna': 'the departments',
    'avfarten': 'the exit (road)',
    'avgiftsfri': 'free of charge',
    'avgjord': 'decided/settled',
    'avgår': 'departs',
    'avgör': 'decides',
    'avgörande': 'decisive/crucial',
    'avhandlingen': 'the thesis/dissertation',
    'avkunnades': 'was pronounced',
    'avlägsna': 'remote/distant',
    'avsaknad': 'absence/lack',
    'avseende': 'regard/respect',
    'avses': 'is intended',
    'avskedet': 'the farewell',
    'avslagna': 'rejected',
    'avslappnande': 'relaxing',
    'avslogs': 'was rejected',
    'avslutas': 'is concluded',
    'avslutningsvis': 'in conclusion',
    'avslöjade': 'revealed',
    'avslöjar': 'reveals',
    'avtalet': 'the agreement',
    'avvaktan': 'awaiting/pending',
    'avverkades': 'was felled/logged',
    'avvikelser': 'deviations',
    'avvägningsfråga': 'balancing question',
    'bad': 'asked/bath',
    'bada': 'to bathe/swim',
    'badar': 'bathes/swims',
    'bakas': 'is baked',
    'baket': 'the baking',
    'bakgrund': 'background',
    'banken': 'the bank',
    'bar': 'carried/bare',
    'barnbidraget': 'the child benefit',
    'barndomen': 'the childhood',
    'barnens': 'the children\'s',
    'barnkonventionen': 'the Convention on the Rights of the Child',
    'barnmeny': 'children\'s menu',
    'barnombudsmannen': 'the Children\'s Ombudsman',
    'barns': 'children\'s',
    'baserades': 'was based',
    'baseras': 'is based',
    'beaktas': 'is taken into account',
    'beaktats': 'has been taken into account',
    'bearbetats': 'has been processed',
    'bedömdes': 'was assessed',
    'bedöms': 'is assessed',
    'befintliga': 'existing',
    'befogenhet': 'authority/competence',
    'befolkningen': 'the population',
    'befriande': 'liberating',
    'began': 'committed',
    'begreppen': 'the concepts',
    'begreppet': 'the concept',
    'begrundade': 'pondered',
    'begränsad': 'limited',
    'begränsas': 'is limited',
    'begränsningar': 'limitations',
    'behandlade': 'treated/handled',
    'behandlades': 'was treated',
    'behandlar': 'treats/handles',
    'behandlas': 'is treated',
    'behövde': 'needed',
    'behövdes': 'was needed',
    # B continued
    'bekant': 'familiar/acquaintance',
    'bekanta': 'acquaintances',
    'beklagade': 'regretted/lamented',
    'bekräftade': 'confirmed',
    'bekräftar': 'confirms',
    'bekväm': 'comfortable',
    'belopp': 'amount',
    'beloppet': 'the amount',
    'belyser': 'illuminates/highlights',
    'bemöta': 'to respond to/counter',
    'ben': 'leg/bone',
    'benen': 'the legs',
    'bensin': 'gasoline/petrol',
    'beordrade': 'ordered/commanded',
    'beredd': 'prepared/ready',
    'beredda': 'prepared',
    'beredskap': 'readiness/preparedness',
    'berg': 'mountain',
    'berget': 'the mountain',
    'bero': 'to depend',
    'beror': 'depends',
    'berättade': 'told/narrated',
    'berättar': 'tells/narrates',
    'berättelse': 'story/narrative',
    'berättelsen': 'the story',
    'besked': 'message/answer',
    'beskedet': 'the message',
    'beslut': 'decision',
    'beslutar': 'decides',
    'beslutat': 'decided',
    'beslutade': 'decided',
    'beslutet': 'the decision',
    'bestod': 'consisted',
    'bestraffning': 'punishment',
    'besviken': 'disappointed',
    'besvär': 'trouble/difficulty',
    'besvärad': 'troubled',
    'besök': 'visit',
    'besöka': 'to visit',
    'besöker': 'visits',
    'besöket': 'the visit',
    'besökta': 'visited',
    'betalade': 'paid',
    'betalar': 'pays',
    'betalt': 'paid (supine)',
    'betecknas': 'is designated',
    'betrakta': 'to regard/consider',
    'betraktade': 'regarded/considered',
    'betyda': 'to mean',
    'betydde': 'meant',
    'betydelse': 'meaning/importance',
    'betydelsen': 'the meaning',
    'betyder': 'means',
    'beundrade': 'admired',
    'bevara': 'to preserve',
    'bevarade': 'preserved',
    'bevis': 'proof/evidence',
    'bevisa': 'to prove',
    'bevisade': 'proved',
    'bevisning': 'evidence',
    'bibliotek': 'library',
    'biblioteket': 'the library',
    'bidrag': 'contribution/grant',
    'bidraget': 'the contribution',
    'bidrar': 'contributes',
    'bil': 'car',
    'bilen': 'the car',
    'billig': 'cheap',
    'billigare': 'cheaper',
    'billigaste': 'cheapest',
    'billigt': 'cheaply/cheap (neuter)',
    'biograf': 'cinema',
    'biografen': 'the cinema',
    'bit': 'piece/bit',
    'bitar': 'pieces',
    'bjöd': 'invited/offered',
    'blad': 'leaf/page',
    'bland': 'among',
    'blandat': 'mixed',
    'blick': 'gaze/glance',
    'blicken': 'the gaze',
    'blev': 'became',
    'blind': 'blind',
    'blod': 'blood',
    'blodet': 'the blood',
    'blomma': 'flower',
    'blommor': 'flowers',
    'blommorna': 'the flowers',
    'blott': 'mere/only',
    'blåser': 'blows',
    'bo': 'to live/reside',
    'bok': 'book',
    'boken': 'the book',
    'bolag': 'company',
    'bolaget': 'the company',
    'bor': 'lives/resides',
    'bord': 'table',
    'bordet': 'the table',
    'borgmästaren': 'the mayor',
    'borta': 'away/gone',
    'bostaden': 'the residence',
    'bostad': 'residence',
    'bostadsområdet': 'the residential area',
    'bot': 'fine/remedy',
    'bred': 'wide/broad',
    'bredvid': 'next to/beside',
    'brev': 'letter',
    'brevet': 'the letter',
    'briljant': 'brilliant',
    'brinna': 'to burn',
    'brist': 'lack/shortage',
    'bro': 'bridge',
    'bron': 'the bridge',
    'bror': 'brother',
    'broschyr': 'brochure',
    'brott': 'crime/offence',
    'brottet': 'the crime',
    'bruk': 'use/custom',
    'brukade': 'used to',
    'brukar': 'usually/tends to',
    'brunnen': 'the well',
    'brus': 'noise/fizz',
    'bruten': 'broken',
    'bry': 'to care/bother',
    'bryr': 'cares',
    'bryta': 'to break',
    'bränsle': 'fuel',
    'bröd': 'bread',
    'brödet': 'the bread',
    'bröllop': 'wedding',
    'bröllopet': 'the wedding',
    'bröst': 'breast/chest',
    'budget': 'budget',
    'budgeten': 'the budget',
    'bukt': 'bay/cove',
    'bur': 'cage',
    'buss': 'bus',
    'bussen': 'the bus',
    'busshållplatsen': 'the bus stop',
    'butik': 'shop/store',
    'butiken': 'the shop',
    'by': 'village',
    'bygga': 'to build',
    'byggde': 'built',
    'bygger': 'builds',
    'byggnad': 'building',
    'byggnaden': 'the building',
    'byggt': 'built (supine)',
    'byn': 'the village',
    'byte': 'exchange/swap',
    'bytte': 'exchanged',
    'bättre': 'better',
    'bäst': 'best',
    'böcker': 'books',
    'böckerna': 'the books',
    'bönor': 'beans',
    'början': 'the beginning',
    # C
    'campus': 'campus',
    'chans': 'chance',
    'chansen': 'the chance',
    'chef': 'boss/manager',
    'chefen': 'the boss',
    'citat': 'quote/citation',
    'cykel': 'bicycle',
    'cykeln': 'the bicycle',
    'cyklar': 'bicycles/cycles (verb)',
    # D
    'dag': 'day',
    'dagbok': 'diary',
    'dagen': 'the day',
    'dagar': 'days',
    'dagarna': 'the days',
    'daghem': 'daycare',
    'dagligen': 'daily',
    'dal': 'valley',
    'dalen': 'the valley',
    'dam': 'lady/dam',
    'damer': 'ladies',
    'dammig': 'dusty',
    'dans': 'dance',
    'dansen': 'the dance',
    'dansar': 'dances',
    'dansade': 'danced',
    'data': 'data',
    'dator': 'computer',
    'datorn': 'the computer',
    'datum': 'date',
    'de': 'they/the',
    'debatt': 'debate',
    'debatten': 'the debate',
    'december': 'December',
    'del': 'part',
    'dela': 'to share/divide',
    'delad': 'shared/divided',
    'delade': 'shared/divided',
    'delar': 'parts/shares (verb)',
    'delarna': 'the parts',
    'delas': 'is shared',
    'deltog': 'participated',
    'den': 'it/the (en)',
    'denna': 'this',
    'dens': 'its',
    'deras': 'their',
    'dess': 'its (formal)',
    'dessa': 'these',
    'dessutom': 'moreover/besides',
    'det': 'it/the (ett)',
    'detsamma': 'the same',
    'detta': 'this',
    'diamant': 'diamond',
    'dig': 'you (object)',
    'din': 'your (en)',
    'dina': 'your (plural)',
    'direkt': 'direct/directly',
    'diskutera': 'to discuss',
    'diskuterade': 'discussed',
    'diskuterar': 'discusses',
    'diskussion': 'discussion',
    'diskussionen': 'the discussion',
    'dit': 'there (direction)',
    'ditt': 'your (ett)',
    'diverse': 'various',
    'dock': 'however/though',
    'dokument': 'document',
    'dokumentet': 'the document',
    'dom': 'judgment/verdict',
    'domen': 'the verdict',
    'domstol': 'court',
    'domstolen': 'the court',
    'dottern': 'the daughter',
    'dotter': 'daughter',
    'dra': 'to pull/draw',
    'drabbar': 'strikes/affects',
    'drabbade': 'struck/affected',
    'drag': 'feature/pull',
    'drake': 'dragon/kite',
    'drar': 'pulls/draws',
    'driven': 'driven/energetic',
    'drivs': 'is driven/operated',
    'drog': 'pulled/drew',
    'droppe': 'drop',
    'drottning': 'queen',
    'drottningen': 'the queen',
    'dryck': 'drink/beverage',
    'dröm': 'dream',
    'drömde': 'dreamed',
    'drömmen': 'the dream',
    'drömmer': 'dreams',
    'du': 'you',
    'duk': 'cloth/tablecloth',
    'dum': 'stupid/foolish',
    'dumt': 'stupid (neuter)',
    'duschar': 'showers (verb)',
    'dygn': 'day and night (24h)',
    'dyr': 'expensive',
    'dyrare': 'more expensive',
    'dyrast': 'most expensive',
    'dyrt': 'expensive (neuter)',
    'dålig': 'bad',
    'dåligt': 'badly',
    'där': 'there',
    'därefter': 'thereafter/after that',
    'därför': 'therefore',
    'döda': 'to kill/dead (plural)',
    'dödade': 'killed',
    'döden': 'the death',
    'dörr': 'door',
    'dörren': 'the door',
    # E
    'efterfrågan': 'demand',
    'eftermiddag': 'afternoon',
    'eftermiddagen': 'the afternoon',
    'eftersom': 'because/since',
    'efteråt': 'afterwards',
    'egen': 'own',
    'egentligen': 'actually',
    'egna': 'own (plural)',
    'egendom': 'property',
    'ekonomi': 'economy/finances',
    'ekonomin': 'the economy',
    'ekonomisk': 'economic',
    'ekonomiska': 'economic (plural/def)',
    'eld': 'fire',
    'elev': 'student/pupil',
    'eleven': 'the student',
    'elever': 'students',
    'eleverna': 'the students',
    'eller': 'or',
    'elva': 'eleven',
    'emellan': 'between',
    'emellertid': 'however',
    'emot': 'against/towards',
    'en': 'a/one',
    'ena': 'one (definite)',
    'enda': 'only/single',
    'endags': 'one-day',
    'energi': 'energy',
    'energin': 'the energy',
    'engelska': 'English',
    'enhet': 'unit',
    'enheten': 'the unit',
    'enheter': 'units',
    'enig': 'agreed/united',
    'eniga': 'agreed (plural)',
    'enligt': 'according to',
    'enorm': 'enormous',
    'enormt': 'enormously',
    'ensam': 'alone/lonely',
    'ensamma': 'alone (plural)',
    'enskild': 'individual/private',
    'enskilda': 'individual (plural)',
    'era': 'your (plural)',
    'erbjuda': 'to offer',
    'erbjuder': 'offers',
    'erbjudande': 'offer/deal',
    'erbjöd': 'offered',
    'erfaren': 'experienced',
    'erfarenhet': 'experience',
    'erfarenheten': 'the experience',
    'erkände': 'admitted/acknowledged',
    'erkänner': 'admits/acknowledges',
    'ersätta': 'to replace/compensate',
    'ersättning': 'compensation/replacement',
    'ett': 'a/one (neuter)',
    'europeiska': 'European',
    'exakt': 'exact/exactly',
    'examen': 'degree/exam',
    'exempel': 'example',
    'experimentet': 'the experiment',
    'expert': 'expert',
    'experten': 'the expert',
    'exporterade': 'exported',
    'extra': 'extra',
    # F
    'fabrik': 'factory',
    'fabriken': 'the factory',
    'fackföreningen': 'the trade union',
    'faktiskt': 'actually/in fact',
    'fakta': 'facts',
    'faktum': 'fact',
    'fall': 'case/fall',
    'fallet': 'the case',
    'falsk': 'false/fake',
    'familj': 'family',
    'familjen': 'the family',
    'familjens': 'the family\'s',
    'familjer': 'families',
    'fann': 'found',
    'far': 'father',
    'fara': 'danger/to go',
    'faran': 'the danger',
    'farfar': 'grandfather (paternal)',
    'farlig': 'dangerous',
    'farligt': 'dangerous (neuter)',
    'farmor': 'grandmother (paternal)',
    'fart': 'speed',
    'fast': 'firm/although',
    'fastighet': 'property/real estate',
    'fastigheten': 'the property',
    'fattig': 'poor',
    'fattiga': 'poor (plural)',
    'fattigdom': 'poverty',
    'feber': 'fever',
    'februari': 'February',
    'fel': 'wrong/mistake',
    'felet': 'the mistake',
    'fem': 'five',
    'femte': 'fifth',
    'femtio': 'fifty',
    'fest': 'party/celebration',
    'festen': 'the party',
    'fester': 'parties',
    'fick': 'got/received',
    'fika': 'coffee break/fika',
    'fikan': 'the fika',
    'film': 'film/movie',
    'filmen': 'the film',
    'filosofi': 'philosophy',
    'fina': 'fine/nice (plural)',
    'finansiella': 'financial',
    'finna': 'to find',
    'fint': 'nice/fine (neuter)',
    'fisk': 'fish',
    'fisken': 'the fish',
    'fjord': 'fjord',
    'fjärde': 'fourth',
    'flagga': 'flag',
    'flaggan': 'the flag',
    'fler': 'more (countable)',
    'flera': 'several',
    'flest': 'most (countable)',
    'flicka': 'girl',
    'flickan': 'the girl',
    'flickor': 'girls',
    'flingor': 'flakes/cereal',
    'flod': 'river',
    'floden': 'the river',
    'flyg': 'flight/aviation',
    'flyger': 'flies',
    'flygplan': 'airplane',
    'flygplanet': 'the airplane',
    'flygplats': 'airport',
    'flygplatsen': 'the airport',
    'flykt': 'escape/flight',
    'flytta': 'to move',
    'flyttade': 'moved',
    'flyttar': 'moves',
    'flyttat': 'moved (supine)',
    'flöt': 'floated',
    'fn': 'UN',
    'folk': 'people/folk',
    'folket': 'the people',
    'folkrätten': 'international law',
    'form': 'form/shape',
    'formen': 'the form',
    'formellt': 'formally',
    'former': 'forms/shapes',
    'formulerat': 'formulated',
    'forskning': 'research',
    'forskningen': 'the research',
    'fort': 'fast/quickly',
    'fortfarande': 'still',
    'fortsatte': 'continued',
    'fortsätta': 'to continue',
    'fotboll': 'football/soccer',
    'foto': 'photo',
    'fot': 'foot',
    'foten': 'the foot',
    'fots': 'foot\'s',
    'fotografi': 'photograph',
    'framför': 'in front of',
    'framgång': 'success',
    'framgångsrik': 'successful',
    'framme': 'arrived/there',
    'framtid': 'future',
    'framtiden': 'the future',
    'framtida': 'future (adj)',
    'framåt': 'forward',
    'fred': 'peace',
    'freden': 'the peace',
    'fredag': 'Friday',
    'fri': 'free',
    'frihet': 'freedom',
    'friheten': 'the freedom',
    'frisk': 'healthy',
    'fritt': 'free (neuter)',
    'frukost': 'breakfast',
    'frukosten': 'the breakfast',
    'frukt': 'fruit',
    'frukten': 'the fruit',
    'fråga': 'question/to ask',
    'frågan': 'the question',
    'frågade': 'asked',
    'frågar': 'asks',
    'frågor': 'questions',
    'frågorna': 'the questions',
    'från': 'from',
    'främja': 'to promote',
    'främst': 'primarily/foremost',
    'full': 'full/drunk',
    'fullständig': 'complete',
    'fullständigt': 'completely',
    'fundera': 'to think/wonder',
    'funderade': 'thought about/wondered',
    'fungerar': 'works/functions',
    'fyra': 'four',
    'fågel': 'bird',
    'fågeln': 'the bird',
    'fåglar': 'birds',
    'fält': 'field',
    'fängelset': 'the prison',
    'färdig': 'ready/finished',
    'färdiga': 'ready (plural)',
    'färdigt': 'ready (neuter)',
    'färg': 'color',
    'färger': 'colors',
    'färja': 'ferry',
    'färjan': 'the ferry',
    'färre': 'fewer',
    'fäst': 'attached',
    'föda': 'to give birth/food',
    'föddes': 'was born',
    'födda': 'born (plural)',
    'födelsedag': 'birthday',
    'födelsedagen': 'the birthday',
    'följ': 'follow!',
    'följd': 'consequence',
    'följden': 'the consequence',
    'följer': 'follows',
    'följt': 'followed (supine)',
    'fönster': 'window',
    'fönstret': 'the window',
    'för': 'for/too',
    'föra': 'to lead/carry',
    'förberedde': 'prepared',
    'förbereder': 'prepares',
    'förberedelse': 'preparation',
    'förberedelser': 'preparations',
    'förbättring': 'improvement',
    'fördelarna': 'the advantages',
    'fördel': 'advantage',
    'fördjupa': 'to deepen',
    'före': 'before',
    'förebilder': 'role models',
    'förekomma': 'to occur',
    'förekommit': 'occurred',
    'förening': 'association/club',
    'föreningen': 'the association',
    'föreslog': 'suggested',
    'föreställning': 'performance/notion',
    'företag': 'company/business',
    'företagen': 'the companies',
    'företaget': 'the company',
    'företagare': 'entrepreneur',
    'förgäves': 'in vain',
    'förhandla': 'to negotiate',
    'förhandlingar': 'negotiations',
    'förklarade': 'explained',
    'förklarar': 'explains',
    'förklaring': 'explanation',
    'förklaringen': 'the explanation',
    'förlorade': 'lost',
    'förlåt': 'sorry/forgive',
    'formellt': 'formally',
    'förmedla': 'to convey/mediate',
    'förmåga': 'ability',
    'förmodligen': 'presumably',
    'förnuft': 'reason/sense',
    'förorenande': 'polluting',
    'förra': 'last/previous',
    'försenad': 'delayed',
    'försenade': 'delayed (plural)',
    'försening': 'delay',
    'först': 'first',
    'första': 'first (def)',
    'förstatliganden': 'nationalizations',
    'förste': 'first (masc)',
    'försvarar': 'defends',
    'försök': 'attempt/experiment',
    'försöka': 'to try',
    'försöker': 'tries',
    'försökte': 'tried',
    'förstod': 'understood',
    'förstår': 'understands',
    'förstås': 'of course',
    'försvann': 'disappeared',
    'försvara': 'to defend',
    'försvarade': 'defended',
    'försvinner': 'disappears',
    'förtjänar': 'deserves/earns',
    'förtjänst': 'merit/earning',
    'förtroende': 'trust/confidence',
    'förtroendet': 'the trust',
    'förutsättning': 'condition/prerequisite',
    'förvaltning': 'administration',
    'förvaltningen': 'the administration',
    'förväntade': 'expected',
    'förväntar': 'expects',
    'förändra': 'to change',
    'förändrade': 'changed',
    'förändras': 'changes (passive)',
    'förändring': 'change',
    'förändringen': 'the change',
    'förändringar': 'changes',
    # G
    'ganska': 'quite/rather',
    'garage': 'garage',
    'garanti': 'guarantee',
    'gardin': 'curtain',
    'gata': 'street',
    'gatan': 'the street',
    'gator': 'streets',
    'gemensam': 'common/shared',
    'gemensamma': 'common (plural)',
    'gemenskap': 'community',
    'genom': 'through',
    'genomförande': 'implementation',
    'genomfördes': 'was carried out',
    'genomgått': 'gone through',
    'ger': 'gives',
    'gillar': 'likes',
    'glaciär': 'glacier',
    'glad': 'happy/glad',
    'glada': 'happy (plural)',
    'glades': 'rejoiced',
    'glass': 'ice cream',
    'glassen': 'the ice cream',
    'glas': 'glass',
    'glaset': 'the glass',
    'global': 'global',
    'globalt': 'globally',
    'god': 'good',
    'goda': 'good (plural)',
    'godis': 'candy/sweets',
    'godkänna': 'to approve',
    'godkänt': 'approved',
    'golfströmmen': 'the Gulf Stream',
    'golv': 'floor',
    'golvet': 'the floor',
    'gott': 'good (neuter)/tasty',
    'grad': 'degree',
    'grader': 'degrees',
    'granne': 'neighbor',
    'grannen': 'the neighbor',
    'grannar': 'neighbors',
    'gratis': 'free (of charge)',
    'gripa': 'to grab/arrest',
    'grov': 'coarse/rough',
    'grund': 'ground/basis',
    'grunden': 'the basis',
    'grundlagar': 'constitutions',
    'grundläggande': 'fundamental',
    'grupp': 'group',
    'gruppen': 'the group',
    'grupper': 'groups',
    'grå': 'gray',
    'gräns': 'border/limit',
    'gränsen': 'the border',
    'gräs': 'grass',
    'grön': 'green',
    'grönsaker': 'vegetables',
    'grönt': 'green (neuter)',
    'guide': 'guide',
    'guiden': 'the guide',
    'guld': 'gold',
    'gul': 'yellow',
    'gult': 'yellow (neuter)',
    'gång': 'time/path/corridor',
    'gånger': 'times',
    'gård': 'farm/yard',
    'gården': 'the farm',
    'gärna': 'gladly/willingly',
    'gäst': 'guest',
    'gästen': 'the guest',
    'gäster': 'guests',
    'gästerna': 'the guests',
    'gäller': 'applies/concerns',
    'gällande': 'regarding/applicable',
    'göra': 'to do/make',
    'göteborg': 'Gothenburg',
    # H
    'hamn': 'harbor/port',
    'hamnar': 'harbors/ends up',
    'hamnen': 'the harbor',
    'han': 'he',
    'handla': 'to shop/act',
    'handlade': 'shopped/was about',
    'handlar': 'shops/is about',
    'handling': 'action/act',
    'handlingen': 'the action',
    'handlingar': 'actions/documents',
    'hans': 'his',
    'hav': 'sea/ocean',
    'havet': 'the sea',
    'hemma': 'at home',
    'hemmet': 'the home',
    'hemsk': 'terrible/awful',
    'hemskt': 'terribly',
    'hen': 'they (gender-neutral)',
    'henne': 'her',
    'hennes': 'her/hers',
    'het': 'hot',
    'heta': 'to be called',
    'heter': 'is called',
    'hett': 'hot (neuter)',
    'himmel': 'sky/heaven',
    'himlen': 'the sky',
    'historia': 'history/story',
    'historien': 'the history',
    'historisk': 'historical',
    'historiska': 'historical (plural)',
    'hit': 'here (direction)',
    'hitta': 'to find',
    'hittade': 'found',
    'hittar': 'finds',
    'hjort': 'deer',
    'hjälp': 'help',
    'hjälpa': 'to help',
    'hjälper': 'helps',
    'hjälpte': 'helped',
    'hjärna': 'brain',
    'hjärta': 'heart',
    'hjärtat': 'the heart',
    'hon': 'she',
    'hopp': 'hope/jump',
    'hoppas': 'to hope',
    'horn': 'horn',
    'hotell': 'hotel',
    'hotellet': 'the hotel',
    'hotellrum': 'hotel room',
    'hotellrummet': 'the hotel room',
    'hund': 'dog',
    'hunden': 'the dog',
    'hundra': 'hundred',
    'hunger': 'hunger',
    'hungrig': 'hungry',
    'hur': 'how',
    'hus': 'house',
    'huset': 'the house',
    'huvudstad': 'capital city',
    'huvudstaden': 'the capital',
    'huvud': 'head',
    'huvudet': 'the head',
    'hyra': 'to rent/rent',
    'hyrde': 'rented',
    'håll': 'direction/hold',
    'hålla': 'to hold/keep',
    'håller': 'holds/keeps',
    'hår': 'hair',
    'hård': 'hard/tough',
    'hårt': 'hard (adv)',
    'hälsa': 'health/to greet',
    'hälsan': 'the health',
    'hälsade': 'greeted',
    'hälsar': 'greets',
    'hälsning': 'greeting',
    'hämta': 'to fetch/pick up',
    'hämtade': 'fetched',
    'hämtar': 'fetches',
    'hända': 'to happen',
    'händer': 'happens/hands',
    'händelse': 'event/incident',
    'händelsen': 'the event',
    'händelser': 'events',
    'här': 'here',
    'härifrån': 'from here',
    'häst': 'horse',
    'hästar': 'horses',
    'höger': 'right',
    'hög': 'high/tall',
    'höga': 'high (plural)',
    'högre': 'higher',
    'högst': 'highest',
    'högt': 'high (neuter)/loudly',
    'höll': 'held',
    'höra': 'to hear',
    'hörde': 'heard',
    'hörn': 'corner',
    'hörnet': 'the corner',
    'höst': 'autumn/fall',
    'hösten': 'the autumn',
    # I
    'idé': 'idea',
    'idén': 'the idea',
    'idéer': 'ideas',
    'igen': 'again',
    'igenom': 'through',
    'igår': 'yesterday',
    'imorgon': 'tomorrow',
    'imponerad': 'impressed',
    'importerade': 'imported',
    'in': 'in/into',
    'inbjudande': 'inviting',
    'incheckning': 'check-in',
    'incheckningsdisken': 'the check-in desk',
    'indelningen': 'the division',
    'indien': 'India',
    'inför': 'before/ahead of',
    'information': 'information',
    'informationen': 'the information',
    'informerade': 'informed',
    'ingen': 'no one/none',
    'ingenting': 'nothing',
    'inget': 'nothing (neuter)',
    'inklusive': 'including',
    'inkomster': 'incomes',
    'inne': 'inside',
    'innebär': 'means/implies',
    'innebar': 'meant/implied',
    'innehåll': 'content',
    'innehålla': 'to contain',
    'innehåller': 'contains',
    'innerstad': 'city center',
    'innerstaden': 'the city center',
    'inom': 'within',
    'insats': 'effort/contribution',
    'insatser': 'efforts',
    'insåg': 'realized',
    'inte': 'not',
    'intresse': 'interest',
    'intresset': 'the interest',
    'intressant': 'interesting',
    'intressanta': 'interesting (plural)',
    'intresserad': 'interested',
    'introducerade': 'introduced',
    'invandrare': 'immigrant',
    'investering': 'investment',
    'investeringar': 'investments',
    'invitera': 'to invite',
    'inviterade': 'invited',
    'invånare': 'inhabitants',
    'iphone': 'iPhone',
    'island': 'Iceland',
    'istället': 'instead',
    # J
    'ja': 'yes',
    'jag': 'I',
    'jakt': 'hunt/hunting',
    'januari': 'January',
    'jazz': 'jazz',
    'jo': 'yes (contradicting)',
    'jobb': 'job',
    'jobba': 'to work',
    'jobbade': 'worked',
    'jobbar': 'works',
    'jobbet': 'the job',
    'jord': 'earth/soil',
    'jorden': 'the earth',
    'jordbruk': 'agriculture',
    'journalist': 'journalist',
    'journalisten': 'the journalist',
    'ju': 'you know/after all',
    'jul': 'Christmas',
    'julen': 'the Christmas',
    'julklapp': 'Christmas present',
    'julklappar': 'Christmas presents',
    'julmat': 'Christmas food',
    'juni': 'June',
    'juli': 'July',
    'juridisk': 'legal/juridical',
    'just': 'just/exactly',
    'jämföra': 'to compare',
    'jämförde': 'compared',
    'jämställdhet': 'gender equality',
    # K
    'kafé': 'café',
    'kaffe': 'coffee',
    'kaffet': 'the coffee',
    'kaka': 'cake/cookie',
    'kakor': 'cookies',
    'kall': 'cold',
    'kalla': 'to call',
    'kallade': 'called',
    'kallas': 'is called',
    'kallare': 'colder',
    'kallast': 'coldest',
    'kallt': 'cold (neuter)',
    'kamp': 'struggle/fight',
    'kampen': 'the struggle',
    'kanal': 'channel/canal',
    'kanalen': 'the channel',
    'kanske': 'maybe/perhaps',
    'kapitel': 'chapter',
    'kapitlet': 'the chapter',
    'kart': 'map',
    'karta': 'map',
    'kartan': 'the map',
    'kassa': 'cash register/checkout',
    'kassan': 'the checkout',
    'katt': 'cat',
    'katten': 'the cat',
    'klar': 'clear/ready',
    'klara': 'to manage/clear',
    'klarade': 'managed',
    'klarar': 'manages',
    'klart': 'clear (neuter)/obviously',
    'klass': 'class',
    'klassen': 'the class',
    'klocka': 'clock/watch',
    'klockan': 'the clock/at (time)',
    'kläder': 'clothes',
    'kläderna': 'the clothes',
    'knapp': 'button/barely',
    'knappt': 'barely/hardly',
    'kniv': 'knife',
    'kniven': 'the knife',
    'koka': 'to boil/cook',
    'kokar': 'boils/cooks',
    'koll': 'check/control',
    'kollega': 'colleague',
    'kollegan': 'the colleague',
    'komma': 'to come',
    'kommer': 'comes/will',
    'kommentar': 'comment',
    'kommunen': 'the municipality',
    'kompis': 'friend/buddy',
    'komplex': 'complex',
    'konflikt': 'conflict',
    'konflikten': 'the conflict',
    'konst': 'art',
    'konsten': 'the art',
    'konstig': 'strange/weird',
    'konstigt': 'strange (neuter)',
    'kontor': 'office',
    'kontoret': 'the office',
    'kontakt': 'contact',
    'kontakta': 'to contact',
    'kontaktade': 'contacted',
    'kontaktar': 'contacts',
    'kontakten': 'the contact',
    'konto': 'account',
    'kontot': 'the account',
    'kontroll': 'control/check',
    'kontrollen': 'the control',
    'kontrollera': 'to check/control',
    'kontrollerade': 'checked',
    'kontrollerar': 'checks',
    'konversation': 'conversation',
    'kopp': 'cup',
    'koppen': 'the cup',
    'korg': 'basket',
    'korgen': 'the basket',
    'korrekt': 'correct',
    'kort': 'card/short',
    'kortet': 'the card',
    'kosta': 'to cost',
    'kostar': 'costs',
    'kostnad': 'cost',
    'kostnaden': 'the cost',
    'kostnader': 'costs',
    'kraft': 'power/force',
    'kraften': 'the power',
    'krav': 'demand/requirement',
    'kravet': 'the demand',
    'krig': 'war',
    'kriget': 'the war',
    'kring': 'around',
    'kris': 'crisis',
    'krisen': 'the crisis',
    'kritik': 'criticism',
    'kritiken': 'the criticism',
    'kritisk': 'critical',
    'kronan': 'the crown/krona',
    'kronor': 'crowns/kronor',
    'kropp': 'body',
    'kroppen': 'the body',
    'krydda': 'spice',
    'kryddor': 'spices',
    'kultur': 'culture',
    'kulturen': 'the culture',
    'kulturell': 'cultural',
    'kund': 'customer',
    'kunden': 'the customer',
    'kunder': 'customers',
    'kung': 'king',
    'kungen': 'the king',
    'kunna': 'to be able to',
    'kunskap': 'knowledge',
    'kunskapen': 'the knowledge',
    'kurs': 'course/rate',
    'kursen': 'the course',
    'kusin': 'cousin',
    'kust': 'coast',
    'kusten': 'the coast',
    'kvalitet': 'quality',
    'kvaliteten': 'the quality',
    'kvarter': 'quarter/block',
    'kvinna': 'woman',
    'kvinnan': 'the woman',
    'kvinnor': 'women',
    'kvinnorna': 'the women',
    'kväll': 'evening',
    'kvällen': 'the evening',
    'kylig': 'chilly',
    'kyrka': 'church',
    'kyrkan': 'the church',
    'kök': 'kitchen',
    'köket': 'the kitchen',
    'köpa': 'to buy',
    'köpte': 'bought',
    'kör': 'drives/runs',
    'köra': 'to drive',
    'kött': 'meat',
    'köttet': 'the meat',
    # L
    'lag': 'law/team',
    'lagen': 'the law',
    'lager': 'stock/layer',
    'lagom': 'just right/moderate',
    'lagstiftning': 'legislation',
    'land': 'country/land',
    'landet': 'the country',
    'landskap': 'landscape/province',
    'landskapet': 'the landscape',
    'landsting': 'county council',
    'lapp': 'note/patch',
    'laser': 'laser',
    'leda': 'to lead',
    'ledande': 'leading',
    'ledare': 'leader',
    'ledaren': 'the leader',
    'ledning': 'leadership/management',
    'ledningen': 'the management',
    'ledig': 'free/available',
    'ledsam': 'sad',
    'lejon': 'lion',
    'lek': 'play/game',
    'leka': 'to play',
    'lekar': 'games',
    'lektion': 'lesson',
    'lektionen': 'the lesson',
    'lektioner': 'lessons',
    'leta': 'to look for',
    'letar': 'looks for',
    'leva': 'to live',
    'lever': 'lives',
    'levde': 'lived',
    'levnadskostnaderna': 'the living costs',
    'licens': 'license',
    'lidande': 'suffering',
    'lika': 'equally/same',
    'likadan': 'similar/same kind',
    'liksom': 'like/as',
    'likvärdig': 'equal/equivalent',
    'lilla': 'little (def)',
    'linje': 'line',
    'linjen': 'the line',
    'lista': 'list',
    'listan': 'the list',
    'lite': 'a little',
    'liten': 'small/little',
    'litet': 'small (neuter)',
    'liv': 'life',
    'livet': 'the life',
    'ljus': 'light/bright',
    'ljuset': 'the light',
    'ljuvlig': 'lovely/delightful',
    'lock': 'lid/lock',
    'lockar': 'attracts/tempts',
    'logi': 'accommodation',
    'lokal': 'local/premises',
    'lokala': 'local (def/plural)',
    'lokalen': 'the premises',
    'lov': 'holiday/permission',
    'lovar': 'promises',
    'luciatåget': 'the Lucia procession',
    'luft': 'air',
    'luften': 'the air',
    'lugn': 'calm',
    'lugnt': 'calmly',
    'lunch': 'lunch',
    'lunchen': 'the lunch',
    'lust': 'desire/pleasure',
    'lycka': 'happiness/luck',
    'lycklig': 'happy',
    'lyckligtvis': 'fortunately',
    'lyfta': 'to lift',
    'lyfte': 'lifted',
    'lyssna': 'to listen',
    'lyssnade': 'listened',
    'lyssnar': 'listens',
    'lång': 'long/tall',
    'låndsam': 'slow',
    'långsam': 'slow',
    'långsamt': 'slowly',
    'långt': 'far/long (neuter)',
    'låna': 'to borrow/lend',
    'lånade': 'borrowed',
    'lånar': 'borrows',
    'lås': 'lock',
    'låta': 'to let/sound',
    'låter': 'sounds/lets',
    'lägga': 'to put/lay',
    'lägenhet': 'apartment',
    'lägenheten': 'the apartment',
    'läger': 'camp',
    'lägre': 'lower',
    'lägst': 'lowest',
    'läkare': 'doctor',
    'läkaren': 'the doctor',
    'lämna': 'to leave',
    'lämnade': 'left',
    'lämnar': 'leaves',
    'län': 'county',
    'lämplig': 'suitable/appropriate',
    'länder': 'countries',
    'länderna': 'the countries',
    'länge': 'for a long time',
    'längre': 'longer/further',
    'längst': 'longest/farthest',
    'längtan': 'longing',
    'läpp': 'lip',
    'lära': 'to learn/teach',
    'lärare': 'teacher',
    'läraren': 'the teacher',
    'lärde': 'learned/taught',
    'läsa': 'to read',
    'läsare': 'reader',
    'läser': 'reads',
    'läst': 'read (supine)',
    'lätt': 'easy/light',
    'läxa': 'homework',
    'löfte': 'promise',
    'löftet': 'the promise',
    'lön': 'salary/wage',
    'lönen': 'the salary',
    'lördag': 'Saturday',
    'lösa': 'to solve',
    'lösning': 'solution',
    'lösningen': 'the solution',
    # M
    'makt': 'power',
    'makten': 'the power',
    'man': 'man/one',
    'mamma': 'mom',
    'mannen': 'the man',
    'mark': 'ground/land',
    'marknad': 'market',
    'marknaden': 'the market',
    'mars': 'March',
    'mat': 'food',
    'maten': 'the food',
    'material': 'material',
    'materialet': 'the material',
    'matlagning': 'cooking',
    'maträtt': 'dish/course',
    'me': 'me',
    'med': 'with',
    'medan': 'while',
    'medarbetare': 'co-worker',
    'meddelande': 'message',
    'meddelandet': 'the message',
    'medel': 'means/average',
    'medlem': 'member',
    'medlemmar': 'members',
    'medsols': 'clockwise',
    'medvetande': 'consciousness',
    'medveten': 'aware',
    'mening': 'sentence/meaning',
    'meningsfull': 'meaningful',
    'mer': 'more',
    'mera': 'more',
    'mest': 'most',
    'meter': 'meter',
    'metod': 'method',
    'metoden': 'the method',
    'middag': 'dinner',
    'middagen': 'the dinner',
    'midsommar': 'midsummer',
    'midsommarstång': 'maypole',
    'mig': 'me',
    'miljon': 'million',
    'miljoner': 'millions',
    'miljö': 'environment',
    'miljön': 'the environment',
    'min': 'my/mine',
    'mina': 'my (plural)',
    'mindre': 'smaller/less',
    'minnas': 'to remember',
    'minne': 'memory',
    'minnet': 'the memory',
    'minst': 'least/smallest',
    'minut': 'minute',
    'minuter': 'minutes',
    'minuterna': 'the minutes',
    'missa': 'to miss',
    'missade': 'missed',
    'missar': 'misses',
    'misstag': 'mistake',
    'misstaget': 'the mistake',
    'mitt': 'my (neuter)/middle',
    'mjuk': 'soft',
    'mjukt': 'soft (neuter)',
    'mjöl': 'flour',
    'mjölk': 'milk',
    'mjölken': 'the milk',
    'mobil': 'mobile phone',
    'mobilen': 'the mobile phone',
    'modern': 'the mother/modern',
    'modig': 'brave/courageous',
    'modigt': 'bravely',
    'molnig': 'cloudy',
    'molnigt': 'cloudy (neuter)',
    'moment': 'moment/element',
    'mor': 'mother',
    'morbror': 'uncle (maternal)',
    'morfar': 'grandfather (maternal)',
    'morgon': 'morning',
    'morgonen': 'the morning',
    'mormor': 'grandmother (maternal)',
    'morse': 'this morning',
    'motiv': 'motive',
    'motivet': 'the motive',
    'motor': 'engine/motor',
    'motorn': 'the engine',
    'motståndet': 'the resistance',
    'mottagning': 'reception',
    'mun': 'mouth',
    'munnen': 'the mouth',
    'museum': 'museum',
    'museet': 'the museum',
    'musik': 'music',
    'musiken': 'the music',
    'mycke': 'much',
    'mycket': 'very/much',
    'myndighet': 'authority',
    'myndigheten': 'the authority',
    'myndigheter': 'authorities',
    'myndigheterna': 'the authorities',
    'mål': 'goal/target',
    'målet': 'the goal',
    'måltid': 'meal',
    'månad': 'month',
    'månaden': 'the month',
    'månader': 'months',
    'mång': 'many',
    'många': 'many',
    'måndag': 'Monday',
    'måste': 'must',
    'mäktig': 'powerful/mighty',
    'mäktiga': 'powerful (plural)',
    'människa': 'human being',
    'människan': 'the human',
    'människor': 'people',
    'människorna': 'the people',
    'mänsklig': 'human (adj)',
    'mänskliga': 'human (plural adj)',
    'märka': 'to notice',
    'märkte': 'noticed',
    'möjlig': 'possible',
    'möjligen': 'possibly',
    'möjlighet': 'possibility',
    'möjligheten': 'the possibility',
    'möjligheter': 'possibilities',
    'möjligt': 'possible (neuter)',
    'mönster': 'pattern',
    'mörk': 'dark',
    'mörkret': 'the darkness',
    'mörkt': 'dark (neuter)',
    'möte': 'meeting',
    'mötet': 'the meeting',
    'möten': 'meetings',
    'möter': 'meets',
    'möttes': 'met (passive)',
    'möjligtvis': 'possibly',
    # N
    'natt': 'night',
    'natten': 'the night',
    'natur': 'nature',
    'naturen': 'the nature',
    'naturlig': 'natural',
    'naturligt': 'naturally',
    'naturligtvis': 'of course',
    'namn': 'name',
    'namnet': 'the name',
    'nej': 'no',
    'nere': 'down/below',
    'ni': 'you (plural)',
    'nio': 'nine',
    'nionde': 'ninth',
    'nitton': 'nineteen',
    'njuter': 'enjoys',
    'nobelpriset': 'the Nobel Prize',
    'nog': 'enough/probably',
    'noga': 'carefully',
    'noll': 'zero',
    'nord': 'north',
    'norden': 'the Nordic countries',
    'nordisk': 'Nordic',
    'norr': 'north',
    'norrland': 'Norrland',
    'ny': 'new',
    'nyhet': 'news/novelty',
    'nyheten': 'the news',
    'nyheter': 'news',
    'nyligen': 'recently',
    'nyss': 'just now',
    'nytt': 'new (neuter)',
    'nya': 'new (def/plural)',
    'nyckel': 'key',
    'nyckeln': 'the key',
    'nå': 'to reach',
    'någon': 'someone/some',
    'någonsin': 'ever',
    'någonstans': 'somewhere',
    'något': 'something/somewhat',
    'några': 'some (plural)',
    'når': 'reaches',
    'nådde': 'reached',
    'nämligen': 'namely',
    'nämna': 'to mention',
    'nämner': 'mentions',
    'nära': 'near/close',
    'näring': 'nutrition',
    'näringslivet': 'the business community',
    'närmaste': 'nearest',
    'nästkommande': 'next/upcoming',
    'nöjd': 'satisfied/pleased',
    'nöjda': 'satisfied (plural)',
    'nödvändig': 'necessary',
    'nödvändigt': 'necessary (neuter)',
    # O
    'obligation': 'bond/obligation',
    'och': 'and',
    'också': 'also/too',
    'ofta': 'often',
    'oftast': 'most often',
    'olja': 'oil',
    'oljan': 'the oil',
    'olik': 'different',
    'olika': 'different/various',
    'om': 'about/if',
    'omkring': 'around',
    'område': 'area/region',
    'området': 'the area',
    'områden': 'areas',
    'omständigheter': 'circumstances',
    'omvandla': 'to transform',
    'onsdag': 'Wednesday',
    'oss': 'us',
    'ost': 'cheese',
    'osten': 'the cheese',
    'otroligt': 'incredibly',
    'ovanlig': 'unusual',
    'ovanligt': 'unusually',
    'ovanför': 'above',
    # P
    'pappa': 'dad',
    'par': 'pair/couple',
    'pardon': 'pardon',
    'park': 'park',
    'parken': 'the park',
    'parlament': 'parliament',
    'parlamentet': 'the parliament',
    'parti': 'party (political)',
    'partiet': 'the party',
    'pass': 'passport/pass',
    'passet': 'the passport',
    'passagerare': 'passenger',
    'paus': 'break/pause',
    'peng': 'money',
    'pengar': 'money',
    'pengarna': 'the money',
    'period': 'period',
    'perioden': 'the period',
    'person': 'person',
    'personen': 'the person',
    'personer': 'persons',
    'personerna': 'the persons',
    'perspektiv': 'perspective',
    'piano': 'piano',
    'piga': 'maid',
    'plan': 'plan/flat',
    'planen': 'the plan',
    'planer': 'plans',
    'planet': 'the plan (neuter)',
    'plats': 'place/seat',
    'platsen': 'the place',
    'plats': 'place',
    'plikt': 'duty',
    'plikten': 'the duty',
    'plockade': 'picked',
    'plötsligt': 'suddenly',
    'pojke': 'boy',
    'pojken': 'the boy',
    'politik': 'politics/policy',
    'politiken': 'the politics',
    'politisk': 'political',
    'politiska': 'political (plural)',
    'polisen': 'the police',
    'populär': 'popular',
    'populärt': 'popular (neuter)',
    'port': 'gate/door',
    'porten': 'the gate',
    'position': 'position',
    'positiv': 'positive',
    'positivt': 'positively',
    'post': 'mail/post',
    'posten': 'the mail',
    'pratar': 'talks',
    'pratade': 'talked',
    'precis': 'precisely/just',
    'pressen': 'the press',
    'princip': 'principle',
    'principen': 'the principle',
    'pris': 'price/prize',
    'priset': 'the price',
    'problem': 'problem',
    'problemet': 'the problem',
    'producera': 'to produce',
    'produkt': 'product',
    'produkten': 'the product',
    'produkter': 'products',
    'produktion': 'production',
    'program': 'program',
    'programmet': 'the program',
    'projekt': 'project',
    'projektet': 'the project',
    'promenad': 'walk/stroll',
    'promenaden': 'the walk',
    'promenera': 'to walk/stroll',
    'protest': 'protest',
    'protesten': 'the protest',
    'provar': 'tries on',
    'provade': 'tried on',
    'punkt': 'point/period',
    'pund': 'pound',
    'på': 'on/at',
    'påverka': 'to affect/influence',
    'påverkade': 'affected',
    'påverkan': 'influence/impact',
    'påverkar': 'affects',
    # R
    'rad': 'row/line',
    'raden': 'the row',
    'ramen': 'the frame',
    'rapport': 'report',
    'rapporten': 'the report',
    'reagera': 'to react',
    'reagerade': 'reacted',
    'redan': 'already',
    'redo': 'ready',
    'regel': 'rule',
    'regeln': 'the rule',
    'regler': 'rules',
    'reglerna': 'the rules',
    'region': 'region',
    'regionen': 'the region',
    'regn': 'rain',
    'regnar': 'rains',
    'regnet': 'the rain',
    'ren': 'clean/reindeer',
    'rent': 'clean (neuter)',
    'resa': 'journey/to travel',
    'resan': 'the journey',
    'reser': 'travels',
    'reste': 'traveled',
    'resor': 'trips/journeys',
    'resultat': 'result',
    'resultatet': 'the result',
    'restaurang': 'restaurant',
    'restaurangen': 'the restaurant',
    'rik': 'rich',
    'riktigt': 'really/correctly',
    'riktig': 'correct/real',
    'riktning': 'direction',
    'rim': 'rhyme',
    'ring': 'ring',
    'ringer': 'calls/rings',
    'ringde': 'called/rang',
    'risk': 'risk',
    'risken': 'the risk',
    'ro': 'peace/calm',
    'rolig': 'funny/fun',
    'roligt': 'fun (neuter)',
    'roll': 'role',
    'rollen': 'the role',
    'romantisk': 'romantic',
    'ros': 'rose',
    'rum': 'room',
    'rummet': 'the room',
    'runt': 'around',
    'röd': 'red',
    'röda': 'red (plural)',
    'rödvin': 'red wine',
    'röra': 'to move/touch',
    'rörde': 'moved/touched',
    'rörelse': 'movement',
    'röst': 'voice/vote',
    'rösta': 'to vote',
    'röstade': 'voted',
    'röstar': 'votes',
    'rösten': 'the voice',
    # S
    'sak': 'thing',
    'saker': 'things',
    'sakerna': 'the things',
    'sakna': 'to miss/lack',
    'saknade': 'missed/lacked',
    'saknar': 'misses/lacks',
    'sal': 'hall/room',
    'salen': 'the hall',
    'salong': 'lounge/salon',
    'salt': 'salt',
    'samma': 'same',
    'samarbete': 'cooperation',
    'samband': 'connection',
    'sambandet': 'the connection',
    'samhälle': 'society',
    'samhället': 'the society',
    'samla': 'to collect/gather',
    'samlade': 'collected/gathered',
    'samling': 'collection',
    'samlingen': 'the collection',
    'samman': 'together',
    'sammanhang': 'context',
    'sammanhanget': 'the context',
    'sammanlagt': 'in total',
    'sammanträde': 'meeting',
    'samt': 'and/as well as',
    'samtalet': 'the conversation',
    'samtid': 'contemporary',
    'samtidig': 'simultaneous',
    'samtidigt': 'at the same time',
    'sand': 'sand',
    'sanden': 'the sand',
    'sanning': 'truth',
    'sanningen': 'the truth',
    'satte': 'put/placed',
    'se': 'to see',
    'sedan': 'then/since',
    'semester': 'vacation',
    'semestern': 'the vacation',
    'sen': 'late/then',
    'senast': 'at the latest',
    'senaste': 'latest/most recent',
    'sent': 'late (neuter)',
    'serie': 'series',
    'servera': 'to serve',
    'serverade': 'served',
    'serverar': 'serves',
    'service': 'service',
    'sida': 'side/page',
    'sidan': 'the side',
    'sig': 'oneself',
    'signal': 'signal',
    'sin': 'his/her/its (reflexive)',
    'sina': 'his/her (plural reflexive)',
    'sist': 'last',
    'sista': 'last (def)',
    'situation': 'situation',
    'situationen': 'the situation',
    'sjuk': 'sick/ill',
    'sjukhus': 'hospital',
    'sjukhuset': 'the hospital',
    'sjukvård': 'healthcare',
    'sjukvården': 'the healthcare',
    'själv': 'self',
    'själva': 'themselves/itself',
    'sjö': 'lake',
    'sjön': 'the lake',
    'ska': 'shall/will',
    'skadar': 'damages/hurts',
    'skala': 'scale/shell',
    'skap': 'cupboard',
    'skapa': 'to create',
    'skapade': 'created',
    'skapar': 'creates',
    'skatt': 'tax/treasure',
    'skatten': 'the tax',
    'ske': 'to happen',
    'sked': 'spoon',
    'skeden': 'the spoon',
    'sker': 'happens',
    'skicka': 'to send',
    'skickade': 'sent',
    'skickar': 'sends',
    'skild': 'separate/divorced',
    'skillnad': 'difference',
    'skillnaden': 'the difference',
    'skiva': 'slice/disc',
    'skog': 'forest',
    'skogen': 'the forest',
    'skola': 'school',
    'skolan': 'the school',
    'skolor': 'schools',
    'skolorna': 'the schools',
    'skon': 'the shoe',
    'skor': 'shoes',
    'skorna': 'the shoes',
    'skriva': 'to write',
    'skrivbord': 'desk',
    'skriver': 'writes',
    'skrev': 'wrote',
    'skydd': 'protection',
    'skydda': 'to protect',
    'skyddade': 'protected',
    'skyddar': 'protects',
    'skyddas': 'is protected',
    'skull': 'sake',
    'skulle': 'would/should',
    'skylt': 'sign',
    'skynda': 'to hurry',
    'skyndade': 'hurried',
    'skäl': 'reason',
    'skärgård': 'archipelago',
    'skärgården': 'the archipelago',
    'skönt': 'nice/comfortable',
    'sköta': 'to take care of',
    'slags': 'kind of',
    'slut': 'end',
    'slutet': 'the end',
    'slutligen': 'finally',
    'slå': 'to hit/beat',
    'släkt': 'relatives/family',
    'släkten': 'the family',
    'släkting': 'relative',
    'släktingar': 'relatives',
    'släppa': 'to release/let go',
    'släppte': 'released',
    'smak': 'taste/flavor',
    'smaken': 'the taste',
    'smal': 'narrow/thin',
    'smart': 'smart/clever',
    'smör': 'butter',
    'smöret': 'the butter',
    'snabb': 'fast/quick',
    'snabbt': 'quickly',
    'snart': 'soon',
    'snäll': 'kind/nice',
    'snö': 'snow',
    'snön': 'the snow',
    'social': 'social',
    'sociala': 'social (plural)',
    'socker': 'sugar',
    'sockret': 'the sugar',
    'soffa': 'sofa/couch',
    'soffan': 'the sofa',
    'sol': 'sun',
    'solen': 'the sun',
    'solig': 'sunny',
    'solsken': 'sunshine',
    'sommar': 'summer',
    'sommaren': 'the summer',
    'son': 'son',
    'sonen': 'the son',
    'sorg': 'grief/sorrow',
    'sort': 'kind/sort',
    'sovrum': 'bedroom',
    'sovrummet': 'the bedroom',
    'sova': 'to sleep',
    'sover': 'sleeps',
    'sport': 'sport',
    'sporten': 'the sport',
    'springa': 'to run',
    'springer': 'runs',
    'språk': 'language',
    'språket': 'the language',
    'spår': 'track/trace',
    'spårvagn': 'tram',
    'spännande': 'exciting',
    'stad': 'city',
    'staden': 'the city',
    'stannar': 'stays/stops',
    'stark': 'strong',
    'starkt': 'strongly',
    'stat': 'state',
    'staten': 'the state',
    'station': 'station',
    'stationen': 'the station',
    'stavning': 'spelling',
    'sten': 'stone',
    'stenen': 'the stone',
    'steg': 'step',
    'steget': 'the step',
    'stigen': 'the path',
    'stil': 'style',
    'stilen': 'the style',
    'stjärna': 'star',
    'stjärnor': 'stars',
    'stol': 'chair',
    'stolen': 'the chair',
    'stor': 'big/large',
    'stora': 'big (plural/def)',
    'storlek': 'size',
    'storleken': 'the size',
    'storm': 'storm',
    'stormen': 'the storm',
    'storstad': 'big city',
    'storstaden': 'the big city',
    'stort': 'big (neuter)',
    'strand': 'beach',
    'stranden': 'the beach',
    'strategi': 'strategy',
    'strategin': 'the strategy',
    'strid': 'battle/fight',
    'striden': 'the battle',
    'struktur': 'structure',
    'strukturen': 'the structure',
    'ström': 'current/stream',
    'strömmen': 'the current',
    'student': 'student',
    'studenten': 'the student',
    'studenter': 'students',
    'studera': 'to study',
    'studerade': 'studied',
    'studerar': 'studies',
    'studie': 'study',
    'studien': 'the study',
    'studier': 'studies',
    'stuga': 'cottage/cabin',
    'stugan': 'the cottage',
    'stund': 'moment/while',
    'stunden': 'the moment',
    'stycke': 'piece/paragraph',
    'stycken': 'pieces',
    'styrka': 'strength/force',
    'styrkan': 'the strength',
    'stå': 'to stand',
    'stånd': 'stand/condition',
    'ställa': 'to put/place',
    'ställe': 'place',
    'stället': 'the place',
    'stämma': 'to be correct/voice',
    'stänga': 'to close',
    'stängde': 'closed',
    'stänger': 'closes',
    'stöd': 'support',
    'stödet': 'the support',
    'stödja': 'to support',
    'störa': 'to disturb',
    'störande': 'disturbing',
    'störst': 'biggest/largest',
    'största': 'biggest (def)',
    'sund': 'sound/strait',
    'svag': 'weak',
    'svagt': 'weakly',
    'svar': 'answer',
    'svarat': 'answered (supine)',
    'svaren': 'the answers',
    'svaret': 'the answer',
    'svensk': 'Swedish',
    'svenska': 'Swedish (def)/the Swede',
    'svenskar': 'Swedes',
    'svårt': 'difficult (neuter)',
    'svår': 'difficult',
    'svåra': 'difficult (plural)',
    'svårighet': 'difficulty',
    'svårigheter': 'difficulties',
    'sy': 'to sew',
    'syfte': 'purpose',
    'syftet': 'the purpose',
    'synpunkt': 'viewpoint',
    'system': 'system',
    'systemet': 'the system',
    'syster': 'sister',
    'systern': 'the sister',
    'så': 'so/then',
    'sådan': 'such',
    'sådana': 'such (plural)',
    'sådant': 'such (neuter)',
    'såg': 'saw',
    'sång': 'song',
    'sången': 'the song',
    'sånger': 'songs',
    'sångerskan': 'the female singer',
    'särskild': 'special/particular',
    'särskilda': 'special (plural)',
    'särskilt': 'especially',
    'sätter': 'puts/places',
    'söder': 'south',
    'söka': 'to search/apply',
    'söker': 'searches/applies',
    'sökte': 'searched/applied',
    'söndag': 'Sunday',
    'söt': 'sweet/cute',
    'sötsaker': 'sweets/candy',
    # T
    'ta': 'to take',
    'tack': 'thank you',
    'tacka': 'to thank',
    'tackade': 'thanked',
    'tackar': 'thanks',
    'tackla': 'to tackle',
    'tal': 'speech/number',
    'tala': 'to speak',
    'talar': 'speaks',
    'text': 'text',
    'tid': 'time',
    'tiden': 'the time',
    'tidigt': 'early',
    'tidning': 'newspaper',
    'tidningen': 'the newspaper',
    'tidningar': 'newspapers',
    'tillbaka': 'back',
    'tills': 'until',
    'tillsammans': 'together',
    'tillräcklig': 'sufficient',
    'tillräckligt': 'sufficiently',
    'tillägg': 'addition/supplement',
    'timmar': 'hours',
    'timme': 'hour',
    'tio': 'ten',
    'tionde': 'tenth',
    'tisdag': 'Tuesday',
    'titta': 'to look',
    'tittade': 'looked',
    'tittar': 'looks',
    'tjugo': 'twenty',
    'tjänst': 'service/position',
    'tjänsten': 'the service',
    'tog': 'took',
    'tomt': 'empty (neuter)/plot',
    'torsdag': 'Thursday',
    'total': 'total',
    'totalt': 'totally',
    'tradition': 'tradition',
    'traditionen': 'the tradition',
    'traditionell': 'traditional',
    'trafik': 'traffic',
    'trafiken': 'the traffic',
    'trevlig': 'nice/pleasant',
    'trevligt': 'nicely/pleasant (neuter)',
    'tre': 'three',
    'tredje': 'third',
    'trettio': 'thirty',
    'tro': 'to believe/faith',
    'trodde': 'believed',
    'troligtvis': 'probably',
    'tror': 'believes',
    'trots': 'despite',
    'trottoaren': 'the sidewalk',
    'trygga': 'safe (plural)',
    'trygg': 'safe/secure',
    'trygghet': 'safety/security',
    'träd': 'tree',
    'trädet': 'the tree',
    'trädgård': 'garden',
    'trädgården': 'the garden',
    'träna': 'to exercise/train',
    'tränade': 'trained',
    'tränar': 'trains',
    'träning': 'training/exercise',
    'tråkig': 'boring',
    'tråkigt': 'boring (neuter)',
    'tunnelbana': 'subway/metro',
    'tunnelbanan': 'the subway',
    'tur': 'luck/turn/trip',
    'turen': 'the luck',
    'turism': 'tourism',
    'turist': 'tourist',
    'turisten': 'the tourist',
    'turister': 'tourists',
    'tusen': 'thousand',
    'tvätta': 'to wash',
    'tvättade': 'washed',
    'tvättar': 'washes',
    'två': 'two',
    'tydlig': 'clear/obvious',
    'tydligt': 'clearly',
    'typ': 'type/kind',
    'typen': 'the type',
    'typisk': 'typical',
    'typiskt': 'typically',
    'tyst': 'quiet/silent',
    'tyvärr': 'unfortunately',
    'tåg': 'train',
    'tåget': 'the train',
    'tänka': 'to think',
    'tänker': 'thinks',
    'tänkte': 'thought',
    'tätt': 'densely/tightly',
    'tät': 'dense/tight',
    # U
    'ull': 'wool',
    'under': 'under/during/wonder',
    'underbar': 'wonderful',
    'underlättar': 'facilitates',
    'undersöka': 'to investigate',
    'undersökning': 'investigation/survey',
    'undersökningen': 'the investigation',
    'underskatta': 'to underestimate',
    'underskattade': 'underestimated',
    'undra': 'to wonder',
    'undrade': 'wondered',
    'undrar': 'wonders',
    'ung': 'young',
    'unga': 'young (plural)',
    'ungdom': 'youth',
    'ungdomar': 'young people',
    'ungefär': 'approximately',
    'universitet': 'university',
    'universitetet': 'the university',
    'uppe': 'up',
    'uppgift': 'task/information',
    'uppgiften': 'the task',
    'upplevelse': 'experience',
    'upplevelsen': 'the experience',
    'upplever': 'experiences',
    'uppmanade': 'urged',
    'uppmärksam': 'attentive',
    'uppmärksamhet': 'attention',
    'uppnå': 'to achieve',
    'uppstod': 'arose/occurred',
    'uppsats': 'essay',
    'uppsatsen': 'the essay',
    'uppsättning': 'set/production',
    'ur': 'out of/clock',
    'ursprungliga': 'original',
    'ursäkta': 'excuse me',
    'ut': 'out',
    'utan': 'without/but',
    'utanför': 'outside',
    'utbildning': 'education',
    'utbildningen': 'the education',
    'utbyte': 'exchange',
    'utbytet': 'the exchange',
    'ute': 'outside',
    'utforskning': 'exploration',
    'utforma': 'to design',
    'utformningen': 'the design',
    'utfört': 'carried out',
    'utföra': 'to carry out',
    'utgifter': 'expenses',
    'utgör': 'constitutes',
    'utländsk': 'foreign',
    'utländska': 'foreign (plural)',
    'utmaning': 'challenge',
    'utmaningen': 'the challenge',
    'utmaningar': 'challenges',
    'utredning': 'investigation',
    'utredningen': 'the investigation',
    'utrustning': 'equipment',
    'utsikt': 'view',
    'utsikten': 'the view',
    'utsikter': 'prospects',
    'utställning': 'exhibition',
    'utställningen': 'the exhibition',
    'utsätta': 'to expose',
    'uttryck': 'expression',
    'uttrycket': 'the expression',
    'uttryckte': 'expressed',
    'utveckla': 'to develop',
    'utvecklade': 'developed',
    'utvecklar': 'develops',
    'utvecklas': 'develops (passive)',
    'utveckling': 'development',
    'utvecklingen': 'the development',
    'utöver': 'beyond/in addition to',
    # V
    'vacker': 'beautiful',
    'vackert': 'beautifully',
    'vackra': 'beautiful (plural)',
    'vagn': 'cart/carriage',
    'val': 'choice/election/whale',
    'valet': 'the choice',
    'vandra': 'to hike/wander',
    'vandrade': 'hiked/wandered',
    'vandring': 'hike/walking',
    'vanlig': 'common/ordinary',
    'vanligen': 'usually',
    'vanligt': 'common (neuter)',
    'vanligtvis': 'usually',
    'vapen': 'weapon',
    'vapnet': 'the weapon',
    'vara': 'to be/goods',
    'varandra': 'each other',
    'vardag': 'everyday life',
    'vardagen': 'the everyday',
    'varför': 'why',
    'varm': 'warm',
    'varmt': 'warm (neuter)/warmly',
    'varje': 'every/each',
    'vart': 'where (direction)',
    'vatten': 'water',
    'vattnet': 'the water',
    'vecka': 'week',
    'veckan': 'the week',
    'veckor': 'weeks',
    'veckorna': 'the weeks',
    'vem': 'who',
    'verklig': 'real/actual',
    'verkligen': 'really/truly',
    'verklighet': 'reality',
    'verkligheten': 'the reality',
    'verksamhet': 'activity/business',
    'verksamheten': 'the business',
    'verktyg': 'tool',
    'vi': 'we',
    'vid': 'at/by/wide',
    'vidare': 'further',
    'viktig': 'important',
    'viktiga': 'important (plural)',
    'viktigt': 'important (neuter)',
    'vikt': 'weight/importance',
    'vild': 'wild',
    'vilda': 'wild (plural)',
    'vilja': 'to want/will',
    'vill': 'wants',
    'vilken': 'which (en)',
    'vilka': 'which (plural)',
    'vilket': 'which (neuter)',
    'vin': 'wine',
    'vind': 'wind',
    'vinden': 'the wind',
    'vinet': 'the wine',
    'vinkade': 'waved',
    'vinkar': 'waves',
    'vinna': 'to win',
    'vinst': 'profit/win',
    'vinter': 'winter',
    'vintern': 'the winter',
    'visa': 'to show',
    'visade': 'showed',
    'visar': 'shows',
    'viss': 'certain',
    'vissa': 'certain (plural)',
    'visst': 'certainly/sure',
    'vit': 'white',
    'vitt': 'white (neuter)',
    'väcker': 'wakes/arouses',
    'väg': 'road/way',
    'vägen': 'the road',
    'väggar': 'walls',
    'väl': 'well/surely',
    'väld': 'realm',
    'väldig': 'enormous/tremendous',
    'väldigt': 'very/tremendously',
    'välja': 'to choose',
    'välkomna': 'to welcome',
    'välkommen': 'welcome',
    'vän': 'friend',
    'vänlig': 'friendly',
    'vänligt': 'friendly (neuter)',
    'vänner': 'friends',
    'vännerna': 'the friends',
    'vänster': 'left',
    'vänta': 'to wait',
    'väntade': 'waited',
    'väntar': 'waits',
    'värd': 'worth/host',
    'värde': 'value',
    'värdet': 'the value',
    'värld': 'world',
    'världen': 'the world',
    'värt': 'worth (neuter)',
    'väsen': 'being/essence',
    'väst': 'west/vest',
    'västra': 'western',
    'väte': 'hydrogen',
    'växa': 'to grow',
    'växer': 'grows',
    'växt': 'plant/growth',
    'växten': 'the plant',
    'växter': 'plants',
    # Y/Z/Å/Ä/Ö
    'yrke': 'profession/occupation',
    'yrket': 'the profession',
    'yta': 'surface',
    'ytan': 'the surface',
    'ytterligare': 'additional/further',
    'yttre': 'outer/external',
    'åker': 'goes (by vehicle)/field',
    'år': 'year',
    'åren': 'the years',
    'året': 'the year',
    'årsdag': 'anniversary',
    'årstid': 'season',
    'årstiden': 'the season',
    'årstiderna': 'the seasons',
    'årtionde': 'decade',
    'ås': 'ridge',
    'åsikt': 'opinion',
    'åsikten': 'the opinion',
    'åsikter': 'opinions',
    'åt': 'ate/to/for',
    'åtgärd': 'measure/action',
    'åtgärder': 'measures',
    'åtminstone': 'at least',
    'åtta': 'eight',
    'åttonde': 'eighth',
    'äga': 'to own',
    'ägare': 'owner',
    'ägaren': 'the owner',
    'äger': 'owns',
    'älska': 'to love',
    'älskade': 'loved',
    'älskar': 'loves',
    'äldre': 'older/elderly',
    'äldsta': 'oldest',
    'ämne': 'subject/topic',
    'ämnet': 'the subject',
    'ämnen': 'subjects',
    'ände': 'end',
    'ändra': 'to change',
    'ändrade': 'changed',
    'ändrar': 'changes',
    'ändå': 'still/anyway',
    'ängslighet': 'anxiety',
    'äntligen': 'finally',
    'ärende': 'errand/matter',
    'ärendet': 'the matter',
    'ärenden': 'errands/matters',
    'ärlig': 'honest',
    'ärligt': 'honestly',
    'även': 'also/even',
    'äventyr': 'adventure',
    'äventyret': 'the adventure',
    'ö': 'island',
    'öga': 'eye',
    'ögon': 'eyes',
    'ögonen': 'the eyes',
    'öka': 'to increase',
    'ökade': 'increased',
    'ökar': 'increases',
    'ökning': 'increase',
    'ökningen': 'the increase',
    'öl': 'beer',
    'ön': 'the island',
    'önska': 'to wish',
    'önskade': 'wished',
    'önskar': 'wishes',
    'öppen': 'open',
    'öppet': 'open (neuter)',
    'öppna': 'to open/open (plural)',
    'öppnade': 'opened',
    'öppnar': 'opens',
    'öra': 'ear',
    'öst': 'east',
    'östra': 'eastern',
    'över': 'over/above',
    'överallt': 'everywhere',
    'överens': 'in agreement',
    'överenskommelse': 'agreement',
    'överge': 'to abandon',
    'överhuvudtaget': 'at all',
    'överleva': 'to survive',
    'överlevde': 'survived',
    'överraskad': 'surprised',
    'överraskande': 'surprising',
    'översätta': 'to translate',
    'överväga': 'to consider',
    'övning': 'exercise/practice',
    'övrig': 'remaining/other',
    'övriga': 'remaining (plural)',
    'övrigt': 'otherwise',
}

# POS corrections based on word form patterns
POS_FIXES = {}

with open(INPUT, 'r') as f:
    content = f.read()

# Parse all entries
entries = re.findall(r"'([^']+)':\s*\{\s*en:\s*'([^']*)',\s*ipa:\s*'([^']*)',\s*pos:\s*'([^']*)'\s*\}", content)

# Also grab the IRREGULAR_MAP keys to know which words are verb forms
irr_block = re.search(r'const IRREGULAR_MAP.*?\{(.*?)\};', content, re.DOTALL)
irr_keys = set()
if irr_block:
    for m in re.finditer(r"'([^']+)':", irr_block.group(1)):
        irr_keys.add(m.group(1))

fixes_applied = 0
trans_added = 0
pos_fixed = 0

for word, en, ipa, pos in entries:
    new_en = en
    new_pos = pos
    changed = False

    # 1. Fix translations
    if word.lower() in TRANSLATIONS and (word == en or word == en.lower()):
        new_en = TRANSLATIONS[word.lower()]
        trans_added += 1
        changed = True

    # 2. Fix POS for words in IRREGULAR_MAP → must be 'v'
    if word in irr_keys and pos != 'v':
        new_pos = 'v'
        pos_fixed += 1
        changed = True

    # 3. Fix POS based on patterns
    # Verb forms ending in -ade (past tense)
    if word.endswith('ade') and pos != 'v' and len(word) > 4:
        new_pos = 'v'
        pos_fixed += 1
        changed = True
    # -ades (passive past)
    elif word.endswith('ades') and pos != 'v' and len(word) > 5:
        new_pos = 'v'
        pos_fixed += 1
        changed = True
    # Words ending in -lig, -isk, -ig → adjective (unless already adj or v)
    elif pos == 'n' and any(word.endswith(suf) for suf in ['lig', 'isk', 'ig']) and len(word) > 4:
        new_pos = 'adj'
        pos_fixed += 1
        changed = True
    # Words ending in -liga, -iska, -iga → adjective (plural/definite)
    elif pos == 'n' and any(word.endswith(suf) for suf in ['liga', 'iska', 'iga']) and len(word) > 5:
        new_pos = 'adj'
        pos_fixed += 1
        changed = True
    # Words ending in -ligt, -iskt, -igt → adverb form
    elif pos == 'n' and any(word.endswith(suf) for suf in ['ligt', 'iskt', 'igt']) and len(word) > 5:
        new_pos = 'adv'
        pos_fixed += 1
        changed = True
    # Words ending in -het, -tion, -ning, -skap, -dom → noun (keep)
    # Words ending in -ande, -ende → could be noun or adj (present participle), keep as-is

    # 4. Fix translation: if en starts with "to " and pos isn't 'v', make it 'v'
    if new_en.startswith('to ') and new_pos != 'v':
        new_pos = 'v'
        pos_fixed += 1
        changed = True

    if changed:
        # Escape apostrophes in new_en for the replacement
        old_entry = f"'{word}': {{ en: '{en}', ipa: '{ipa}', pos: '{pos}' }}"
        new_entry = f"'{word}': {{ en: '{new_en}', ipa: '{ipa}', pos: '{new_pos}' }}"
        content = content.replace(old_entry, new_entry, 1)
        fixes_applied += 1

with open(INPUT, 'w') as f:
    f.write(content)

print(f'Total entries: {len(entries)}')
print(f'Translations added: {trans_added}')
print(f'POS fixed: {pos_fixed}')
print(f'Total entries modified: {fixes_applied}')

# Verify remaining self-translated count
entries2 = re.findall(r"'([^']+)':\s*\{\s*en:\s*'([^']*)',\s*ipa:\s*'([^']*)',\s*pos:\s*'([^']*)'\s*\}", content)
self_remaining = sum(1 for w, en, _, _ in entries2 if w == en.lower() or w == en)
print(f'Self-translated remaining: {self_remaining} ({100*self_remaining/len(entries2):.1f}%)')
pos_counts2 = {}
for _, _, _, p in entries2:
    pos_counts2[p] = pos_counts2.get(p, 0) + 1
print(f'New POS distribution: {pos_counts2}')
