import { lookupWord as luRu } from '../src/data/dictionary/ru';
import { lookupWord as luHi } from '../src/data/dictionary/hi';
import { lookupWord as luDe } from '../src/data/dictionary/de';
import { lookupWord as luTr } from '../src/data/dictionary/tr';
import { lookupWord as luEs } from '../src/data/dictionary/es';

console.log('User-reported issues — final state:');
console.log('');
console.log('Russian:');
console.log('  туалет:', JSON.stringify(luRu('туалет')));
console.log('  по-русски:', JSON.stringify(luRu('по-русски')));
console.log('  зовут:', JSON.stringify(luRu('зовут')));
console.log('  из-за:', JSON.stringify(luRu('из-за')));
console.log('');
console.log('Hindi:');
console.log('  बता:', JSON.stringify(luHi('बता')));
console.log('  माता-पिता:', JSON.stringify(luHi('माता-पिता')));
console.log('  सबसे:', JSON.stringify(luHi('सबसे')));
console.log('');
console.log('German:');
console.log('  ihnen:', JSON.stringify(luDe('ihnen')));
console.log('  frage:', JSON.stringify(luDe('frage')));
console.log('  das:', JSON.stringify(luDe('das')));
console.log('  schön:', JSON.stringify(luDe('schön')));
console.log('  siehst:', JSON.stringify(luDe('siehst')));
console.log('');
console.log('Turkish:');
console.log('  tuvalet:', JSON.stringify(luTr('tuvalet')));
console.log('  e-posta:', JSON.stringify(luTr('e-posta')));
